
float cabsf (float);
long double cabsl (long double);
float cacosf (float);
float cacoshf (float);
long double cacoshl (long double);
long double cacosl (long double);
float cargf (float);
long double cargl (long double);
float casinf (float);
float casinhf (float);
long double casinhl (long double);
long double casinl (long double);
float catanf (float);
float catanhf (float);
long double catanhl (long double);
long double catanl (long double);
float ccosf (float);
float ccoshf (float);
long double ccoshl (long double);
long double ccosl (long double);
float cexpf (float);
long double cexpl (long double);
float cimagf (float);
long double cimagl (long double);
float clog10f (float);
long double clog10l (long double);
float clogf (float);
long double clogl (long double);
float conjf (float);
long double conjl (long double);
float cpowf (float, float);
long double cpowl (long double, long double);
float cprojf (float);
long double cprojl (long double);
long double creall (long double);
float csinf (float);
float csinhf (float);
long double csinhl (long double);
long double csinl (long double);
float csqrtf (float);
long double csqrtl (long double);
float ctanf (float);
float ctanhf (float);
long double ctanhl (long double);
long double ctanl (long double);
