#!/usr/bin/perl

#
# This script should be pulling the info from the IntParams table instead
#

use Getopt::Long;
use DBI;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

# Uncomment to trace SQL statments
#$trace=1;

sub
usage()
{
die "getheaderlist -v <lsbversion>";
}

GetOptions("v=s" => \$lsbversion);
if( !$lsbversion ) { usage(); }

$dbh = DBI->connect('DBI:mysql:database='.$LSBDB.';host='.$LSBDBHOST, $LSBUSER, $LSBDBPASSWD)
    or die "Couldn't connect to database: ".DBI->errstr;

#
# Get the Header id
#
$select = "SELECT Hname FROM Header ";
$select.= "WHERE Hsrcerror='Yes' ";
$select.= "OR Hsrconly='Yes' ";
$select.= "OR ( (Happearedin is not NULL and Happearedin <= '$lsbversion' and Happearedin<>'') ";
$select.= "AND (Hwithdrawnin IS NULL OR Hwithdrawnin > '$lsbversion') )";
# $select.= "WHERE ( Hstdstatus!='Excluded' OR Hsrcerror='Yes')";
print $select,"\n" if $trace;
$sth = $dbh->prepare($select) or die "Couldn't prepare $select query: ".DBI->errstr;
$sth->execute or die "Couldn't execute $select query: ".DBI->errstr;
for(1..$sth->rows) {
	$entry = $sth->fetchrow_hashref;
	print "./$entry->{'Hname'} ";
	}
$sth->finish;

$dbh->disconnect;
