#!/usr/local/bin/perl

#print "<PART>\n";
#print "<TITLE>Standard C Library Data Definitions</TITLE>\n";
#print "<PARA></PARA>\n";

foreach $hdr (sort @ARGV) {
	printf "<SECT1>\n";
	printf "<TITLE>%s</TITLE>\n", $hdr;
	printf "<PARA></PARA>\n";
	printf "<SCREEN>\n";
	printf "include(%s)\n", $hdr;
	printf "</SCREEN>\n";
	printf "</SECT1>\n";
	}
#print "</PART>\n";
