#!/usr/bin/perl

#
# This script should be pulling the infor from the IntParams table instead
#

use CGI;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$query = new CGI;

#print $query->header;
#print $query->start_html('Standards Table');

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

$select = "SELECT Iprototype FROM Interface ";
$select.= "WHERE Iheader='".$query->param('Iheader')."'";

#print $select;

$sth = $Dbh->query($select) || die $Dbh->errmsg();

for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	printf "%s;\n",$entry{'Iprototype'};
}

#print $query->end_html;
