#ifndef _QTGUI_QACCESSIBLEWIDGET_H_
#define _QTGUI_QACCESSIBLEWIDGET_H_

class QAccessibleWidget;
// *INDENT-OFF*



class QAccessibleWidget : public QAccessibleObject
{
private:
public:
};


extern QAccessibleWidget _ZN17QAccessibleWidgetC2EP7QWidgetN11QAccessible4RoleERK7QString(void);
extern QAccessibleWidget _ZN17QAccessibleWidgetC1EP7QWidgetN11QAccessible4RoleERK7QString(void);
extern int _ZNK17QAccessibleWidget10childCountEv(void);
extern int _ZNK17QAccessibleWidget12indexOfChildEPK20QAccessibleInterface(void);
extern N11QAccessible8RelationE _ZNK17QAccessibleWidget10relationToEiPK20QAccessibleInterfacei(void);
extern int _ZNK17QAccessibleWidget7childAtEii(void);
extern QRect _ZNK17QAccessibleWidget4rectEi(void);
extern int _ZNK17QAccessibleWidget8navigateEN11QAccessible12RelationFlagEiPP20QAccessibleInterface(void);
extern QString _ZNK17QAccessibleWidget4textEN11QAccessible4TextEi(void);
extern enum N11QAccessible4RoleE _ZNK17QAccessibleWidget4roleEi(void);
extern N11QAccessible5StateE _ZNK17QAccessibleWidget5stateEi(void);
extern QString _ZNK17QAccessibleWidget10actionTextEiN11QAccessible4TextEi(void);
extern bool _ZN17QAccessibleWidget8doActionEiiRK5QListI8QVariantE(void);
extern QAccessibleWidget _ZN17QAccessibleWidgetD2Ev(void);
extern QAccessibleWidget _ZN17QAccessibleWidgetD1Ev(void);
extern QAccessibleWidget _ZN17QAccessibleWidgetD0Ev(void);
extern QWidget _ZNK17QAccessibleWidget6widgetEv(void);
extern QObject _ZNK17QAccessibleWidget12parentObjectEv(void);
extern void _ZN17QAccessibleWidget20addControllingSignalERK7QString(void);
extern void _ZN17QAccessibleWidget8setValueERK7QString(void);
extern void _ZN17QAccessibleWidget14setDescriptionERK7QString(void);
extern void _ZN17QAccessibleWidget7setHelpERK7QString(void);
extern void _ZN17QAccessibleWidget14setAcceleratorERK7QString(void);
// *INDENT-ON*
#endif
