#ifndef _QTGUI_QPLASTIQUESTYLE_H_
#define _QTGUI_QPLASTIQUESTYLE_H_

class QPlastiqueStyle;
// *INDENT-OFF*




class QPlastiqueStyle : public QWindowsStyle
{
private:
public:
};


extern struct QMetaObject _ZN15QPlastiqueStyle16staticMetaObjectE ;
extern struct QMetaObject _ZNK15QPlastiqueStyle10metaObjectEv(void);
extern void _ZN15QPlastiqueStyle11qt_metacastEPKc(void);
extern int _ZN15QPlastiqueStyle11qt_metacallEN11QMetaObject4CallEiPPv(void);
extern QPlastiqueStyle _ZN15QPlastiqueStyleC2Ev(void);
extern QPlastiqueStyle _ZN15QPlastiqueStyleC1Ev(void);
extern QPlastiqueStyle _ZN15QPlastiqueStyleD2Ev(void);
extern QPlastiqueStyle _ZN15QPlastiqueStyleD1Ev(void);
extern QPlastiqueStyle _ZN15QPlastiqueStyleD0Ev(void);
extern void _ZNK15QPlastiqueStyle13drawPrimitiveEN6QStyle16PrimitiveElementEPK12QStyleOptionP8QPainterPK7QWidget(void);
extern void _ZNK15QPlastiqueStyle11drawControlEN6QStyle14ControlElementEPK12QStyleOptionP8QPainterPK7QWidget(void);
extern void _ZNK15QPlastiqueStyle18drawComplexControlEN6QStyle14ComplexControlEPK19QStyleOptionComplexP8QPainterPK7QWidget(void);
extern QSize _ZNK15QPlastiqueStyle16sizeFromContentsEN6QStyle12ContentsTypeEPK12QStyleOptionRK5QSizePK7QWidget(void);
extern QRect _ZNK15QPlastiqueStyle14subElementRectEN6QStyle10SubElementEPK12QStyleOptionPK7QWidget(void);
extern QRect _ZNK15QPlastiqueStyle14subControlRectEN6QStyle14ComplexControlEPK19QStyleOptionComplexNS0_10SubControlEPK7QWidget(void);
extern int _ZNK15QPlastiqueStyle9styleHintEN6QStyle9StyleHintEPK12QStyleOptionPK7QWidgetP16QStyleHintReturn(void);
extern enum N6QStyle10SubControlE _ZNK15QPlastiqueStyle21hitTestComplexControlEN6QStyle14ComplexControlEPK19QStyleOptionComplexRK6QPointPK7QWidget(void);
extern int _ZNK15QPlastiqueStyle11pixelMetricEN6QStyle11PixelMetricEPK12QStyleOptionPK7QWidget(void);
extern void _ZN15QPlastiqueStyle6polishEP7QWidget(void);
extern void _ZN15QPlastiqueStyle6polishEP12QApplication(void);
extern void _ZN15QPlastiqueStyle6polishER8QPalette(void);
extern void _ZN15QPlastiqueStyle8unpolishEP7QWidget(void);
extern void _ZN15QPlastiqueStyle8unpolishEP12QApplication(void);
extern QPalette _ZNK15QPlastiqueStyle15standardPaletteEv(void);
extern bool _ZN15QPlastiqueStyle11eventFilterEP7QObjectP6QEvent(void);
extern void _ZN15QPlastiqueStyle10timerEventEP11QTimerEvent(void);
// *INDENT-ON*
#endif
