#ifndef _QTGUI_QTREEWIDGET_H_
#define _QTGUI_QTREEWIDGET_H_

class QTreeWidget;
// *INDENT-OFF*



class QTreeWidgetItem
{
private:
public:
};

class QTreeWidget : public QTreeView
{
private:
public:
};


extern QTreeWidgetItem _ZN15QTreeWidgetItemC2Ei(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1Ei(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2ERK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1ERK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EP11QTreeWidgeti(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EP11QTreeWidgeti(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EP11QTreeWidgetRK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EP11QTreeWidgetRK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EP11QTreeWidgetPS_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EP11QTreeWidgetPS_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EPS_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EPS_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EPS_RK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EPS_RK11QStringListi(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2EPS_S0_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1EPS_S0_i(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC2ERKS_(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemC1ERKS_(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemD2Ev(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemD1Ev(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemD0Ev(void);
extern QTreeWidgetItem _ZNK15QTreeWidgetItem5cloneEv(void);
extern QVariant _ZNK15QTreeWidgetItem4dataEii(void);
extern void _ZN15QTreeWidgetItem7setDataEiiRK8QVariant(void);
extern bool _ZNK15QTreeWidgetItemltERKS_(void);
extern void _ZN15QTreeWidgetItem4readER11QDataStream(void);
extern void _ZNK15QTreeWidgetItem5writeER11QDataStream(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItemaSERKS_(void);
extern void _ZN15QTreeWidgetItem8addChildEPS_(void);
extern void _ZN15QTreeWidgetItem11insertChildEiPS_(void);
extern QTreeWidgetItem _ZN15QTreeWidgetItem9takeChildEi(void);
extern void _ZN15QTreeWidgetItem11addChildrenERK5QListIPS_E(void);
extern void _ZN15QTreeWidgetItem14insertChildrenEiRK5QListIPS_E(void);
extern  _ZN15QTreeWidgetItem12takeChildrenEv(void);
extern QDataStream _ZlsR11QDataStreamRK15QTreeWidgetItem(void);
extern QDataStream _ZrsR11QDataStreamR15QTreeWidgetItem(void);
extern struct QMetaObject _ZN11QTreeWidget16staticMetaObjectE ;
extern struct QMetaObject _ZNK11QTreeWidget10metaObjectEv(void);
extern void _ZN11QTreeWidget11qt_metacastEPKc(void);
extern int _ZN11QTreeWidget11qt_metacallEN11QMetaObject4CallEiPPv(void);
extern QTreeWidget _ZN11QTreeWidgetC2EP7QWidget(void);
extern QTreeWidget _ZN11QTreeWidgetC1EP7QWidget(void);
extern QTreeWidget _ZN11QTreeWidgetD2Ev(void);
extern QTreeWidget _ZN11QTreeWidgetD1Ev(void);
extern QTreeWidget _ZN11QTreeWidgetD0Ev(void);
extern int _ZNK11QTreeWidget11columnCountEv(void);
extern void _ZN11QTreeWidget14setColumnCountEi(void);
extern QTreeWidgetItem _ZNK11QTreeWidget12topLevelItemEi(void);
extern int _ZNK11QTreeWidget17topLevelItemCountEv(void);
extern void _ZN11QTreeWidget18insertTopLevelItemEiP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget15addTopLevelItemEP15QTreeWidgetItem(void);
extern QTreeWidgetItem _ZN11QTreeWidget16takeTopLevelItemEi(void);
extern int _ZN11QTreeWidget19indexOfTopLevelItemEP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget19insertTopLevelItemsEiRK5QListIP15QTreeWidgetItemE(void);
extern void _ZN11QTreeWidget16addTopLevelItemsERK5QListIP15QTreeWidgetItemE(void);
extern QTreeWidgetItem _ZNK11QTreeWidget10headerItemEv(void);
extern void _ZN11QTreeWidget13setHeaderItemEP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget15setHeaderLabelsERK11QStringList(void);
extern QTreeWidgetItem _ZNK11QTreeWidget11currentItemEv(void);
extern int _ZNK11QTreeWidget13currentColumnEv(void);
extern void _ZN11QTreeWidget14setCurrentItemEP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget14setCurrentItemEP15QTreeWidgetItemi(void);
extern QTreeWidgetItem _ZNK11QTreeWidget6itemAtERK6QPoint(void);
extern QRect _ZNK11QTreeWidget14visualItemRectEPK15QTreeWidgetItem(void);
extern int _ZNK11QTreeWidget10sortColumnEv(void);
extern void _ZN11QTreeWidget9sortItemsEiN2Qt9SortOrderE(void);
extern void _ZN11QTreeWidget17setSortingEnabledEb(void);
extern bool _ZNK11QTreeWidget16isSortingEnabledEv(void);
extern void _ZN11QTreeWidget8editItemEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget20openPersistentEditorEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget21closePersistentEditorEP15QTreeWidgetItemi(void);
extern QWidget _ZNK11QTreeWidget10itemWidgetEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget13setItemWidgetEP15QTreeWidgetItemiP7QWidget(void);
extern bool _ZNK11QTreeWidget14isItemSelectedEPK15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget15setItemSelectedEPK15QTreeWidgetItemb(void);
extern  _ZNK11QTreeWidget13selectedItemsEv(void);
extern  _ZNK11QTreeWidget9findItemsERK7QString6QFlagsIN2Qt9MatchFlagEEi(void);
extern bool _ZNK11QTreeWidget12isItemHiddenEPK15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget13setItemHiddenEPK15QTreeWidgetItemb(void);
extern bool _ZNK11QTreeWidget14isItemExpandedEPK15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget15setItemExpandedEPK15QTreeWidgetItemb(void);
extern void _ZN11QTreeWidget12scrollToItemEPK15QTreeWidgetItemN17QAbstractItemView10ScrollHintE(void);
extern void _ZN11QTreeWidget10expandItemEPK15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget12collapseItemEPK15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget5clearEv(void);
extern void _ZN11QTreeWidget11itemPressedEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget11itemClickedEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget17itemDoubleClickedEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget13itemActivatedEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget11itemEnteredEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget11itemChangedEP15QTreeWidgetItemi(void);
extern void _ZN11QTreeWidget12itemExpandedEP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget13itemCollapsedEP15QTreeWidgetItem(void);
extern void _ZN11QTreeWidget18currentItemChangedEP15QTreeWidgetItemS1_(void);
extern void _ZN11QTreeWidget20itemSelectionChangedEv(void);
extern bool _ZN11QTreeWidget5eventEP6QEvent(void);
extern QStringList _ZNK11QTreeWidget9mimeTypesEv(void);
extern QMimeData _ZNK11QTreeWidget8mimeDataE5QListIP15QTreeWidgetItemE(void);
extern bool _ZN11QTreeWidget12dropMimeDataEP15QTreeWidgetItemiPK9QMimeDataN2Qt10DropActionE(void);
extern N2Qt11DropActionsE _ZNK11QTreeWidget20supportedDropActionsEv(void);
extern  _ZNK11QTreeWidget5itemsEPK9QMimeData(void);
extern QModelIndex _ZNK11QTreeWidget13indexFromItemEP15QTreeWidgetItemi(void);
extern QTreeWidgetItem _ZNK11QTreeWidget13itemFromIndexERK11QModelIndex(void);
extern void _ZN11QTreeWidget8setModelEP18QAbstractItemModel(void);
// *INDENT-ON*
#endif
