#ifndef _QTGUI_QWINDOWSSTYLE_H_
#define _QTGUI_QWINDOWSSTYLE_H_

class QWindowsStyle;
// *INDENT-OFF*




class QWindowsStyle : public QCommonStyle
{
private:
public:
};


extern struct QMetaObject _ZN13QWindowsStyle16staticMetaObjectE ;
extern struct QMetaObject _ZNK13QWindowsStyle10metaObjectEv(void);
extern void _ZN13QWindowsStyle11qt_metacastEPKc(void);
extern int _ZN13QWindowsStyle11qt_metacallEN11QMetaObject4CallEiPPv(void);
extern QWindowsStyle _ZN13QWindowsStyleC2Ev(void);
extern QWindowsStyle _ZN13QWindowsStyleC1Ev(void);
extern  _ZN13QWindowsStyleD2Ev(void);
extern  _ZN13QWindowsStyleD1Ev(void);
extern  _ZN13QWindowsStyleD0Ev(void);
extern void _ZN13QWindowsStyle6polishEP12QApplication(void);
extern void _ZN13QWindowsStyle8unpolishEP12QApplication(void);
extern void _ZN13QWindowsStyle6polishEP7QWidget(void);
extern void _ZN13QWindowsStyle8unpolishEP7QWidget(void);
extern void _ZN13QWindowsStyle6polishER8QPalette(void);
extern void _ZNK13QWindowsStyle13drawPrimitiveEN6QStyle16PrimitiveElementEPK12QStyleOptionP8QPainterPK7QWidget(void);
extern void _ZNK13QWindowsStyle11drawControlEN6QStyle14ControlElementEPK12QStyleOptionP8QPainterPK7QWidget(void);
extern QRect _ZNK13QWindowsStyle14subElementRectEN6QStyle10SubElementEPK12QStyleOptionPK7QWidget(void);
extern void _ZNK13QWindowsStyle18drawComplexControlEN6QStyle14ComplexControlEPK19QStyleOptionComplexP8QPainterPK7QWidget(void);
extern QSize _ZNK13QWindowsStyle16sizeFromContentsEN6QStyle12ContentsTypeEPK12QStyleOptionRK5QSizePK7QWidget(void);
extern int _ZNK13QWindowsStyle11pixelMetricEN6QStyle11PixelMetricEPK12QStyleOptionPK7QWidget(void);
extern int _ZNK13QWindowsStyle9styleHintEN6QStyle9StyleHintEPK12QStyleOptionPK7QWidgetP16QStyleHintReturn(void);
extern QPixmap _ZNK13QWindowsStyle14standardPixmapEN6QStyle14StandardPixmapEPK12QStyleOptionPK7QWidget(void);
extern bool _ZN13QWindowsStyle11eventFilterEP7QObjectP6QEvent(void);
extern void _ZN13QWindowsStyle10timerEventEP11QTimerEvent(void);
extern QWindowsStyle _ZN13QWindowsStyleC2ER20QWindowsStylePrivate(void);
extern QWindowsStyle _ZN13QWindowsStyleC1ER20QWindowsStylePrivate(void);
// *INDENT-ON*
#endif
