__asm__(".globl _IO_feof");
__asm__("	.type _IO_feof,@function");
__asm__("_IO_feof:");
__asm__("	ret");
__asm__(".globl _IO_getc");
__asm__("	.type _IO_getc,@function");
__asm__("_IO_getc:");
__asm__("	ret");
__asm__(".globl _IO_putc");
__asm__("	.type _IO_putc,@function");
__asm__("_IO_putc:");
__asm__("	ret");
__asm__(".globl _IO_puts");
__asm__("	.type _IO_puts,@function");
__asm__("_IO_puts:");
__asm__("	ret");
__asm__(".globl __assert_fail");
__asm__("	.type __assert_fail,@function");
__asm__("__assert_fail:");
__asm__("	ret");
__asm__(".globl __bzero");
__asm__("	.type __bzero,@function");
__asm__("__bzero:");
__asm__("	ret");
__asm__(".globl __cxa_atexit");
__asm__("	.type __cxa_atexit,@function");
__asm__("__cxa_atexit:");
__asm__("	ret");
__asm__(".globl __dcgettext");
__asm__("	.type __dcgettext,@function");
__asm__("__dcgettext:");
__asm__("	ret");
__asm__(".globl __divdi3");
__asm__("	.type __divdi3,@function");
__asm__("__divdi3:");
__asm__("	ret");
__asm__(".globl __fxstat");
__asm__("	.type __fxstat,@function");
__asm__("__fxstat:");
__asm__("	ret");
__asm__(".globl __fxstat64");
__asm__("	.type __fxstat64,@function");
__asm__("__fxstat64:");
__asm__("	ret");
__asm__(".globl __getpgid");
__asm__("	.type __getpgid,@function");
__asm__("__getpgid:");
__asm__("	ret");
__asm__(".globl __libc_current_sigrtmax");
__asm__("	.type __libc_current_sigrtmax,@function");
__asm__("__libc_current_sigrtmax:");
__asm__("	ret");
__asm__(".globl __libc_current_sigrtmin");
__asm__("	.type __libc_current_sigrtmin,@function");
__asm__("__libc_current_sigrtmin:");
__asm__("	ret");
__asm__(".globl __lxstat");
__asm__("	.type __lxstat,@function");
__asm__("__lxstat:");
__asm__("	ret");
__asm__(".globl __lxstat64");
__asm__("	.type __lxstat64,@function");
__asm__("__lxstat64:");
__asm__("	ret");
__asm__(".globl __mbrlen");
__asm__("	.type __mbrlen,@function");
__asm__("__mbrlen:");
__asm__("	ret");
__asm__(".globl __mempcpy");
__asm__("	.type __mempcpy,@function");
__asm__("__mempcpy:");
__asm__("	ret");
__asm__(".globl __rawmemchr");
__asm__("	.type __rawmemchr,@function");
__asm__("__rawmemchr:");
__asm__("	ret");
__asm__(".globl __secure_getenv");
__asm__("	.type __secure_getenv,@function");
__asm__("__secure_getenv:");
__asm__("	ret");
__asm__(".globl __sigpause");
__asm__("	.type __sigpause,@function");
__asm__("__sigpause:");
__asm__("	ret");
__asm__(".globl __sigsetjmp");
__asm__("	.type __sigsetjmp,@function");
__asm__("__sigsetjmp:");
__asm__("	ret");
__asm__(".globl __stpcpy");
__asm__("	.type __stpcpy,@function");
__asm__("__stpcpy:");
__asm__("	ret");
__asm__(".globl __strdup");
__asm__("	.type __strdup,@function");
__asm__("__strdup:");
__asm__("	ret");
__asm__(".globl __strtod_internal");
__asm__("	.type __strtod_internal,@function");
__asm__("__strtod_internal:");
__asm__("	ret");
__asm__(".globl __strtof_internal");
__asm__("	.type __strtof_internal,@function");
__asm__("__strtof_internal:");
__asm__("	ret");
__asm__(".globl __strtok_r");
__asm__("	.type __strtok_r,@function");
__asm__("__strtok_r:");
__asm__("	ret");
__asm__(".globl __strtol_internal");
__asm__("	.type __strtol_internal,@function");
__asm__("__strtol_internal:");
__asm__("	ret");
__asm__(".globl __strtold_internal");
__asm__("	.type __strtold_internal,@function");
__asm__("__strtold_internal:");
__asm__("	ret");
__asm__(".globl __strtoll_internal");
__asm__("	.type __strtoll_internal,@function");
__asm__("__strtoll_internal:");
__asm__("	ret");
__asm__(".globl __strtoul_internal");
__asm__("	.type __strtoul_internal,@function");
__asm__("__strtoul_internal:");
__asm__("	ret");
__asm__(".globl __strtoull_internal");
__asm__("	.type __strtoull_internal,@function");
__asm__("__strtoull_internal:");
__asm__("	ret");
__asm__(".globl __sysv_signal");
__asm__("	.type __sysv_signal,@function");
__asm__("__sysv_signal:");
__asm__("	ret");
__asm__(".globl __wcstod_internal");
__asm__("	.type __wcstod_internal,@function");
__asm__("__wcstod_internal:");
__asm__("	ret");
__asm__(".globl __wcstof_internal");
__asm__("	.type __wcstof_internal,@function");
__asm__("__wcstof_internal:");
__asm__("	ret");
__asm__(".globl __wcstol_internal");
__asm__("	.type __wcstol_internal,@function");
__asm__("__wcstol_internal:");
__asm__("	ret");
__asm__(".globl __wcstold_internal");
__asm__("	.type __wcstold_internal,@function");
__asm__("__wcstold_internal:");
__asm__("	ret");
__asm__(".globl __wcstoll_internal");
__asm__("	.type __wcstoll_internal,@function");
__asm__("__wcstoll_internal:");
__asm__("	ret");
__asm__(".globl __wcstoul_internal");
__asm__("	.type __wcstoul_internal,@function");
__asm__("__wcstoul_internal:");
__asm__("	ret");
__asm__(".globl __wcstoull_internal");
__asm__("	.type __wcstoull_internal,@function");
__asm__("__wcstoull_internal:");
__asm__("	ret");
__asm__(".globl __xmknod");
__asm__("	.type __xmknod,@function");
__asm__("__xmknod:");
__asm__("	ret");
__asm__(".globl __xstat");
__asm__("	.type __xstat,@function");
__asm__("__xstat:");
__asm__("	ret");
__asm__(".globl __xstat64");
__asm__("	.type __xstat64,@function");
__asm__("__xstat64:");
__asm__("	ret");
__asm__(".globl _exit");
__asm__("	.type _exit,@function");
__asm__("_exit:");
__asm__("	ret");
__asm__(".globl _obstack_begin");
__asm__("	.type _obstack_begin,@function");
__asm__("_obstack_begin:");
__asm__("	ret");
__asm__(".globl _obstack_newchunk");
__asm__("	.type _obstack_newchunk,@function");
__asm__("_obstack_newchunk:");
__asm__("	ret");
__asm__(".globl _tolower");
__asm__("	.type _tolower,@function");
__asm__("_tolower:");
__asm__("	ret");
__asm__(".globl _toupper");
__asm__("	.type _toupper,@function");
__asm__("_toupper:");
__asm__("	ret");
__asm__(".globl a64l");
__asm__("	.type a64l,@function");
__asm__("a64l:");
__asm__("	ret");
__asm__(".globl abort");
__asm__("	.type abort,@function");
__asm__("abort:");
__asm__("	ret");
__asm__(".globl abs");
__asm__("	.type abs,@function");
__asm__("abs:");
__asm__("	ret");
__asm__(".globl acct");
__asm__("	.type acct,@function");
__asm__("acct:");
__asm__("	ret");
__asm__(".globl alarm");
__asm__("	.type alarm,@function");
__asm__("alarm:");
__asm__("	ret");
__asm__(".globl alphasort");
__asm__("	.type alphasort,@function");
__asm__("alphasort:");
__asm__("	ret");
__asm__(".globl alphasort64");
__asm__("	.type alphasort64,@function");
__asm__("alphasort64:");
__asm__("	ret");
__asm__(".globl asctime");
__asm__("	.type asctime,@function");
__asm__("asctime:");
__asm__("	ret");
__asm__(".globl atexit");
__asm__("	.type atexit,@function");
__asm__("atexit:");
__asm__("	ret");
__asm__(".globl atof");
__asm__("	.type atof,@function");
__asm__("atof:");
__asm__("	ret");
__asm__(".globl atoi");
__asm__("	.type atoi,@function");
__asm__("atoi:");
__asm__("	ret");
__asm__(".globl atol");
__asm__("	.type atol,@function");
__asm__("atol:");
__asm__("	ret");
__asm__(".globl basename");
__asm__("	.type basename,@function");
__asm__("basename:");
__asm__("	ret");
__asm__(".globl bcopy");
__asm__("	.type bcopy,@function");
__asm__("bcopy:");
__asm__("	ret");
__asm__(".globl bind");
__asm__("	.type bind,@function");
__asm__("bind:");
__asm__("	ret");
__asm__(".globl bindresvport");
__asm__("	.type bindresvport,@function");
__asm__("bindresvport:");
__asm__("	ret");
__asm__(".globl bsearch");
__asm__("	.type bsearch,@function");
__asm__("bsearch:");
__asm__("	ret");
__asm__(".globl catclose");
__asm__("	.type catclose,@function");
__asm__("catclose:");
__asm__("	ret");
__asm__(".globl catgets");
__asm__("	.type catgets,@function");
__asm__("catgets:");
__asm__("	ret");
__asm__(".globl catopen");
__asm__("	.type catopen,@function");
__asm__("catopen:");
__asm__("	ret");
__asm__(".globl cfgetispeed");
__asm__("	.type cfgetispeed,@function");
__asm__("cfgetispeed:");
__asm__("	ret");
__asm__(".globl cfgetospeed");
__asm__("	.type cfgetospeed,@function");
__asm__("cfgetospeed:");
__asm__("	ret");
__asm__(".globl cfmakeraw");
__asm__("	.type cfmakeraw,@function");
__asm__("cfmakeraw:");
__asm__("	ret");
__asm__(".globl cfsetispeed");
__asm__("	.type cfsetispeed,@function");
__asm__("cfsetispeed:");
__asm__("	ret");
__asm__(".globl cfsetospeed");
__asm__("	.type cfsetospeed,@function");
__asm__("cfsetospeed:");
__asm__("	ret");
__asm__(".globl cfsetspeed");
__asm__("	.type cfsetspeed,@function");
__asm__("cfsetspeed:");
__asm__("	ret");
__asm__(".globl chown");
__asm__("	.type chown,@function");
__asm__("chown:");
__asm__("	ret");
__asm__(".globl chroot");
__asm__("	.type chroot,@function");
__asm__("chroot:");
__asm__("	ret");
__asm__(".globl clearerr");
__asm__("	.type clearerr,@function");
__asm__("clearerr:");
__asm__("	ret");
__asm__(".globl clock");
__asm__("	.type clock,@function");
__asm__("clock:");
__asm__("	ret");
__asm__(".globl closelog");
__asm__("	.type closelog,@function");
__asm__("closelog:");
__asm__("	ret");
__asm__(".globl confstr");
__asm__("	.type confstr,@function");
__asm__("confstr:");
__asm__("	ret");
__asm__(".globl creat");
__asm__("	.type creat,@function");
__asm__("creat:");
__asm__("	ret");
__asm__(".globl creat64");
__asm__("	.type creat64,@function");
__asm__("creat64:");
__asm__("	ret");
__asm__(".globl ctermid");
__asm__("	.type ctermid,@function");
__asm__("ctermid:");
__asm__("	ret");
__asm__(".globl ctime");
__asm__("	.type ctime,@function");
__asm__("ctime:");
__asm__("	ret");
__asm__(".globl cuserid");
__asm__("	.type cuserid,@function");
__asm__("cuserid:");
__asm__("	ret");
__asm__(".globl daemon");
__asm__("	.type daemon,@function");
__asm__("daemon:");
__asm__("	ret");
__asm__(".globl difftime");
__asm__("	.type difftime,@function");
__asm__("difftime:");
__asm__("	ret");
__asm__(".globl dirname");
__asm__("	.type dirname,@function");
__asm__("dirname:");
__asm__("	ret");
__asm__(".globl div");
__asm__("	.type div,@function");
__asm__("div:");
__asm__("	ret");
__asm__(".globl drand48");
__asm__("	.type drand48,@function");
__asm__("drand48:");
__asm__("	ret");
__asm__(".globl ecvt");
__asm__("	.type ecvt,@function");
__asm__("ecvt:");
__asm__("	ret");
__asm__(".globl endgrent");
__asm__("	.type endgrent,@function");
__asm__("endgrent:");
__asm__("	ret");
__asm__(".globl endhostent");
__asm__("	.type endhostent,@function");
__asm__("endhostent:");
__asm__("	ret");
__asm__(".globl endnetent");
__asm__("	.type endnetent,@function");
__asm__("endnetent:");
__asm__("	ret");
__asm__(".globl endprotoent");
__asm__("	.type endprotoent,@function");
__asm__("endprotoent:");
__asm__("	ret");
__asm__(".globl endpwent");
__asm__("	.type endpwent,@function");
__asm__("endpwent:");
__asm__("	ret");
__asm__(".globl endservent");
__asm__("	.type endservent,@function");
__asm__("endservent:");
__asm__("	ret");
__asm__(".globl endutxent");
__asm__("	.type endutxent,@function");
__asm__("endutxent:");
__asm__("	ret");
__asm__(".globl erand48");
__asm__("	.type erand48,@function");
__asm__("erand48:");
__asm__("	ret");
__asm__(".globl err");
__asm__("	.type err,@function");
__asm__("err:");
__asm__("	ret");
__asm__(".globl errx");
__asm__("	.type errx,@function");
__asm__("errx:");
__asm__("	ret");
__asm__(".globl execl");
__asm__("	.type execl,@function");
__asm__("execl:");
__asm__("	ret");
__asm__(".globl execle");
__asm__("	.type execle,@function");
__asm__("execle:");
__asm__("	ret");
__asm__(".globl execlp");
__asm__("	.type execlp,@function");
__asm__("execlp:");
__asm__("	ret");
__asm__(".globl execv");
__asm__("	.type execv,@function");
__asm__("execv:");
__asm__("	ret");
__asm__(".globl execvp");
__asm__("	.type execvp,@function");
__asm__("execvp:");
__asm__("	ret");
__asm__(".globl exit");
__asm__("	.type exit,@function");
__asm__("exit:");
__asm__("	ret");
__asm__(".globl fclose");
__asm__("	.type fclose,@function");
__asm__("fclose:");
__asm__("	ret");
__asm__(".globl fcvt");
__asm__("	.type fcvt,@function");
__asm__("fcvt:");
__asm__("	ret");
__asm__(".globl fdatasync");
__asm__("	.type fdatasync,@function");
__asm__("fdatasync:");
__asm__("	ret");
__asm__(".globl fdetach");
__asm__("	.type fdetach,@function");
__asm__("fdetach:");
__asm__("	ret");
__asm__(".globl fdopen");
__asm__("	.type fdopen,@function");
__asm__("fdopen:");
__asm__("	ret");
__asm__(".globl fflush_unlocked");
__asm__("	.type fflush_unlocked,@function");
__asm__("fflush_unlocked:");
__asm__("	ret");
__asm__(".globl fileno");
__asm__("	.type fileno,@function");
__asm__("fileno:");
__asm__("	ret");
__asm__(".globl fmtmsg");
__asm__("	.type fmtmsg,@function");
__asm__("fmtmsg:");
__asm__("	ret");
__asm__(".globl fnmatch");
__asm__("	.type fnmatch,@function");
__asm__("fnmatch:");
__asm__("	ret");
__asm__(".globl fopen");
__asm__("	.type fopen,@function");
__asm__("fopen:");
__asm__("	ret");
__asm__(".globl fprintf");
__asm__("	.type fprintf,@function");
__asm__("fprintf:");
__asm__("	ret");
__asm__(".globl fputc");
__asm__("	.type fputc,@function");
__asm__("fputc:");
__asm__("	ret");
__asm__(".globl freopen");
__asm__("	.type freopen,@function");
__asm__("freopen:");
__asm__("	ret");
__asm__(".globl freopen64");
__asm__("	.type freopen64,@function");
__asm__("freopen64:");
__asm__("	ret");
__asm__(".globl fscanf");
__asm__("	.type fscanf,@function");
__asm__("fscanf:");
__asm__("	ret");
__asm__(".globl fseek");
__asm__("	.type fseek,@function");
__asm__("fseek:");
__asm__("	ret");
__asm__(".globl fseeko");
__asm__("	.type fseeko,@function");
__asm__("fseeko:");
__asm__("	ret");
__asm__(".globl fseeko64");
__asm__("	.type fseeko64,@function");
__asm__("fseeko64:");
__asm__("	ret");
__asm__(".globl fstatfs64");
__asm__("	.type fstatfs64,@function");
__asm__("fstatfs64:");
__asm__("	ret");
__asm__(".globl fstatvfs");
__asm__("	.type fstatvfs,@function");
__asm__("fstatvfs:");
__asm__("	ret");
__asm__(".globl fstatvfs64");
__asm__("	.type fstatvfs64,@function");
__asm__("fstatvfs64:");
__asm__("	ret");
__asm__(".globl ftello");
__asm__("	.type ftello,@function");
__asm__("ftello:");
__asm__("	ret");
__asm__(".globl ftello64");
__asm__("	.type ftello64,@function");
__asm__("ftello64:");
__asm__("	ret");
__asm__(".globl ftime");
__asm__("	.type ftime,@function");
__asm__("ftime:");
__asm__("	ret");
__asm__(".globl ftok");
__asm__("	.type ftok,@function");
__asm__("ftok:");
__asm__("	ret");
__asm__(".globl ftruncate64");
__asm__("	.type ftruncate64,@function");
__asm__("ftruncate64:");
__asm__("	ret");
__asm__(".globl ftw");
__asm__("	.type ftw,@function");
__asm__("ftw:");
__asm__("	ret");
__asm__(".globl ftw64");
__asm__("	.type ftw64,@function");
__asm__("ftw64:");
__asm__("	ret");
__asm__(".globl gcvt");
__asm__("	.type gcvt,@function");
__asm__("gcvt:");
__asm__("	ret");
__asm__(".globl getchar");
__asm__("	.type getchar,@function");
__asm__("getchar:");
__asm__("	ret");
__asm__(".globl getchar_unlocked");
__asm__("	.type getchar_unlocked,@function");
__asm__("getchar_unlocked:");
__asm__("	ret");
__asm__(".globl getcontext");
__asm__("	.type getcontext,@function");
__asm__("getcontext:");
__asm__("	ret");
__asm__(".globl getdate");
__asm__("	.type getdate,@function");
__asm__("getdate:");
__asm__("	ret");
__asm__(".globl getenv");
__asm__("	.type getenv,@function");
__asm__("getenv:");
__asm__("	ret");
__asm__(".globl getgrent");
__asm__("	.type getgrent,@function");
__asm__("getgrent:");
__asm__("	ret");
__asm__(".globl getgrgid");
__asm__("	.type getgrgid,@function");
__asm__("getgrgid:");
__asm__("	ret");
__asm__(".globl getgrnam");
__asm__("	.type getgrnam,@function");
__asm__("getgrnam:");
__asm__("	ret");
__asm__(".globl gethostbyaddr");
__asm__("	.type gethostbyaddr,@function");
__asm__("gethostbyaddr:");
__asm__("	ret");
__asm__(".globl gethostbyname");
__asm__("	.type gethostbyname,@function");
__asm__("gethostbyname:");
__asm__("	ret");
__asm__(".globl gethostid");
__asm__("	.type gethostid,@function");
__asm__("gethostid:");
__asm__("	ret");
__asm__(".globl getlogin");
__asm__("	.type getlogin,@function");
__asm__("getlogin:");
__asm__("	ret");
__asm__(".globl getmsg");
__asm__("	.type getmsg,@function");
__asm__("getmsg:");
__asm__("	ret");
__asm__(".globl getnetbyaddr");
__asm__("	.type getnetbyaddr,@function");
__asm__("getnetbyaddr:");
__asm__("	ret");
__asm__(".globl getopt");
__asm__("	.type getopt,@function");
__asm__("getopt:");
__asm__("	ret");
__asm__(".globl getopt_long");
__asm__("	.type getopt_long,@function");
__asm__("getopt_long:");
__asm__("	ret");
__asm__(".globl getopt_long_only");
__asm__("	.type getopt_long_only,@function");
__asm__("getopt_long_only:");
__asm__("	ret");
__asm__(".globl getpgrp");
__asm__("	.type getpgrp,@function");
__asm__("getpgrp:");
__asm__("	ret");
__asm__(".globl getpriority");
__asm__("	.type getpriority,@function");
__asm__("getpriority:");
__asm__("	ret");
__asm__(".globl getprotobyname");
__asm__("	.type getprotobyname,@function");
__asm__("getprotobyname:");
__asm__("	ret");
__asm__(".globl getprotobynumber");
__asm__("	.type getprotobynumber,@function");
__asm__("getprotobynumber:");
__asm__("	ret");
__asm__(".globl getprotoent");
__asm__("	.type getprotoent,@function");
__asm__("getprotoent:");
__asm__("	ret");
__asm__(".globl getpwent");
__asm__("	.type getpwent,@function");
__asm__("getpwent:");
__asm__("	ret");
__asm__(".globl getpwnam");
__asm__("	.type getpwnam,@function");
__asm__("getpwnam:");
__asm__("	ret");
__asm__(".globl getpwuid");
__asm__("	.type getpwuid,@function");
__asm__("getpwuid:");
__asm__("	ret");
__asm__(".globl getrlimit64");
__asm__("	.type getrlimit64,@function");
__asm__("getrlimit64:");
__asm__("	ret");
__asm__(".globl getservbyname");
__asm__("	.type getservbyname,@function");
__asm__("getservbyname:");
__asm__("	ret");
__asm__(".globl getservbyport");
__asm__("	.type getservbyport,@function");
__asm__("getservbyport:");
__asm__("	ret");
__asm__(".globl getservent");
__asm__("	.type getservent,@function");
__asm__("getservent:");
__asm__("	ret");
__asm__(".globl getsid");
__asm__("	.type getsid,@function");
__asm__("getsid:");
__asm__("	ret");
__asm__(".globl getsockname");
__asm__("	.type getsockname,@function");
__asm__("getsockname:");
__asm__("	ret");
__asm__(".globl getsubopt");
__asm__("	.type getsubopt,@function");
__asm__("getsubopt:");
__asm__("	ret");
__asm__(".globl getutxent");
__asm__("	.type getutxent,@function");
__asm__("getutxent:");
__asm__("	ret");
__asm__(".globl getutxid");
__asm__("	.type getutxid,@function");
__asm__("getutxid:");
__asm__("	ret");
__asm__(".globl getutxline");
__asm__("	.type getutxline,@function");
__asm__("getutxline:");
__asm__("	ret");
__asm__(".globl getw");
__asm__("	.type getw,@function");
__asm__("getw:");
__asm__("	ret");
__asm__(".globl getwd");
__asm__("	.type getwd,@function");
__asm__("getwd:");
__asm__("	ret");
__asm__(".globl glob");
__asm__("	.type glob,@function");
__asm__("glob:");
__asm__("	ret");
__asm__(".globl glob64");
__asm__("	.type glob64,@function");
__asm__("glob64:");
__asm__("	ret");
__asm__(".globl globfree");
__asm__("	.type globfree,@function");
__asm__("globfree:");
__asm__("	ret");
__asm__(".globl globfree64");
__asm__("	.type globfree64,@function");
__asm__("globfree64:");
__asm__("	ret");
__asm__(".globl gmtime");
__asm__("	.type gmtime,@function");
__asm__("gmtime:");
__asm__("	ret");
__asm__(".globl grantpt");
__asm__("	.type grantpt,@function");
__asm__("grantpt:");
__asm__("	ret");
__asm__(".globl hcreate");
__asm__("	.type hcreate,@function");
__asm__("hcreate:");
__asm__("	ret");
__asm__(".globl hsearch");
__asm__("	.type hsearch,@function");
__asm__("hsearch:");
__asm__("	ret");
__asm__(".globl htonl");
__asm__("	.type htonl,@function");
__asm__("htonl:");
__asm__("	ret");
__asm__(".globl htons");
__asm__("	.type htons,@function");
__asm__("htons:");
__asm__("	ret");
__asm__(".globl iconv");
__asm__("	.type iconv,@function");
__asm__("iconv:");
__asm__("	ret");
__asm__(".globl iconv_close");
__asm__("	.type iconv_close,@function");
__asm__("iconv_close:");
__asm__("	ret");
__asm__(".globl iconv_open");
__asm__("	.type iconv_open,@function");
__asm__("iconv_open:");
__asm__("	ret");
__asm__(".globl inet_addr");
__asm__("	.type inet_addr,@function");
__asm__("inet_addr:");
__asm__("	ret");
__asm__(".globl inet_aton");
__asm__("	.type inet_aton,@function");
__asm__("inet_aton:");
__asm__("	ret");
__asm__(".globl inet_ntoa");
__asm__("	.type inet_ntoa,@function");
__asm__("inet_ntoa:");
__asm__("	ret");
__asm__(".globl initgroups");
__asm__("	.type initgroups,@function");
__asm__("initgroups:");
__asm__("	ret");
__asm__(".globl insque");
__asm__("	.type insque,@function");
__asm__("insque:");
__asm__("	ret");
__asm__(".globl ioperm");
__asm__("	.type ioperm,@function");
__asm__("ioperm:");
__asm__("	ret");
__asm__(".globl iopl");
__asm__("	.type iopl,@function");
__asm__("iopl:");
__asm__("	ret");
__asm__(".globl isalnum");
__asm__("	.type isalnum,@function");
__asm__("isalnum:");
__asm__("	ret");
__asm__(".globl isalpha");
__asm__("	.type isalpha,@function");
__asm__("isalpha:");
__asm__("	ret");
__asm__(".globl isascii");
__asm__("	.type isascii,@function");
__asm__("isascii:");
__asm__("	ret");
__asm__(".globl iscntrl");
__asm__("	.type iscntrl,@function");
__asm__("iscntrl:");
__asm__("	ret");
__asm__(".globl isdigit");
__asm__("	.type isdigit,@function");
__asm__("isdigit:");
__asm__("	ret");
__asm__(".globl isgraph");
__asm__("	.type isgraph,@function");
__asm__("isgraph:");
__asm__("	ret");
__asm__(".globl islower");
__asm__("	.type islower,@function");
__asm__("islower:");
__asm__("	ret");
__asm__(".globl isprint");
__asm__("	.type isprint,@function");
__asm__("isprint:");
__asm__("	ret");
__asm__(".globl ispunct");
__asm__("	.type ispunct,@function");
__asm__("ispunct:");
__asm__("	ret");
__asm__(".globl isspace");
__asm__("	.type isspace,@function");
__asm__("isspace:");
__asm__("	ret");
__asm__(".globl isupper");
__asm__("	.type isupper,@function");
__asm__("isupper:");
__asm__("	ret");
__asm__(".globl iswblank");
__asm__("	.type iswblank,@function");
__asm__("iswblank:");
__asm__("	ret");
__asm__(".globl isxdigit");
__asm__("	.type isxdigit,@function");
__asm__("isxdigit:");
__asm__("	ret");
__asm__(".globl jrand48");
__asm__("	.type jrand48,@function");
__asm__("jrand48:");
__asm__("	ret");
__asm__(".globl killpg");
__asm__("	.type killpg,@function");
__asm__("killpg:");
__asm__("	ret");
__asm__(".globl l64a");
__asm__("	.type l64a,@function");
__asm__("l64a:");
__asm__("	ret");
__asm__(".globl labs");
__asm__("	.type labs,@function");
__asm__("labs:");
__asm__("	ret");
__asm__(".globl ldiv");
__asm__("	.type ldiv,@function");
__asm__("ldiv:");
__asm__("	ret");
__asm__(".globl lfind");
__asm__("	.type lfind,@function");
__asm__("lfind:");
__asm__("	ret");
__asm__(".globl listen");
__asm__("	.type listen,@function");
__asm__("listen:");
__asm__("	ret");
__asm__(".globl llabs");
__asm__("	.type llabs,@function");
__asm__("llabs:");
__asm__("	ret");
__asm__(".globl lldiv");
__asm__("	.type lldiv,@function");
__asm__("lldiv:");
__asm__("	ret");
__asm__(".globl localeconv");
__asm__("	.type localeconv,@function");
__asm__("localeconv:");
__asm__("	ret");
__asm__(".globl localtime");
__asm__("	.type localtime,@function");
__asm__("localtime:");
__asm__("	ret");
__asm__(".globl lockf");
__asm__("	.type lockf,@function");
__asm__("lockf:");
__asm__("	ret");
__asm__(".globl lockf64");
__asm__("	.type lockf64,@function");
__asm__("lockf64:");
__asm__("	ret");
__asm__(".globl lrand48");
__asm__("	.type lrand48,@function");
__asm__("lrand48:");
__asm__("	ret");
__asm__(".globl lsearch");
__asm__("	.type lsearch,@function");
__asm__("lsearch:");
__asm__("	ret");
__asm__(".globl makecontext");
__asm__("	.type makecontext,@function");
__asm__("makecontext:");
__asm__("	ret");
__asm__(".globl mblen");
__asm__("	.type mblen,@function");
__asm__("mblen:");
__asm__("	ret");
__asm__(".globl mbstowcs");
__asm__("	.type mbstowcs,@function");
__asm__("mbstowcs:");
__asm__("	ret");
__asm__(".globl mbtowc");
__asm__("	.type mbtowc,@function");
__asm__("mbtowc:");
__asm__("	ret");
__asm__(".globl memchr");
__asm__("	.type memchr,@function");
__asm__("memchr:");
__asm__("	ret");
__asm__(".globl memcmp");
__asm__("	.type memcmp,@function");
__asm__("memcmp:");
__asm__("	ret");
__asm__(".globl memcpy");
__asm__("	.type memcpy,@function");
__asm__("memcpy:");
__asm__("	ret");
__asm__(".globl memmem");
__asm__("	.type memmem,@function");
__asm__("memmem:");
__asm__("	ret");
__asm__(".globl memmove");
__asm__("	.type memmove,@function");
__asm__("memmove:");
__asm__("	ret");
__asm__(".globl memset");
__asm__("	.type memset,@function");
__asm__("memset:");
__asm__("	ret");
__asm__(".globl mkfifo");
__asm__("	.type mkfifo,@function");
__asm__("mkfifo:");
__asm__("	ret");
__asm__(".globl mkstemp");
__asm__("	.type mkstemp,@function");
__asm__("mkstemp:");
__asm__("	ret");
__asm__(".globl mktemp");
__asm__("	.type mktemp,@function");
__asm__("mktemp:");
__asm__("	ret");
__asm__(".globl mktime");
__asm__("	.type mktime,@function");
__asm__("mktime:");
__asm__("	ret");
__asm__(".globl mrand48");
__asm__("	.type mrand48,@function");
__asm__("mrand48:");
__asm__("	ret");
__asm__(".globl msgctl");
__asm__("	.type msgctl,@function");
__asm__("msgctl:");
__asm__("	ret");
__asm__(".globl msgget");
__asm__("	.type msgget,@function");
__asm__("msgget:");
__asm__("	ret");
__asm__(".globl msgrcv");
__asm__("	.type msgrcv,@function");
__asm__("msgrcv:");
__asm__("	ret");
__asm__(".globl msgsnd");
__asm__("	.type msgsnd,@function");
__asm__("msgsnd:");
__asm__("	ret");
__asm__(".globl nftw");
__asm__("	.type nftw,@function");
__asm__("nftw:");
__asm__("	ret");
__asm__(".globl nftw64");
__asm__("	.type nftw64,@function");
__asm__("nftw64:");
__asm__("	ret");
__asm__(".globl nice");
__asm__("	.type nice,@function");
__asm__("nice:");
__asm__("	ret");
__asm__(".globl nl_langinfo");
__asm__("	.type nl_langinfo,@function");
__asm__("nl_langinfo:");
__asm__("	ret");
__asm__(".globl nrand48");
__asm__("	.type nrand48,@function");
__asm__("nrand48:");
__asm__("	ret");
__asm__(".globl obstack_free");
__asm__("	.type obstack_free,@function");
__asm__("obstack_free:");
__asm__("	ret");
__asm__(".globl openlog");
__asm__("	.type openlog,@function");
__asm__("openlog:");
__asm__("	ret");
__asm__(".globl pclose");
__asm__("	.type pclose,@function");
__asm__("pclose:");
__asm__("	ret");
__asm__(".globl perror");
__asm__("	.type perror,@function");
__asm__("perror:");
__asm__("	ret");
__asm__(".globl popen");
__asm__("	.type popen,@function");
__asm__("popen:");
__asm__("	ret");
__asm__(".globl printf");
__asm__("	.type printf,@function");
__asm__("printf:");
__asm__("	ret");
__asm__(".globl psignal");
__asm__("	.type psignal,@function");
__asm__("psignal:");
__asm__("	ret");
__asm__(".globl ptsname");
__asm__("	.type ptsname,@function");
__asm__("ptsname:");
__asm__("	ret");
__asm__(".globl putc_unlocked");
__asm__("	.type putc_unlocked,@function");
__asm__("putc_unlocked:");
__asm__("	ret");
__asm__(".globl putchar");
__asm__("	.type putchar,@function");
__asm__("putchar:");
__asm__("	ret");
__asm__(".globl putchar_unlocked");
__asm__("	.type putchar_unlocked,@function");
__asm__("putchar_unlocked:");
__asm__("	ret");
__asm__(".globl putenv");
__asm__("	.type putenv,@function");
__asm__("putenv:");
__asm__("	ret");
__asm__(".globl putmsg");
__asm__("	.type putmsg,@function");
__asm__("putmsg:");
__asm__("	ret");
__asm__(".globl pututxline");
__asm__("	.type pututxline,@function");
__asm__("pututxline:");
__asm__("	ret");
__asm__(".globl putw");
__asm__("	.type putw,@function");
__asm__("putw:");
__asm__("	ret");
__asm__(".globl qsort");
__asm__("	.type qsort,@function");
__asm__("qsort:");
__asm__("	ret");
__asm__(".globl raise");
__asm__("	.type raise,@function");
__asm__("raise:");
__asm__("	ret");
__asm__(".globl rand");
__asm__("	.type rand,@function");
__asm__("rand:");
__asm__("	ret");
__asm__(".globl remove");
__asm__("	.type remove,@function");
__asm__("remove:");
__asm__("	ret");
__asm__(".globl remque");
__asm__("	.type remque,@function");
__asm__("remque:");
__asm__("	ret");
__asm__(".globl rename");
__asm__("	.type rename,@function");
__asm__("rename:");
__asm__("	ret");
__asm__(".globl rewind");
__asm__("	.type rewind,@function");
__asm__("rewind:");
__asm__("	ret");
__asm__(".globl rewinddir");
__asm__("	.type rewinddir,@function");
__asm__("rewinddir:");
__asm__("	ret");
__asm__(".globl scanf");
__asm__("	.type scanf,@function");
__asm__("scanf:");
__asm__("	ret");
__asm__(".globl seed48");
__asm__("	.type seed48,@function");
__asm__("seed48:");
__asm__("	ret");
__asm__(".globl seekdir");
__asm__("	.type seekdir,@function");
__asm__("seekdir:");
__asm__("	ret");
__asm__(".globl semctl");
__asm__("	.type semctl,@function");
__asm__("semctl:");
__asm__("	ret");
__asm__(".globl semget");
__asm__("	.type semget,@function");
__asm__("semget:");
__asm__("	ret");
__asm__(".globl semop");
__asm__("	.type semop,@function");
__asm__("semop:");
__asm__("	ret");
__asm__(".globl setbuf");
__asm__("	.type setbuf,@function");
__asm__("setbuf:");
__asm__("	ret");
__asm__(".globl setcontext");
__asm__("	.type setcontext,@function");
__asm__("setcontext:");
__asm__("	ret");
__asm__(".globl setegid");
__asm__("	.type setegid,@function");
__asm__("setegid:");
__asm__("	ret");
__asm__(".globl seteuid");
__asm__("	.type seteuid,@function");
__asm__("seteuid:");
__asm__("	ret");
__asm__(".globl setgrent");
__asm__("	.type setgrent,@function");
__asm__("setgrent:");
__asm__("	ret");
__asm__(".globl sethostent");
__asm__("	.type sethostent,@function");
__asm__("sethostent:");
__asm__("	ret");
__asm__(".globl sethostid");
__asm__("	.type sethostid,@function");
__asm__("sethostid:");
__asm__("	ret");
__asm__(".globl sethostname");
__asm__("	.type sethostname,@function");
__asm__("sethostname:");
__asm__("	ret");
__asm__(".globl setlocale");
__asm__("	.type setlocale,@function");
__asm__("setlocale:");
__asm__("	ret");
__asm__(".globl setnetent");
__asm__("	.type setnetent,@function");
__asm__("setnetent:");
__asm__("	ret");
__asm__(".globl setpgrp");
__asm__("	.type setpgrp,@function");
__asm__("setpgrp:");
__asm__("	ret");
__asm__(".globl setpriority");
__asm__("	.type setpriority,@function");
__asm__("setpriority:");
__asm__("	ret");
__asm__(".globl setprotoent");
__asm__("	.type setprotoent,@function");
__asm__("setprotoent:");
__asm__("	ret");
__asm__(".globl setpwent");
__asm__("	.type setpwent,@function");
__asm__("setpwent:");
__asm__("	ret");
__asm__(".globl setrlimit");
__asm__("	.type setrlimit,@function");
__asm__("setrlimit:");
__asm__("	ret");
__asm__(".globl setservent");
__asm__("	.type setservent,@function");
__asm__("setservent:");
__asm__("	ret");
__asm__(".globl setsockopt");
__asm__("	.type setsockopt,@function");
__asm__("setsockopt:");
__asm__("	ret");
__asm__(".globl setutxent");
__asm__("	.type setutxent,@function");
__asm__("setutxent:");
__asm__("	ret");
__asm__(".globl shmat");
__asm__("	.type shmat,@function");
__asm__("shmat:");
__asm__("	ret");
__asm__(".globl shmctl");
__asm__("	.type shmctl,@function");
__asm__("shmctl:");
__asm__("	ret");
__asm__(".globl shmdt");
__asm__("	.type shmdt,@function");
__asm__("shmdt:");
__asm__("	ret");
__asm__(".globl shmget");
__asm__("	.type shmget,@function");
__asm__("shmget:");
__asm__("	ret");
__asm__(".globl sigaddset");
__asm__("	.type sigaddset,@function");
__asm__("sigaddset:");
__asm__("	ret");
__asm__(".globl sigandset");
__asm__("	.type sigandset,@function");
__asm__("sigandset:");
__asm__("	ret");
__asm__(".globl sigdelset");
__asm__("	.type sigdelset,@function");
__asm__("sigdelset:");
__asm__("	ret");
__asm__(".globl sigemptyset");
__asm__("	.type sigemptyset,@function");
__asm__("sigemptyset:");
__asm__("	ret");
__asm__(".globl sigfillset");
__asm__("	.type sigfillset,@function");
__asm__("sigfillset:");
__asm__("	ret");
__asm__(".globl siggetmask");
__asm__("	.type siggetmask,@function");
__asm__("siggetmask:");
__asm__("	ret");
__asm__(".globl sighold");
__asm__("	.type sighold,@function");
__asm__("sighold:");
__asm__("	ret");
__asm__(".globl sigignore");
__asm__("	.type sigignore,@function");
__asm__("sigignore:");
__asm__("	ret");
__asm__(".globl siginterrupt");
__asm__("	.type siginterrupt,@function");
__asm__("siginterrupt:");
__asm__("	ret");
__asm__(".globl sigisemptyset");
__asm__("	.type sigisemptyset,@function");
__asm__("sigisemptyset:");
__asm__("	ret");
__asm__(".globl sigismember");
__asm__("	.type sigismember,@function");
__asm__("sigismember:");
__asm__("	ret");
__asm__(".globl sigorset");
__asm__("	.type sigorset,@function");
__asm__("sigorset:");
__asm__("	ret");
__asm__(".globl sigpending");
__asm__("	.type sigpending,@function");
__asm__("sigpending:");
__asm__("	ret");
__asm__(".globl sigrelse");
__asm__("	.type sigrelse,@function");
__asm__("sigrelse:");
__asm__("	ret");
__asm__(".globl sigset");
__asm__("	.type sigset,@function");
__asm__("sigset:");
__asm__("	ret");
__asm__(".globl sigstack");
__asm__("	.type sigstack,@function");
__asm__("sigstack:");
__asm__("	ret");
__asm__(".globl sprintf");
__asm__("	.type sprintf,@function");
__asm__("sprintf:");
__asm__("	ret");
__asm__(".globl srand48");
__asm__("	.type srand48,@function");
__asm__("srand48:");
__asm__("	ret");
__asm__(".globl sscanf");
__asm__("	.type sscanf,@function");
__asm__("sscanf:");
__asm__("	ret");
__asm__(".globl statvfs");
__asm__("	.type statvfs,@function");
__asm__("statvfs:");
__asm__("	ret");
__asm__(".globl stime");
__asm__("	.type stime,@function");
__asm__("stime:");
__asm__("	ret");
__asm__(".globl strcat");
__asm__("	.type strcat,@function");
__asm__("strcat:");
__asm__("	ret");
__asm__(".globl strchr");
__asm__("	.type strchr,@function");
__asm__("strchr:");
__asm__("	ret");
__asm__(".globl strcmp");
__asm__("	.type strcmp,@function");
__asm__("strcmp:");
__asm__("	ret");
__asm__(".globl strcoll");
__asm__("	.type strcoll,@function");
__asm__("strcoll:");
__asm__("	ret");
__asm__(".globl strcpy");
__asm__("	.type strcpy,@function");
__asm__("strcpy:");
__asm__("	ret");
__asm__(".globl strcspn");
__asm__("	.type strcspn,@function");
__asm__("strcspn:");
__asm__("	ret");
__asm__(".globl strerror");
__asm__("	.type strerror,@function");
__asm__("strerror:");
__asm__("	ret");
__asm__(".globl strfmon");
__asm__("	.type strfmon,@function");
__asm__("strfmon:");
__asm__("	ret");
__asm__(".globl strfry");
__asm__("	.type strfry,@function");
__asm__("strfry:");
__asm__("	ret");
__asm__(".globl strftime");
__asm__("	.type strftime,@function");
__asm__("strftime:");
__asm__("	ret");
__asm__(".globl strlen");
__asm__("	.type strlen,@function");
__asm__("strlen:");
__asm__("	ret");
__asm__(".globl strncat");
__asm__("	.type strncat,@function");
__asm__("strncat:");
__asm__("	ret");
__asm__(".globl strncmp");
__asm__("	.type strncmp,@function");
__asm__("strncmp:");
__asm__("	ret");
__asm__(".globl strncpy");
__asm__("	.type strncpy,@function");
__asm__("strncpy:");
__asm__("	ret");
__asm__(".globl strpbrk");
__asm__("	.type strpbrk,@function");
__asm__("strpbrk:");
__asm__("	ret");
__asm__(".globl strptime");
__asm__("	.type strptime,@function");
__asm__("strptime:");
__asm__("	ret");
__asm__(".globl strrchr");
__asm__("	.type strrchr,@function");
__asm__("strrchr:");
__asm__("	ret");
__asm__(".globl strsignal");
__asm__("	.type strsignal,@function");
__asm__("strsignal:");
__asm__("	ret");
__asm__(".globl strspn");
__asm__("	.type strspn,@function");
__asm__("strspn:");
__asm__("	ret");
__asm__(".globl strstr");
__asm__("	.type strstr,@function");
__asm__("strstr:");
__asm__("	ret");
__asm__(".globl strtoimax");
__asm__("	.type strtoimax,@function");
__asm__("strtoimax:");
__asm__("	ret");
__asm__(".globl strtok");
__asm__("	.type strtok,@function");
__asm__("strtok:");
__asm__("	ret");
__asm__(".globl strtoumax");
__asm__("	.type strtoumax,@function");
__asm__("strtoumax:");
__asm__("	ret");
__asm__(".globl strxfrm");
__asm__("	.type strxfrm,@function");
__asm__("strxfrm:");
__asm__("	ret");
__asm__(".globl swab");
__asm__("	.type swab,@function");
__asm__("swab:");
__asm__("	ret");
__asm__(".globl swapcontext");
__asm__("	.type swapcontext,@function");
__asm__("swapcontext:");
__asm__("	ret");
__asm__(".globl sync");
__asm__("	.type sync,@function");
__asm__("sync:");
__asm__("	ret");
__asm__(".globl syslog");
__asm__("	.type syslog,@function");
__asm__("syslog:");
__asm__("	ret");
__asm__(".globl tcflow");
__asm__("	.type tcflow,@function");
__asm__("tcflow:");
__asm__("	ret");
__asm__(".globl tcflush");
__asm__("	.type tcflush,@function");
__asm__("tcflush:");
__asm__("	ret");
__asm__(".globl tcgetpgrp");
__asm__("	.type tcgetpgrp,@function");
__asm__("tcgetpgrp:");
__asm__("	ret");
__asm__(".globl tcgetsid");
__asm__("	.type tcgetsid,@function");
__asm__("tcgetsid:");
__asm__("	ret");
__asm__(".globl tcsendbreak");
__asm__("	.type tcsendbreak,@function");
__asm__("tcsendbreak:");
__asm__("	ret");
__asm__(".globl tcsetattr");
__asm__("	.type tcsetattr,@function");
__asm__("tcsetattr:");
__asm__("	ret");
__asm__(".globl tcsetpgrp");
__asm__("	.type tcsetpgrp,@function");
__asm__("tcsetpgrp:");
__asm__("	ret");
__asm__(".globl telldir");
__asm__("	.type telldir,@function");
__asm__("telldir:");
__asm__("	ret");
__asm__(".globl tempnam");
__asm__("	.type tempnam,@function");
__asm__("tempnam:");
__asm__("	ret");
__asm__(".globl time");
__asm__("	.type time,@function");
__asm__("time:");
__asm__("	ret");
__asm__(".globl tmpfile64");
__asm__("	.type tmpfile64,@function");
__asm__("tmpfile64:");
__asm__("	ret");
__asm__(".globl tmpfile");
__asm__("	.type tmpfile,@function");
__asm__("tmpfile:");
__asm__("	ret");
__asm__(".globl tmpnam");
__asm__("	.type tmpnam,@function");
__asm__("tmpnam:");
__asm__("	ret");
__asm__(".globl toascii");
__asm__("	.type toascii,@function");
__asm__("toascii:");
__asm__("	ret");
__asm__(".globl tolower");
__asm__("	.type tolower,@function");
__asm__("tolower:");
__asm__("	ret");
__asm__(".globl toupper");
__asm__("	.type toupper,@function");
__asm__("toupper:");
__asm__("	ret");
__asm__(".globl towlower");
__asm__("	.type towlower,@function");
__asm__("towlower:");
__asm__("	ret");
__asm__(".globl towupper");
__asm__("	.type towupper,@function");
__asm__("towupper:");
__asm__("	ret");
__asm__(".globl truncate");
__asm__("	.type truncate,@function");
__asm__("truncate:");
__asm__("	ret");
__asm__(".globl truncate64");
__asm__("	.type truncate64,@function");
__asm__("truncate64:");
__asm__("	ret");
__asm__(".globl ttyname");
__asm__("	.type ttyname,@function");
__asm__("ttyname:");
__asm__("	ret");
__asm__(".globl ualarm");
__asm__("	.type ualarm,@function");
__asm__("ualarm:");
__asm__("	ret");
__asm__(".globl uname");
__asm__("	.type uname,@function");
__asm__("uname:");
__asm__("	ret");
__asm__(".globl unlockpt");
__asm__("	.type unlockpt,@function");
__asm__("unlockpt:");
__asm__("	ret");
__asm__(".globl usleep");
__asm__("	.type usleep,@function");
__asm__("usleep:");
__asm__("	ret");
__asm__(".globl utime");
__asm__("	.type utime,@function");
__asm__("utime:");
__asm__("	ret");
__asm__(".globl verrx");
__asm__("	.type verrx,@function");
__asm__("verrx:");
__asm__("	ret");
__asm__(".globl vfprintf");
__asm__("	.type vfprintf,@function");
__asm__("vfprintf:");
__asm__("	ret");
__asm__(".globl vprintf");
__asm__("	.type vprintf,@function");
__asm__("vprintf:");
__asm__("	ret");
__asm__(".globl waitid");
__asm__("	.type waitid,@function");
__asm__("waitid:");
__asm__("	ret");
__asm__(".globl warn");
__asm__("	.type warn,@function");
__asm__("warn:");
__asm__("	ret");
__asm__(".globl warnx");
__asm__("	.type warnx,@function");
__asm__("warnx:");
__asm__("	ret");
__asm__(".globl wcscat");
__asm__("	.type wcscat,@function");
__asm__("wcscat:");
__asm__("	ret");
__asm__(".globl wcschr");
__asm__("	.type wcschr,@function");
__asm__("wcschr:");
__asm__("	ret");
__asm__(".globl wcscmp");
__asm__("	.type wcscmp,@function");
__asm__("wcscmp:");
__asm__("	ret");
__asm__(".globl wcscoll");
__asm__("	.type wcscoll,@function");
__asm__("wcscoll:");
__asm__("	ret");
__asm__(".globl wcscpy");
__asm__("	.type wcscpy,@function");
__asm__("wcscpy:");
__asm__("	ret");
__asm__(".globl wcscspn");
__asm__("	.type wcscspn,@function");
__asm__("wcscspn:");
__asm__("	ret");
__asm__(".globl wcsdup");
__asm__("	.type wcsdup,@function");
__asm__("wcsdup:");
__asm__("	ret");
__asm__(".globl wcsncat");
__asm__("	.type wcsncat,@function");
__asm__("wcsncat:");
__asm__("	ret");
__asm__(".globl wcsncmp");
__asm__("	.type wcsncmp,@function");
__asm__("wcsncmp:");
__asm__("	ret");
__asm__(".globl wcsncpy");
__asm__("	.type wcsncpy,@function");
__asm__("wcsncpy:");
__asm__("	ret");
__asm__(".globl wcspbrk");
__asm__("	.type wcspbrk,@function");
__asm__("wcspbrk:");
__asm__("	ret");
__asm__(".globl wcsrchr");
__asm__("	.type wcsrchr,@function");
__asm__("wcsrchr:");
__asm__("	ret");
__asm__(".globl wcsspn");
__asm__("	.type wcsspn,@function");
__asm__("wcsspn:");
__asm__("	ret");
__asm__(".globl wcsstr");
__asm__("	.type wcsstr,@function");
__asm__("wcsstr:");
__asm__("	ret");
__asm__(".globl wcstoimax");
__asm__("	.type wcstoimax,@function");
__asm__("wcstoimax:");
__asm__("	ret");
__asm__(".globl wcstok");
__asm__("	.type wcstok,@function");
__asm__("wcstok:");
__asm__("	ret");
__asm__(".globl wcstombs");
__asm__("	.type wcstombs,@function");
__asm__("wcstombs:");
__asm__("	ret");
__asm__(".globl wcstoumax");
__asm__("	.type wcstoumax,@function");
__asm__("wcstoumax:");
__asm__("	ret");
__asm__(".globl wcswidth");
__asm__("	.type wcswidth,@function");
__asm__("wcswidth:");
__asm__("	ret");
__asm__(".globl wcsxfrm");
__asm__("	.type wcsxfrm,@function");
__asm__("wcsxfrm:");
__asm__("	ret");
__asm__(".globl wctob");
__asm__("	.type wctob,@function");
__asm__("wctob:");
__asm__("	ret");
__asm__(".globl wctomb");
__asm__("	.type wctomb,@function");
__asm__("wctomb:");
__asm__("	ret");
__asm__(".globl wctrans");
__asm__("	.type wctrans,@function");
__asm__("wctrans:");
__asm__("	ret");
__asm__(".globl wcwidth");
__asm__("	.type wcwidth,@function");
__asm__("wcwidth:");
__asm__("	ret");
__asm__(".globl wmemchr");
__asm__("	.type wmemchr,@function");
__asm__("wmemchr:");
__asm__("	ret");
__asm__(".globl wmemcmp");
__asm__("	.type wmemcmp,@function");
__asm__("wmemcmp:");
__asm__("	ret");
__asm__(".globl wmemcpy");
__asm__("	.type wmemcpy,@function");
__asm__("wmemcpy:");
__asm__("	ret");
__asm__(".globl wmemmove");
__asm__("	.type wmemmove,@function");
__asm__("wmemmove:");
__asm__("	ret");
__asm__(".globl wmemset");
__asm__("	.type wmemset,@function");
__asm__("wmemset:");
__asm__("	ret");
__asm__(".globl wordexp");
__asm__("	.type wordexp,@function");
__asm__("wordexp:");
__asm__("	ret");
__asm__(".globl wordfree");
__asm__("	.type wordfree,@function");
__asm__("wordfree:");
__asm__("	ret");
__asm__(".globl __errno_location");
__asm__("	.type __errno_location,@function");
__asm__("__errno_location:");
__asm__("	ret");
__asm__(".globl accept");
__asm__("	.type accept,@function");
__asm__("accept:");
__asm__("	ret");
__asm__(".globl close");
__asm__("	.type close,@function");
__asm__("close:");
__asm__("	ret");
__asm__(".globl connect");
__asm__("	.type connect,@function");
__asm__("connect:");
__asm__("	ret");
__asm__(".globl fcntl");
__asm__("	.type fcntl,@function");
__asm__("fcntl:");
__asm__("	ret");
__asm__(".globl fsync");
__asm__("	.type fsync,@function");
__asm__("fsync:");
__asm__("	ret");
__asm__(".globl longjmp");
__asm__("	.type longjmp,@function");
__asm__("longjmp:");
__asm__("	ret");
__asm__(".globl lseek");
__asm__("	.type lseek,@function");
__asm__("lseek:");
__asm__("	ret");
__asm__(".globl msync");
__asm__("	.type msync,@function");
__asm__("msync:");
__asm__("	ret");
__asm__(".globl nanosleep");
__asm__("	.type nanosleep,@function");
__asm__("nanosleep:");
__asm__("	ret");
__asm__(".globl open");
__asm__("	.type open,@function");
__asm__("open:");
__asm__("	ret");
__asm__(".globl pause");
__asm__("	.type pause,@function");
__asm__("pause:");
__asm__("	ret");
__asm__(".globl read");
__asm__("	.type read,@function");
__asm__("read:");
__asm__("	ret");
__asm__(".globl recv");
__asm__("	.type recv,@function");
__asm__("recv:");
__asm__("	ret");
__asm__(".globl recvfrom");
__asm__("	.type recvfrom,@function");
__asm__("recvfrom:");
__asm__("	ret");
__asm__(".globl recvmsg");
__asm__("	.type recvmsg,@function");
__asm__("recvmsg:");
__asm__("	ret");
__asm__(".globl send");
__asm__("	.type send,@function");
__asm__("send:");
__asm__("	ret");
__asm__(".globl sendmsg");
__asm__("	.type sendmsg,@function");
__asm__("sendmsg:");
__asm__("	ret");
__asm__(".globl sendto");
__asm__("	.type sendto,@function");
__asm__("sendto:");
__asm__("	ret");
__asm__(".globl sigaction");
__asm__("	.type sigaction,@function");
__asm__("sigaction:");
__asm__("	ret");
__asm__(".globl siglongjmp");
__asm__("	.type siglongjmp,@function");
__asm__("siglongjmp:");
__asm__("	ret");
__asm__(".globl sigwait");
__asm__("	.type sigwait,@function");
__asm__("sigwait:");
__asm__("	ret");
__asm__(".globl system");
__asm__("	.type system,@function");
__asm__("system:");
__asm__("	ret");
__asm__(".globl tcdrain");
__asm__("	.type tcdrain,@function");
__asm__("tcdrain:");
__asm__("	ret");
__asm__(".globl wait");
__asm__("	.type wait,@function");
__asm__("wait:");
__asm__("	ret");
__asm__(".globl waitpid");
__asm__("	.type waitpid,@function");
__asm__("waitpid:");
__asm__("	ret");
__asm__(".globl write");
__asm__("	.type write,@function");
__asm__("write:");
__asm__("	ret");
__asm__(".globl access");
__asm__("	.type access,@function");
__asm__("access:");
__asm__("	ret");
__asm__(".globl bcmp");
__asm__("	.type bcmp,@function");
__asm__("bcmp:");
__asm__("	ret");
__asm__(".globl brk");
__asm__("	.type brk,@function");
__asm__("brk:");
__asm__("	ret");
__asm__(".globl bzero");
__asm__("	.type bzero,@function");
__asm__("bzero:");
__asm__("	ret");
__asm__(".globl calloc");
__asm__("	.type calloc,@function");
__asm__("calloc:");
__asm__("	ret");
__asm__(".globl chdir");
__asm__("	.type chdir,@function");
__asm__("chdir:");
__asm__("	ret");
__asm__(".globl chmod");
__asm__("	.type chmod,@function");
__asm__("chmod:");
__asm__("	ret");
__asm__(".globl closedir");
__asm__("	.type closedir,@function");
__asm__("closedir:");
__asm__("	ret");
__asm__(".globl daylight");
__asm__("	.type daylight,@function");
__asm__("daylight:");
__asm__("	ret");
__asm__(".globl dup");
__asm__("	.type dup,@function");
__asm__("dup:");
__asm__("	ret");
__asm__(".globl dup2");
__asm__("	.type dup2,@function");
__asm__("dup2:");
__asm__("	ret");
__asm__(".globl endutent");
__asm__("	.type endutent,@function");
__asm__("endutent:");
__asm__("	ret");
__asm__(".globl execve");
__asm__("	.type execve,@function");
__asm__("execve:");
__asm__("	ret");
__asm__(".globl fchdir");
__asm__("	.type fchdir,@function");
__asm__("fchdir:");
__asm__("	ret");
__asm__(".globl fchmod");
__asm__("	.type fchmod,@function");
__asm__("fchmod:");
__asm__("	ret");
__asm__(".globl fchown");
__asm__("	.type fchown,@function");
__asm__("fchown:");
__asm__("	ret");
__asm__(".globl feof");
__asm__("	.type feof,@function");
__asm__("feof:");
__asm__("	ret");
__asm__(".globl ferror");
__asm__("	.type ferror,@function");
__asm__("ferror:");
__asm__("	ret");
__asm__(".globl fflush");
__asm__("	.type fflush,@function");
__asm__("fflush:");
__asm__("	ret");
__asm__(".globl ffs");
__asm__("	.type ffs,@function");
__asm__("ffs:");
__asm__("	ret");
__asm__(".globl fgetc");
__asm__("	.type fgetc,@function");
__asm__("fgetc:");
__asm__("	ret");
__asm__(".globl fgetpos");
__asm__("	.type fgetpos,@function");
__asm__("fgetpos:");
__asm__("	ret");
__asm__(".globl fgets");
__asm__("	.type fgets,@function");
__asm__("fgets:");
__asm__("	ret");
__asm__(".globl flock");
__asm__("	.type flock,@function");
__asm__("flock:");
__asm__("	ret");
__asm__(".globl fork");
__asm__("	.type fork,@function");
__asm__("fork:");
__asm__("	ret");
__asm__(".globl fputs");
__asm__("	.type fputs,@function");
__asm__("fputs:");
__asm__("	ret");
__asm__(".globl fread");
__asm__("	.type fread,@function");
__asm__("fread:");
__asm__("	ret");
__asm__(".globl free");
__asm__("	.type free,@function");
__asm__("free:");
__asm__("	ret");
__asm__(".globl fsetpos");
__asm__("	.type fsetpos,@function");
__asm__("fsetpos:");
__asm__("	ret");
__asm__(".globl fstatfs");
__asm__("	.type fstatfs,@function");
__asm__("fstatfs:");
__asm__("	ret");
__asm__(".globl ftell");
__asm__("	.type ftell,@function");
__asm__("ftell:");
__asm__("	ret");
__asm__(".globl fwrite");
__asm__("	.type fwrite,@function");
__asm__("fwrite:");
__asm__("	ret");
__asm__(".globl getc");
__asm__("	.type getc,@function");
__asm__("getc:");
__asm__("	ret");
__asm__(".globl getegid");
__asm__("	.type getegid,@function");
__asm__("getegid:");
__asm__("	ret");
__asm__(".globl geteuid");
__asm__("	.type geteuid,@function");
__asm__("geteuid:");
__asm__("	ret");
__asm__(".globl getgid");
__asm__("	.type getgid,@function");
__asm__("getgid:");
__asm__("	ret");
__asm__(".globl getgroups");
__asm__("	.type getgroups,@function");
__asm__("getgroups:");
__asm__("	ret");
__asm__(".globl gethostname");
__asm__("	.type gethostname,@function");
__asm__("gethostname:");
__asm__("	ret");
__asm__(".globl getitimer");
__asm__("	.type getitimer,@function");
__asm__("getitimer:");
__asm__("	ret");
__asm__(".globl getpeername");
__asm__("	.type getpeername,@function");
__asm__("getpeername:");
__asm__("	ret");
__asm__(".globl getpgid");
__asm__("	.type getpgid,@function");
__asm__("getpgid:");
__asm__("	ret");
__asm__(".globl getpid");
__asm__("	.type getpid,@function");
__asm__("getpid:");
__asm__("	ret");
__asm__(".globl getrlimit");
__asm__("	.type getrlimit,@function");
__asm__("getrlimit:");
__asm__("	ret");
__asm__(".globl getrusage");
__asm__("	.type getrusage,@function");
__asm__("getrusage:");
__asm__("	ret");
__asm__(".globl gets");
__asm__("	.type gets,@function");
__asm__("gets:");
__asm__("	ret");
__asm__(".globl getsockopt");
__asm__("	.type getsockopt,@function");
__asm__("getsockopt:");
__asm__("	ret");
__asm__(".globl getuid");
__asm__("	.type getuid,@function");
__asm__("getuid:");
__asm__("	ret");
__asm__(".globl getutent");
__asm__("	.type getutent,@function");
__asm__("getutent:");
__asm__("	ret");
__asm__(".globl index");
__asm__("	.type index,@function");
__asm__("index:");
__asm__("	ret");
__asm__(".globl initstate");
__asm__("	.type initstate,@function");
__asm__("initstate:");
__asm__("	ret");
__asm__(".globl ioctl");
__asm__("	.type ioctl,@function");
__asm__("ioctl:");
__asm__("	ret");
__asm__(".globl isinf");
__asm__("	.type isinf,@function");
__asm__("isinf:");
__asm__("	ret");
__asm__(".globl iswalnum");
__asm__("	.type iswalnum,@function");
__asm__("iswalnum:");
__asm__("	ret");
__asm__(".globl iswalpha");
__asm__("	.type iswalpha,@function");
__asm__("iswalpha:");
__asm__("	ret");
__asm__(".globl iswcntrl");
__asm__("	.type iswcntrl,@function");
__asm__("iswcntrl:");
__asm__("	ret");
__asm__(".globl iswctype");
__asm__("	.type iswctype,@function");
__asm__("iswctype:");
__asm__("	ret");
__asm__(".globl iswdigit");
__asm__("	.type iswdigit,@function");
__asm__("iswdigit:");
__asm__("	ret");
__asm__(".globl iswgraph");
__asm__("	.type iswgraph,@function");
__asm__("iswgraph:");
__asm__("	ret");
__asm__(".globl iswlower");
__asm__("	.type iswlower,@function");
__asm__("iswlower:");
__asm__("	ret");
__asm__(".globl iswprint");
__asm__("	.type iswprint,@function");
__asm__("iswprint:");
__asm__("	ret");
__asm__(".globl iswpunct");
__asm__("	.type iswpunct,@function");
__asm__("iswpunct:");
__asm__("	ret");
__asm__(".globl iswspace");
__asm__("	.type iswspace,@function");
__asm__("iswspace:");
__asm__("	ret");
__asm__(".globl iswupper");
__asm__("	.type iswupper,@function");
__asm__("iswupper:");
__asm__("	ret");
__asm__(".globl iswxdigit");
__asm__("	.type iswxdigit,@function");
__asm__("iswxdigit:");
__asm__("	ret");
__asm__(".globl kill");
__asm__("	.type kill,@function");
__asm__("kill:");
__asm__("	ret");
__asm__(".globl lchown");
__asm__("	.type lchown,@function");
__asm__("lchown:");
__asm__("	ret");
__asm__(".globl link");
__asm__("	.type link,@function");
__asm__("link:");
__asm__("	ret");
__asm__(".globl malloc");
__asm__("	.type malloc,@function");
__asm__("malloc:");
__asm__("	ret");
__asm__(".globl mbrlen");
__asm__("	.type mbrlen,@function");
__asm__("mbrlen:");
__asm__("	ret");
__asm__(".globl mbrtowc");
__asm__("	.type mbrtowc,@function");
__asm__("mbrtowc:");
__asm__("	ret");
__asm__(".globl mbsinit");
__asm__("	.type mbsinit,@function");
__asm__("mbsinit:");
__asm__("	ret");
__asm__(".globl mbsnrtowcs");
__asm__("	.type mbsnrtowcs,@function");
__asm__("mbsnrtowcs:");
__asm__("	ret");
__asm__(".globl mbsrtowcs");
__asm__("	.type mbsrtowcs,@function");
__asm__("mbsrtowcs:");
__asm__("	ret");
__asm__(".globl memccpy");
__asm__("	.type memccpy,@function");
__asm__("memccpy:");
__asm__("	ret");
__asm__(".globl mkdir");
__asm__("	.type mkdir,@function");
__asm__("mkdir:");
__asm__("	ret");
__asm__(".globl mlock");
__asm__("	.type mlock,@function");
__asm__("mlock:");
__asm__("	ret");
__asm__(".globl mlockall");
__asm__("	.type mlockall,@function");
__asm__("mlockall:");
__asm__("	ret");
__asm__(".globl mmap");
__asm__("	.type mmap,@function");
__asm__("mmap:");
__asm__("	ret");
__asm__(".globl mprotect");
__asm__("	.type mprotect,@function");
__asm__("mprotect:");
__asm__("	ret");
__asm__(".globl munlock");
__asm__("	.type munlock,@function");
__asm__("munlock:");
__asm__("	ret");
__asm__(".globl munlockall");
__asm__("	.type munlockall,@function");
__asm__("munlockall:");
__asm__("	ret");
__asm__(".globl munmap");
__asm__("	.type munmap,@function");
__asm__("munmap:");
__asm__("	ret");
__asm__(".globl opendir");
__asm__("	.type opendir,@function");
__asm__("opendir:");
__asm__("	ret");
__asm__(".globl pathconf");
__asm__("	.type pathconf,@function");
__asm__("pathconf:");
__asm__("	ret");
__asm__(".globl pipe");
__asm__("	.type pipe,@function");
__asm__("pipe:");
__asm__("	ret");
__asm__(".globl poll");
__asm__("	.type poll,@function");
__asm__("poll:");
__asm__("	ret");
__asm__(".globl putc");
__asm__("	.type putc,@function");
__asm__("putc:");
__asm__("	ret");
__asm__(".globl puts");
__asm__("	.type puts,@function");
__asm__("puts:");
__asm__("	ret");
__asm__(".globl random");
__asm__("	.type random,@function");
__asm__("random:");
__asm__("	ret");
__asm__(".globl readdir");
__asm__("	.type readdir,@function");
__asm__("readdir:");
__asm__("	ret");
__asm__(".globl readlink");
__asm__("	.type readlink,@function");
__asm__("readlink:");
__asm__("	ret");
__asm__(".globl readv");
__asm__("	.type readv,@function");
__asm__("readv:");
__asm__("	ret");
__asm__(".globl realloc");
__asm__("	.type realloc,@function");
__asm__("realloc:");
__asm__("	ret");
__asm__(".globl regcomp");
__asm__("	.type regcomp,@function");
__asm__("regcomp:");
__asm__("	ret");
__asm__(".globl regerror");
__asm__("	.type regerror,@function");
__asm__("regerror:");
__asm__("	ret");
__asm__(".globl regexec");
__asm__("	.type regexec,@function");
__asm__("regexec:");
__asm__("	ret");
__asm__(".globl regfree");
__asm__("	.type regfree,@function");
__asm__("regfree:");
__asm__("	ret");
__asm__(".globl rindex");
__asm__("	.type rindex,@function");
__asm__("rindex:");
__asm__("	ret");
__asm__(".globl rmdir");
__asm__("	.type rmdir,@function");
__asm__("rmdir:");
__asm__("	ret");
__asm__(".globl sbrk");
__asm__("	.type sbrk,@function");
__asm__("sbrk:");
__asm__("	ret");
__asm__(".globl select");
__asm__("	.type select,@function");
__asm__("select:");
__asm__("	ret");
__asm__(".globl setgid");
__asm__("	.type setgid,@function");
__asm__("setgid:");
__asm__("	ret");
__asm__(".globl setitimer");
__asm__("	.type setitimer,@function");
__asm__("setitimer:");
__asm__("	ret");
__asm__(".globl setmntent");
__asm__("	.type setmntent,@function");
__asm__("setmntent:");
__asm__("	ret");
__asm__(".globl setpgid");
__asm__("	.type setpgid,@function");
__asm__("setpgid:");
__asm__("	ret");
__asm__(".globl setregid");
__asm__("	.type setregid,@function");
__asm__("setregid:");
__asm__("	ret");
__asm__(".globl setreuid");
__asm__("	.type setreuid,@function");
__asm__("setreuid:");
__asm__("	ret");
__asm__(".globl setsid");
__asm__("	.type setsid,@function");
__asm__("setsid:");
__asm__("	ret");
__asm__(".globl setstate");
__asm__("	.type setstate,@function");
__asm__("setstate:");
__asm__("	ret");
__asm__(".globl setuid");
__asm__("	.type setuid,@function");
__asm__("setuid:");
__asm__("	ret");
__asm__(".globl setutent");
__asm__("	.type setutent,@function");
__asm__("setutent:");
__asm__("	ret");
__asm__(".globl setvbuf");
__asm__("	.type setvbuf,@function");
__asm__("setvbuf:");
__asm__("	ret");
__asm__(".globl shutdown");
__asm__("	.type shutdown,@function");
__asm__("shutdown:");
__asm__("	ret");
__asm__(".globl sigaltstack");
__asm__("	.type sigaltstack,@function");
__asm__("sigaltstack:");
__asm__("	ret");
__asm__(".globl sigblock");
__asm__("	.type sigblock,@function");
__asm__("sigblock:");
__asm__("	ret");
__asm__(".globl signal");
__asm__("	.type signal,@function");
__asm__("signal:");
__asm__("	ret");
__asm__(".globl sigpause");
__asm__("	.type sigpause,@function");
__asm__("sigpause:");
__asm__("	ret");
__asm__(".globl sigprocmask");
__asm__("	.type sigprocmask,@function");
__asm__("sigprocmask:");
__asm__("	ret");
__asm__(".globl sigreturn");
__asm__("	.type sigreturn,@function");
__asm__("sigreturn:");
__asm__("	ret");
__asm__(".globl sigsuspend");
__asm__("	.type sigsuspend,@function");
__asm__("sigsuspend:");
__asm__("	ret");
__asm__(".globl sleep");
__asm__("	.type sleep,@function");
__asm__("sleep:");
__asm__("	ret");
__asm__(".globl snprintf");
__asm__("	.type snprintf,@function");
__asm__("snprintf:");
__asm__("	ret");
__asm__(".globl socket");
__asm__("	.type socket,@function");
__asm__("socket:");
__asm__("	ret");
__asm__(".globl socketpair");
__asm__("	.type socketpair,@function");
__asm__("socketpair:");
__asm__("	ret");
__asm__(".globl srand");
__asm__("	.type srand,@function");
__asm__("srand:");
__asm__("	ret");
__asm__(".globl srandom");
__asm__("	.type srandom,@function");
__asm__("srandom:");
__asm__("	ret");
__asm__(".globl statfs");
__asm__("	.type statfs,@function");
__asm__("statfs:");
__asm__("	ret");
__asm__(".globl strcasecmp");
__asm__("	.type strcasecmp,@function");
__asm__("strcasecmp:");
__asm__("	ret");
__asm__(".globl strdup");
__asm__("	.type strdup,@function");
__asm__("strdup:");
__asm__("	ret");
__asm__(".globl strncasecmp");
__asm__("	.type strncasecmp,@function");
__asm__("strncasecmp:");
__asm__("	ret");
__asm__(".globl strndup");
__asm__("	.type strndup,@function");
__asm__("strndup:");
__asm__("	ret");
__asm__(".globl strnlen");
__asm__("	.type strnlen,@function");
__asm__("strnlen:");
__asm__("	ret");
__asm__(".globl strsep");
__asm__("	.type strsep,@function");
__asm__("strsep:");
__asm__("	ret");
__asm__(".globl strtod");
__asm__("	.type strtod,@function");
__asm__("strtod:");
__asm__("	ret");
__asm__(".globl strtof");
__asm__("	.type strtof,@function");
__asm__("strtof:");
__asm__("	ret");
__asm__(".globl strtol");
__asm__("	.type strtol,@function");
__asm__("strtol:");
__asm__("	ret");
__asm__(".globl strtold");
__asm__("	.type strtold,@function");
__asm__("strtold:");
__asm__("	ret");
__asm__(".globl strtoll");
__asm__("	.type strtoll,@function");
__asm__("strtoll:");
__asm__("	ret");
__asm__(".globl strtoq");
__asm__("	.type strtoq,@function");
__asm__("strtoq:");
__asm__("	ret");
__asm__(".globl strtoul");
__asm__("	.type strtoul,@function");
__asm__("strtoul:");
__asm__("	ret");
__asm__(".globl strtoull");
__asm__("	.type strtoull,@function");
__asm__("strtoull:");
__asm__("	ret");
__asm__(".globl strtouq");
__asm__("	.type strtouq,@function");
__asm__("strtouq:");
__asm__("	ret");
__asm__(".globl symlink");
__asm__("	.type symlink,@function");
__asm__("symlink:");
__asm__("	ret");
__asm__(".globl sysconf");
__asm__("	.type sysconf,@function");
__asm__("sysconf:");
__asm__("	ret");
__asm__(".globl tcgetattr");
__asm__("	.type tcgetattr,@function");
__asm__("tcgetattr:");
__asm__("	ret");
__asm__(".globl times");
__asm__("	.type times,@function");
__asm__("times:");
__asm__("	ret");
__asm__(".globl tzname");
__asm__("	.type tzname,@function");
__asm__("tzname:");
__asm__("	ret");
__asm__(".globl tzset");
__asm__("	.type tzset,@function");
__asm__("tzset:");
__asm__("	ret");
__asm__(".globl ulimit");
__asm__("	.type ulimit,@function");
__asm__("ulimit:");
__asm__("	ret");
__asm__(".globl umask");
__asm__("	.type umask,@function");
__asm__("umask:");
__asm__("	ret");
__asm__(".globl ungetc");
__asm__("	.type ungetc,@function");
__asm__("ungetc:");
__asm__("	ret");
__asm__(".globl unlink");
__asm__("	.type unlink,@function");
__asm__("unlink:");
__asm__("	ret");
__asm__(".globl vfork");
__asm__("	.type vfork,@function");
__asm__("vfork:");
__asm__("	ret");
__asm__(".globl vsnprintf");
__asm__("	.type vsnprintf,@function");
__asm__("vsnprintf:");
__asm__("	ret");
__asm__(".globl vsprintf");
__asm__("	.type vsprintf,@function");
__asm__("vsprintf:");
__asm__("	ret");
__asm__(".globl wait3");
__asm__("	.type wait3,@function");
__asm__("wait3:");
__asm__("	ret");
__asm__(".globl wait4");
__asm__("	.type wait4,@function");
__asm__("wait4:");
__asm__("	ret");
__asm__(".globl wcpcpy");
__asm__("	.type wcpcpy,@function");
__asm__("wcpcpy:");
__asm__("	ret");
__asm__(".globl wcpncpy");
__asm__("	.type wcpncpy,@function");
__asm__("wcpncpy:");
__asm__("	ret");
__asm__(".globl wcrtomb");
__asm__("	.type wcrtomb,@function");
__asm__("wcrtomb:");
__asm__("	ret");
__asm__(".globl wcslen");
__asm__("	.type wcslen,@function");
__asm__("wcslen:");
__asm__("	ret");
__asm__(".globl wcsnrtombs");
__asm__("	.type wcsnrtombs,@function");
__asm__("wcsnrtombs:");
__asm__("	ret");
__asm__(".globl wcsrtombs");
__asm__("	.type wcsrtombs,@function");
__asm__("wcsrtombs:");
__asm__("	ret");
__asm__(".globl wcstod");
__asm__("	.type wcstod,@function");
__asm__("wcstod:");
__asm__("	ret");
__asm__(".globl wcstof");
__asm__("	.type wcstof,@function");
__asm__("wcstof:");
__asm__("	ret");
__asm__(".globl wcstol");
__asm__("	.type wcstol,@function");
__asm__("wcstol:");
__asm__("	ret");
__asm__(".globl wcstold");
__asm__("	.type wcstold,@function");
__asm__("wcstold:");
__asm__("	ret");
__asm__(".globl wcstoq");
__asm__("	.type wcstoq,@function");
__asm__("wcstoq:");
__asm__("	ret");
__asm__(".globl wcstoul");
__asm__("	.type wcstoul,@function");
__asm__("wcstoul:");
__asm__("	ret");
__asm__(".globl wcstouq");
__asm__("	.type wcstouq,@function");
__asm__("wcstouq:");
__asm__("	ret");
__asm__(".globl wctype");
__asm__("	.type wctype,@function");
__asm__("wctype:");
__asm__("	ret");
__asm__(".globl writev");
__asm__("	.type writev,@function");
__asm__("writev:");
__asm__("	ret");
__asm__(".globl pread");
__asm__("	.type pread,@function");
__asm__("pread:");
__asm__("	ret");
__asm__(".globl pwrite");
__asm__("	.type pwrite,@function");
__asm__("pwrite:");
__asm__("	ret");
__asm__(".globl sigqueue");
__asm__("	.type sigqueue,@function");
__asm__("sigqueue:");
__asm__("	ret");
__asm__(".globl sigwaitinfo");
__asm__("	.type sigwaitinfo,@function");
__asm__("sigwaitinfo:");
__asm__("	ret");
__asm__(".globl sigtimedwait");
__asm__("	.type sigtimedwait,@function");
__asm__("sigtimedwait:");
__asm__("	ret");
__asm__(".globl wcswcs");
__asm__("	.type wcswcs,@function");
__asm__("wcswcs:");
__asm__("	ret");
__asm__(".globl re_comp");
__asm__("	.type re_comp,@function");
__asm__("re_comp:");
__asm__("	ret");
__asm__(".globl re_exec");
__asm__("	.type re_exec,@function");
__asm__("re_exec:");
__asm__("	ret");
__asm__(".globl sched_get_priority_max");
__asm__("	.type sched_get_priority_max,@function");
__asm__("sched_get_priority_max:");
__asm__("	ret");
__asm__(".globl sched_get_priority_min");
__asm__("	.type sched_get_priority_min,@function");
__asm__("sched_get_priority_min:");
__asm__("	ret");
__asm__(".globl sched_getparam");
__asm__("	.type sched_getparam,@function");
__asm__("sched_getparam:");
__asm__("	ret");
__asm__(".globl sched_getscheduler");
__asm__("	.type sched_getscheduler,@function");
__asm__("sched_getscheduler:");
__asm__("	ret");
__asm__(".globl sched_rr_get_interval");
__asm__("	.type sched_rr_get_interval,@function");
__asm__("sched_rr_get_interval:");
__asm__("	ret");
__asm__(".globl sched_setparam");
__asm__("	.type sched_setparam,@function");
__asm__("sched_setparam:");
__asm__("	ret");
__asm__(".globl sched_setscheduler");
__asm__("	.type sched_setscheduler,@function");
__asm__("sched_setscheduler:");
__asm__("	ret");
__asm__(".globl sched_yield");
__asm__("	.type sched_yield,@function");
__asm__("sched_yield:");
__asm__("	ret");
__asm__(".globl strerror_r");
__asm__("	.type strerror_r,@function");
__asm__("strerror_r:");
__asm__("	ret");
__asm__(".globl strtok_r");
__asm__("	.type strtok_r,@function");
__asm__("strtok_r:");
__asm__("	ret");
__asm__(".globl strcasestr");
__asm__("	.type strcasestr,@function");
__asm__("strcasestr:");
__asm__("	ret");
__asm__(".globl strverscmp");
__asm__("	.type strverscmp,@function");
__asm__("strverscmp:");
__asm__("	ret");
__asm__(".globl wcscasecmp");
__asm__("	.type wcscasecmp,@function");
__asm__("wcscasecmp:");
__asm__("	ret");
__asm__(".globl wcsncasecmp");
__asm__("	.type wcsncasecmp,@function");
__asm__("wcsncasecmp:");
__asm__("	ret");
__asm__(".globl wcsnlen");
__asm__("	.type wcsnlen,@function");
__asm__("wcsnlen:");
__asm__("	ret");
__asm__(".globl wcstoll");
__asm__("	.type wcstoll,@function");
__asm__("wcstoll:");
__asm__("	ret");
__asm__(".globl wcstoull");
__asm__("	.type wcstoull,@function");
__asm__("wcstoull:");
__asm__("	ret");
__asm__(".globl flockfile");
__asm__("	.type flockfile,@function");
__asm__("flockfile:");
__asm__("	ret");
__asm__(".globl _Exit");
__asm__("	.type _Exit,@function");
__asm__("_Exit:");
__asm__("	ret");
__asm__(".globl __ctype_get_mb_cur_max");
__asm__("	.type __ctype_get_mb_cur_max,@function");
__asm__("__ctype_get_mb_cur_max:");
__asm__("	ret");
__asm__(".globl _h_errno");
__asm__("	.type _h_errno,@function");
__asm__("_h_errno:");
__asm__("	ret");
__asm__(".globl _longjmp");
__asm__("	.type _longjmp,@function");
__asm__("_longjmp:");
__asm__("	ret");
__asm__(".globl _setjmp");
__asm__("	.type _setjmp,@function");
__asm__("_setjmp:");
__asm__("	ret");
__asm__(".globl adjtime");
__asm__("	.type adjtime,@function");
__asm__("adjtime:");
__asm__("	ret");
__asm__(".globl adjtimex");
__asm__("	.type adjtimex,@function");
__asm__("adjtimex:");
__asm__("	ret");
__asm__(".globl advance");
__asm__("	.type advance,@function");
__asm__("advance:");
__asm__("	ret");
__asm__(".globl bindtextdomain");
__asm__("	.type bindtextdomain,@function");
__asm__("bindtextdomain:");
__asm__("	ret");
__asm__(".globl bsd_signal");
__asm__("	.type bsd_signal,@function");
__asm__("bsd_signal:");
__asm__("	ret");
__asm__(".globl btowc");
__asm__("	.type btowc,@function");
__asm__("btowc:");
__asm__("	ret");
__asm__(".globl dcgettext");
__asm__("	.type dcgettext,@function");
__asm__("dcgettext:");
__asm__("	ret");
__asm__(".globl error");
__asm__("	.type error,@function");
__asm__("error:");
__asm__("	ret");
__asm__(".globl fgetpos64");
__asm__("	.type fgetpos64,@function");
__asm__("fgetpos64:");
__asm__("	ret");
__asm__(".globl fopen64");
__asm__("	.type fopen64,@function");
__asm__("fopen64:");
__asm__("	ret");
__asm__(".globl fpathconf");
__asm__("	.type fpathconf,@function");
__asm__("fpathconf:");
__asm__("	ret");
__asm__(".globl fsetpos64");
__asm__("	.type fsetpos64,@function");
__asm__("fsetpos64:");
__asm__("	ret");
__asm__(".globl ftruncate");
__asm__("	.type ftruncate,@function");
__asm__("ftruncate:");
__asm__("	ret");
__asm__(".globl ftrylockfile");
__asm__("	.type ftrylockfile,@function");
__asm__("ftrylockfile:");
__asm__("	ret");
__asm__(".globl funlockfile");
__asm__("	.type funlockfile,@function");
__asm__("funlockfile:");
__asm__("	ret");
__asm__(".globl getc_unlocked");
__asm__("	.type getc_unlocked,@function");
__asm__("getc_unlocked:");
__asm__("	ret");
__asm__(".globl getcwd");
__asm__("	.type getcwd,@function");
__asm__("getcwd:");
__asm__("	ret");
__asm__(".globl getpagesize");
__asm__("	.type getpagesize,@function");
__asm__("getpagesize:");
__asm__("	ret");
__asm__(".globl getppid");
__asm__("	.type getppid,@function");
__asm__("getppid:");
__asm__("	ret");
__asm__(".globl gettext");
__asm__("	.type gettext,@function");
__asm__("gettext:");
__asm__("	ret");
__asm__(".globl gettimeofday");
__asm__("	.type gettimeofday,@function");
__asm__("gettimeofday:");
__asm__("	ret");
__asm__(".globl hdestroy");
__asm__("	.type hdestroy,@function");
__asm__("hdestroy:");
__asm__("	ret");
__asm__(".globl imaxabs");
__asm__("	.type imaxabs,@function");
__asm__("imaxabs:");
__asm__("	ret");
__asm__(".globl imaxdiv");
__asm__("	.type imaxdiv,@function");
__asm__("imaxdiv:");
__asm__("	ret");
__asm__(".globl isatty");
__asm__("	.type isatty,@function");
__asm__("isatty:");
__asm__("	ret");
__asm__(".globl isblank");
__asm__("	.type isblank,@function");
__asm__("isblank:");
__asm__("	ret");
__asm__(".globl isinfl");
__asm__("	.type isinfl,@function");
__asm__("isinfl:");
__asm__("	ret");
__asm__(".globl isnan");
__asm__("	.type isnan,@function");
__asm__("isnan:");
__asm__("	ret");
__asm__(".globl isnanf");
__asm__("	.type isnanf,@function");
__asm__("isnanf:");
__asm__("	ret");
__asm__(".globl isnanl");
__asm__("	.type isnanl,@function");
__asm__("isnanl:");
__asm__("	ret");
__asm__(".globl lseek64");
__asm__("	.type lseek64,@function");
__asm__("lseek64:");
__asm__("	ret");
__asm__(".globl mmap64");
__asm__("	.type mmap64,@function");
__asm__("mmap64:");
__asm__("	ret");
__asm__(".globl ntohl");
__asm__("	.type ntohl,@function");
__asm__("ntohl:");
__asm__("	ret");
__asm__(".globl ntohs");
__asm__("	.type ntohs,@function");
__asm__("ntohs:");
__asm__("	ret");
__asm__(".globl open64");
__asm__("	.type open64,@function");
__asm__("open64:");
__asm__("	ret");
__asm__(".globl pwrite64");
__asm__("	.type pwrite64,@function");
__asm__("pwrite64:");
__asm__("	ret");
__asm__(".globl readdir64");
__asm__("	.type readdir64,@function");
__asm__("readdir64:");
__asm__("	ret");
__asm__(".globl realpath");
__asm__("	.type realpath,@function");
__asm__("realpath:");
__asm__("	ret");
__asm__(".globl setbuffer");
__asm__("	.type setbuffer,@function");
__asm__("setbuffer:");
__asm__("	ret");
__asm__(".globl step");
__asm__("	.type step,@function");
__asm__("step:");
__asm__("	ret");
__asm__(".globl stpcpy");
__asm__("	.type stpcpy,@function");
__asm__("stpcpy:");
__asm__("	ret");
__asm__(".globl stpncpy");
__asm__("	.type stpncpy,@function");
__asm__("stpncpy:");
__asm__("	ret");
__asm__(".globl textdomain");
__asm__("	.type textdomain,@function");
__asm__("textdomain:");
__asm__("	ret");
__asm__(".globl tfind");
__asm__("	.type tfind,@function");
__asm__("tfind:");
__asm__("	ret");
__asm__(".globl towctrans");
__asm__("	.type towctrans,@function");
__asm__("towctrans:");
__asm__("	ret");
__asm__(".globl tsearch");
__asm__("	.type tsearch,@function");
__asm__("tsearch:");
__asm__("	ret");
__asm__(".globl ttyname_r");
__asm__("	.type ttyname_r,@function");
__asm__("ttyname_r:");
__asm__("	ret");
__asm__(".globl twalk");
__asm__("	.type twalk,@function");
__asm__("twalk:");
__asm__("	ret");
__asm__(".globl utimes");
__asm__("	.type utimes,@function");
__asm__("utimes:");
__asm__("	ret");
__asm__(".globl vasprintf");
__asm__("	.type vasprintf,@function");
__asm__("vasprintf:");
__asm__("	ret");
__asm__(".globl vdprintf");
__asm__("	.type vdprintf,@function");
__asm__("vdprintf:");
__asm__("	ret");
__asm__(".globl __fpending");
__asm__("	.type __fpending,@function");
__asm__("__fpending:");
__asm__("	ret");
__asm__(".globl __sysconf");
__asm__("	.type __sysconf,@function");
__asm__("__sysconf:");
__asm__("	ret");
__asm__(".globl fgetws");
__asm__("	.type fgetws,@function");
__asm__("fgetws:");
__asm__("	ret");
__asm__(".globl fputwc");
__asm__("	.type fputwc,@function");
__asm__("fputwc:");
__asm__("	ret");
__asm__(".globl fputws");
__asm__("	.type fputws,@function");
__asm__("fputws:");
__asm__("	ret");
__asm__(".globl fwide");
__asm__("	.type fwide,@function");
__asm__("fwide:");
__asm__("	ret");
__asm__(".globl fwprintf");
__asm__("	.type fwprintf,@function");
__asm__("fwprintf:");
__asm__("	ret");
__asm__(".globl fwscanf");
__asm__("	.type fwscanf,@function");
__asm__("fwscanf:");
__asm__("	ret");
__asm__(".globl getloadavg");
__asm__("	.type getloadavg,@function");
__asm__("getloadavg:");
__asm__("	ret");
__asm__(".globl memrchr");
__asm__("	.type memrchr,@function");
__asm__("memrchr:");
__asm__("	ret");
__asm__(".globl mkstemp64");
__asm__("	.type mkstemp64,@function");
__asm__("mkstemp64:");
__asm__("	ret");
__asm__(".globl putwc");
__asm__("	.type putwc,@function");
__asm__("putwc:");
__asm__("	ret");
__asm__(".globl putwchar");
__asm__("	.type putwchar,@function");
__asm__("putwchar:");
__asm__("	ret");
__asm__(".globl swprintf");
__asm__("	.type swprintf,@function");
__asm__("swprintf:");
__asm__("	ret");
__asm__(".globl swscanf");
__asm__("	.type swscanf,@function");
__asm__("swscanf:");
__asm__("	ret");
__asm__(".globl ungetwc");
__asm__("	.type ungetwc,@function");
__asm__("ungetwc:");
__asm__("	ret");
__asm__(".globl vfwprintf");
__asm__("	.type vfwprintf,@function");
__asm__("vfwprintf:");
__asm__("	ret");
__asm__(".globl vswscanf");
__asm__("	.type vswscanf,@function");
__asm__("vswscanf:");
__asm__("	ret");
__asm__(".globl vwprintf");
__asm__("	.type vwprintf,@function");
__asm__("vwprintf:");
__asm__("	ret");
__asm__(".globl vwscanf");
__asm__("	.type vwscanf,@function");
__asm__("vwscanf:");
__asm__("	ret");
__asm__(".globl wcsftime");
__asm__("	.type wcsftime,@function");
__asm__("wcsftime:");
__asm__("	ret");
__asm__(".globl wprintf");
__asm__("	.type wprintf,@function");
__asm__("wprintf:");
__asm__("	ret");
__asm__(".globl wscanf");
__asm__("	.type wscanf,@function");
__asm__("wscanf:");
__asm__("	ret");
__asm__(".globl __libc_start_main");
__asm__("	.type __libc_start_main,@function");
__asm__("__libc_start_main:");
__asm__("	ret");
__asm__(".globl _IO_2_1_stderr_");
__asm__("	.type _IO_2_1_stderr_,@object");
__asm__("	.size _IO_2_1_stderr_,4");
__asm__("_IO_2_1_stderr_:");
__asm__("	.long 0");
__asm__(".globl _IO_2_1_stdin_");
__asm__("	.type _IO_2_1_stdin_,@object");
__asm__("	.size _IO_2_1_stdin_,4");
__asm__("_IO_2_1_stdin_:");
__asm__("	.long 0");
__asm__(".globl _IO_2_1_stdout_");
__asm__("	.type _IO_2_1_stdout_,@object");
__asm__("	.size _IO_2_1_stdout_,4");
__asm__("_IO_2_1_stdout_:");
__asm__("	.long 0");
__asm__(".globl __ctype_b");
__asm__("	.type __ctype_b,@object");
__asm__("	.size __ctype_b,4");
__asm__("__ctype_b:");
__asm__("	.long 0");
__asm__(".globl __ctype_tolower");
__asm__("	.type __ctype_tolower,@object");
__asm__("	.size __ctype_tolower,4");
__asm__("__ctype_tolower:");
__asm__("	.long 0");
__asm__(".globl __ctype_toupper");
__asm__("	.type __ctype_toupper,@object");
__asm__("	.size __ctype_toupper,4");
__asm__("__ctype_toupper:");
__asm__("	.long 0");
__asm__(".globl __environ");
__asm__("	.type __environ,@object");
__asm__("	.size __environ,4");
__asm__("__environ:");
__asm__("	.long 0");
__asm__(".globl _nl_msg_cat_cntr");
__asm__("	.type _nl_msg_cat_cntr,@object");
__asm__("	.size _nl_msg_cat_cntr,4");
__asm__("_nl_msg_cat_cntr:");
__asm__("	.long 0");
__asm__(".globl _sys_errlist");
__asm__("	.type _sys_errlist,@object");
__asm__("	.size _sys_errlist,4");
__asm__("_sys_errlist:");
__asm__("	.long 0");
__asm__(".globl _sys_siglist");
__asm__("	.type _sys_siglist,@object");
__asm__("	.size _sys_siglist,4");
__asm__("_sys_siglist:");
__asm__("	.long 0");
__asm__(".globl errno");
__asm__("	.type errno,@object");
__asm__("	.size errno,4");
__asm__("errno:");
__asm__("	.long 0");
__asm__(".globl getdate_err");
__asm__("	.type getdate_err,@object");
__asm__("	.size getdate_err,4");
__asm__("getdate_err:");
__asm__("	.long 0");
__asm__(".globl h_errno");
__asm__("	.type h_errno,@object");
__asm__("	.size h_errno,4");
__asm__("h_errno:");
__asm__("	.long 0");
__asm__(".globl loc1");
__asm__("	.type loc1,@object");
__asm__("	.size loc1,4");
__asm__("loc1:");
__asm__("	.long 0");
__asm__(".globl loc2");
__asm__("	.type loc2,@object");
__asm__("	.size loc2,4");
__asm__("loc2:");
__asm__("	.long 0");
__asm__(".globl locs");
__asm__("	.type locs,@object");
__asm__("	.size locs,4");
__asm__("locs:");
__asm__("	.long 0");
__asm__(".globl optarg");
__asm__("	.type optarg,@object");
__asm__("	.size optarg,4");
__asm__("optarg:");
__asm__("	.long 0");
__asm__(".globl opterr");
__asm__("	.type opterr,@object");
__asm__("	.size opterr,4");
__asm__("opterr:");
__asm__("	.long 0");
__asm__(".globl optind");
__asm__("	.type optind,@object");
__asm__("	.size optind,4");
__asm__("optind:");
__asm__("	.long 0");
__asm__(".globl optopt");
__asm__("	.type optopt,@object");
__asm__("	.size optopt,4");
__asm__("optopt:");
__asm__("	.long 0");
__asm__(".globl stderr");
__asm__("	.type stderr,@object");
__asm__("	.size stderr,4");
__asm__("stderr:");
__asm__("	.long 0");
__asm__(".globl stdin");
__asm__("	.type stdin,@object");
__asm__("	.size stdin,4");
__asm__("stdin:");
__asm__("	.long 0");
__asm__(".globl stdout");
__asm__("	.type stdout,@object");
__asm__("	.size stdout,4");
__asm__("stdout:");
__asm__("	.long 0");
__asm__(".globl timezone");
__asm__("	.type timezone,@object");
__asm__("	.size timezone,4");
__asm__("timezone:");
__asm__("	.long 0");
__asm__(".globl _environ");
__asm__("	.type _environ,@object");
__asm__("	.size _environ,4");
__asm__("_environ:");
__asm__("	.long 0");
__asm__(".globl environ");
__asm__("	.type environ,@object");
__asm__("	.size environ,4");
__asm__("environ:");
__asm__("	.long 0");
