__asm__(".globl crypt");
__asm__("	.type crypt,@function");
__asm__("crypt:");
__asm__("	ret");
__asm__(".globl encrypt");
__asm__("	.type encrypt,@function");
__asm__("encrypt:");
__asm__("	ret");
__asm__(".globl setkey");
__asm__("	.type setkey,@function");
__asm__("setkey:");
__asm__("	ret");
