__asm__(".globl dladdr");
__asm__("	.type dladdr,@function");
__asm__("dladdr:");
__asm__("	ret");
__asm__(".globl dlclose");
__asm__("	.type dlclose,@function");
__asm__("dlclose:");
__asm__("	ret");
__asm__(".globl dlerror");
__asm__("	.type dlerror,@function");
__asm__("dlerror:");
__asm__("	ret");
__asm__(".globl dlopen");
__asm__("	.type dlopen,@function");
__asm__("dlopen:");
__asm__("	ret");
__asm__(".globl dlsym");
__asm__("	.type dlsym,@function");
__asm__("dlsym:");
__asm__("	ret");
