__asm__(".globl glAccum");
__asm__("	.type glAccum,@function");
__asm__("glAccum:");
__asm__("	ret");
__asm__(".globl glAlphaFunc");
__asm__("	.type glAlphaFunc,@function");
__asm__("glAlphaFunc:");
__asm__("	ret");
__asm__(".globl glAreTexturesResident");
__asm__("	.type glAreTexturesResident,@function");
__asm__("glAreTexturesResident:");
__asm__("	ret");
__asm__(".globl glArrayElement");
__asm__("	.type glArrayElement,@function");
__asm__("glArrayElement:");
__asm__("	ret");
__asm__(".globl glBegin");
__asm__("	.type glBegin,@function");
__asm__("glBegin:");
__asm__("	ret");
__asm__(".globl glBindTexture");
__asm__("	.type glBindTexture,@function");
__asm__("glBindTexture:");
__asm__("	ret");
__asm__(".globl glBitmap");
__asm__("	.type glBitmap,@function");
__asm__("glBitmap:");
__asm__("	ret");
__asm__(".globl glBlendColorEXT");
__asm__("	.type glBlendColorEXT,@function");
__asm__("glBlendColorEXT:");
__asm__("	ret");
__asm__(".globl glBlendEquationEXT");
__asm__("	.type glBlendEquationEXT,@function");
__asm__("glBlendEquationEXT:");
__asm__("	ret");
__asm__(".globl glBlendFunc");
__asm__("	.type glBlendFunc,@function");
__asm__("glBlendFunc:");
__asm__("	ret");
__asm__(".globl glCallList");
__asm__("	.type glCallList,@function");
__asm__("glCallList:");
__asm__("	ret");
__asm__(".globl glCallLists");
__asm__("	.type glCallLists,@function");
__asm__("glCallLists:");
__asm__("	ret");
__asm__(".globl glClear");
__asm__("	.type glClear,@function");
__asm__("glClear:");
__asm__("	ret");
__asm__(".globl glClearAccum");
__asm__("	.type glClearAccum,@function");
__asm__("glClearAccum:");
__asm__("	ret");
__asm__(".globl glClearColor");
__asm__("	.type glClearColor,@function");
__asm__("glClearColor:");
__asm__("	ret");
__asm__(".globl glClearDepth");
__asm__("	.type glClearDepth,@function");
__asm__("glClearDepth:");
__asm__("	ret");
__asm__(".globl glClearIndex");
__asm__("	.type glClearIndex,@function");
__asm__("glClearIndex:");
__asm__("	ret");
__asm__(".globl glClearStencil");
__asm__("	.type glClearStencil,@function");
__asm__("glClearStencil:");
__asm__("	ret");
__asm__(".globl glClipPlane");
__asm__("	.type glClipPlane,@function");
__asm__("glClipPlane:");
__asm__("	ret");
__asm__(".globl glColor3b");
__asm__("	.type glColor3b,@function");
__asm__("glColor3b:");
__asm__("	ret");
__asm__(".globl glColor3bv");
__asm__("	.type glColor3bv,@function");
__asm__("glColor3bv:");
__asm__("	ret");
__asm__(".globl glColor3d");
__asm__("	.type glColor3d,@function");
__asm__("glColor3d:");
__asm__("	ret");
__asm__(".globl glColor3dv");
__asm__("	.type glColor3dv,@function");
__asm__("glColor3dv:");
__asm__("	ret");
__asm__(".globl glColor3f");
__asm__("	.type glColor3f,@function");
__asm__("glColor3f:");
__asm__("	ret");
__asm__(".globl glColor3fv");
__asm__("	.type glColor3fv,@function");
__asm__("glColor3fv:");
__asm__("	ret");
__asm__(".globl glColor3i");
__asm__("	.type glColor3i,@function");
__asm__("glColor3i:");
__asm__("	ret");
__asm__(".globl glColor3iv");
__asm__("	.type glColor3iv,@function");
__asm__("glColor3iv:");
__asm__("	ret");
__asm__(".globl glColor3s");
__asm__("	.type glColor3s,@function");
__asm__("glColor3s:");
__asm__("	ret");
__asm__(".globl glColor3sv");
__asm__("	.type glColor3sv,@function");
__asm__("glColor3sv:");
__asm__("	ret");
__asm__(".globl glColor3ub");
__asm__("	.type glColor3ub,@function");
__asm__("glColor3ub:");
__asm__("	ret");
__asm__(".globl glColor3ubv");
__asm__("	.type glColor3ubv,@function");
__asm__("glColor3ubv:");
__asm__("	ret");
__asm__(".globl glColor3ui");
__asm__("	.type glColor3ui,@function");
__asm__("glColor3ui:");
__asm__("	ret");
__asm__(".globl glColor3uiv");
__asm__("	.type glColor3uiv,@function");
__asm__("glColor3uiv:");
__asm__("	ret");
__asm__(".globl glColor3us");
__asm__("	.type glColor3us,@function");
__asm__("glColor3us:");
__asm__("	ret");
__asm__(".globl glColor3usv");
__asm__("	.type glColor3usv,@function");
__asm__("glColor3usv:");
__asm__("	ret");
__asm__(".globl glColor4b");
__asm__("	.type glColor4b,@function");
__asm__("glColor4b:");
__asm__("	ret");
__asm__(".globl glColor4bv");
__asm__("	.type glColor4bv,@function");
__asm__("glColor4bv:");
__asm__("	ret");
__asm__(".globl glColor4d");
__asm__("	.type glColor4d,@function");
__asm__("glColor4d:");
__asm__("	ret");
__asm__(".globl glColor4dv");
__asm__("	.type glColor4dv,@function");
__asm__("glColor4dv:");
__asm__("	ret");
__asm__(".globl glColor4f");
__asm__("	.type glColor4f,@function");
__asm__("glColor4f:");
__asm__("	ret");
__asm__(".globl glColor4fv");
__asm__("	.type glColor4fv,@function");
__asm__("glColor4fv:");
__asm__("	ret");
__asm__(".globl glColor4i");
__asm__("	.type glColor4i,@function");
__asm__("glColor4i:");
__asm__("	ret");
__asm__(".globl glColor4iv");
__asm__("	.type glColor4iv,@function");
__asm__("glColor4iv:");
__asm__("	ret");
__asm__(".globl glColor4s");
__asm__("	.type glColor4s,@function");
__asm__("glColor4s:");
__asm__("	ret");
__asm__(".globl glColor4sv");
__asm__("	.type glColor4sv,@function");
__asm__("glColor4sv:");
__asm__("	ret");
__asm__(".globl glColor4ub");
__asm__("	.type glColor4ub,@function");
__asm__("glColor4ub:");
__asm__("	ret");
__asm__(".globl glColor4ubv");
__asm__("	.type glColor4ubv,@function");
__asm__("glColor4ubv:");
__asm__("	ret");
__asm__(".globl glColor4ui");
__asm__("	.type glColor4ui,@function");
__asm__("glColor4ui:");
__asm__("	ret");
__asm__(".globl glColor4uiv");
__asm__("	.type glColor4uiv,@function");
__asm__("glColor4uiv:");
__asm__("	ret");
__asm__(".globl glColor4us");
__asm__("	.type glColor4us,@function");
__asm__("glColor4us:");
__asm__("	ret");
__asm__(".globl glColor4usv");
__asm__("	.type glColor4usv,@function");
__asm__("glColor4usv:");
__asm__("	ret");
__asm__(".globl glColorMask");
__asm__("	.type glColorMask,@function");
__asm__("glColorMask:");
__asm__("	ret");
__asm__(".globl glColorMaterial");
__asm__("	.type glColorMaterial,@function");
__asm__("glColorMaterial:");
__asm__("	ret");
__asm__(".globl glColorPointer");
__asm__("	.type glColorPointer,@function");
__asm__("glColorPointer:");
__asm__("	ret");
__asm__(".globl glCopyPixels");
__asm__("	.type glCopyPixels,@function");
__asm__("glCopyPixels:");
__asm__("	ret");
__asm__(".globl glCopyTexImage1D");
__asm__("	.type glCopyTexImage1D,@function");
__asm__("glCopyTexImage1D:");
__asm__("	ret");
__asm__(".globl glCopyTexImage2D");
__asm__("	.type glCopyTexImage2D,@function");
__asm__("glCopyTexImage2D:");
__asm__("	ret");
__asm__(".globl glCopyTexSubImage1D");
__asm__("	.type glCopyTexSubImage1D,@function");
__asm__("glCopyTexSubImage1D:");
__asm__("	ret");
__asm__(".globl glCopyTexSubImage2D");
__asm__("	.type glCopyTexSubImage2D,@function");
__asm__("glCopyTexSubImage2D:");
__asm__("	ret");
__asm__(".globl glCullFace");
__asm__("	.type glCullFace,@function");
__asm__("glCullFace:");
__asm__("	ret");
__asm__(".globl glDeleteLists");
__asm__("	.type glDeleteLists,@function");
__asm__("glDeleteLists:");
__asm__("	ret");
__asm__(".globl glDeleteTextures");
__asm__("	.type glDeleteTextures,@function");
__asm__("glDeleteTextures:");
__asm__("	ret");
__asm__(".globl glDepthFunc");
__asm__("	.type glDepthFunc,@function");
__asm__("glDepthFunc:");
__asm__("	ret");
__asm__(".globl glDepthMask");
__asm__("	.type glDepthMask,@function");
__asm__("glDepthMask:");
__asm__("	ret");
__asm__(".globl glDepthRange");
__asm__("	.type glDepthRange,@function");
__asm__("glDepthRange:");
__asm__("	ret");
__asm__(".globl glDisable");
__asm__("	.type glDisable,@function");
__asm__("glDisable:");
__asm__("	ret");
__asm__(".globl glDisableClientState");
__asm__("	.type glDisableClientState,@function");
__asm__("glDisableClientState:");
__asm__("	ret");
__asm__(".globl glDrawArrays");
__asm__("	.type glDrawArrays,@function");
__asm__("glDrawArrays:");
__asm__("	ret");
__asm__(".globl glDrawBuffer");
__asm__("	.type glDrawBuffer,@function");
__asm__("glDrawBuffer:");
__asm__("	ret");
__asm__(".globl glDrawElements");
__asm__("	.type glDrawElements,@function");
__asm__("glDrawElements:");
__asm__("	ret");
__asm__(".globl glDrawPixels");
__asm__("	.type glDrawPixels,@function");
__asm__("glDrawPixels:");
__asm__("	ret");
__asm__(".globl glEdgeFlag");
__asm__("	.type glEdgeFlag,@function");
__asm__("glEdgeFlag:");
__asm__("	ret");
__asm__(".globl glEdgeFlagPointer");
__asm__("	.type glEdgeFlagPointer,@function");
__asm__("glEdgeFlagPointer:");
__asm__("	ret");
__asm__(".globl glEdgeFlagv");
__asm__("	.type glEdgeFlagv,@function");
__asm__("glEdgeFlagv:");
__asm__("	ret");
__asm__(".globl glEnable");
__asm__("	.type glEnable,@function");
__asm__("glEnable:");
__asm__("	ret");
__asm__(".globl glEnableClientState");
__asm__("	.type glEnableClientState,@function");
__asm__("glEnableClientState:");
__asm__("	ret");
__asm__(".globl glEnd");
__asm__("	.type glEnd,@function");
__asm__("glEnd:");
__asm__("	ret");
__asm__(".globl glEndList");
__asm__("	.type glEndList,@function");
__asm__("glEndList:");
__asm__("	ret");
__asm__(".globl glEvalCoord1d");
__asm__("	.type glEvalCoord1d,@function");
__asm__("glEvalCoord1d:");
__asm__("	ret");
__asm__(".globl glEvalCoord1dv");
__asm__("	.type glEvalCoord1dv,@function");
__asm__("glEvalCoord1dv:");
__asm__("	ret");
__asm__(".globl glEvalCoord1f");
__asm__("	.type glEvalCoord1f,@function");
__asm__("glEvalCoord1f:");
__asm__("	ret");
__asm__(".globl glEvalCoord1fv");
__asm__("	.type glEvalCoord1fv,@function");
__asm__("glEvalCoord1fv:");
__asm__("	ret");
__asm__(".globl glEvalCoord2d");
__asm__("	.type glEvalCoord2d,@function");
__asm__("glEvalCoord2d:");
__asm__("	ret");
__asm__(".globl glEvalCoord2dv");
__asm__("	.type glEvalCoord2dv,@function");
__asm__("glEvalCoord2dv:");
__asm__("	ret");
__asm__(".globl glEvalCoord2f");
__asm__("	.type glEvalCoord2f,@function");
__asm__("glEvalCoord2f:");
__asm__("	ret");
__asm__(".globl glEvalCoord2fv");
__asm__("	.type glEvalCoord2fv,@function");
__asm__("glEvalCoord2fv:");
__asm__("	ret");
__asm__(".globl glEvalMesh1");
__asm__("	.type glEvalMesh1,@function");
__asm__("glEvalMesh1:");
__asm__("	ret");
__asm__(".globl glEvalMesh2");
__asm__("	.type glEvalMesh2,@function");
__asm__("glEvalMesh2:");
__asm__("	ret");
__asm__(".globl glEvalPoint1");
__asm__("	.type glEvalPoint1,@function");
__asm__("glEvalPoint1:");
__asm__("	ret");
__asm__(".globl glEvalPoint2");
__asm__("	.type glEvalPoint2,@function");
__asm__("glEvalPoint2:");
__asm__("	ret");
__asm__(".globl glFeedbackBuffer");
__asm__("	.type glFeedbackBuffer,@function");
__asm__("glFeedbackBuffer:");
__asm__("	ret");
__asm__(".globl glFinish");
__asm__("	.type glFinish,@function");
__asm__("glFinish:");
__asm__("	ret");
__asm__(".globl glFlush");
__asm__("	.type glFlush,@function");
__asm__("glFlush:");
__asm__("	ret");
__asm__(".globl glFogf");
__asm__("	.type glFogf,@function");
__asm__("glFogf:");
__asm__("	ret");
__asm__(".globl glFogfv");
__asm__("	.type glFogfv,@function");
__asm__("glFogfv:");
__asm__("	ret");
__asm__(".globl glFogi");
__asm__("	.type glFogi,@function");
__asm__("glFogi:");
__asm__("	ret");
__asm__(".globl glFogiv");
__asm__("	.type glFogiv,@function");
__asm__("glFogiv:");
__asm__("	ret");
__asm__(".globl glFrontFace");
__asm__("	.type glFrontFace,@function");
__asm__("glFrontFace:");
__asm__("	ret");
__asm__(".globl glFrustum");
__asm__("	.type glFrustum,@function");
__asm__("glFrustum:");
__asm__("	ret");
__asm__(".globl glGenLists");
__asm__("	.type glGenLists,@function");
__asm__("glGenLists:");
__asm__("	ret");
__asm__(".globl glGenTextures");
__asm__("	.type glGenTextures,@function");
__asm__("glGenTextures:");
__asm__("	ret");
__asm__(".globl glGetBooleanv");
__asm__("	.type glGetBooleanv,@function");
__asm__("glGetBooleanv:");
__asm__("	ret");
__asm__(".globl glGetClipPlane");
__asm__("	.type glGetClipPlane,@function");
__asm__("glGetClipPlane:");
__asm__("	ret");
__asm__(".globl glGetDoublev");
__asm__("	.type glGetDoublev,@function");
__asm__("glGetDoublev:");
__asm__("	ret");
__asm__(".globl glGetError");
__asm__("	.type glGetError,@function");
__asm__("glGetError:");
__asm__("	ret");
__asm__(".globl glGetFloatv");
__asm__("	.type glGetFloatv,@function");
__asm__("glGetFloatv:");
__asm__("	ret");
__asm__(".globl glGetIntegerv");
__asm__("	.type glGetIntegerv,@function");
__asm__("glGetIntegerv:");
__asm__("	ret");
__asm__(".globl glGetLightfv");
__asm__("	.type glGetLightfv,@function");
__asm__("glGetLightfv:");
__asm__("	ret");
__asm__(".globl glGetLightiv");
__asm__("	.type glGetLightiv,@function");
__asm__("glGetLightiv:");
__asm__("	ret");
__asm__(".globl glGetMapdv");
__asm__("	.type glGetMapdv,@function");
__asm__("glGetMapdv:");
__asm__("	ret");
__asm__(".globl glGetMapfv");
__asm__("	.type glGetMapfv,@function");
__asm__("glGetMapfv:");
__asm__("	ret");
__asm__(".globl glGetMapiv");
__asm__("	.type glGetMapiv,@function");
__asm__("glGetMapiv:");
__asm__("	ret");
__asm__(".globl glGetMaterialfv");
__asm__("	.type glGetMaterialfv,@function");
__asm__("glGetMaterialfv:");
__asm__("	ret");
__asm__(".globl glGetMaterialiv");
__asm__("	.type glGetMaterialiv,@function");
__asm__("glGetMaterialiv:");
__asm__("	ret");
__asm__(".globl glGetPixelMapfv");
__asm__("	.type glGetPixelMapfv,@function");
__asm__("glGetPixelMapfv:");
__asm__("	ret");
__asm__(".globl glGetPixelMapuiv");
__asm__("	.type glGetPixelMapuiv,@function");
__asm__("glGetPixelMapuiv:");
__asm__("	ret");
__asm__(".globl glGetPixelMapusv");
__asm__("	.type glGetPixelMapusv,@function");
__asm__("glGetPixelMapusv:");
__asm__("	ret");
__asm__(".globl glGetPointerv");
__asm__("	.type glGetPointerv,@function");
__asm__("glGetPointerv:");
__asm__("	ret");
__asm__(".globl glGetPolygonStipple");
__asm__("	.type glGetPolygonStipple,@function");
__asm__("glGetPolygonStipple:");
__asm__("	ret");
__asm__(".globl glGetString");
__asm__("	.type glGetString,@function");
__asm__("glGetString:");
__asm__("	ret");
__asm__(".globl glGetTexEnvfv");
__asm__("	.type glGetTexEnvfv,@function");
__asm__("glGetTexEnvfv:");
__asm__("	ret");
__asm__(".globl glGetTexEnviv");
__asm__("	.type glGetTexEnviv,@function");
__asm__("glGetTexEnviv:");
__asm__("	ret");
__asm__(".globl glGetTexGendv");
__asm__("	.type glGetTexGendv,@function");
__asm__("glGetTexGendv:");
__asm__("	ret");
__asm__(".globl glGetTexGenfv");
__asm__("	.type glGetTexGenfv,@function");
__asm__("glGetTexGenfv:");
__asm__("	ret");
__asm__(".globl glGetTexGeniv");
__asm__("	.type glGetTexGeniv,@function");
__asm__("glGetTexGeniv:");
__asm__("	ret");
__asm__(".globl glGetTexImage");
__asm__("	.type glGetTexImage,@function");
__asm__("glGetTexImage:");
__asm__("	ret");
__asm__(".globl glGetTexLevelParameterfv");
__asm__("	.type glGetTexLevelParameterfv,@function");
__asm__("glGetTexLevelParameterfv:");
__asm__("	ret");
__asm__(".globl glGetTexLevelParameteriv");
__asm__("	.type glGetTexLevelParameteriv,@function");
__asm__("glGetTexLevelParameteriv:");
__asm__("	ret");
__asm__(".globl glGetTexParameterfv");
__asm__("	.type glGetTexParameterfv,@function");
__asm__("glGetTexParameterfv:");
__asm__("	ret");
__asm__(".globl glGetTexParameteriv");
__asm__("	.type glGetTexParameteriv,@function");
__asm__("glGetTexParameteriv:");
__asm__("	ret");
__asm__(".globl glHint");
__asm__("	.type glHint,@function");
__asm__("glHint:");
__asm__("	ret");
__asm__(".globl glIndexMask");
__asm__("	.type glIndexMask,@function");
__asm__("glIndexMask:");
__asm__("	ret");
__asm__(".globl glIndexPointer");
__asm__("	.type glIndexPointer,@function");
__asm__("glIndexPointer:");
__asm__("	ret");
__asm__(".globl glIndexd");
__asm__("	.type glIndexd,@function");
__asm__("glIndexd:");
__asm__("	ret");
__asm__(".globl glIndexdv");
__asm__("	.type glIndexdv,@function");
__asm__("glIndexdv:");
__asm__("	ret");
__asm__(".globl glIndexf");
__asm__("	.type glIndexf,@function");
__asm__("glIndexf:");
__asm__("	ret");
__asm__(".globl glIndexfv");
__asm__("	.type glIndexfv,@function");
__asm__("glIndexfv:");
__asm__("	ret");
__asm__(".globl glIndexi");
__asm__("	.type glIndexi,@function");
__asm__("glIndexi:");
__asm__("	ret");
__asm__(".globl glIndexiv");
__asm__("	.type glIndexiv,@function");
__asm__("glIndexiv:");
__asm__("	ret");
__asm__(".globl glIndexs");
__asm__("	.type glIndexs,@function");
__asm__("glIndexs:");
__asm__("	ret");
__asm__(".globl glIndexsv");
__asm__("	.type glIndexsv,@function");
__asm__("glIndexsv:");
__asm__("	ret");
__asm__(".globl glIndexub");
__asm__("	.type glIndexub,@function");
__asm__("glIndexub:");
__asm__("	ret");
__asm__(".globl glIndexubv");
__asm__("	.type glIndexubv,@function");
__asm__("glIndexubv:");
__asm__("	ret");
__asm__(".globl glInitNames");
__asm__("	.type glInitNames,@function");
__asm__("glInitNames:");
__asm__("	ret");
__asm__(".globl glInterleavedArrays");
__asm__("	.type glInterleavedArrays,@function");
__asm__("glInterleavedArrays:");
__asm__("	ret");
__asm__(".globl glIsEnabled");
__asm__("	.type glIsEnabled,@function");
__asm__("glIsEnabled:");
__asm__("	ret");
__asm__(".globl glIsList");
__asm__("	.type glIsList,@function");
__asm__("glIsList:");
__asm__("	ret");
__asm__(".globl glIsTexture");
__asm__("	.type glIsTexture,@function");
__asm__("glIsTexture:");
__asm__("	ret");
__asm__(".globl glLightModelf");
__asm__("	.type glLightModelf,@function");
__asm__("glLightModelf:");
__asm__("	ret");
__asm__(".globl glLightModelfv");
__asm__("	.type glLightModelfv,@function");
__asm__("glLightModelfv:");
__asm__("	ret");
__asm__(".globl glLightModeli");
__asm__("	.type glLightModeli,@function");
__asm__("glLightModeli:");
__asm__("	ret");
__asm__(".globl glLightModeliv");
__asm__("	.type glLightModeliv,@function");
__asm__("glLightModeliv:");
__asm__("	ret");
__asm__(".globl glLightf");
__asm__("	.type glLightf,@function");
__asm__("glLightf:");
__asm__("	ret");
__asm__(".globl glLightfv");
__asm__("	.type glLightfv,@function");
__asm__("glLightfv:");
__asm__("	ret");
__asm__(".globl glLighti");
__asm__("	.type glLighti,@function");
__asm__("glLighti:");
__asm__("	ret");
__asm__(".globl glLightiv");
__asm__("	.type glLightiv,@function");
__asm__("glLightiv:");
__asm__("	ret");
__asm__(".globl glLineStipple");
__asm__("	.type glLineStipple,@function");
__asm__("glLineStipple:");
__asm__("	ret");
__asm__(".globl glLineWidth");
__asm__("	.type glLineWidth,@function");
__asm__("glLineWidth:");
__asm__("	ret");
__asm__(".globl glListBase");
__asm__("	.type glListBase,@function");
__asm__("glListBase:");
__asm__("	ret");
__asm__(".globl glLoadIdentity");
__asm__("	.type glLoadIdentity,@function");
__asm__("glLoadIdentity:");
__asm__("	ret");
__asm__(".globl glLoadMatrixd");
__asm__("	.type glLoadMatrixd,@function");
__asm__("glLoadMatrixd:");
__asm__("	ret");
__asm__(".globl glLoadMatrixf");
__asm__("	.type glLoadMatrixf,@function");
__asm__("glLoadMatrixf:");
__asm__("	ret");
__asm__(".globl glLoadName");
__asm__("	.type glLoadName,@function");
__asm__("glLoadName:");
__asm__("	ret");
__asm__(".globl glLogicOp");
__asm__("	.type glLogicOp,@function");
__asm__("glLogicOp:");
__asm__("	ret");
__asm__(".globl glMap1d");
__asm__("	.type glMap1d,@function");
__asm__("glMap1d:");
__asm__("	ret");
__asm__(".globl glMap1f");
__asm__("	.type glMap1f,@function");
__asm__("glMap1f:");
__asm__("	ret");
__asm__(".globl glMap2d");
__asm__("	.type glMap2d,@function");
__asm__("glMap2d:");
__asm__("	ret");
__asm__(".globl glMap2f");
__asm__("	.type glMap2f,@function");
__asm__("glMap2f:");
__asm__("	ret");
__asm__(".globl glMapGrid1d");
__asm__("	.type glMapGrid1d,@function");
__asm__("glMapGrid1d:");
__asm__("	ret");
__asm__(".globl glMapGrid1f");
__asm__("	.type glMapGrid1f,@function");
__asm__("glMapGrid1f:");
__asm__("	ret");
__asm__(".globl glMapGrid2d");
__asm__("	.type glMapGrid2d,@function");
__asm__("glMapGrid2d:");
__asm__("	ret");
__asm__(".globl glMapGrid2f");
__asm__("	.type glMapGrid2f,@function");
__asm__("glMapGrid2f:");
__asm__("	ret");
__asm__(".globl glMaterialf");
__asm__("	.type glMaterialf,@function");
__asm__("glMaterialf:");
__asm__("	ret");
__asm__(".globl glMaterialfv");
__asm__("	.type glMaterialfv,@function");
__asm__("glMaterialfv:");
__asm__("	ret");
__asm__(".globl glMateriali");
__asm__("	.type glMateriali,@function");
__asm__("glMateriali:");
__asm__("	ret");
__asm__(".globl glMaterialiv");
__asm__("	.type glMaterialiv,@function");
__asm__("glMaterialiv:");
__asm__("	ret");
__asm__(".globl glMatrixMode");
__asm__("	.type glMatrixMode,@function");
__asm__("glMatrixMode:");
__asm__("	ret");
__asm__(".globl glMultMatrixd");
__asm__("	.type glMultMatrixd,@function");
__asm__("glMultMatrixd:");
__asm__("	ret");
__asm__(".globl glMultMatrixf");
__asm__("	.type glMultMatrixf,@function");
__asm__("glMultMatrixf:");
__asm__("	ret");
__asm__(".globl glNewList");
__asm__("	.type glNewList,@function");
__asm__("glNewList:");
__asm__("	ret");
__asm__(".globl glNormal3b");
__asm__("	.type glNormal3b,@function");
__asm__("glNormal3b:");
__asm__("	ret");
__asm__(".globl glNormal3bv");
__asm__("	.type glNormal3bv,@function");
__asm__("glNormal3bv:");
__asm__("	ret");
__asm__(".globl glNormal3d");
__asm__("	.type glNormal3d,@function");
__asm__("glNormal3d:");
__asm__("	ret");
__asm__(".globl glNormal3dv");
__asm__("	.type glNormal3dv,@function");
__asm__("glNormal3dv:");
__asm__("	ret");
__asm__(".globl glNormal3f");
__asm__("	.type glNormal3f,@function");
__asm__("glNormal3f:");
__asm__("	ret");
__asm__(".globl glNormal3fv");
__asm__("	.type glNormal3fv,@function");
__asm__("glNormal3fv:");
__asm__("	ret");
__asm__(".globl glNormal3i");
__asm__("	.type glNormal3i,@function");
__asm__("glNormal3i:");
__asm__("	ret");
__asm__(".globl glNormal3iv");
__asm__("	.type glNormal3iv,@function");
__asm__("glNormal3iv:");
__asm__("	ret");
__asm__(".globl glNormal3s");
__asm__("	.type glNormal3s,@function");
__asm__("glNormal3s:");
__asm__("	ret");
__asm__(".globl glNormal3sv");
__asm__("	.type glNormal3sv,@function");
__asm__("glNormal3sv:");
__asm__("	ret");
__asm__(".globl glNormalPointer");
__asm__("	.type glNormalPointer,@function");
__asm__("glNormalPointer:");
__asm__("	ret");
__asm__(".globl glOrtho");
__asm__("	.type glOrtho,@function");
__asm__("glOrtho:");
__asm__("	ret");
__asm__(".globl glPassThrough");
__asm__("	.type glPassThrough,@function");
__asm__("glPassThrough:");
__asm__("	ret");
__asm__(".globl glPixelMapfv");
__asm__("	.type glPixelMapfv,@function");
__asm__("glPixelMapfv:");
__asm__("	ret");
__asm__(".globl glPixelMapuiv");
__asm__("	.type glPixelMapuiv,@function");
__asm__("glPixelMapuiv:");
__asm__("	ret");
__asm__(".globl glPixelMapusv");
__asm__("	.type glPixelMapusv,@function");
__asm__("glPixelMapusv:");
__asm__("	ret");
__asm__(".globl glPixelStoref");
__asm__("	.type glPixelStoref,@function");
__asm__("glPixelStoref:");
__asm__("	ret");
__asm__(".globl glPixelStorei");
__asm__("	.type glPixelStorei,@function");
__asm__("glPixelStorei:");
__asm__("	ret");
__asm__(".globl glPixelTransferf");
__asm__("	.type glPixelTransferf,@function");
__asm__("glPixelTransferf:");
__asm__("	ret");
__asm__(".globl glPixelTransferi");
__asm__("	.type glPixelTransferi,@function");
__asm__("glPixelTransferi:");
__asm__("	ret");
__asm__(".globl glPixelZoom");
__asm__("	.type glPixelZoom,@function");
__asm__("glPixelZoom:");
__asm__("	ret");
__asm__(".globl glPointSize");
__asm__("	.type glPointSize,@function");
__asm__("glPointSize:");
__asm__("	ret");
__asm__(".globl glPolygonMode");
__asm__("	.type glPolygonMode,@function");
__asm__("glPolygonMode:");
__asm__("	ret");
__asm__(".globl glPolygonOffset");
__asm__("	.type glPolygonOffset,@function");
__asm__("glPolygonOffset:");
__asm__("	ret");
__asm__(".globl glPolygonStipple");
__asm__("	.type glPolygonStipple,@function");
__asm__("glPolygonStipple:");
__asm__("	ret");
__asm__(".globl glPopAttrib");
__asm__("	.type glPopAttrib,@function");
__asm__("glPopAttrib:");
__asm__("	ret");
__asm__(".globl glPopClientAttrib");
__asm__("	.type glPopClientAttrib,@function");
__asm__("glPopClientAttrib:");
__asm__("	ret");
__asm__(".globl glPopMatrix");
__asm__("	.type glPopMatrix,@function");
__asm__("glPopMatrix:");
__asm__("	ret");
__asm__(".globl glPopName");
__asm__("	.type glPopName,@function");
__asm__("glPopName:");
__asm__("	ret");
__asm__(".globl glPrioritizeTextures");
__asm__("	.type glPrioritizeTextures,@function");
__asm__("glPrioritizeTextures:");
__asm__("	ret");
__asm__(".globl glPushAttrib");
__asm__("	.type glPushAttrib,@function");
__asm__("glPushAttrib:");
__asm__("	ret");
__asm__(".globl glPushClientAttrib");
__asm__("	.type glPushClientAttrib,@function");
__asm__("glPushClientAttrib:");
__asm__("	ret");
__asm__(".globl glPushMatrix");
__asm__("	.type glPushMatrix,@function");
__asm__("glPushMatrix:");
__asm__("	ret");
__asm__(".globl glPushName");
__asm__("	.type glPushName,@function");
__asm__("glPushName:");
__asm__("	ret");
__asm__(".globl glRasterPos2d");
__asm__("	.type glRasterPos2d,@function");
__asm__("glRasterPos2d:");
__asm__("	ret");
__asm__(".globl glRasterPos2dv");
__asm__("	.type glRasterPos2dv,@function");
__asm__("glRasterPos2dv:");
__asm__("	ret");
__asm__(".globl glRasterPos2f");
__asm__("	.type glRasterPos2f,@function");
__asm__("glRasterPos2f:");
__asm__("	ret");
__asm__(".globl glRasterPos2fv");
__asm__("	.type glRasterPos2fv,@function");
__asm__("glRasterPos2fv:");
__asm__("	ret");
__asm__(".globl glRasterPos2i");
__asm__("	.type glRasterPos2i,@function");
__asm__("glRasterPos2i:");
__asm__("	ret");
__asm__(".globl glRasterPos2iv");
__asm__("	.type glRasterPos2iv,@function");
__asm__("glRasterPos2iv:");
__asm__("	ret");
__asm__(".globl glRasterPos2s");
__asm__("	.type glRasterPos2s,@function");
__asm__("glRasterPos2s:");
__asm__("	ret");
__asm__(".globl glRasterPos2sv");
__asm__("	.type glRasterPos2sv,@function");
__asm__("glRasterPos2sv:");
__asm__("	ret");
__asm__(".globl glRasterPos3d");
__asm__("	.type glRasterPos3d,@function");
__asm__("glRasterPos3d:");
__asm__("	ret");
__asm__(".globl glRasterPos3dv");
__asm__("	.type glRasterPos3dv,@function");
__asm__("glRasterPos3dv:");
__asm__("	ret");
__asm__(".globl glRasterPos3f");
__asm__("	.type glRasterPos3f,@function");
__asm__("glRasterPos3f:");
__asm__("	ret");
__asm__(".globl glRasterPos3fv");
__asm__("	.type glRasterPos3fv,@function");
__asm__("glRasterPos3fv:");
__asm__("	ret");
__asm__(".globl glRasterPos3i");
__asm__("	.type glRasterPos3i,@function");
__asm__("glRasterPos3i:");
__asm__("	ret");
__asm__(".globl glRasterPos3iv");
__asm__("	.type glRasterPos3iv,@function");
__asm__("glRasterPos3iv:");
__asm__("	ret");
__asm__(".globl glRasterPos3s");
__asm__("	.type glRasterPos3s,@function");
__asm__("glRasterPos3s:");
__asm__("	ret");
__asm__(".globl glRasterPos3sv");
__asm__("	.type glRasterPos3sv,@function");
__asm__("glRasterPos3sv:");
__asm__("	ret");
__asm__(".globl glRasterPos4d");
__asm__("	.type glRasterPos4d,@function");
__asm__("glRasterPos4d:");
__asm__("	ret");
__asm__(".globl glRasterPos4dv");
__asm__("	.type glRasterPos4dv,@function");
__asm__("glRasterPos4dv:");
__asm__("	ret");
__asm__(".globl glRasterPos4f");
__asm__("	.type glRasterPos4f,@function");
__asm__("glRasterPos4f:");
__asm__("	ret");
__asm__(".globl glRasterPos4fv");
__asm__("	.type glRasterPos4fv,@function");
__asm__("glRasterPos4fv:");
__asm__("	ret");
__asm__(".globl glRasterPos4i");
__asm__("	.type glRasterPos4i,@function");
__asm__("glRasterPos4i:");
__asm__("	ret");
__asm__(".globl glRasterPos4iv");
__asm__("	.type glRasterPos4iv,@function");
__asm__("glRasterPos4iv:");
__asm__("	ret");
__asm__(".globl glRasterPos4s");
__asm__("	.type glRasterPos4s,@function");
__asm__("glRasterPos4s:");
__asm__("	ret");
__asm__(".globl glRasterPos4sv");
__asm__("	.type glRasterPos4sv,@function");
__asm__("glRasterPos4sv:");
__asm__("	ret");
__asm__(".globl glReadBuffer");
__asm__("	.type glReadBuffer,@function");
__asm__("glReadBuffer:");
__asm__("	ret");
__asm__(".globl glReadPixels");
__asm__("	.type glReadPixels,@function");
__asm__("glReadPixels:");
__asm__("	ret");
__asm__(".globl glRectd");
__asm__("	.type glRectd,@function");
__asm__("glRectd:");
__asm__("	ret");
__asm__(".globl glRectdv");
__asm__("	.type glRectdv,@function");
__asm__("glRectdv:");
__asm__("	ret");
__asm__(".globl glRectf");
__asm__("	.type glRectf,@function");
__asm__("glRectf:");
__asm__("	ret");
__asm__(".globl glRectfv");
__asm__("	.type glRectfv,@function");
__asm__("glRectfv:");
__asm__("	ret");
__asm__(".globl glRecti");
__asm__("	.type glRecti,@function");
__asm__("glRecti:");
__asm__("	ret");
__asm__(".globl glRectiv");
__asm__("	.type glRectiv,@function");
__asm__("glRectiv:");
__asm__("	ret");
__asm__(".globl glRects");
__asm__("	.type glRects,@function");
__asm__("glRects:");
__asm__("	ret");
__asm__(".globl glRectsv");
__asm__("	.type glRectsv,@function");
__asm__("glRectsv:");
__asm__("	ret");
__asm__(".globl glRenderMode");
__asm__("	.type glRenderMode,@function");
__asm__("glRenderMode:");
__asm__("	ret");
__asm__(".globl glRotated");
__asm__("	.type glRotated,@function");
__asm__("glRotated:");
__asm__("	ret");
__asm__(".globl glRotatef");
__asm__("	.type glRotatef,@function");
__asm__("glRotatef:");
__asm__("	ret");
__asm__(".globl glScaled");
__asm__("	.type glScaled,@function");
__asm__("glScaled:");
__asm__("	ret");
__asm__(".globl glScalef");
__asm__("	.type glScalef,@function");
__asm__("glScalef:");
__asm__("	ret");
__asm__(".globl glScissor");
__asm__("	.type glScissor,@function");
__asm__("glScissor:");
__asm__("	ret");
__asm__(".globl glSelectBuffer");
__asm__("	.type glSelectBuffer,@function");
__asm__("glSelectBuffer:");
__asm__("	ret");
__asm__(".globl glShadeModel");
__asm__("	.type glShadeModel,@function");
__asm__("glShadeModel:");
__asm__("	ret");
__asm__(".globl glStencilFunc");
__asm__("	.type glStencilFunc,@function");
__asm__("glStencilFunc:");
__asm__("	ret");
__asm__(".globl glStencilMask");
__asm__("	.type glStencilMask,@function");
__asm__("glStencilMask:");
__asm__("	ret");
__asm__(".globl glStencilOp");
__asm__("	.type glStencilOp,@function");
__asm__("glStencilOp:");
__asm__("	ret");
__asm__(".globl glTexCoord1d");
__asm__("	.type glTexCoord1d,@function");
__asm__("glTexCoord1d:");
__asm__("	ret");
__asm__(".globl glTexCoord1dv");
__asm__("	.type glTexCoord1dv,@function");
__asm__("glTexCoord1dv:");
__asm__("	ret");
__asm__(".globl glTexCoord1f");
__asm__("	.type glTexCoord1f,@function");
__asm__("glTexCoord1f:");
__asm__("	ret");
__asm__(".globl glTexCoord1fv");
__asm__("	.type glTexCoord1fv,@function");
__asm__("glTexCoord1fv:");
__asm__("	ret");
__asm__(".globl glTexCoord1i");
__asm__("	.type glTexCoord1i,@function");
__asm__("glTexCoord1i:");
__asm__("	ret");
__asm__(".globl glTexCoord1iv");
__asm__("	.type glTexCoord1iv,@function");
__asm__("glTexCoord1iv:");
__asm__("	ret");
__asm__(".globl glTexCoord1s");
__asm__("	.type glTexCoord1s,@function");
__asm__("glTexCoord1s:");
__asm__("	ret");
__asm__(".globl glTexCoord1sv");
__asm__("	.type glTexCoord1sv,@function");
__asm__("glTexCoord1sv:");
__asm__("	ret");
__asm__(".globl glTexCoord2d");
__asm__("	.type glTexCoord2d,@function");
__asm__("glTexCoord2d:");
__asm__("	ret");
__asm__(".globl glTexCoord2dv");
__asm__("	.type glTexCoord2dv,@function");
__asm__("glTexCoord2dv:");
__asm__("	ret");
__asm__(".globl glTexCoord2f");
__asm__("	.type glTexCoord2f,@function");
__asm__("glTexCoord2f:");
__asm__("	ret");
__asm__(".globl glTexCoord2fv");
__asm__("	.type glTexCoord2fv,@function");
__asm__("glTexCoord2fv:");
__asm__("	ret");
__asm__(".globl glTexCoord2i");
__asm__("	.type glTexCoord2i,@function");
__asm__("glTexCoord2i:");
__asm__("	ret");
__asm__(".globl glTexCoord2iv");
__asm__("	.type glTexCoord2iv,@function");
__asm__("glTexCoord2iv:");
__asm__("	ret");
__asm__(".globl glTexCoord2s");
__asm__("	.type glTexCoord2s,@function");
__asm__("glTexCoord2s:");
__asm__("	ret");
__asm__(".globl glTexCoord2sv");
__asm__("	.type glTexCoord2sv,@function");
__asm__("glTexCoord2sv:");
__asm__("	ret");
__asm__(".globl glTexCoord3d");
__asm__("	.type glTexCoord3d,@function");
__asm__("glTexCoord3d:");
__asm__("	ret");
__asm__(".globl glTexCoord3dv");
__asm__("	.type glTexCoord3dv,@function");
__asm__("glTexCoord3dv:");
__asm__("	ret");
__asm__(".globl glTexCoord3f");
__asm__("	.type glTexCoord3f,@function");
__asm__("glTexCoord3f:");
__asm__("	ret");
__asm__(".globl glTexCoord3fv");
__asm__("	.type glTexCoord3fv,@function");
__asm__("glTexCoord3fv:");
__asm__("	ret");
__asm__(".globl glTexCoord3i");
__asm__("	.type glTexCoord3i,@function");
__asm__("glTexCoord3i:");
__asm__("	ret");
__asm__(".globl glTexCoord3iv");
__asm__("	.type glTexCoord3iv,@function");
__asm__("glTexCoord3iv:");
__asm__("	ret");
__asm__(".globl glTexCoord3s");
__asm__("	.type glTexCoord3s,@function");
__asm__("glTexCoord3s:");
__asm__("	ret");
__asm__(".globl glTexCoord3sv");
__asm__("	.type glTexCoord3sv,@function");
__asm__("glTexCoord3sv:");
__asm__("	ret");
__asm__(".globl glTexCoord4d");
__asm__("	.type glTexCoord4d,@function");
__asm__("glTexCoord4d:");
__asm__("	ret");
__asm__(".globl glTexCoord4dv");
__asm__("	.type glTexCoord4dv,@function");
__asm__("glTexCoord4dv:");
__asm__("	ret");
__asm__(".globl glTexCoord4f");
__asm__("	.type glTexCoord4f,@function");
__asm__("glTexCoord4f:");
__asm__("	ret");
__asm__(".globl glTexCoord4fv");
__asm__("	.type glTexCoord4fv,@function");
__asm__("glTexCoord4fv:");
__asm__("	ret");
__asm__(".globl glTexCoord4i");
__asm__("	.type glTexCoord4i,@function");
__asm__("glTexCoord4i:");
__asm__("	ret");
__asm__(".globl glTexCoord4iv");
__asm__("	.type glTexCoord4iv,@function");
__asm__("glTexCoord4iv:");
__asm__("	ret");
__asm__(".globl glTexCoord4s");
__asm__("	.type glTexCoord4s,@function");
__asm__("glTexCoord4s:");
__asm__("	ret");
__asm__(".globl glTexCoord4sv");
__asm__("	.type glTexCoord4sv,@function");
__asm__("glTexCoord4sv:");
__asm__("	ret");
__asm__(".globl glTexCoordPointer");
__asm__("	.type glTexCoordPointer,@function");
__asm__("glTexCoordPointer:");
__asm__("	ret");
__asm__(".globl glTexEnvf");
__asm__("	.type glTexEnvf,@function");
__asm__("glTexEnvf:");
__asm__("	ret");
__asm__(".globl glTexEnvfv");
__asm__("	.type glTexEnvfv,@function");
__asm__("glTexEnvfv:");
__asm__("	ret");
__asm__(".globl glTexEnvi");
__asm__("	.type glTexEnvi,@function");
__asm__("glTexEnvi:");
__asm__("	ret");
__asm__(".globl glTexEnviv");
__asm__("	.type glTexEnviv,@function");
__asm__("glTexEnviv:");
__asm__("	ret");
__asm__(".globl glTexGend");
__asm__("	.type glTexGend,@function");
__asm__("glTexGend:");
__asm__("	ret");
__asm__(".globl glTexGendv");
__asm__("	.type glTexGendv,@function");
__asm__("glTexGendv:");
__asm__("	ret");
__asm__(".globl glTexGenf");
__asm__("	.type glTexGenf,@function");
__asm__("glTexGenf:");
__asm__("	ret");
__asm__(".globl glTexGenfv");
__asm__("	.type glTexGenfv,@function");
__asm__("glTexGenfv:");
__asm__("	ret");
__asm__(".globl glTexGeni");
__asm__("	.type glTexGeni,@function");
__asm__("glTexGeni:");
__asm__("	ret");
__asm__(".globl glTexGeniv");
__asm__("	.type glTexGeniv,@function");
__asm__("glTexGeniv:");
__asm__("	ret");
__asm__(".globl glTexImage1D");
__asm__("	.type glTexImage1D,@function");
__asm__("glTexImage1D:");
__asm__("	ret");
__asm__(".globl glTexImage2D");
__asm__("	.type glTexImage2D,@function");
__asm__("glTexImage2D:");
__asm__("	ret");
__asm__(".globl glTexParameterf");
__asm__("	.type glTexParameterf,@function");
__asm__("glTexParameterf:");
__asm__("	ret");
__asm__(".globl glTexParameterfv");
__asm__("	.type glTexParameterfv,@function");
__asm__("glTexParameterfv:");
__asm__("	ret");
__asm__(".globl glTexParameteri");
__asm__("	.type glTexParameteri,@function");
__asm__("glTexParameteri:");
__asm__("	ret");
__asm__(".globl glTexParameteriv");
__asm__("	.type glTexParameteriv,@function");
__asm__("glTexParameteriv:");
__asm__("	ret");
__asm__(".globl glTexSubImage1D");
__asm__("	.type glTexSubImage1D,@function");
__asm__("glTexSubImage1D:");
__asm__("	ret");
__asm__(".globl glTexSubImage2D");
__asm__("	.type glTexSubImage2D,@function");
__asm__("glTexSubImage2D:");
__asm__("	ret");
__asm__(".globl glTranslated");
__asm__("	.type glTranslated,@function");
__asm__("glTranslated:");
__asm__("	ret");
__asm__(".globl glTranslatef");
__asm__("	.type glTranslatef,@function");
__asm__("glTranslatef:");
__asm__("	ret");
__asm__(".globl glVertex2d");
__asm__("	.type glVertex2d,@function");
__asm__("glVertex2d:");
__asm__("	ret");
__asm__(".globl glVertex2dv");
__asm__("	.type glVertex2dv,@function");
__asm__("glVertex2dv:");
__asm__("	ret");
__asm__(".globl glVertex2f");
__asm__("	.type glVertex2f,@function");
__asm__("glVertex2f:");
__asm__("	ret");
__asm__(".globl glVertex2fv");
__asm__("	.type glVertex2fv,@function");
__asm__("glVertex2fv:");
__asm__("	ret");
__asm__(".globl glVertex2i");
__asm__("	.type glVertex2i,@function");
__asm__("glVertex2i:");
__asm__("	ret");
__asm__(".globl glVertex2iv");
__asm__("	.type glVertex2iv,@function");
__asm__("glVertex2iv:");
__asm__("	ret");
__asm__(".globl glVertex2s");
__asm__("	.type glVertex2s,@function");
__asm__("glVertex2s:");
__asm__("	ret");
__asm__(".globl glVertex2sv");
__asm__("	.type glVertex2sv,@function");
__asm__("glVertex2sv:");
__asm__("	ret");
__asm__(".globl glVertex3d");
__asm__("	.type glVertex3d,@function");
__asm__("glVertex3d:");
__asm__("	ret");
__asm__(".globl glVertex3dv");
__asm__("	.type glVertex3dv,@function");
__asm__("glVertex3dv:");
__asm__("	ret");
__asm__(".globl glVertex3f");
__asm__("	.type glVertex3f,@function");
__asm__("glVertex3f:");
__asm__("	ret");
__asm__(".globl glVertex3fv");
__asm__("	.type glVertex3fv,@function");
__asm__("glVertex3fv:");
__asm__("	ret");
__asm__(".globl glVertex3i");
__asm__("	.type glVertex3i,@function");
__asm__("glVertex3i:");
__asm__("	ret");
__asm__(".globl glVertex3iv");
__asm__("	.type glVertex3iv,@function");
__asm__("glVertex3iv:");
__asm__("	ret");
__asm__(".globl glVertex3s");
__asm__("	.type glVertex3s,@function");
__asm__("glVertex3s:");
__asm__("	ret");
__asm__(".globl glVertex3sv");
__asm__("	.type glVertex3sv,@function");
__asm__("glVertex3sv:");
__asm__("	ret");
__asm__(".globl glVertex4d");
__asm__("	.type glVertex4d,@function");
__asm__("glVertex4d:");
__asm__("	ret");
__asm__(".globl glVertex4dv");
__asm__("	.type glVertex4dv,@function");
__asm__("glVertex4dv:");
__asm__("	ret");
__asm__(".globl glVertex4f");
__asm__("	.type glVertex4f,@function");
__asm__("glVertex4f:");
__asm__("	ret");
__asm__(".globl glVertex4fv");
__asm__("	.type glVertex4fv,@function");
__asm__("glVertex4fv:");
__asm__("	ret");
__asm__(".globl glVertex4i");
__asm__("	.type glVertex4i,@function");
__asm__("glVertex4i:");
__asm__("	ret");
__asm__(".globl glVertex4iv");
__asm__("	.type glVertex4iv,@function");
__asm__("glVertex4iv:");
__asm__("	ret");
__asm__(".globl glVertex4s");
__asm__("	.type glVertex4s,@function");
__asm__("glVertex4s:");
__asm__("	ret");
__asm__(".globl glVertex4sv");
__asm__("	.type glVertex4sv,@function");
__asm__("glVertex4sv:");
__asm__("	ret");
__asm__(".globl glVertexPointer");
__asm__("	.type glVertexPointer,@function");
__asm__("glVertexPointer:");
__asm__("	ret");
__asm__(".globl glViewport");
__asm__("	.type glViewport,@function");
__asm__("glViewport:");
__asm__("	ret");
__asm__(".globl glXChooseVisual");
__asm__("	.type glXChooseVisual,@function");
__asm__("glXChooseVisual:");
__asm__("	ret");
__asm__(".globl glXCopyContext");
__asm__("	.type glXCopyContext,@function");
__asm__("glXCopyContext:");
__asm__("	ret");
__asm__(".globl glXCreateContext");
__asm__("	.type glXCreateContext,@function");
__asm__("glXCreateContext:");
__asm__("	ret");
__asm__(".globl glXCreateGLXPixmap");
__asm__("	.type glXCreateGLXPixmap,@function");
__asm__("glXCreateGLXPixmap:");
__asm__("	ret");
__asm__(".globl glXDestroyContext");
__asm__("	.type glXDestroyContext,@function");
__asm__("glXDestroyContext:");
__asm__("	ret");
__asm__(".globl glXDestroyGLXPixmap");
__asm__("	.type glXDestroyGLXPixmap,@function");
__asm__("glXDestroyGLXPixmap:");
__asm__("	ret");
__asm__(".globl glXFreeContextEXT");
__asm__("	.type glXFreeContextEXT,@function");
__asm__("glXFreeContextEXT:");
__asm__("	ret");
__asm__(".globl glXGetClientString");
__asm__("	.type glXGetClientString,@function");
__asm__("glXGetClientString:");
__asm__("	ret");
__asm__(".globl glXGetConfig");
__asm__("	.type glXGetConfig,@function");
__asm__("glXGetConfig:");
__asm__("	ret");
__asm__(".globl glXGetContextIDEXT");
__asm__("	.type glXGetContextIDEXT,@function");
__asm__("glXGetContextIDEXT:");
__asm__("	ret");
__asm__(".globl glXGetCurrentContext");
__asm__("	.type glXGetCurrentContext,@function");
__asm__("glXGetCurrentContext:");
__asm__("	ret");
__asm__(".globl glXGetCurrentDisplay");
__asm__("	.type glXGetCurrentDisplay,@function");
__asm__("glXGetCurrentDisplay:");
__asm__("	ret");
__asm__(".globl glXGetCurrentDrawable");
__asm__("	.type glXGetCurrentDrawable,@function");
__asm__("glXGetCurrentDrawable:");
__asm__("	ret");
__asm__(".globl glXImportContextEXT");
__asm__("	.type glXImportContextEXT,@function");
__asm__("glXImportContextEXT:");
__asm__("	ret");
__asm__(".globl glXIsDirect");
__asm__("	.type glXIsDirect,@function");
__asm__("glXIsDirect:");
__asm__("	ret");
__asm__(".globl glXMakeCurrent");
__asm__("	.type glXMakeCurrent,@function");
__asm__("glXMakeCurrent:");
__asm__("	ret");
__asm__(".globl glXQueryContextInfoEXT");
__asm__("	.type glXQueryContextInfoEXT,@function");
__asm__("glXQueryContextInfoEXT:");
__asm__("	ret");
__asm__(".globl glXQueryExtension");
__asm__("	.type glXQueryExtension,@function");
__asm__("glXQueryExtension:");
__asm__("	ret");
__asm__(".globl glXQueryExtensionsString");
__asm__("	.type glXQueryExtensionsString,@function");
__asm__("glXQueryExtensionsString:");
__asm__("	ret");
__asm__(".globl glXQueryServerString");
__asm__("	.type glXQueryServerString,@function");
__asm__("glXQueryServerString:");
__asm__("	ret");
__asm__(".globl glXQueryVersion");
__asm__("	.type glXQueryVersion,@function");
__asm__("glXQueryVersion:");
__asm__("	ret");
__asm__(".globl glXSwapBuffers");
__asm__("	.type glXSwapBuffers,@function");
__asm__("glXSwapBuffers:");
__asm__("	ret");
__asm__(".globl glXUseXFont");
__asm__("	.type glXUseXFont,@function");
__asm__("glXUseXFont:");
__asm__("	ret");
__asm__(".globl glXWaitGL");
__asm__("	.type glXWaitGL,@function");
__asm__("glXWaitGL:");
__asm__("	ret");
__asm__(".globl glXWaitX");
__asm__("	.type glXWaitX,@function");
__asm__("glXWaitX:");
__asm__("	ret");
__asm__(".globl glDrawRangeElements");
__asm__("	.type glDrawRangeElements,@function");
__asm__("glDrawRangeElements:");
__asm__("	ret");
__asm__(".globl glTexImage3D");
__asm__("	.type glTexImage3D,@function");
__asm__("glTexImage3D:");
__asm__("	ret");
__asm__(".globl glTexSubImage3D");
__asm__("	.type glTexSubImage3D,@function");
__asm__("glTexSubImage3D:");
__asm__("	ret");
__asm__(".globl glCopyTexSubImage3D");
__asm__("	.type glCopyTexSubImage3D,@function");
__asm__("glCopyTexSubImage3D:");
__asm__("	ret");
__asm__(".globl glColorTable");
__asm__("	.type glColorTable,@function");
__asm__("glColorTable:");
__asm__("	ret");
__asm__(".globl glColorSubTable");
__asm__("	.type glColorSubTable,@function");
__asm__("glColorSubTable:");
__asm__("	ret");
__asm__(".globl glColorTableParameteriv");
__asm__("	.type glColorTableParameteriv,@function");
__asm__("glColorTableParameteriv:");
__asm__("	ret");
__asm__(".globl glColorTableParameterfv");
__asm__("	.type glColorTableParameterfv,@function");
__asm__("glColorTableParameterfv:");
__asm__("	ret");
__asm__(".globl glCopyColorSubTable");
__asm__("	.type glCopyColorSubTable,@function");
__asm__("glCopyColorSubTable:");
__asm__("	ret");
__asm__(".globl glCopyColorTable");
__asm__("	.type glCopyColorTable,@function");
__asm__("glCopyColorTable:");
__asm__("	ret");
__asm__(".globl glGetColorTable");
__asm__("	.type glGetColorTable,@function");
__asm__("glGetColorTable:");
__asm__("	ret");
__asm__(".globl glGetColorTableParameterfv");
__asm__("	.type glGetColorTableParameterfv,@function");
__asm__("glGetColorTableParameterfv:");
__asm__("	ret");
__asm__(".globl glGetColorTableParameteriv");
__asm__("	.type glGetColorTableParameteriv,@function");
__asm__("glGetColorTableParameteriv:");
__asm__("	ret");
__asm__(".globl glBlendEquation");
__asm__("	.type glBlendEquation,@function");
__asm__("glBlendEquation:");
__asm__("	ret");
__asm__(".globl glBlendColor");
__asm__("	.type glBlendColor,@function");
__asm__("glBlendColor:");
__asm__("	ret");
__asm__(".globl glHistogram");
__asm__("	.type glHistogram,@function");
__asm__("glHistogram:");
__asm__("	ret");
__asm__(".globl glResetHistogram");
__asm__("	.type glResetHistogram,@function");
__asm__("glResetHistogram:");
__asm__("	ret");
__asm__(".globl glGetHistogram");
__asm__("	.type glGetHistogram,@function");
__asm__("glGetHistogram:");
__asm__("	ret");
__asm__(".globl glGetHistogramParameterfv");
__asm__("	.type glGetHistogramParameterfv,@function");
__asm__("glGetHistogramParameterfv:");
__asm__("	ret");
__asm__(".globl glGetHistogramParameteriv");
__asm__("	.type glGetHistogramParameteriv,@function");
__asm__("glGetHistogramParameteriv:");
__asm__("	ret");
__asm__(".globl glMinmax");
__asm__("	.type glMinmax,@function");
__asm__("glMinmax:");
__asm__("	ret");
__asm__(".globl glResetMinmax");
__asm__("	.type glResetMinmax,@function");
__asm__("glResetMinmax:");
__asm__("	ret");
__asm__(".globl glGetMinmax");
__asm__("	.type glGetMinmax,@function");
__asm__("glGetMinmax:");
__asm__("	ret");
__asm__(".globl glGetMinmaxParameterfv");
__asm__("	.type glGetMinmaxParameterfv,@function");
__asm__("glGetMinmaxParameterfv:");
__asm__("	ret");
__asm__(".globl glGetMinmaxParameteriv");
__asm__("	.type glGetMinmaxParameteriv,@function");
__asm__("glGetMinmaxParameteriv:");
__asm__("	ret");
__asm__(".globl glConvolutionFilter1D");
__asm__("	.type glConvolutionFilter1D,@function");
__asm__("glConvolutionFilter1D:");
__asm__("	ret");
__asm__(".globl glConvolutionFilter2D");
__asm__("	.type glConvolutionFilter2D,@function");
__asm__("glConvolutionFilter2D:");
__asm__("	ret");
__asm__(".globl glConvolutionParameterf");
__asm__("	.type glConvolutionParameterf,@function");
__asm__("glConvolutionParameterf:");
__asm__("	ret");
__asm__(".globl glConvolutionParameterfv");
__asm__("	.type glConvolutionParameterfv,@function");
__asm__("glConvolutionParameterfv:");
__asm__("	ret");
__asm__(".globl glConvolutionParameteri");
__asm__("	.type glConvolutionParameteri,@function");
__asm__("glConvolutionParameteri:");
__asm__("	ret");
__asm__(".globl glConvolutionParameteriv");
__asm__("	.type glConvolutionParameteriv,@function");
__asm__("glConvolutionParameteriv:");
__asm__("	ret");
__asm__(".globl glCopyConvolutionFilter1D");
__asm__("	.type glCopyConvolutionFilter1D,@function");
__asm__("glCopyConvolutionFilter1D:");
__asm__("	ret");
__asm__(".globl glCopyConvolutionFilter2D");
__asm__("	.type glCopyConvolutionFilter2D,@function");
__asm__("glCopyConvolutionFilter2D:");
__asm__("	ret");
__asm__(".globl glGetConvolutionFilter");
__asm__("	.type glGetConvolutionFilter,@function");
__asm__("glGetConvolutionFilter:");
__asm__("	ret");
__asm__(".globl glGetConvolutionParameterfv");
__asm__("	.type glGetConvolutionParameterfv,@function");
__asm__("glGetConvolutionParameterfv:");
__asm__("	ret");
__asm__(".globl glGetConvolutionParameteriv");
__asm__("	.type glGetConvolutionParameteriv,@function");
__asm__("glGetConvolutionParameteriv:");
__asm__("	ret");
__asm__(".globl glSeparableFilter2D");
__asm__("	.type glSeparableFilter2D,@function");
__asm__("glSeparableFilter2D:");
__asm__("	ret");
__asm__(".globl glGetSeparableFilter");
__asm__("	.type glGetSeparableFilter,@function");
__asm__("glGetSeparableFilter:");
__asm__("	ret");
__asm__(".globl glActiveTextureARB");
__asm__("	.type glActiveTextureARB,@function");
__asm__("glActiveTextureARB:");
__asm__("	ret");
__asm__(".globl glClientActiveTextureARB");
__asm__("	.type glClientActiveTextureARB,@function");
__asm__("glClientActiveTextureARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1dARB");
__asm__("	.type glMultiTexCoord1dARB,@function");
__asm__("glMultiTexCoord1dARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1dvARB");
__asm__("	.type glMultiTexCoord1dvARB,@function");
__asm__("glMultiTexCoord1dvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1fARB");
__asm__("	.type glMultiTexCoord1fARB,@function");
__asm__("glMultiTexCoord1fARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1fvARB");
__asm__("	.type glMultiTexCoord1fvARB,@function");
__asm__("glMultiTexCoord1fvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1iARB");
__asm__("	.type glMultiTexCoord1iARB,@function");
__asm__("glMultiTexCoord1iARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1ivARB");
__asm__("	.type glMultiTexCoord1ivARB,@function");
__asm__("glMultiTexCoord1ivARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1sARB");
__asm__("	.type glMultiTexCoord1sARB,@function");
__asm__("glMultiTexCoord1sARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord1svARB");
__asm__("	.type glMultiTexCoord1svARB,@function");
__asm__("glMultiTexCoord1svARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2dARB");
__asm__("	.type glMultiTexCoord2dARB,@function");
__asm__("glMultiTexCoord2dARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2dvARB");
__asm__("	.type glMultiTexCoord2dvARB,@function");
__asm__("glMultiTexCoord2dvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2fARB");
__asm__("	.type glMultiTexCoord2fARB,@function");
__asm__("glMultiTexCoord2fARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2fvARB");
__asm__("	.type glMultiTexCoord2fvARB,@function");
__asm__("glMultiTexCoord2fvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2iARB");
__asm__("	.type glMultiTexCoord2iARB,@function");
__asm__("glMultiTexCoord2iARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2ivARB");
__asm__("	.type glMultiTexCoord2ivARB,@function");
__asm__("glMultiTexCoord2ivARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2sARB");
__asm__("	.type glMultiTexCoord2sARB,@function");
__asm__("glMultiTexCoord2sARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord2svARB");
__asm__("	.type glMultiTexCoord2svARB,@function");
__asm__("glMultiTexCoord2svARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3dARB");
__asm__("	.type glMultiTexCoord3dARB,@function");
__asm__("glMultiTexCoord3dARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3dvARB");
__asm__("	.type glMultiTexCoord3dvARB,@function");
__asm__("glMultiTexCoord3dvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3fARB");
__asm__("	.type glMultiTexCoord3fARB,@function");
__asm__("glMultiTexCoord3fARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3fvARB");
__asm__("	.type glMultiTexCoord3fvARB,@function");
__asm__("glMultiTexCoord3fvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3iARB");
__asm__("	.type glMultiTexCoord3iARB,@function");
__asm__("glMultiTexCoord3iARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3ivARB");
__asm__("	.type glMultiTexCoord3ivARB,@function");
__asm__("glMultiTexCoord3ivARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3sARB");
__asm__("	.type glMultiTexCoord3sARB,@function");
__asm__("glMultiTexCoord3sARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord3svARB");
__asm__("	.type glMultiTexCoord3svARB,@function");
__asm__("glMultiTexCoord3svARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4dARB");
__asm__("	.type glMultiTexCoord4dARB,@function");
__asm__("glMultiTexCoord4dARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4dvARB");
__asm__("	.type glMultiTexCoord4dvARB,@function");
__asm__("glMultiTexCoord4dvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4fARB");
__asm__("	.type glMultiTexCoord4fARB,@function");
__asm__("glMultiTexCoord4fARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4fvARB");
__asm__("	.type glMultiTexCoord4fvARB,@function");
__asm__("glMultiTexCoord4fvARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4iARB");
__asm__("	.type glMultiTexCoord4iARB,@function");
__asm__("glMultiTexCoord4iARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4ivARB");
__asm__("	.type glMultiTexCoord4ivARB,@function");
__asm__("glMultiTexCoord4ivARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4sARB");
__asm__("	.type glMultiTexCoord4sARB,@function");
__asm__("glMultiTexCoord4sARB:");
__asm__("	ret");
__asm__(".globl glMultiTexCoord4svARB");
__asm__("	.type glMultiTexCoord4svARB,@function");
__asm__("glMultiTexCoord4svARB:");
__asm__("	ret");
__asm__(".globl glXChooseFBConfig");
__asm__("	.type glXChooseFBConfig,@function");
__asm__("glXChooseFBConfig:");
__asm__("	ret");
__asm__(".globl glXGetFBConfigAttrib");
__asm__("	.type glXGetFBConfigAttrib,@function");
__asm__("glXGetFBConfigAttrib:");
__asm__("	ret");
__asm__(".globl glXGetVisualFromFBConfig");
__asm__("	.type glXGetVisualFromFBConfig,@function");
__asm__("glXGetVisualFromFBConfig:");
__asm__("	ret");
__asm__(".globl glXCreateWindow");
__asm__("	.type glXCreateWindow,@function");
__asm__("glXCreateWindow:");
__asm__("	ret");
__asm__(".globl glXDestroyWindow");
__asm__("	.type glXDestroyWindow,@function");
__asm__("glXDestroyWindow:");
__asm__("	ret");
__asm__(".globl glXCreatePixmap");
__asm__("	.type glXCreatePixmap,@function");
__asm__("glXCreatePixmap:");
__asm__("	ret");
__asm__(".globl glXDestroyPixmap");
__asm__("	.type glXDestroyPixmap,@function");
__asm__("glXDestroyPixmap:");
__asm__("	ret");
__asm__(".globl glXCreatePbuffer");
__asm__("	.type glXCreatePbuffer,@function");
__asm__("glXCreatePbuffer:");
__asm__("	ret");
__asm__(".globl glXDestroyPbuffer");
__asm__("	.type glXDestroyPbuffer,@function");
__asm__("glXDestroyPbuffer:");
__asm__("	ret");
__asm__(".globl glXQueryDrawable");
__asm__("	.type glXQueryDrawable,@function");
__asm__("glXQueryDrawable:");
__asm__("	ret");
__asm__(".globl glXCreateNewContext");
__asm__("	.type glXCreateNewContext,@function");
__asm__("glXCreateNewContext:");
__asm__("	ret");
__asm__(".globl glXMakeContextCurrent");
__asm__("	.type glXMakeContextCurrent,@function");
__asm__("glXMakeContextCurrent:");
__asm__("	ret");
__asm__(".globl glXGetCurrentReadDrawable");
__asm__("	.type glXGetCurrentReadDrawable,@function");
__asm__("glXGetCurrentReadDrawable:");
__asm__("	ret");
__asm__(".globl glXQueryContext");
__asm__("	.type glXQueryContext,@function");
__asm__("glXQueryContext:");
__asm__("	ret");
__asm__(".globl glXSelectEvent");
__asm__("	.type glXSelectEvent,@function");
__asm__("glXSelectEvent:");
__asm__("	ret");
__asm__(".globl glXGetSelectedEvent");
__asm__("	.type glXGetSelectedEvent,@function");
__asm__("glXGetSelectedEvent:");
__asm__("	ret");
