__asm__(".globl IceAcceptConnection");
__asm__("	.type IceAcceptConnection,@function");
__asm__("IceAcceptConnection:");
__asm__("	ret");
__asm__(".globl IceAddConnectionWatch");
__asm__("	.type IceAddConnectionWatch,@function");
__asm__("IceAddConnectionWatch:");
__asm__("	ret");
__asm__(".globl IceAllocScratch");
__asm__("	.type IceAllocScratch,@function");
__asm__("IceAllocScratch:");
__asm__("	ret");
__asm__(".globl IceAppLockConn");
__asm__("	.type IceAppLockConn,@function");
__asm__("IceAppLockConn:");
__asm__("	ret");
__asm__(".globl IceAppUnlockConn");
__asm__("	.type IceAppUnlockConn,@function");
__asm__("IceAppUnlockConn:");
__asm__("	ret");
__asm__(".globl IceAuthFileName");
__asm__("	.type IceAuthFileName,@function");
__asm__("IceAuthFileName:");
__asm__("	ret");
__asm__(".globl IceCheckShutdownNegotiation");
__asm__("	.type IceCheckShutdownNegotiation,@function");
__asm__("IceCheckShutdownNegotiation:");
__asm__("	ret");
__asm__(".globl IceCloseConnection");
__asm__("	.type IceCloseConnection,@function");
__asm__("IceCloseConnection:");
__asm__("	ret");
__asm__(".globl IceComposeNetworkIdList");
__asm__("	.type IceComposeNetworkIdList,@function");
__asm__("IceComposeNetworkIdList:");
__asm__("	ret");
__asm__(".globl IceConnectionNumber");
__asm__("	.type IceConnectionNumber,@function");
__asm__("IceConnectionNumber:");
__asm__("	ret");
__asm__(".globl IceConnectionStatus");
__asm__("	.type IceConnectionStatus,@function");
__asm__("IceConnectionStatus:");
__asm__("	ret");
__asm__(".globl IceConnectionString");
__asm__("	.type IceConnectionString,@function");
__asm__("IceConnectionString:");
__asm__("	ret");
__asm__(".globl IceFlush");
__asm__("	.type IceFlush,@function");
__asm__("IceFlush:");
__asm__("	ret");
__asm__(".globl IceFreeAuthFileEntry");
__asm__("	.type IceFreeAuthFileEntry,@function");
__asm__("IceFreeAuthFileEntry:");
__asm__("	ret");
__asm__(".globl IceFreeListenObjs");
__asm__("	.type IceFreeListenObjs,@function");
__asm__("IceFreeListenObjs:");
__asm__("	ret");
__asm__(".globl IceGenerateMagicCookie");
__asm__("	.type IceGenerateMagicCookie,@function");
__asm__("IceGenerateMagicCookie:");
__asm__("	ret");
__asm__(".globl IceGetAuthFileEntry");
__asm__("	.type IceGetAuthFileEntry,@function");
__asm__("IceGetAuthFileEntry:");
__asm__("	ret");
__asm__(".globl IceGetConnectionContext");
__asm__("	.type IceGetConnectionContext,@function");
__asm__("IceGetConnectionContext:");
__asm__("	ret");
__asm__(".globl IceGetInBufSize");
__asm__("	.type IceGetInBufSize,@function");
__asm__("IceGetInBufSize:");
__asm__("	ret");
__asm__(".globl IceGetListenConnectionNumber");
__asm__("	.type IceGetListenConnectionNumber,@function");
__asm__("IceGetListenConnectionNumber:");
__asm__("	ret");
__asm__(".globl IceGetListenConnectionString");
__asm__("	.type IceGetListenConnectionString,@function");
__asm__("IceGetListenConnectionString:");
__asm__("	ret");
__asm__(".globl IceGetOutBufSize");
__asm__("	.type IceGetOutBufSize,@function");
__asm__("IceGetOutBufSize:");
__asm__("	ret");
__asm__(".globl IceInitThreads");
__asm__("	.type IceInitThreads,@function");
__asm__("IceInitThreads:");
__asm__("	ret");
__asm__(".globl IceLastReceivedSequenceNumber");
__asm__("	.type IceLastReceivedSequenceNumber,@function");
__asm__("IceLastReceivedSequenceNumber:");
__asm__("	ret");
__asm__(".globl IceLastSentSequenceNumber");
__asm__("	.type IceLastSentSequenceNumber,@function");
__asm__("IceLastSentSequenceNumber:");
__asm__("	ret");
__asm__(".globl IceListenForConnections");
__asm__("	.type IceListenForConnections,@function");
__asm__("IceListenForConnections:");
__asm__("	ret");
__asm__(".globl IceListenForWellKnownConnections");
__asm__("	.type IceListenForWellKnownConnections,@function");
__asm__("IceListenForWellKnownConnections:");
__asm__("	ret");
__asm__(".globl IceLockAuthFile");
__asm__("	.type IceLockAuthFile,@function");
__asm__("IceLockAuthFile:");
__asm__("	ret");
__asm__(".globl IceOpenConnection");
__asm__("	.type IceOpenConnection,@function");
__asm__("IceOpenConnection:");
__asm__("	ret");
__asm__(".globl IcePing");
__asm__("	.type IcePing,@function");
__asm__("IcePing:");
__asm__("	ret");
__asm__(".globl IceProcessMessages");
__asm__("	.type IceProcessMessages,@function");
__asm__("IceProcessMessages:");
__asm__("	ret");
__asm__(".globl IceProtocolRevision");
__asm__("	.type IceProtocolRevision,@function");
__asm__("IceProtocolRevision:");
__asm__("	ret");
__asm__(".globl IceProtocolSetup");
__asm__("	.type IceProtocolSetup,@function");
__asm__("IceProtocolSetup:");
__asm__("	ret");
__asm__(".globl IceProtocolShutdown");
__asm__("	.type IceProtocolShutdown,@function");
__asm__("IceProtocolShutdown:");
__asm__("	ret");
__asm__(".globl IceProtocolVersion");
__asm__("	.type IceProtocolVersion,@function");
__asm__("IceProtocolVersion:");
__asm__("	ret");
__asm__(".globl IceReadAuthFileEntry");
__asm__("	.type IceReadAuthFileEntry,@function");
__asm__("IceReadAuthFileEntry:");
__asm__("	ret");
__asm__(".globl IceRegisterForProtocolReply");
__asm__("	.type IceRegisterForProtocolReply,@function");
__asm__("IceRegisterForProtocolReply:");
__asm__("	ret");
__asm__(".globl IceRegisterForProtocolSetup");
__asm__("	.type IceRegisterForProtocolSetup,@function");
__asm__("IceRegisterForProtocolSetup:");
__asm__("	ret");
__asm__(".globl IceRelease");
__asm__("	.type IceRelease,@function");
__asm__("IceRelease:");
__asm__("	ret");
__asm__(".globl IceRemoveConnectionWatch");
__asm__("	.type IceRemoveConnectionWatch,@function");
__asm__("IceRemoveConnectionWatch:");
__asm__("	ret");
__asm__(".globl IceSetErrorHandler");
__asm__("	.type IceSetErrorHandler,@function");
__asm__("IceSetErrorHandler:");
__asm__("	ret");
__asm__(".globl IceSetHostBasedAuthProc");
__asm__("	.type IceSetHostBasedAuthProc,@function");
__asm__("IceSetHostBasedAuthProc:");
__asm__("	ret");
__asm__(".globl IceSetIOErrorHandler");
__asm__("	.type IceSetIOErrorHandler,@function");
__asm__("IceSetIOErrorHandler:");
__asm__("	ret");
__asm__(".globl IceSetPaAuthData");
__asm__("	.type IceSetPaAuthData,@function");
__asm__("IceSetPaAuthData:");
__asm__("	ret");
__asm__(".globl IceSetShutdownNegotiation");
__asm__("	.type IceSetShutdownNegotiation,@function");
__asm__("IceSetShutdownNegotiation:");
__asm__("	ret");
__asm__(".globl IceSwapping");
__asm__("	.type IceSwapping,@function");
__asm__("IceSwapping:");
__asm__("	ret");
__asm__(".globl IceUnlockAuthFile");
__asm__("	.type IceUnlockAuthFile,@function");
__asm__("IceUnlockAuthFile:");
__asm__("	ret");
__asm__(".globl IceVendor");
__asm__("	.type IceVendor,@function");
__asm__("IceVendor:");
__asm__("	ret");
__asm__(".globl IceWriteAuthFileEntry");
__asm__("	.type IceWriteAuthFileEntry,@function");
__asm__("IceWriteAuthFileEntry:");
__asm__("	ret");
