__asm__(".globl _lsb_feclearexcept");
__asm__("	.type _lsb_feclearexcept,@function");
__asm__("_lsb_feclearexcept:");
__asm__("	ret");
__asm__(".symver _lsb_feclearexcept,feclearexcept@@GLIBC_2.1");
__asm__(".globl _lsb_fegetenv");
__asm__("	.type _lsb_fegetenv,@function");
__asm__("_lsb_fegetenv:");
__asm__("	ret");
__asm__(".symver _lsb_fegetenv,fegetenv@@GLIBC_2.1");
__asm__(".globl _lsb_fegetexceptflag");
__asm__("	.type _lsb_fegetexceptflag,@function");
__asm__("_lsb_fegetexceptflag:");
__asm__("	ret");
__asm__(".symver _lsb_fegetexceptflag,fegetexceptflag@@GLIBC_2.1");
__asm__(".globl _lsb_fegetround");
__asm__("	.type _lsb_fegetround,@function");
__asm__("_lsb_fegetround:");
__asm__("	ret");
__asm__(".symver _lsb_fegetround,fegetround@@GLIBC_2.1");
__asm__(".globl _lsb_feholdexcept");
__asm__("	.type _lsb_feholdexcept,@function");
__asm__("_lsb_feholdexcept:");
__asm__("	ret");
__asm__(".symver _lsb_feholdexcept,feholdexcept@@GLIBC_2.1");
__asm__(".globl _lsb_feraiseexcept");
__asm__("	.type _lsb_feraiseexcept,@function");
__asm__("_lsb_feraiseexcept:");
__asm__("	ret");
__asm__(".symver _lsb_feraiseexcept,feraiseexcept@@GLIBC_2.1");
__asm__(".globl _lsb_fesetenv");
__asm__("	.type _lsb_fesetenv,@function");
__asm__("_lsb_fesetenv:");
__asm__("	ret");
__asm__(".symver _lsb_fesetenv,fesetenv@@GLIBC_2.1");
__asm__(".globl _lsb_fesetexceptflag");
__asm__("	.type _lsb_fesetexceptflag,@function");
__asm__("_lsb_fesetexceptflag:");
__asm__("	ret");
__asm__(".symver _lsb_fesetexceptflag,fesetexceptflag@@GLIBC_2.1");
__asm__(".globl _lsb_fesetround");
__asm__("	.type _lsb_fesetround,@function");
__asm__("_lsb_fesetround:");
__asm__("	ret");
__asm__(".symver _lsb_fesetround,fesetround@@GLIBC_2.1");
__asm__(".globl _lsb_fetestexcept");
__asm__("	.type _lsb_fetestexcept,@function");
__asm__("_lsb_fetestexcept:");
__asm__("	ret");
__asm__(".symver _lsb_fetestexcept,fetestexcept@@GLIBC_2.1");
__asm__(".globl _lsb_feupdateenv");
__asm__("	.type _lsb_feupdateenv,@function");
__asm__("_lsb_feupdateenv:");
__asm__("	ret");
__asm__(".symver _lsb_feupdateenv,feupdateenv@@GLIBC_2.1");
__asm__(".globl _lsb_copysign");
__asm__("	.type _lsb_copysign,@function");
__asm__("_lsb_copysign:");
__asm__("	ret");
__asm__(".symver _lsb_copysign,copysign@@GLIBC_2.0");
__asm__(".globl _lsb_finite");
__asm__("	.type _lsb_finite,@function");
__asm__("_lsb_finite:");
__asm__("	ret");
__asm__(".symver _lsb_finite,finite@@GLIBC_2.0");
__asm__(".globl _lsb_frexp");
__asm__("	.type _lsb_frexp,@function");
__asm__("_lsb_frexp:");
__asm__("	ret");
__asm__(".symver _lsb_frexp,frexp@@GLIBC_2.0");
__asm__(".globl _lsb_ldexp");
__asm__("	.type _lsb_ldexp,@function");
__asm__("_lsb_ldexp:");
__asm__("	ret");
__asm__(".symver _lsb_ldexp,ldexp@@GLIBC_2.0");
__asm__(".globl _lsb_modf");
__asm__("	.type _lsb_modf,@function");
__asm__("_lsb_modf:");
__asm__("	ret");
__asm__(".symver _lsb_modf,modf@@GLIBC_2.0");
__asm__(".globl _lsb_acos");
__asm__("	.type _lsb_acos,@function");
__asm__("_lsb_acos:");
__asm__("	ret");
__asm__(".symver _lsb_acos,acos@@GLIBC_2.0");
__asm__(".globl _lsb_acosh");
__asm__("	.type _lsb_acosh,@function");
__asm__("_lsb_acosh:");
__asm__("	ret");
__asm__(".symver _lsb_acosh,acosh@@GLIBC_2.0");
__asm__(".globl _lsb_asinh");
__asm__("	.type _lsb_asinh,@function");
__asm__("_lsb_asinh:");
__asm__("	ret");
__asm__(".symver _lsb_asinh,asinh@@GLIBC_2.0");
__asm__(".globl _lsb_atanh");
__asm__("	.type _lsb_atanh,@function");
__asm__("_lsb_atanh:");
__asm__("	ret");
__asm__(".symver _lsb_atanh,atanh@@GLIBC_2.0");
__asm__(".globl _lsb_asin");
__asm__("	.type _lsb_asin,@function");
__asm__("_lsb_asin:");
__asm__("	ret");
__asm__(".symver _lsb_asin,asin@@GLIBC_2.0");
__asm__(".globl _lsb_atan");
__asm__("	.type _lsb_atan,@function");
__asm__("_lsb_atan:");
__asm__("	ret");
__asm__(".symver _lsb_atan,atan@@GLIBC_2.0");
__asm__(".globl _lsb_atan2");
__asm__("	.type _lsb_atan2,@function");
__asm__("_lsb_atan2:");
__asm__("	ret");
__asm__(".symver _lsb_atan2,atan2@@GLIBC_2.0");
__asm__(".globl _lsb_cbrt");
__asm__("	.type _lsb_cbrt,@function");
__asm__("_lsb_cbrt:");
__asm__("	ret");
__asm__(".symver _lsb_cbrt,cbrt@@GLIBC_2.0");
__asm__(".globl _lsb_ceil");
__asm__("	.type _lsb_ceil,@function");
__asm__("_lsb_ceil:");
__asm__("	ret");
__asm__(".symver _lsb_ceil,ceil@@GLIBC_2.0");
__asm__(".globl _lsb_cos");
__asm__("	.type _lsb_cos,@function");
__asm__("_lsb_cos:");
__asm__("	ret");
__asm__(".symver _lsb_cos,cos@@GLIBC_2.0");
__asm__(".globl _lsb_cosh");
__asm__("	.type _lsb_cosh,@function");
__asm__("_lsb_cosh:");
__asm__("	ret");
__asm__(".symver _lsb_cosh,cosh@@GLIBC_2.0");
__asm__(".globl _lsb_erf");
__asm__("	.type _lsb_erf,@function");
__asm__("_lsb_erf:");
__asm__("	ret");
__asm__(".symver _lsb_erf,erf@@GLIBC_2.0");
__asm__(".globl _lsb_erfc");
__asm__("	.type _lsb_erfc,@function");
__asm__("_lsb_erfc:");
__asm__("	ret");
__asm__(".symver _lsb_erfc,erfc@@GLIBC_2.0");
__asm__(".globl _lsb_exp");
__asm__("	.type _lsb_exp,@function");
__asm__("_lsb_exp:");
__asm__("	ret");
__asm__(".symver _lsb_exp,exp@@GLIBC_2.0");
__asm__(".globl _lsb_expm1");
__asm__("	.type _lsb_expm1,@function");
__asm__("_lsb_expm1:");
__asm__("	ret");
__asm__(".symver _lsb_expm1,expm1@@GLIBC_2.0");
__asm__(".globl _lsb_fabs");
__asm__("	.type _lsb_fabs,@function");
__asm__("_lsb_fabs:");
__asm__("	ret");
__asm__(".symver _lsb_fabs,fabs@@GLIBC_2.0");
__asm__(".globl _lsb_floor");
__asm__("	.type _lsb_floor,@function");
__asm__("_lsb_floor:");
__asm__("	ret");
__asm__(".symver _lsb_floor,floor@@GLIBC_2.0");
__asm__(".globl _lsb_fmod");
__asm__("	.type _lsb_fmod,@function");
__asm__("_lsb_fmod:");
__asm__("	ret");
__asm__(".symver _lsb_fmod,fmod@@GLIBC_2.0");
__asm__(".globl _lsb_gamma");
__asm__("	.type _lsb_gamma,@function");
__asm__("_lsb_gamma:");
__asm__("	ret");
__asm__(".symver _lsb_gamma,gamma@@GLIBC_2.0");
__asm__(".globl _lsb_hypot");
__asm__("	.type _lsb_hypot,@function");
__asm__("_lsb_hypot:");
__asm__("	ret");
__asm__(".symver _lsb_hypot,hypot@@GLIBC_2.0");
__asm__(".globl _lsb_ilogb");
__asm__("	.type _lsb_ilogb,@function");
__asm__("_lsb_ilogb:");
__asm__("	ret");
__asm__(".symver _lsb_ilogb,ilogb@@GLIBC_2.0");
__asm__(".globl _lsb_j0");
__asm__("	.type _lsb_j0,@function");
__asm__("_lsb_j0:");
__asm__("	ret");
__asm__(".symver _lsb_j0,j0@@GLIBC_2.0");
__asm__(".globl _lsb_j1");
__asm__("	.type _lsb_j1,@function");
__asm__("_lsb_j1:");
__asm__("	ret");
__asm__(".symver _lsb_j1,j1@@GLIBC_2.0");
__asm__(".globl _lsb_jn");
__asm__("	.type _lsb_jn,@function");
__asm__("_lsb_jn:");
__asm__("	ret");
__asm__(".symver _lsb_jn,jn@@GLIBC_2.0");
__asm__(".globl _lsb_lgamma");
__asm__("	.type _lsb_lgamma,@function");
__asm__("_lsb_lgamma:");
__asm__("	ret");
__asm__(".symver _lsb_lgamma,lgamma@@GLIBC_2.0");
__asm__(".globl _lsb_log");
__asm__("	.type _lsb_log,@function");
__asm__("_lsb_log:");
__asm__("	ret");
__asm__(".symver _lsb_log,log@@GLIBC_2.0");
__asm__(".globl _lsb_log10");
__asm__("	.type _lsb_log10,@function");
__asm__("_lsb_log10:");
__asm__("	ret");
__asm__(".symver _lsb_log10,log10@@GLIBC_2.0");
__asm__(".globl _lsb_log1p");
__asm__("	.type _lsb_log1p,@function");
__asm__("_lsb_log1p:");
__asm__("	ret");
__asm__(".symver _lsb_log1p,log1p@@GLIBC_2.0");
__asm__(".globl _lsb_logb");
__asm__("	.type _lsb_logb,@function");
__asm__("_lsb_logb:");
__asm__("	ret");
__asm__(".symver _lsb_logb,logb@@GLIBC_2.0");
__asm__(".globl _lsb_nextafter");
__asm__("	.type _lsb_nextafter,@function");
__asm__("_lsb_nextafter:");
__asm__("	ret");
__asm__(".symver _lsb_nextafter,nextafter@@GLIBC_2.0");
__asm__(".globl _lsb_pow");
__asm__("	.type _lsb_pow,@function");
__asm__("_lsb_pow:");
__asm__("	ret");
__asm__(".symver _lsb_pow,pow@@GLIBC_2.0");
__asm__(".globl _lsb_remainder");
__asm__("	.type _lsb_remainder,@function");
__asm__("_lsb_remainder:");
__asm__("	ret");
__asm__(".symver _lsb_remainder,remainder@@GLIBC_2.0");
__asm__(".globl _lsb_rint");
__asm__("	.type _lsb_rint,@function");
__asm__("_lsb_rint:");
__asm__("	ret");
__asm__(".symver _lsb_rint,rint@@GLIBC_2.0");
__asm__(".globl _lsb_scalb");
__asm__("	.type _lsb_scalb,@function");
__asm__("_lsb_scalb:");
__asm__("	ret");
__asm__(".symver _lsb_scalb,scalb@@GLIBC_2.0");
__asm__(".globl _lsb_sin");
__asm__("	.type _lsb_sin,@function");
__asm__("_lsb_sin:");
__asm__("	ret");
__asm__(".symver _lsb_sin,sin@@GLIBC_2.0");
__asm__(".globl _lsb_sinh");
__asm__("	.type _lsb_sinh,@function");
__asm__("_lsb_sinh:");
__asm__("	ret");
__asm__(".symver _lsb_sinh,sinh@@GLIBC_2.0");
__asm__(".globl _lsb_sqrt");
__asm__("	.type _lsb_sqrt,@function");
__asm__("_lsb_sqrt:");
__asm__("	ret");
__asm__(".symver _lsb_sqrt,sqrt@@GLIBC_2.0");
__asm__(".globl _lsb_tan");
__asm__("	.type _lsb_tan,@function");
__asm__("_lsb_tan:");
__asm__("	ret");
__asm__(".symver _lsb_tan,tan@@GLIBC_2.0");
__asm__(".globl _lsb_tanh");
__asm__("	.type _lsb_tanh,@function");
__asm__("_lsb_tanh:");
__asm__("	ret");
__asm__(".symver _lsb_tanh,tanh@@GLIBC_2.0");
__asm__(".globl _lsb_y0");
__asm__("	.type _lsb_y0,@function");
__asm__("_lsb_y0:");
__asm__("	ret");
__asm__(".symver _lsb_y0,y0@@GLIBC_2.0");
__asm__(".globl _lsb_y1");
__asm__("	.type _lsb_y1,@function");
__asm__("_lsb_y1:");
__asm__("	ret");
__asm__(".symver _lsb_y1,y1@@GLIBC_2.0");
__asm__(".globl _lsb_yn");
__asm__("	.type _lsb_yn,@function");
__asm__("_lsb_yn:");
__asm__("	ret");
__asm__(".symver _lsb_yn,yn@@GLIBC_2.0");
__asm__(".globl _lsb_cabs");
__asm__("	.type _lsb_cabs,@function");
__asm__("_lsb_cabs:");
__asm__("	ret");
__asm__(".symver _lsb_cabs,cabs@@GLIBC_2.1");
__asm__(".globl _lsb_copysignf");
__asm__("	.type _lsb_copysignf,@function");
__asm__("_lsb_copysignf:");
__asm__("	ret");
__asm__(".symver _lsb_copysignf,copysignf@@GLIBC_2.0");
__asm__(".globl _lsb_copysignl");
__asm__("	.type _lsb_copysignl,@function");
__asm__("_lsb_copysignl:");
__asm__("	ret");
__asm__(".symver _lsb_copysignl,copysignl@@GLIBC_2.0");
__asm__(".globl _lsb_finitef");
__asm__("	.type _lsb_finitef,@function");
__asm__("_lsb_finitef:");
__asm__("	ret");
__asm__(".symver _lsb_finitef,finitef@@GLIBC_2.0");
__asm__(".globl _lsb_finitel");
__asm__("	.type _lsb_finitel,@function");
__asm__("_lsb_finitel:");
__asm__("	ret");
__asm__(".symver _lsb_finitel,finitel@@GLIBC_2.0");
__asm__(".globl _lsb_frexpf");
__asm__("	.type _lsb_frexpf,@function");
__asm__("_lsb_frexpf:");
__asm__("	ret");
__asm__(".symver _lsb_frexpf,frexpf@@GLIBC_2.0");
__asm__(".globl _lsb_frexpl");
__asm__("	.type _lsb_frexpl,@function");
__asm__("_lsb_frexpl:");
__asm__("	ret");
__asm__(".symver _lsb_frexpl,frexpl@@GLIBC_2.0");
__asm__(".globl _lsb_ldexpf");
__asm__("	.type _lsb_ldexpf,@function");
__asm__("_lsb_ldexpf:");
__asm__("	ret");
__asm__(".symver _lsb_ldexpf,ldexpf@@GLIBC_2.0");
__asm__(".globl _lsb_ldexpl");
__asm__("	.type _lsb_ldexpl,@function");
__asm__("_lsb_ldexpl:");
__asm__("	ret");
__asm__(".symver _lsb_ldexpl,ldexpl@@GLIBC_2.0");
__asm__(".globl _lsb_modff");
__asm__("	.type _lsb_modff,@function");
__asm__("_lsb_modff:");
__asm__("	ret");
__asm__(".symver _lsb_modff,modff@@GLIBC_2.0");
__asm__(".globl _lsb_modfl");
__asm__("	.type _lsb_modfl,@function");
__asm__("_lsb_modfl:");
__asm__("	ret");
__asm__(".symver _lsb_modfl,modfl@@GLIBC_2.0");
__asm__(".globl _lsb_scalbln");
__asm__("	.type _lsb_scalbln,@function");
__asm__("_lsb_scalbln:");
__asm__("	ret");
__asm__(".symver _lsb_scalbln,scalbln@@GLIBC_2.1");
__asm__(".globl _lsb_scalblnf");
__asm__("	.type _lsb_scalblnf,@function");
__asm__("_lsb_scalblnf:");
__asm__("	ret");
__asm__(".symver _lsb_scalblnf,scalblnf@@GLIBC_2.1");
__asm__(".globl _lsb_scalblnl");
__asm__("	.type _lsb_scalblnl,@function");
__asm__("_lsb_scalblnl:");
__asm__("	ret");
__asm__(".symver _lsb_scalblnl,scalblnl@@GLIBC_2.1");
__asm__(".globl _lsb_scalbn");
__asm__("	.type _lsb_scalbn,@function");
__asm__("_lsb_scalbn:");
__asm__("	ret");
__asm__(".symver _lsb_scalbn,scalbn@@GLIBC_2.0");
__asm__(".globl _lsb_scalbnf");
__asm__("	.type _lsb_scalbnf,@function");
__asm__("_lsb_scalbnf:");
__asm__("	ret");
__asm__(".symver _lsb_scalbnf,scalbnf@@GLIBC_2.0");
__asm__(".globl _lsb_scalbnl");
__asm__("	.type _lsb_scalbnl,@function");
__asm__("_lsb_scalbnl:");
__asm__("	ret");
__asm__(".symver _lsb_scalbnl,scalbnl@@GLIBC_2.0");
__asm__(".globl _lsb_acosf");
__asm__("	.type _lsb_acosf,@function");
__asm__("_lsb_acosf:");
__asm__("	ret");
__asm__(".symver _lsb_acosf,acosf@@GLIBC_2.0");
__asm__(".globl _lsb_acoshf");
__asm__("	.type _lsb_acoshf,@function");
__asm__("_lsb_acoshf:");
__asm__("	ret");
__asm__(".symver _lsb_acoshf,acoshf@@GLIBC_2.0");
__asm__(".globl _lsb_acoshl");
__asm__("	.type _lsb_acoshl,@function");
__asm__("_lsb_acoshl:");
__asm__("	ret");
__asm__(".symver _lsb_acoshl,acoshl@@GLIBC_2.0");
__asm__(".globl _lsb_acosl");
__asm__("	.type _lsb_acosl,@function");
__asm__("_lsb_acosl:");
__asm__("	ret");
__asm__(".symver _lsb_acosl,acosl@@GLIBC_2.0");
__asm__(".globl _lsb_asinf");
__asm__("	.type _lsb_asinf,@function");
__asm__("_lsb_asinf:");
__asm__("	ret");
__asm__(".symver _lsb_asinf,asinf@@GLIBC_2.0");
__asm__(".globl _lsb_asinhf");
__asm__("	.type _lsb_asinhf,@function");
__asm__("_lsb_asinhf:");
__asm__("	ret");
__asm__(".symver _lsb_asinhf,asinhf@@GLIBC_2.0");
__asm__(".globl _lsb_asinhl");
__asm__("	.type _lsb_asinhl,@function");
__asm__("_lsb_asinhl:");
__asm__("	ret");
__asm__(".symver _lsb_asinhl,asinhl@@GLIBC_2.0");
__asm__(".globl _lsb_asinl");
__asm__("	.type _lsb_asinl,@function");
__asm__("_lsb_asinl:");
__asm__("	ret");
__asm__(".symver _lsb_asinl,asinl@@GLIBC_2.0");
__asm__(".globl _lsb_atan2f");
__asm__("	.type _lsb_atan2f,@function");
__asm__("_lsb_atan2f:");
__asm__("	ret");
__asm__(".symver _lsb_atan2f,atan2f@@GLIBC_2.0");
__asm__(".globl _lsb_atan2l");
__asm__("	.type _lsb_atan2l,@function");
__asm__("_lsb_atan2l:");
__asm__("	ret");
__asm__(".symver _lsb_atan2l,atan2l@@GLIBC_2.0");
__asm__(".globl _lsb_atanf");
__asm__("	.type _lsb_atanf,@function");
__asm__("_lsb_atanf:");
__asm__("	ret");
__asm__(".symver _lsb_atanf,atanf@@GLIBC_2.0");
__asm__(".globl _lsb_atanhf");
__asm__("	.type _lsb_atanhf,@function");
__asm__("_lsb_atanhf:");
__asm__("	ret");
__asm__(".symver _lsb_atanhf,atanhf@@GLIBC_2.0");
__asm__(".globl _lsb_atanhl");
__asm__("	.type _lsb_atanhl,@function");
__asm__("_lsb_atanhl:");
__asm__("	ret");
__asm__(".symver _lsb_atanhl,atanhl@@GLIBC_2.0");
__asm__(".globl _lsb_atanl");
__asm__("	.type _lsb_atanl,@function");
__asm__("_lsb_atanl:");
__asm__("	ret");
__asm__(".symver _lsb_atanl,atanl@@GLIBC_2.0");
__asm__(".globl _lsb_cabsf");
__asm__("	.type _lsb_cabsf,@function");
__asm__("_lsb_cabsf:");
__asm__("	ret");
__asm__(".symver _lsb_cabsf,cabsf@@GLIBC_2.1");
__asm__(".globl _lsb_cabsl");
__asm__("	.type _lsb_cabsl,@function");
__asm__("_lsb_cabsl:");
__asm__("	ret");
__asm__(".symver _lsb_cabsl,cabsl@@GLIBC_2.1");
__asm__(".globl _lsb_cacos");
__asm__("	.type _lsb_cacos,@function");
__asm__("_lsb_cacos:");
__asm__("	ret");
__asm__(".symver _lsb_cacos,cacos@@GLIBC_2.1");
__asm__(".globl _lsb_cacosf");
__asm__("	.type _lsb_cacosf,@function");
__asm__("_lsb_cacosf:");
__asm__("	ret");
__asm__(".symver _lsb_cacosf,cacosf@@GLIBC_2.1");
__asm__(".globl _lsb_cacosh");
__asm__("	.type _lsb_cacosh,@function");
__asm__("_lsb_cacosh:");
__asm__("	ret");
__asm__(".symver _lsb_cacosh,cacosh@@GLIBC_2.1");
__asm__(".globl _lsb_cacoshf");
__asm__("	.type _lsb_cacoshf,@function");
__asm__("_lsb_cacoshf:");
__asm__("	ret");
__asm__(".symver _lsb_cacoshf,cacoshf@@GLIBC_2.1");
__asm__(".globl _lsb_cacoshl");
__asm__("	.type _lsb_cacoshl,@function");
__asm__("_lsb_cacoshl:");
__asm__("	ret");
__asm__(".symver _lsb_cacoshl,cacoshl@@GLIBC_2.1");
__asm__(".globl _lsb_cacosl");
__asm__("	.type _lsb_cacosl,@function");
__asm__("_lsb_cacosl:");
__asm__("	ret");
__asm__(".symver _lsb_cacosl,cacosl@@GLIBC_2.1");
__asm__(".globl _lsb_carg");
__asm__("	.type _lsb_carg,@function");
__asm__("_lsb_carg:");
__asm__("	ret");
__asm__(".symver _lsb_carg,carg@@GLIBC_2.1");
__asm__(".globl _lsb_cargf");
__asm__("	.type _lsb_cargf,@function");
__asm__("_lsb_cargf:");
__asm__("	ret");
__asm__(".symver _lsb_cargf,cargf@@GLIBC_2.1");
__asm__(".globl _lsb_cargl");
__asm__("	.type _lsb_cargl,@function");
__asm__("_lsb_cargl:");
__asm__("	ret");
__asm__(".symver _lsb_cargl,cargl@@GLIBC_2.1");
__asm__(".globl _lsb_casin");
__asm__("	.type _lsb_casin,@function");
__asm__("_lsb_casin:");
__asm__("	ret");
__asm__(".symver _lsb_casin,casin@@GLIBC_2.1");
__asm__(".globl _lsb_casinf");
__asm__("	.type _lsb_casinf,@function");
__asm__("_lsb_casinf:");
__asm__("	ret");
__asm__(".symver _lsb_casinf,casinf@@GLIBC_2.1");
__asm__(".globl _lsb_casinh");
__asm__("	.type _lsb_casinh,@function");
__asm__("_lsb_casinh:");
__asm__("	ret");
__asm__(".symver _lsb_casinh,casinh@@GLIBC_2.1");
__asm__(".globl _lsb_casinhf");
__asm__("	.type _lsb_casinhf,@function");
__asm__("_lsb_casinhf:");
__asm__("	ret");
__asm__(".symver _lsb_casinhf,casinhf@@GLIBC_2.1");
__asm__(".globl _lsb_casinhl");
__asm__("	.type _lsb_casinhl,@function");
__asm__("_lsb_casinhl:");
__asm__("	ret");
__asm__(".symver _lsb_casinhl,casinhl@@GLIBC_2.1");
__asm__(".globl _lsb_casinl");
__asm__("	.type _lsb_casinl,@function");
__asm__("_lsb_casinl:");
__asm__("	ret");
__asm__(".symver _lsb_casinl,casinl@@GLIBC_2.1");
__asm__(".globl _lsb_catan");
__asm__("	.type _lsb_catan,@function");
__asm__("_lsb_catan:");
__asm__("	ret");
__asm__(".symver _lsb_catan,catan@@GLIBC_2.1");
__asm__(".globl _lsb_catanf");
__asm__("	.type _lsb_catanf,@function");
__asm__("_lsb_catanf:");
__asm__("	ret");
__asm__(".symver _lsb_catanf,catanf@@GLIBC_2.1");
__asm__(".globl _lsb_catanh");
__asm__("	.type _lsb_catanh,@function");
__asm__("_lsb_catanh:");
__asm__("	ret");
__asm__(".symver _lsb_catanh,catanh@@GLIBC_2.1");
__asm__(".globl _lsb_catanhf");
__asm__("	.type _lsb_catanhf,@function");
__asm__("_lsb_catanhf:");
__asm__("	ret");
__asm__(".symver _lsb_catanhf,catanhf@@GLIBC_2.1");
__asm__(".globl _lsb_catanhl");
__asm__("	.type _lsb_catanhl,@function");
__asm__("_lsb_catanhl:");
__asm__("	ret");
__asm__(".symver _lsb_catanhl,catanhl@@GLIBC_2.1");
__asm__(".globl _lsb_catanl");
__asm__("	.type _lsb_catanl,@function");
__asm__("_lsb_catanl:");
__asm__("	ret");
__asm__(".symver _lsb_catanl,catanl@@GLIBC_2.1");
__asm__(".globl _lsb_cbrtf");
__asm__("	.type _lsb_cbrtf,@function");
__asm__("_lsb_cbrtf:");
__asm__("	ret");
__asm__(".symver _lsb_cbrtf,cbrtf@@GLIBC_2.0");
__asm__(".globl _lsb_cbrtl");
__asm__("	.type _lsb_cbrtl,@function");
__asm__("_lsb_cbrtl:");
__asm__("	ret");
__asm__(".symver _lsb_cbrtl,cbrtl@@GLIBC_2.0");
__asm__(".globl _lsb_ccos");
__asm__("	.type _lsb_ccos,@function");
__asm__("_lsb_ccos:");
__asm__("	ret");
__asm__(".symver _lsb_ccos,ccos@@GLIBC_2.1");
__asm__(".globl _lsb_ccosf");
__asm__("	.type _lsb_ccosf,@function");
__asm__("_lsb_ccosf:");
__asm__("	ret");
__asm__(".symver _lsb_ccosf,ccosf@@GLIBC_2.1");
__asm__(".globl _lsb_ccosh");
__asm__("	.type _lsb_ccosh,@function");
__asm__("_lsb_ccosh:");
__asm__("	ret");
__asm__(".symver _lsb_ccosh,ccosh@@GLIBC_2.1");
__asm__(".globl _lsb_ccoshf");
__asm__("	.type _lsb_ccoshf,@function");
__asm__("_lsb_ccoshf:");
__asm__("	ret");
__asm__(".symver _lsb_ccoshf,ccoshf@@GLIBC_2.1");
__asm__(".globl _lsb_ccoshl");
__asm__("	.type _lsb_ccoshl,@function");
__asm__("_lsb_ccoshl:");
__asm__("	ret");
__asm__(".symver _lsb_ccoshl,ccoshl@@GLIBC_2.1");
__asm__(".globl _lsb_ccosl");
__asm__("	.type _lsb_ccosl,@function");
__asm__("_lsb_ccosl:");
__asm__("	ret");
__asm__(".symver _lsb_ccosl,ccosl@@GLIBC_2.1");
__asm__(".globl _lsb_ceilf");
__asm__("	.type _lsb_ceilf,@function");
__asm__("_lsb_ceilf:");
__asm__("	ret");
__asm__(".symver _lsb_ceilf,ceilf@@GLIBC_2.0");
__asm__(".globl _lsb_ceill");
__asm__("	.type _lsb_ceill,@function");
__asm__("_lsb_ceill:");
__asm__("	ret");
__asm__(".symver _lsb_ceill,ceill@@GLIBC_2.0");
__asm__(".globl _lsb_cexp");
__asm__("	.type _lsb_cexp,@function");
__asm__("_lsb_cexp:");
__asm__("	ret");
__asm__(".symver _lsb_cexp,cexp@@GLIBC_2.1");
__asm__(".globl _lsb_cexpf");
__asm__("	.type _lsb_cexpf,@function");
__asm__("_lsb_cexpf:");
__asm__("	ret");
__asm__(".symver _lsb_cexpf,cexpf@@GLIBC_2.1");
__asm__(".globl _lsb_cexpl");
__asm__("	.type _lsb_cexpl,@function");
__asm__("_lsb_cexpl:");
__asm__("	ret");
__asm__(".symver _lsb_cexpl,cexpl@@GLIBC_2.1");
__asm__(".globl _lsb_cimag");
__asm__("	.type _lsb_cimag,@function");
__asm__("_lsb_cimag:");
__asm__("	ret");
__asm__(".symver _lsb_cimag,cimag@@GLIBC_2.1");
__asm__(".globl _lsb_cimagf");
__asm__("	.type _lsb_cimagf,@function");
__asm__("_lsb_cimagf:");
__asm__("	ret");
__asm__(".symver _lsb_cimagf,cimagf@@GLIBC_2.1");
__asm__(".globl _lsb_cimagl");
__asm__("	.type _lsb_cimagl,@function");
__asm__("_lsb_cimagl:");
__asm__("	ret");
__asm__(".symver _lsb_cimagl,cimagl@@GLIBC_2.1");
__asm__(".globl _lsb_clog10");
__asm__("	.type _lsb_clog10,@function");
__asm__("_lsb_clog10:");
__asm__("	ret");
__asm__(".symver _lsb_clog10,clog10@@GLIBC_2.1");
__asm__(".globl _lsb_clog10f");
__asm__("	.type _lsb_clog10f,@function");
__asm__("_lsb_clog10f:");
__asm__("	ret");
__asm__(".symver _lsb_clog10f,clog10f@@GLIBC_2.1");
__asm__(".globl _lsb_clog10l");
__asm__("	.type _lsb_clog10l,@function");
__asm__("_lsb_clog10l:");
__asm__("	ret");
__asm__(".symver _lsb_clog10l,clog10l@@GLIBC_2.1");
__asm__(".globl _lsb_clogf");
__asm__("	.type _lsb_clogf,@function");
__asm__("_lsb_clogf:");
__asm__("	ret");
__asm__(".symver _lsb_clogf,clogf@@GLIBC_2.1");
__asm__(".globl _lsb_clogl");
__asm__("	.type _lsb_clogl,@function");
__asm__("_lsb_clogl:");
__asm__("	ret");
__asm__(".symver _lsb_clogl,clogl@@GLIBC_2.1");
__asm__(".globl _lsb_conj");
__asm__("	.type _lsb_conj,@function");
__asm__("_lsb_conj:");
__asm__("	ret");
__asm__(".symver _lsb_conj,conj@@GLIBC_2.1");
__asm__(".globl _lsb_conjf");
__asm__("	.type _lsb_conjf,@function");
__asm__("_lsb_conjf:");
__asm__("	ret");
__asm__(".symver _lsb_conjf,conjf@@GLIBC_2.1");
__asm__(".globl _lsb_conjl");
__asm__("	.type _lsb_conjl,@function");
__asm__("_lsb_conjl:");
__asm__("	ret");
__asm__(".symver _lsb_conjl,conjl@@GLIBC_2.1");
__asm__(".globl _lsb_cosf");
__asm__("	.type _lsb_cosf,@function");
__asm__("_lsb_cosf:");
__asm__("	ret");
__asm__(".symver _lsb_cosf,cosf@@GLIBC_2.0");
__asm__(".globl _lsb_coshf");
__asm__("	.type _lsb_coshf,@function");
__asm__("_lsb_coshf:");
__asm__("	ret");
__asm__(".symver _lsb_coshf,coshf@@GLIBC_2.0");
__asm__(".globl _lsb_coshl");
__asm__("	.type _lsb_coshl,@function");
__asm__("_lsb_coshl:");
__asm__("	ret");
__asm__(".symver _lsb_coshl,coshl@@GLIBC_2.0");
__asm__(".globl _lsb_cosl");
__asm__("	.type _lsb_cosl,@function");
__asm__("_lsb_cosl:");
__asm__("	ret");
__asm__(".symver _lsb_cosl,cosl@@GLIBC_2.0");
__asm__(".globl _lsb_cpow");
__asm__("	.type _lsb_cpow,@function");
__asm__("_lsb_cpow:");
__asm__("	ret");
__asm__(".symver _lsb_cpow,cpow@@GLIBC_2.1");
__asm__(".globl _lsb_cpowf");
__asm__("	.type _lsb_cpowf,@function");
__asm__("_lsb_cpowf:");
__asm__("	ret");
__asm__(".symver _lsb_cpowf,cpowf@@GLIBC_2.1");
__asm__(".globl _lsb_cpowl");
__asm__("	.type _lsb_cpowl,@function");
__asm__("_lsb_cpowl:");
__asm__("	ret");
__asm__(".symver _lsb_cpowl,cpowl@@GLIBC_2.1");
__asm__(".globl _lsb_cproj");
__asm__("	.type _lsb_cproj,@function");
__asm__("_lsb_cproj:");
__asm__("	ret");
__asm__(".symver _lsb_cproj,cproj@@GLIBC_2.1");
__asm__(".globl _lsb_cprojf");
__asm__("	.type _lsb_cprojf,@function");
__asm__("_lsb_cprojf:");
__asm__("	ret");
__asm__(".symver _lsb_cprojf,cprojf@@GLIBC_2.1");
__asm__(".globl _lsb_cprojl");
__asm__("	.type _lsb_cprojl,@function");
__asm__("_lsb_cprojl:");
__asm__("	ret");
__asm__(".symver _lsb_cprojl,cprojl@@GLIBC_2.1");
__asm__(".globl _lsb_creal");
__asm__("	.type _lsb_creal,@function");
__asm__("_lsb_creal:");
__asm__("	ret");
__asm__(".symver _lsb_creal,creal@@GLIBC_2.1");
__asm__(".globl _lsb_crealf");
__asm__("	.type _lsb_crealf,@function");
__asm__("_lsb_crealf:");
__asm__("	ret");
__asm__(".symver _lsb_crealf,crealf@@GLIBC_2.1");
__asm__(".globl _lsb_creall");
__asm__("	.type _lsb_creall,@function");
__asm__("_lsb_creall:");
__asm__("	ret");
__asm__(".symver _lsb_creall,creall@@GLIBC_2.1");
__asm__(".globl _lsb_csin");
__asm__("	.type _lsb_csin,@function");
__asm__("_lsb_csin:");
__asm__("	ret");
__asm__(".symver _lsb_csin,csin@@GLIBC_2.1");
__asm__(".globl _lsb_csinf");
__asm__("	.type _lsb_csinf,@function");
__asm__("_lsb_csinf:");
__asm__("	ret");
__asm__(".symver _lsb_csinf,csinf@@GLIBC_2.1");
__asm__(".globl _lsb_csinh");
__asm__("	.type _lsb_csinh,@function");
__asm__("_lsb_csinh:");
__asm__("	ret");
__asm__(".symver _lsb_csinh,csinh@@GLIBC_2.1");
__asm__(".globl _lsb_csinhf");
__asm__("	.type _lsb_csinhf,@function");
__asm__("_lsb_csinhf:");
__asm__("	ret");
__asm__(".symver _lsb_csinhf,csinhf@@GLIBC_2.1");
__asm__(".globl _lsb_csinhl");
__asm__("	.type _lsb_csinhl,@function");
__asm__("_lsb_csinhl:");
__asm__("	ret");
__asm__(".symver _lsb_csinhl,csinhl@@GLIBC_2.1");
__asm__(".globl _lsb_csinl");
__asm__("	.type _lsb_csinl,@function");
__asm__("_lsb_csinl:");
__asm__("	ret");
__asm__(".symver _lsb_csinl,csinl@@GLIBC_2.1");
__asm__(".globl _lsb_csqrt");
__asm__("	.type _lsb_csqrt,@function");
__asm__("_lsb_csqrt:");
__asm__("	ret");
__asm__(".symver _lsb_csqrt,csqrt@@GLIBC_2.1");
__asm__(".globl _lsb_csqrtf");
__asm__("	.type _lsb_csqrtf,@function");
__asm__("_lsb_csqrtf:");
__asm__("	ret");
__asm__(".symver _lsb_csqrtf,csqrtf@@GLIBC_2.1");
__asm__(".globl _lsb_csqrtl");
__asm__("	.type _lsb_csqrtl,@function");
__asm__("_lsb_csqrtl:");
__asm__("	ret");
__asm__(".symver _lsb_csqrtl,csqrtl@@GLIBC_2.1");
__asm__(".globl _lsb_ctan");
__asm__("	.type _lsb_ctan,@function");
__asm__("_lsb_ctan:");
__asm__("	ret");
__asm__(".symver _lsb_ctan,ctan@@GLIBC_2.1");
__asm__(".globl _lsb_ctanf");
__asm__("	.type _lsb_ctanf,@function");
__asm__("_lsb_ctanf:");
__asm__("	ret");
__asm__(".symver _lsb_ctanf,ctanf@@GLIBC_2.1");
__asm__(".globl _lsb_ctanh");
__asm__("	.type _lsb_ctanh,@function");
__asm__("_lsb_ctanh:");
__asm__("	ret");
__asm__(".symver _lsb_ctanh,ctanh@@GLIBC_2.1");
__asm__(".globl _lsb_ctanhf");
__asm__("	.type _lsb_ctanhf,@function");
__asm__("_lsb_ctanhf:");
__asm__("	ret");
__asm__(".symver _lsb_ctanhf,ctanhf@@GLIBC_2.1");
__asm__(".globl _lsb_ctanhl");
__asm__("	.type _lsb_ctanhl,@function");
__asm__("_lsb_ctanhl:");
__asm__("	ret");
__asm__(".symver _lsb_ctanhl,ctanhl@@GLIBC_2.1");
__asm__(".globl _lsb_ctanl");
__asm__("	.type _lsb_ctanl,@function");
__asm__("_lsb_ctanl:");
__asm__("	ret");
__asm__(".symver _lsb_ctanl,ctanl@@GLIBC_2.1");
__asm__(".globl _lsb_dremf");
__asm__("	.type _lsb_dremf,@function");
__asm__("_lsb_dremf:");
__asm__("	ret");
__asm__(".symver _lsb_dremf,dremf@@GLIBC_2.0");
__asm__(".globl _lsb_dreml");
__asm__("	.type _lsb_dreml,@function");
__asm__("_lsb_dreml:");
__asm__("	ret");
__asm__(".symver _lsb_dreml,dreml@@GLIBC_2.0");
__asm__(".globl _lsb_erfcf");
__asm__("	.type _lsb_erfcf,@function");
__asm__("_lsb_erfcf:");
__asm__("	ret");
__asm__(".symver _lsb_erfcf,erfcf@@GLIBC_2.0");
__asm__(".globl _lsb_erfcl");
__asm__("	.type _lsb_erfcl,@function");
__asm__("_lsb_erfcl:");
__asm__("	ret");
__asm__(".symver _lsb_erfcl,erfcl@@GLIBC_2.0");
__asm__(".globl _lsb_erff");
__asm__("	.type _lsb_erff,@function");
__asm__("_lsb_erff:");
__asm__("	ret");
__asm__(".symver _lsb_erff,erff@@GLIBC_2.0");
__asm__(".globl _lsb_erfl");
__asm__("	.type _lsb_erfl,@function");
__asm__("_lsb_erfl:");
__asm__("	ret");
__asm__(".symver _lsb_erfl,erfl@@GLIBC_2.0");
__asm__(".globl _lsb_fabsf");
__asm__("	.type _lsb_fabsf,@function");
__asm__("_lsb_fabsf:");
__asm__("	ret");
__asm__(".symver _lsb_fabsf,fabsf@@GLIBC_2.0");
__asm__(".globl _lsb_fabsl");
__asm__("	.type _lsb_fabsl,@function");
__asm__("_lsb_fabsl:");
__asm__("	ret");
__asm__(".symver _lsb_fabsl,fabsl@@GLIBC_2.0");
__asm__(".globl _lsb_fdim");
__asm__("	.type _lsb_fdim,@function");
__asm__("_lsb_fdim:");
__asm__("	ret");
__asm__(".symver _lsb_fdim,fdim@@GLIBC_2.1");
__asm__(".globl _lsb_fdimf");
__asm__("	.type _lsb_fdimf,@function");
__asm__("_lsb_fdimf:");
__asm__("	ret");
__asm__(".symver _lsb_fdimf,fdimf@@GLIBC_2.1");
__asm__(".globl _lsb_fdiml");
__asm__("	.type _lsb_fdiml,@function");
__asm__("_lsb_fdiml:");
__asm__("	ret");
__asm__(".symver _lsb_fdiml,fdiml@@GLIBC_2.1");
__asm__(".globl _lsb_floorf");
__asm__("	.type _lsb_floorf,@function");
__asm__("_lsb_floorf:");
__asm__("	ret");
__asm__(".symver _lsb_floorf,floorf@@GLIBC_2.0");
__asm__(".globl _lsb_floorl");
__asm__("	.type _lsb_floorl,@function");
__asm__("_lsb_floorl:");
__asm__("	ret");
__asm__(".symver _lsb_floorl,floorl@@GLIBC_2.0");
__asm__(".globl _lsb_fma");
__asm__("	.type _lsb_fma,@function");
__asm__("_lsb_fma:");
__asm__("	ret");
__asm__(".symver _lsb_fma,fma@@GLIBC_2.1");
__asm__(".globl _lsb_fmaf");
__asm__("	.type _lsb_fmaf,@function");
__asm__("_lsb_fmaf:");
__asm__("	ret");
__asm__(".symver _lsb_fmaf,fmaf@@GLIBC_2.1");
__asm__(".globl _lsb_fmal");
__asm__("	.type _lsb_fmal,@function");
__asm__("_lsb_fmal:");
__asm__("	ret");
__asm__(".symver _lsb_fmal,fmal@@GLIBC_2.1");
__asm__(".globl _lsb_fmax");
__asm__("	.type _lsb_fmax,@function");
__asm__("_lsb_fmax:");
__asm__("	ret");
__asm__(".symver _lsb_fmax,fmax@@GLIBC_2.1");
__asm__(".globl _lsb_fmaxf");
__asm__("	.type _lsb_fmaxf,@function");
__asm__("_lsb_fmaxf:");
__asm__("	ret");
__asm__(".symver _lsb_fmaxf,fmaxf@@GLIBC_2.1");
__asm__(".globl _lsb_fmaxl");
__asm__("	.type _lsb_fmaxl,@function");
__asm__("_lsb_fmaxl:");
__asm__("	ret");
__asm__(".symver _lsb_fmaxl,fmaxl@@GLIBC_2.1");
__asm__(".globl _lsb_fmin");
__asm__("	.type _lsb_fmin,@function");
__asm__("_lsb_fmin:");
__asm__("	ret");
__asm__(".symver _lsb_fmin,fmin@@GLIBC_2.1");
__asm__(".globl _lsb_fminf");
__asm__("	.type _lsb_fminf,@function");
__asm__("_lsb_fminf:");
__asm__("	ret");
__asm__(".symver _lsb_fminf,fminf@@GLIBC_2.1");
__asm__(".globl _lsb_fminl");
__asm__("	.type _lsb_fminl,@function");
__asm__("_lsb_fminl:");
__asm__("	ret");
__asm__(".symver _lsb_fminl,fminl@@GLIBC_2.1");
__asm__(".globl _lsb_fmodf");
__asm__("	.type _lsb_fmodf,@function");
__asm__("_lsb_fmodf:");
__asm__("	ret");
__asm__(".symver _lsb_fmodf,fmodf@@GLIBC_2.0");
__asm__(".globl _lsb_fmodl");
__asm__("	.type _lsb_fmodl,@function");
__asm__("_lsb_fmodl:");
__asm__("	ret");
__asm__(".symver _lsb_fmodl,fmodl@@GLIBC_2.0");
__asm__(".globl _lsb_gammaf");
__asm__("	.type _lsb_gammaf,@function");
__asm__("_lsb_gammaf:");
__asm__("	ret");
__asm__(".symver _lsb_gammaf,gammaf@@GLIBC_2.0");
__asm__(".globl _lsb_gammal");
__asm__("	.type _lsb_gammal,@function");
__asm__("_lsb_gammal:");
__asm__("	ret");
__asm__(".symver _lsb_gammal,gammal@@GLIBC_2.0");
__asm__(".globl _lsb_hypotf");
__asm__("	.type _lsb_hypotf,@function");
__asm__("_lsb_hypotf:");
__asm__("	ret");
__asm__(".symver _lsb_hypotf,hypotf@@GLIBC_2.0");
__asm__(".globl _lsb_hypotl");
__asm__("	.type _lsb_hypotl,@function");
__asm__("_lsb_hypotl:");
__asm__("	ret");
__asm__(".symver _lsb_hypotl,hypotl@@GLIBC_2.0");
__asm__(".globl _lsb_ilogbf");
__asm__("	.type _lsb_ilogbf,@function");
__asm__("_lsb_ilogbf:");
__asm__("	ret");
__asm__(".symver _lsb_ilogbf,ilogbf@@GLIBC_2.0");
__asm__(".globl _lsb_ilogbl");
__asm__("	.type _lsb_ilogbl,@function");
__asm__("_lsb_ilogbl:");
__asm__("	ret");
__asm__(".symver _lsb_ilogbl,ilogbl@@GLIBC_2.0");
__asm__(".globl _lsb_j0f");
__asm__("	.type _lsb_j0f,@function");
__asm__("_lsb_j0f:");
__asm__("	ret");
__asm__(".symver _lsb_j0f,j0f@@GLIBC_2.0");
__asm__(".globl _lsb_j0l");
__asm__("	.type _lsb_j0l,@function");
__asm__("_lsb_j0l:");
__asm__("	ret");
__asm__(".symver _lsb_j0l,j0l@@GLIBC_2.0");
__asm__(".globl _lsb_j1f");
__asm__("	.type _lsb_j1f,@function");
__asm__("_lsb_j1f:");
__asm__("	ret");
__asm__(".symver _lsb_j1f,j1f@@GLIBC_2.0");
__asm__(".globl _lsb_j1l");
__asm__("	.type _lsb_j1l,@function");
__asm__("_lsb_j1l:");
__asm__("	ret");
__asm__(".symver _lsb_j1l,j1l@@GLIBC_2.0");
__asm__(".globl _lsb_jnf");
__asm__("	.type _lsb_jnf,@function");
__asm__("_lsb_jnf:");
__asm__("	ret");
__asm__(".symver _lsb_jnf,jnf@@GLIBC_2.0");
__asm__(".globl _lsb_jnl");
__asm__("	.type _lsb_jnl,@function");
__asm__("_lsb_jnl:");
__asm__("	ret");
__asm__(".symver _lsb_jnl,jnl@@GLIBC_2.0");
__asm__(".globl _lsb_lgamma_r");
__asm__("	.type _lsb_lgamma_r,@function");
__asm__("_lsb_lgamma_r:");
__asm__("	ret");
__asm__(".symver _lsb_lgamma_r,lgamma_r@@GLIBC_2.0");
__asm__(".globl _lsb_lgammaf");
__asm__("	.type _lsb_lgammaf,@function");
__asm__("_lsb_lgammaf:");
__asm__("	ret");
__asm__(".symver _lsb_lgammaf,lgammaf@@GLIBC_2.0");
__asm__(".globl _lsb_lgammaf_r");
__asm__("	.type _lsb_lgammaf_r,@function");
__asm__("_lsb_lgammaf_r:");
__asm__("	ret");
__asm__(".symver _lsb_lgammaf_r,lgammaf_r@@GLIBC_2.0");
__asm__(".globl _lsb_lgammal");
__asm__("	.type _lsb_lgammal,@function");
__asm__("_lsb_lgammal:");
__asm__("	ret");
__asm__(".symver _lsb_lgammal,lgammal@@GLIBC_2.0");
__asm__(".globl _lsb_lgammal_r");
__asm__("	.type _lsb_lgammal_r,@function");
__asm__("_lsb_lgammal_r:");
__asm__("	ret");
__asm__(".symver _lsb_lgammal_r,lgammal_r@@GLIBC_2.0");
__asm__(".globl _lsb_llrint");
__asm__("	.type _lsb_llrint,@function");
__asm__("_lsb_llrint:");
__asm__("	ret");
__asm__(".symver _lsb_llrint,llrint@@GLIBC_2.1");
__asm__(".globl _lsb_llrintf");
__asm__("	.type _lsb_llrintf,@function");
__asm__("_lsb_llrintf:");
__asm__("	ret");
__asm__(".symver _lsb_llrintf,llrintf@@GLIBC_2.1");
__asm__(".globl _lsb_llrintl");
__asm__("	.type _lsb_llrintl,@function");
__asm__("_lsb_llrintl:");
__asm__("	ret");
__asm__(".symver _lsb_llrintl,llrintl@@GLIBC_2.1");
__asm__(".globl _lsb_llround");
__asm__("	.type _lsb_llround,@function");
__asm__("_lsb_llround:");
__asm__("	ret");
__asm__(".symver _lsb_llround,llround@@GLIBC_2.1");
__asm__(".globl _lsb_llroundf");
__asm__("	.type _lsb_llroundf,@function");
__asm__("_lsb_llroundf:");
__asm__("	ret");
__asm__(".symver _lsb_llroundf,llroundf@@GLIBC_2.1");
__asm__(".globl _lsb_llroundl");
__asm__("	.type _lsb_llroundl,@function");
__asm__("_lsb_llroundl:");
__asm__("	ret");
__asm__(".symver _lsb_llroundl,llroundl@@GLIBC_2.1");
__asm__(".globl _lsb_lrint");
__asm__("	.type _lsb_lrint,@function");
__asm__("_lsb_lrint:");
__asm__("	ret");
__asm__(".symver _lsb_lrint,lrint@@GLIBC_2.1");
__asm__(".globl _lsb_lrintf");
__asm__("	.type _lsb_lrintf,@function");
__asm__("_lsb_lrintf:");
__asm__("	ret");
__asm__(".symver _lsb_lrintf,lrintf@@GLIBC_2.1");
__asm__(".globl _lsb_lrintl");
__asm__("	.type _lsb_lrintl,@function");
__asm__("_lsb_lrintl:");
__asm__("	ret");
__asm__(".symver _lsb_lrintl,lrintl@@GLIBC_2.1");
__asm__(".globl _lsb_lround");
__asm__("	.type _lsb_lround,@function");
__asm__("_lsb_lround:");
__asm__("	ret");
__asm__(".symver _lsb_lround,lround@@GLIBC_2.1");
__asm__(".globl _lsb_lroundf");
__asm__("	.type _lsb_lroundf,@function");
__asm__("_lsb_lroundf:");
__asm__("	ret");
__asm__(".symver _lsb_lroundf,lroundf@@GLIBC_2.1");
__asm__(".globl _lsb_lroundl");
__asm__("	.type _lsb_lroundl,@function");
__asm__("_lsb_lroundl:");
__asm__("	ret");
__asm__(".symver _lsb_lroundl,lroundl@@GLIBC_2.1");
__asm__(".globl _lsb_matherr");
__asm__("	.type _lsb_matherr,@function");
__asm__("_lsb_matherr:");
__asm__("	ret");
__asm__(".symver _lsb_matherr,matherr@@GLIBC_2.0");
__asm__(".globl _lsb_nan");
__asm__("	.type _lsb_nan,@function");
__asm__("_lsb_nan:");
__asm__("	ret");
__asm__(".symver _lsb_nan,nan@@GLIBC_2.1");
__asm__(".globl _lsb_nanf");
__asm__("	.type _lsb_nanf,@function");
__asm__("_lsb_nanf:");
__asm__("	ret");
__asm__(".symver _lsb_nanf,nanf@@GLIBC_2.1");
__asm__(".globl _lsb_nanl");
__asm__("	.type _lsb_nanl,@function");
__asm__("_lsb_nanl:");
__asm__("	ret");
__asm__(".symver _lsb_nanl,nanl@@GLIBC_2.1");
__asm__(".globl _lsb_nearbyint");
__asm__("	.type _lsb_nearbyint,@function");
__asm__("_lsb_nearbyint:");
__asm__("	ret");
__asm__(".symver _lsb_nearbyint,nearbyint@@GLIBC_2.1");
__asm__(".globl _lsb_nearbyintf");
__asm__("	.type _lsb_nearbyintf,@function");
__asm__("_lsb_nearbyintf:");
__asm__("	ret");
__asm__(".symver _lsb_nearbyintf,nearbyintf@@GLIBC_2.1");
__asm__(".globl _lsb_nearbyintl");
__asm__("	.type _lsb_nearbyintl,@function");
__asm__("_lsb_nearbyintl:");
__asm__("	ret");
__asm__(".symver _lsb_nearbyintl,nearbyintl@@GLIBC_2.1");
__asm__(".globl _lsb_nextafterf");
__asm__("	.type _lsb_nextafterf,@function");
__asm__("_lsb_nextafterf:");
__asm__("	ret");
__asm__(".symver _lsb_nextafterf,nextafterf@@GLIBC_2.0");
__asm__(".globl _lsb_nextafterl");
__asm__("	.type _lsb_nextafterl,@function");
__asm__("_lsb_nextafterl:");
__asm__("	ret");
__asm__(".symver _lsb_nextafterl,nextafterl@@GLIBC_2.0");
__asm__(".globl _lsb_nexttoward");
__asm__("	.type _lsb_nexttoward,@function");
__asm__("_lsb_nexttoward:");
__asm__("	ret");
__asm__(".symver _lsb_nexttoward,nexttoward@@GLIBC_2.1");
__asm__(".globl _lsb_nexttowardf");
__asm__("	.type _lsb_nexttowardf,@function");
__asm__("_lsb_nexttowardf:");
__asm__("	ret");
__asm__(".symver _lsb_nexttowardf,nexttowardf@@GLIBC_2.1");
__asm__(".globl _lsb_nexttowardl");
__asm__("	.type _lsb_nexttowardl,@function");
__asm__("_lsb_nexttowardl:");
__asm__("	ret");
__asm__(".symver _lsb_nexttowardl,nexttowardl@@GLIBC_2.1");
__asm__(".globl _lsb_pow10");
__asm__("	.type _lsb_pow10,@function");
__asm__("_lsb_pow10:");
__asm__("	ret");
__asm__(".symver _lsb_pow10,pow10@@GLIBC_2.1");
__asm__(".globl _lsb_pow10f");
__asm__("	.type _lsb_pow10f,@function");
__asm__("_lsb_pow10f:");
__asm__("	ret");
__asm__(".symver _lsb_pow10f,pow10f@@GLIBC_2.1");
__asm__(".globl _lsb_pow10l");
__asm__("	.type _lsb_pow10l,@function");
__asm__("_lsb_pow10l:");
__asm__("	ret");
__asm__(".symver _lsb_pow10l,pow10l@@GLIBC_2.1");
__asm__(".globl _lsb_powf");
__asm__("	.type _lsb_powf,@function");
__asm__("_lsb_powf:");
__asm__("	ret");
__asm__(".symver _lsb_powf,powf@@GLIBC_2.0");
__asm__(".globl _lsb_powl");
__asm__("	.type _lsb_powl,@function");
__asm__("_lsb_powl:");
__asm__("	ret");
__asm__(".symver _lsb_powl,powl@@GLIBC_2.0");
__asm__(".globl _lsb_remainderf");
__asm__("	.type _lsb_remainderf,@function");
__asm__("_lsb_remainderf:");
__asm__("	ret");
__asm__(".symver _lsb_remainderf,remainderf@@GLIBC_2.0");
__asm__(".globl _lsb_remainderl");
__asm__("	.type _lsb_remainderl,@function");
__asm__("_lsb_remainderl:");
__asm__("	ret");
__asm__(".symver _lsb_remainderl,remainderl@@GLIBC_2.0");
__asm__(".globl _lsb_remquo");
__asm__("	.type _lsb_remquo,@function");
__asm__("_lsb_remquo:");
__asm__("	ret");
__asm__(".symver _lsb_remquo,remquo@@GLIBC_2.1");
__asm__(".globl _lsb_remquof");
__asm__("	.type _lsb_remquof,@function");
__asm__("_lsb_remquof:");
__asm__("	ret");
__asm__(".symver _lsb_remquof,remquof@@GLIBC_2.1");
__asm__(".globl _lsb_remquol");
__asm__("	.type _lsb_remquol,@function");
__asm__("_lsb_remquol:");
__asm__("	ret");
__asm__(".symver _lsb_remquol,remquol@@GLIBC_2.1");
__asm__(".globl _lsb_rintf");
__asm__("	.type _lsb_rintf,@function");
__asm__("_lsb_rintf:");
__asm__("	ret");
__asm__(".symver _lsb_rintf,rintf@@GLIBC_2.0");
__asm__(".globl _lsb_rintl");
__asm__("	.type _lsb_rintl,@function");
__asm__("_lsb_rintl:");
__asm__("	ret");
__asm__(".symver _lsb_rintl,rintl@@GLIBC_2.0");
__asm__(".globl _lsb_round");
__asm__("	.type _lsb_round,@function");
__asm__("_lsb_round:");
__asm__("	ret");
__asm__(".symver _lsb_round,round@@GLIBC_2.1");
__asm__(".globl _lsb_roundf");
__asm__("	.type _lsb_roundf,@function");
__asm__("_lsb_roundf:");
__asm__("	ret");
__asm__(".symver _lsb_roundf,roundf@@GLIBC_2.1");
__asm__(".globl _lsb_roundl");
__asm__("	.type _lsb_roundl,@function");
__asm__("_lsb_roundl:");
__asm__("	ret");
__asm__(".symver _lsb_roundl,roundl@@GLIBC_2.1");
__asm__(".globl _lsb_scalbf");
__asm__("	.type _lsb_scalbf,@function");
__asm__("_lsb_scalbf:");
__asm__("	ret");
__asm__(".symver _lsb_scalbf,scalbf@@GLIBC_2.0");
__asm__(".globl _lsb_scalbl");
__asm__("	.type _lsb_scalbl,@function");
__asm__("_lsb_scalbl:");
__asm__("	ret");
__asm__(".symver _lsb_scalbl,scalbl@@GLIBC_2.0");
__asm__(".globl _lsb_significand");
__asm__("	.type _lsb_significand,@function");
__asm__("_lsb_significand:");
__asm__("	ret");
__asm__(".symver _lsb_significand,significand@@GLIBC_2.0");
__asm__(".globl _lsb_significandf");
__asm__("	.type _lsb_significandf,@function");
__asm__("_lsb_significandf:");
__asm__("	ret");
__asm__(".symver _lsb_significandf,significandf@@GLIBC_2.0");
__asm__(".globl _lsb_significandl");
__asm__("	.type _lsb_significandl,@function");
__asm__("_lsb_significandl:");
__asm__("	ret");
__asm__(".symver _lsb_significandl,significandl@@GLIBC_2.0");
__asm__(".globl _lsb_sincos");
__asm__("	.type _lsb_sincos,@function");
__asm__("_lsb_sincos:");
__asm__("	ret");
__asm__(".symver _lsb_sincos,sincos@@GLIBC_2.1");
__asm__(".globl _lsb_sincosf");
__asm__("	.type _lsb_sincosf,@function");
__asm__("_lsb_sincosf:");
__asm__("	ret");
__asm__(".symver _lsb_sincosf,sincosf@@GLIBC_2.1");
__asm__(".globl _lsb_sincosl");
__asm__("	.type _lsb_sincosl,@function");
__asm__("_lsb_sincosl:");
__asm__("	ret");
__asm__(".symver _lsb_sincosl,sincosl@@GLIBC_2.1");
__asm__(".globl _lsb_sinf");
__asm__("	.type _lsb_sinf,@function");
__asm__("_lsb_sinf:");
__asm__("	ret");
__asm__(".symver _lsb_sinf,sinf@@GLIBC_2.0");
__asm__(".globl _lsb_sinhf");
__asm__("	.type _lsb_sinhf,@function");
__asm__("_lsb_sinhf:");
__asm__("	ret");
__asm__(".symver _lsb_sinhf,sinhf@@GLIBC_2.0");
__asm__(".globl _lsb_sinhl");
__asm__("	.type _lsb_sinhl,@function");
__asm__("_lsb_sinhl:");
__asm__("	ret");
__asm__(".symver _lsb_sinhl,sinhl@@GLIBC_2.0");
__asm__(".globl _lsb_sinl");
__asm__("	.type _lsb_sinl,@function");
__asm__("_lsb_sinl:");
__asm__("	ret");
__asm__(".symver _lsb_sinl,sinl@@GLIBC_2.0");
__asm__(".globl _lsb_sqrtf");
__asm__("	.type _lsb_sqrtf,@function");
__asm__("_lsb_sqrtf:");
__asm__("	ret");
__asm__(".symver _lsb_sqrtf,sqrtf@@GLIBC_2.0");
__asm__(".globl _lsb_sqrtl");
__asm__("	.type _lsb_sqrtl,@function");
__asm__("_lsb_sqrtl:");
__asm__("	ret");
__asm__(".symver _lsb_sqrtl,sqrtl@@GLIBC_2.0");
__asm__(".globl _lsb_tanf");
__asm__("	.type _lsb_tanf,@function");
__asm__("_lsb_tanf:");
__asm__("	ret");
__asm__(".symver _lsb_tanf,tanf@@GLIBC_2.0");
__asm__(".globl _lsb_tanhf");
__asm__("	.type _lsb_tanhf,@function");
__asm__("_lsb_tanhf:");
__asm__("	ret");
__asm__(".symver _lsb_tanhf,tanhf@@GLIBC_2.0");
__asm__(".globl _lsb_tanhl");
__asm__("	.type _lsb_tanhl,@function");
__asm__("_lsb_tanhl:");
__asm__("	ret");
__asm__(".symver _lsb_tanhl,tanhl@@GLIBC_2.0");
__asm__(".globl _lsb_tanl");
__asm__("	.type _lsb_tanl,@function");
__asm__("_lsb_tanl:");
__asm__("	ret");
__asm__(".symver _lsb_tanl,tanl@@GLIBC_2.0");
__asm__(".globl _lsb_tgamma");
__asm__("	.type _lsb_tgamma,@function");
__asm__("_lsb_tgamma:");
__asm__("	ret");
__asm__(".symver _lsb_tgamma,tgamma@@GLIBC_2.1");
__asm__(".globl _lsb_tgammaf");
__asm__("	.type _lsb_tgammaf,@function");
__asm__("_lsb_tgammaf:");
__asm__("	ret");
__asm__(".symver _lsb_tgammaf,tgammaf@@GLIBC_2.1");
__asm__(".globl _lsb_tgammal");
__asm__("	.type _lsb_tgammal,@function");
__asm__("_lsb_tgammal:");
__asm__("	ret");
__asm__(".symver _lsb_tgammal,tgammal@@GLIBC_2.1");
__asm__(".globl _lsb_trunc");
__asm__("	.type _lsb_trunc,@function");
__asm__("_lsb_trunc:");
__asm__("	ret");
__asm__(".symver _lsb_trunc,trunc@@GLIBC_2.1");
__asm__(".globl _lsb_truncf");
__asm__("	.type _lsb_truncf,@function");
__asm__("_lsb_truncf:");
__asm__("	ret");
__asm__(".symver _lsb_truncf,truncf@@GLIBC_2.1");
__asm__(".globl _lsb_truncl");
__asm__("	.type _lsb_truncl,@function");
__asm__("_lsb_truncl:");
__asm__("	ret");
__asm__(".symver _lsb_truncl,truncl@@GLIBC_2.1");
__asm__(".globl _lsb_y0f");
__asm__("	.type _lsb_y0f,@function");
__asm__("_lsb_y0f:");
__asm__("	ret");
__asm__(".symver _lsb_y0f,y0f@@GLIBC_2.0");
__asm__(".globl _lsb_y0l");
__asm__("	.type _lsb_y0l,@function");
__asm__("_lsb_y0l:");
__asm__("	ret");
__asm__(".symver _lsb_y0l,y0l@@GLIBC_2.0");
__asm__(".globl _lsb_y1f");
__asm__("	.type _lsb_y1f,@function");
__asm__("_lsb_y1f:");
__asm__("	ret");
__asm__(".symver _lsb_y1f,y1f@@GLIBC_2.0");
__asm__(".globl _lsb_y1l");
__asm__("	.type _lsb_y1l,@function");
__asm__("_lsb_y1l:");
__asm__("	ret");
__asm__(".symver _lsb_y1l,y1l@@GLIBC_2.0");
__asm__(".globl _lsb_ynf");
__asm__("	.type _lsb_ynf,@function");
__asm__("_lsb_ynf:");
__asm__("	ret");
__asm__(".symver _lsb_ynf,ynf@@GLIBC_2.0");
__asm__(".globl _lsb_ynl");
__asm__("	.type _lsb_ynl,@function");
__asm__("_lsb_ynl:");
__asm__("	ret");
__asm__(".symver _lsb_ynl,ynl@@GLIBC_2.0");
__asm__(".globl _lsb_signgam");
__asm__("	.type _lsb_signgam,@object");
__asm__("	.size _lsb_signgam,4");
__asm__("_lsb_signgam:");
__asm__("	.long 0");
__asm__(".symver _lsb_signgam,signgam@@GLIBC_2.0");
__asm__(".globl _lsb_clog");
__asm__("	.type _lsb_clog,@object");
__asm__("	.size _lsb_clog,4");
__asm__("_lsb_clog:");
__asm__("	.long 0");
__asm__(".symver _lsb_clog,clog@@GLIBC_2.1");
