__asm__(".globl feclearexcept");
__asm__("	.type feclearexcept,@function");
__asm__("feclearexcept:");
__asm__("	ret");
__asm__(".globl fegetenv");
__asm__("	.type fegetenv,@function");
__asm__("fegetenv:");
__asm__("	ret");
__asm__(".globl fegetexceptflag");
__asm__("	.type fegetexceptflag,@function");
__asm__("fegetexceptflag:");
__asm__("	ret");
__asm__(".globl fegetround");
__asm__("	.type fegetround,@function");
__asm__("fegetround:");
__asm__("	ret");
__asm__(".globl feholdexcept");
__asm__("	.type feholdexcept,@function");
__asm__("feholdexcept:");
__asm__("	ret");
__asm__(".globl feraiseexcept");
__asm__("	.type feraiseexcept,@function");
__asm__("feraiseexcept:");
__asm__("	ret");
__asm__(".globl fesetenv");
__asm__("	.type fesetenv,@function");
__asm__("fesetenv:");
__asm__("	ret");
__asm__(".globl fesetexceptflag");
__asm__("	.type fesetexceptflag,@function");
__asm__("fesetexceptflag:");
__asm__("	ret");
__asm__(".globl fesetround");
__asm__("	.type fesetround,@function");
__asm__("fesetround:");
__asm__("	ret");
__asm__(".globl fetestexcept");
__asm__("	.type fetestexcept,@function");
__asm__("fetestexcept:");
__asm__("	ret");
__asm__(".globl feupdateenv");
__asm__("	.type feupdateenv,@function");
__asm__("feupdateenv:");
__asm__("	ret");
__asm__(".globl copysign");
__asm__("	.type copysign,@function");
__asm__("copysign:");
__asm__("	ret");
__asm__(".globl finite");
__asm__("	.type finite,@function");
__asm__("finite:");
__asm__("	ret");
__asm__(".globl frexp");
__asm__("	.type frexp,@function");
__asm__("frexp:");
__asm__("	ret");
__asm__(".globl ldexp");
__asm__("	.type ldexp,@function");
__asm__("ldexp:");
__asm__("	ret");
__asm__(".globl modf");
__asm__("	.type modf,@function");
__asm__("modf:");
__asm__("	ret");
__asm__(".globl acos");
__asm__("	.type acos,@function");
__asm__("acos:");
__asm__("	ret");
__asm__(".globl acosh");
__asm__("	.type acosh,@function");
__asm__("acosh:");
__asm__("	ret");
__asm__(".globl asinh");
__asm__("	.type asinh,@function");
__asm__("asinh:");
__asm__("	ret");
__asm__(".globl atanh");
__asm__("	.type atanh,@function");
__asm__("atanh:");
__asm__("	ret");
__asm__(".globl asin");
__asm__("	.type asin,@function");
__asm__("asin:");
__asm__("	ret");
__asm__(".globl atan");
__asm__("	.type atan,@function");
__asm__("atan:");
__asm__("	ret");
__asm__(".globl atan2");
__asm__("	.type atan2,@function");
__asm__("atan2:");
__asm__("	ret");
__asm__(".globl cbrt");
__asm__("	.type cbrt,@function");
__asm__("cbrt:");
__asm__("	ret");
__asm__(".globl ceil");
__asm__("	.type ceil,@function");
__asm__("ceil:");
__asm__("	ret");
__asm__(".globl cos");
__asm__("	.type cos,@function");
__asm__("cos:");
__asm__("	ret");
__asm__(".globl cosh");
__asm__("	.type cosh,@function");
__asm__("cosh:");
__asm__("	ret");
__asm__(".globl erf");
__asm__("	.type erf,@function");
__asm__("erf:");
__asm__("	ret");
__asm__(".globl erfc");
__asm__("	.type erfc,@function");
__asm__("erfc:");
__asm__("	ret");
__asm__(".globl exp");
__asm__("	.type exp,@function");
__asm__("exp:");
__asm__("	ret");
__asm__(".globl expm1");
__asm__("	.type expm1,@function");
__asm__("expm1:");
__asm__("	ret");
__asm__(".globl fabs");
__asm__("	.type fabs,@function");
__asm__("fabs:");
__asm__("	ret");
__asm__(".globl floor");
__asm__("	.type floor,@function");
__asm__("floor:");
__asm__("	ret");
__asm__(".globl fmod");
__asm__("	.type fmod,@function");
__asm__("fmod:");
__asm__("	ret");
__asm__(".globl gamma");
__asm__("	.type gamma,@function");
__asm__("gamma:");
__asm__("	ret");
__asm__(".globl hypot");
__asm__("	.type hypot,@function");
__asm__("hypot:");
__asm__("	ret");
__asm__(".globl ilogb");
__asm__("	.type ilogb,@function");
__asm__("ilogb:");
__asm__("	ret");
__asm__(".globl j0");
__asm__("	.type j0,@function");
__asm__("j0:");
__asm__("	ret");
__asm__(".globl j1");
__asm__("	.type j1,@function");
__asm__("j1:");
__asm__("	ret");
__asm__(".globl jn");
__asm__("	.type jn,@function");
__asm__("jn:");
__asm__("	ret");
__asm__(".globl lgamma");
__asm__("	.type lgamma,@function");
__asm__("lgamma:");
__asm__("	ret");
__asm__(".globl log");
__asm__("	.type log,@function");
__asm__("log:");
__asm__("	ret");
__asm__(".globl log10");
__asm__("	.type log10,@function");
__asm__("log10:");
__asm__("	ret");
__asm__(".globl log1p");
__asm__("	.type log1p,@function");
__asm__("log1p:");
__asm__("	ret");
__asm__(".globl logb");
__asm__("	.type logb,@function");
__asm__("logb:");
__asm__("	ret");
__asm__(".globl nextafter");
__asm__("	.type nextafter,@function");
__asm__("nextafter:");
__asm__("	ret");
__asm__(".globl pow");
__asm__("	.type pow,@function");
__asm__("pow:");
__asm__("	ret");
__asm__(".globl remainder");
__asm__("	.type remainder,@function");
__asm__("remainder:");
__asm__("	ret");
__asm__(".globl rint");
__asm__("	.type rint,@function");
__asm__("rint:");
__asm__("	ret");
__asm__(".globl scalb");
__asm__("	.type scalb,@function");
__asm__("scalb:");
__asm__("	ret");
__asm__(".globl sin");
__asm__("	.type sin,@function");
__asm__("sin:");
__asm__("	ret");
__asm__(".globl sinh");
__asm__("	.type sinh,@function");
__asm__("sinh:");
__asm__("	ret");
__asm__(".globl sqrt");
__asm__("	.type sqrt,@function");
__asm__("sqrt:");
__asm__("	ret");
__asm__(".globl tan");
__asm__("	.type tan,@function");
__asm__("tan:");
__asm__("	ret");
__asm__(".globl tanh");
__asm__("	.type tanh,@function");
__asm__("tanh:");
__asm__("	ret");
__asm__(".globl y0");
__asm__("	.type y0,@function");
__asm__("y0:");
__asm__("	ret");
__asm__(".globl y1");
__asm__("	.type y1,@function");
__asm__("y1:");
__asm__("	ret");
__asm__(".globl yn");
__asm__("	.type yn,@function");
__asm__("yn:");
__asm__("	ret");
__asm__(".globl cabs");
__asm__("	.type cabs,@function");
__asm__("cabs:");
__asm__("	ret");
__asm__(".globl copysignf");
__asm__("	.type copysignf,@function");
__asm__("copysignf:");
__asm__("	ret");
__asm__(".globl copysignl");
__asm__("	.type copysignl,@function");
__asm__("copysignl:");
__asm__("	ret");
__asm__(".globl finitef");
__asm__("	.type finitef,@function");
__asm__("finitef:");
__asm__("	ret");
__asm__(".globl finitel");
__asm__("	.type finitel,@function");
__asm__("finitel:");
__asm__("	ret");
__asm__(".globl frexpf");
__asm__("	.type frexpf,@function");
__asm__("frexpf:");
__asm__("	ret");
__asm__(".globl frexpl");
__asm__("	.type frexpl,@function");
__asm__("frexpl:");
__asm__("	ret");
__asm__(".globl ldexpf");
__asm__("	.type ldexpf,@function");
__asm__("ldexpf:");
__asm__("	ret");
__asm__(".globl ldexpl");
__asm__("	.type ldexpl,@function");
__asm__("ldexpl:");
__asm__("	ret");
__asm__(".globl modff");
__asm__("	.type modff,@function");
__asm__("modff:");
__asm__("	ret");
__asm__(".globl modfl");
__asm__("	.type modfl,@function");
__asm__("modfl:");
__asm__("	ret");
__asm__(".globl scalbln");
__asm__("	.type scalbln,@function");
__asm__("scalbln:");
__asm__("	ret");
__asm__(".globl scalblnf");
__asm__("	.type scalblnf,@function");
__asm__("scalblnf:");
__asm__("	ret");
__asm__(".globl scalblnl");
__asm__("	.type scalblnl,@function");
__asm__("scalblnl:");
__asm__("	ret");
__asm__(".globl scalbn");
__asm__("	.type scalbn,@function");
__asm__("scalbn:");
__asm__("	ret");
__asm__(".globl scalbnf");
__asm__("	.type scalbnf,@function");
__asm__("scalbnf:");
__asm__("	ret");
__asm__(".globl scalbnl");
__asm__("	.type scalbnl,@function");
__asm__("scalbnl:");
__asm__("	ret");
__asm__(".globl acosf");
__asm__("	.type acosf,@function");
__asm__("acosf:");
__asm__("	ret");
__asm__(".globl acoshf");
__asm__("	.type acoshf,@function");
__asm__("acoshf:");
__asm__("	ret");
__asm__(".globl acoshl");
__asm__("	.type acoshl,@function");
__asm__("acoshl:");
__asm__("	ret");
__asm__(".globl acosl");
__asm__("	.type acosl,@function");
__asm__("acosl:");
__asm__("	ret");
__asm__(".globl asinf");
__asm__("	.type asinf,@function");
__asm__("asinf:");
__asm__("	ret");
__asm__(".globl asinhf");
__asm__("	.type asinhf,@function");
__asm__("asinhf:");
__asm__("	ret");
__asm__(".globl asinhl");
__asm__("	.type asinhl,@function");
__asm__("asinhl:");
__asm__("	ret");
__asm__(".globl asinl");
__asm__("	.type asinl,@function");
__asm__("asinl:");
__asm__("	ret");
__asm__(".globl atan2f");
__asm__("	.type atan2f,@function");
__asm__("atan2f:");
__asm__("	ret");
__asm__(".globl atan2l");
__asm__("	.type atan2l,@function");
__asm__("atan2l:");
__asm__("	ret");
__asm__(".globl atanf");
__asm__("	.type atanf,@function");
__asm__("atanf:");
__asm__("	ret");
__asm__(".globl atanhf");
__asm__("	.type atanhf,@function");
__asm__("atanhf:");
__asm__("	ret");
__asm__(".globl atanhl");
__asm__("	.type atanhl,@function");
__asm__("atanhl:");
__asm__("	ret");
__asm__(".globl atanl");
__asm__("	.type atanl,@function");
__asm__("atanl:");
__asm__("	ret");
__asm__(".globl cabsf");
__asm__("	.type cabsf,@function");
__asm__("cabsf:");
__asm__("	ret");
__asm__(".globl cabsl");
__asm__("	.type cabsl,@function");
__asm__("cabsl:");
__asm__("	ret");
__asm__(".globl cacos");
__asm__("	.type cacos,@function");
__asm__("cacos:");
__asm__("	ret");
__asm__(".globl cacosf");
__asm__("	.type cacosf,@function");
__asm__("cacosf:");
__asm__("	ret");
__asm__(".globl cacosh");
__asm__("	.type cacosh,@function");
__asm__("cacosh:");
__asm__("	ret");
__asm__(".globl cacoshf");
__asm__("	.type cacoshf,@function");
__asm__("cacoshf:");
__asm__("	ret");
__asm__(".globl cacoshl");
__asm__("	.type cacoshl,@function");
__asm__("cacoshl:");
__asm__("	ret");
__asm__(".globl cacosl");
__asm__("	.type cacosl,@function");
__asm__("cacosl:");
__asm__("	ret");
__asm__(".globl carg");
__asm__("	.type carg,@function");
__asm__("carg:");
__asm__("	ret");
__asm__(".globl cargf");
__asm__("	.type cargf,@function");
__asm__("cargf:");
__asm__("	ret");
__asm__(".globl cargl");
__asm__("	.type cargl,@function");
__asm__("cargl:");
__asm__("	ret");
__asm__(".globl casin");
__asm__("	.type casin,@function");
__asm__("casin:");
__asm__("	ret");
__asm__(".globl casinf");
__asm__("	.type casinf,@function");
__asm__("casinf:");
__asm__("	ret");
__asm__(".globl casinh");
__asm__("	.type casinh,@function");
__asm__("casinh:");
__asm__("	ret");
__asm__(".globl casinhf");
__asm__("	.type casinhf,@function");
__asm__("casinhf:");
__asm__("	ret");
__asm__(".globl casinhl");
__asm__("	.type casinhl,@function");
__asm__("casinhl:");
__asm__("	ret");
__asm__(".globl casinl");
__asm__("	.type casinl,@function");
__asm__("casinl:");
__asm__("	ret");
__asm__(".globl catan");
__asm__("	.type catan,@function");
__asm__("catan:");
__asm__("	ret");
__asm__(".globl catanf");
__asm__("	.type catanf,@function");
__asm__("catanf:");
__asm__("	ret");
__asm__(".globl catanh");
__asm__("	.type catanh,@function");
__asm__("catanh:");
__asm__("	ret");
__asm__(".globl catanhf");
__asm__("	.type catanhf,@function");
__asm__("catanhf:");
__asm__("	ret");
__asm__(".globl catanhl");
__asm__("	.type catanhl,@function");
__asm__("catanhl:");
__asm__("	ret");
__asm__(".globl catanl");
__asm__("	.type catanl,@function");
__asm__("catanl:");
__asm__("	ret");
__asm__(".globl cbrtf");
__asm__("	.type cbrtf,@function");
__asm__("cbrtf:");
__asm__("	ret");
__asm__(".globl cbrtl");
__asm__("	.type cbrtl,@function");
__asm__("cbrtl:");
__asm__("	ret");
__asm__(".globl ccos");
__asm__("	.type ccos,@function");
__asm__("ccos:");
__asm__("	ret");
__asm__(".globl ccosf");
__asm__("	.type ccosf,@function");
__asm__("ccosf:");
__asm__("	ret");
__asm__(".globl ccosh");
__asm__("	.type ccosh,@function");
__asm__("ccosh:");
__asm__("	ret");
__asm__(".globl ccoshf");
__asm__("	.type ccoshf,@function");
__asm__("ccoshf:");
__asm__("	ret");
__asm__(".globl ccoshl");
__asm__("	.type ccoshl,@function");
__asm__("ccoshl:");
__asm__("	ret");
__asm__(".globl ccosl");
__asm__("	.type ccosl,@function");
__asm__("ccosl:");
__asm__("	ret");
__asm__(".globl ceilf");
__asm__("	.type ceilf,@function");
__asm__("ceilf:");
__asm__("	ret");
__asm__(".globl ceill");
__asm__("	.type ceill,@function");
__asm__("ceill:");
__asm__("	ret");
__asm__(".globl cexp");
__asm__("	.type cexp,@function");
__asm__("cexp:");
__asm__("	ret");
__asm__(".globl cexpf");
__asm__("	.type cexpf,@function");
__asm__("cexpf:");
__asm__("	ret");
__asm__(".globl cexpl");
__asm__("	.type cexpl,@function");
__asm__("cexpl:");
__asm__("	ret");
__asm__(".globl cimag");
__asm__("	.type cimag,@function");
__asm__("cimag:");
__asm__("	ret");
__asm__(".globl cimagf");
__asm__("	.type cimagf,@function");
__asm__("cimagf:");
__asm__("	ret");
__asm__(".globl cimagl");
__asm__("	.type cimagl,@function");
__asm__("cimagl:");
__asm__("	ret");
__asm__(".globl clog10");
__asm__("	.type clog10,@function");
__asm__("clog10:");
__asm__("	ret");
__asm__(".globl clog10f");
__asm__("	.type clog10f,@function");
__asm__("clog10f:");
__asm__("	ret");
__asm__(".globl clog10l");
__asm__("	.type clog10l,@function");
__asm__("clog10l:");
__asm__("	ret");
__asm__(".globl clogf");
__asm__("	.type clogf,@function");
__asm__("clogf:");
__asm__("	ret");
__asm__(".globl clogl");
__asm__("	.type clogl,@function");
__asm__("clogl:");
__asm__("	ret");
__asm__(".globl conj");
__asm__("	.type conj,@function");
__asm__("conj:");
__asm__("	ret");
__asm__(".globl conjf");
__asm__("	.type conjf,@function");
__asm__("conjf:");
__asm__("	ret");
__asm__(".globl conjl");
__asm__("	.type conjl,@function");
__asm__("conjl:");
__asm__("	ret");
__asm__(".globl cosf");
__asm__("	.type cosf,@function");
__asm__("cosf:");
__asm__("	ret");
__asm__(".globl coshf");
__asm__("	.type coshf,@function");
__asm__("coshf:");
__asm__("	ret");
__asm__(".globl coshl");
__asm__("	.type coshl,@function");
__asm__("coshl:");
__asm__("	ret");
__asm__(".globl cosl");
__asm__("	.type cosl,@function");
__asm__("cosl:");
__asm__("	ret");
__asm__(".globl cpow");
__asm__("	.type cpow,@function");
__asm__("cpow:");
__asm__("	ret");
__asm__(".globl cpowf");
__asm__("	.type cpowf,@function");
__asm__("cpowf:");
__asm__("	ret");
__asm__(".globl cpowl");
__asm__("	.type cpowl,@function");
__asm__("cpowl:");
__asm__("	ret");
__asm__(".globl cproj");
__asm__("	.type cproj,@function");
__asm__("cproj:");
__asm__("	ret");
__asm__(".globl cprojf");
__asm__("	.type cprojf,@function");
__asm__("cprojf:");
__asm__("	ret");
__asm__(".globl cprojl");
__asm__("	.type cprojl,@function");
__asm__("cprojl:");
__asm__("	ret");
__asm__(".globl creal");
__asm__("	.type creal,@function");
__asm__("creal:");
__asm__("	ret");
__asm__(".globl crealf");
__asm__("	.type crealf,@function");
__asm__("crealf:");
__asm__("	ret");
__asm__(".globl creall");
__asm__("	.type creall,@function");
__asm__("creall:");
__asm__("	ret");
__asm__(".globl csin");
__asm__("	.type csin,@function");
__asm__("csin:");
__asm__("	ret");
__asm__(".globl csinf");
__asm__("	.type csinf,@function");
__asm__("csinf:");
__asm__("	ret");
__asm__(".globl csinh");
__asm__("	.type csinh,@function");
__asm__("csinh:");
__asm__("	ret");
__asm__(".globl csinhf");
__asm__("	.type csinhf,@function");
__asm__("csinhf:");
__asm__("	ret");
__asm__(".globl csinhl");
__asm__("	.type csinhl,@function");
__asm__("csinhl:");
__asm__("	ret");
__asm__(".globl csinl");
__asm__("	.type csinl,@function");
__asm__("csinl:");
__asm__("	ret");
__asm__(".globl csqrt");
__asm__("	.type csqrt,@function");
__asm__("csqrt:");
__asm__("	ret");
__asm__(".globl csqrtf");
__asm__("	.type csqrtf,@function");
__asm__("csqrtf:");
__asm__("	ret");
__asm__(".globl csqrtl");
__asm__("	.type csqrtl,@function");
__asm__("csqrtl:");
__asm__("	ret");
__asm__(".globl ctan");
__asm__("	.type ctan,@function");
__asm__("ctan:");
__asm__("	ret");
__asm__(".globl ctanf");
__asm__("	.type ctanf,@function");
__asm__("ctanf:");
__asm__("	ret");
__asm__(".globl ctanh");
__asm__("	.type ctanh,@function");
__asm__("ctanh:");
__asm__("	ret");
__asm__(".globl ctanhf");
__asm__("	.type ctanhf,@function");
__asm__("ctanhf:");
__asm__("	ret");
__asm__(".globl ctanhl");
__asm__("	.type ctanhl,@function");
__asm__("ctanhl:");
__asm__("	ret");
__asm__(".globl ctanl");
__asm__("	.type ctanl,@function");
__asm__("ctanl:");
__asm__("	ret");
__asm__(".globl dremf");
__asm__("	.type dremf,@function");
__asm__("dremf:");
__asm__("	ret");
__asm__(".globl dreml");
__asm__("	.type dreml,@function");
__asm__("dreml:");
__asm__("	ret");
__asm__(".globl erfcf");
__asm__("	.type erfcf,@function");
__asm__("erfcf:");
__asm__("	ret");
__asm__(".globl erfcl");
__asm__("	.type erfcl,@function");
__asm__("erfcl:");
__asm__("	ret");
__asm__(".globl erff");
__asm__("	.type erff,@function");
__asm__("erff:");
__asm__("	ret");
__asm__(".globl erfl");
__asm__("	.type erfl,@function");
__asm__("erfl:");
__asm__("	ret");
__asm__(".globl fabsf");
__asm__("	.type fabsf,@function");
__asm__("fabsf:");
__asm__("	ret");
__asm__(".globl fabsl");
__asm__("	.type fabsl,@function");
__asm__("fabsl:");
__asm__("	ret");
__asm__(".globl fdim");
__asm__("	.type fdim,@function");
__asm__("fdim:");
__asm__("	ret");
__asm__(".globl fdimf");
__asm__("	.type fdimf,@function");
__asm__("fdimf:");
__asm__("	ret");
__asm__(".globl fdiml");
__asm__("	.type fdiml,@function");
__asm__("fdiml:");
__asm__("	ret");
__asm__(".globl floorf");
__asm__("	.type floorf,@function");
__asm__("floorf:");
__asm__("	ret");
__asm__(".globl floorl");
__asm__("	.type floorl,@function");
__asm__("floorl:");
__asm__("	ret");
__asm__(".globl fma");
__asm__("	.type fma,@function");
__asm__("fma:");
__asm__("	ret");
__asm__(".globl fmaf");
__asm__("	.type fmaf,@function");
__asm__("fmaf:");
__asm__("	ret");
__asm__(".globl fmal");
__asm__("	.type fmal,@function");
__asm__("fmal:");
__asm__("	ret");
__asm__(".globl fmax");
__asm__("	.type fmax,@function");
__asm__("fmax:");
__asm__("	ret");
__asm__(".globl fmaxf");
__asm__("	.type fmaxf,@function");
__asm__("fmaxf:");
__asm__("	ret");
__asm__(".globl fmaxl");
__asm__("	.type fmaxl,@function");
__asm__("fmaxl:");
__asm__("	ret");
__asm__(".globl fmin");
__asm__("	.type fmin,@function");
__asm__("fmin:");
__asm__("	ret");
__asm__(".globl fminf");
__asm__("	.type fminf,@function");
__asm__("fminf:");
__asm__("	ret");
__asm__(".globl fminl");
__asm__("	.type fminl,@function");
__asm__("fminl:");
__asm__("	ret");
__asm__(".globl fmodf");
__asm__("	.type fmodf,@function");
__asm__("fmodf:");
__asm__("	ret");
__asm__(".globl fmodl");
__asm__("	.type fmodl,@function");
__asm__("fmodl:");
__asm__("	ret");
__asm__(".globl gammaf");
__asm__("	.type gammaf,@function");
__asm__("gammaf:");
__asm__("	ret");
__asm__(".globl gammal");
__asm__("	.type gammal,@function");
__asm__("gammal:");
__asm__("	ret");
__asm__(".globl hypotf");
__asm__("	.type hypotf,@function");
__asm__("hypotf:");
__asm__("	ret");
__asm__(".globl hypotl");
__asm__("	.type hypotl,@function");
__asm__("hypotl:");
__asm__("	ret");
__asm__(".globl ilogbf");
__asm__("	.type ilogbf,@function");
__asm__("ilogbf:");
__asm__("	ret");
__asm__(".globl ilogbl");
__asm__("	.type ilogbl,@function");
__asm__("ilogbl:");
__asm__("	ret");
__asm__(".globl j0f");
__asm__("	.type j0f,@function");
__asm__("j0f:");
__asm__("	ret");
__asm__(".globl j0l");
__asm__("	.type j0l,@function");
__asm__("j0l:");
__asm__("	ret");
__asm__(".globl j1f");
__asm__("	.type j1f,@function");
__asm__("j1f:");
__asm__("	ret");
__asm__(".globl j1l");
__asm__("	.type j1l,@function");
__asm__("j1l:");
__asm__("	ret");
__asm__(".globl jnf");
__asm__("	.type jnf,@function");
__asm__("jnf:");
__asm__("	ret");
__asm__(".globl jnl");
__asm__("	.type jnl,@function");
__asm__("jnl:");
__asm__("	ret");
__asm__(".globl lgamma_r");
__asm__("	.type lgamma_r,@function");
__asm__("lgamma_r:");
__asm__("	ret");
__asm__(".globl lgammaf");
__asm__("	.type lgammaf,@function");
__asm__("lgammaf:");
__asm__("	ret");
__asm__(".globl lgammaf_r");
__asm__("	.type lgammaf_r,@function");
__asm__("lgammaf_r:");
__asm__("	ret");
__asm__(".globl lgammal");
__asm__("	.type lgammal,@function");
__asm__("lgammal:");
__asm__("	ret");
__asm__(".globl lgammal_r");
__asm__("	.type lgammal_r,@function");
__asm__("lgammal_r:");
__asm__("	ret");
__asm__(".globl llrint");
__asm__("	.type llrint,@function");
__asm__("llrint:");
__asm__("	ret");
__asm__(".globl llrintf");
__asm__("	.type llrintf,@function");
__asm__("llrintf:");
__asm__("	ret");
__asm__(".globl llrintl");
__asm__("	.type llrintl,@function");
__asm__("llrintl:");
__asm__("	ret");
__asm__(".globl llround");
__asm__("	.type llround,@function");
__asm__("llround:");
__asm__("	ret");
__asm__(".globl llroundf");
__asm__("	.type llroundf,@function");
__asm__("llroundf:");
__asm__("	ret");
__asm__(".globl llroundl");
__asm__("	.type llroundl,@function");
__asm__("llroundl:");
__asm__("	ret");
__asm__(".globl lrint");
__asm__("	.type lrint,@function");
__asm__("lrint:");
__asm__("	ret");
__asm__(".globl lrintf");
__asm__("	.type lrintf,@function");
__asm__("lrintf:");
__asm__("	ret");
__asm__(".globl lrintl");
__asm__("	.type lrintl,@function");
__asm__("lrintl:");
__asm__("	ret");
__asm__(".globl lround");
__asm__("	.type lround,@function");
__asm__("lround:");
__asm__("	ret");
__asm__(".globl lroundf");
__asm__("	.type lroundf,@function");
__asm__("lroundf:");
__asm__("	ret");
__asm__(".globl lroundl");
__asm__("	.type lroundl,@function");
__asm__("lroundl:");
__asm__("	ret");
__asm__(".globl matherr");
__asm__("	.type matherr,@function");
__asm__("matherr:");
__asm__("	ret");
__asm__(".globl nan");
__asm__("	.type nan,@function");
__asm__("nan:");
__asm__("	ret");
__asm__(".globl nanf");
__asm__("	.type nanf,@function");
__asm__("nanf:");
__asm__("	ret");
__asm__(".globl nanl");
__asm__("	.type nanl,@function");
__asm__("nanl:");
__asm__("	ret");
__asm__(".globl nearbyint");
__asm__("	.type nearbyint,@function");
__asm__("nearbyint:");
__asm__("	ret");
__asm__(".globl nearbyintf");
__asm__("	.type nearbyintf,@function");
__asm__("nearbyintf:");
__asm__("	ret");
__asm__(".globl nearbyintl");
__asm__("	.type nearbyintl,@function");
__asm__("nearbyintl:");
__asm__("	ret");
__asm__(".globl nextafterf");
__asm__("	.type nextafterf,@function");
__asm__("nextafterf:");
__asm__("	ret");
__asm__(".globl nextafterl");
__asm__("	.type nextafterl,@function");
__asm__("nextafterl:");
__asm__("	ret");
__asm__(".globl nexttoward");
__asm__("	.type nexttoward,@function");
__asm__("nexttoward:");
__asm__("	ret");
__asm__(".globl nexttowardf");
__asm__("	.type nexttowardf,@function");
__asm__("nexttowardf:");
__asm__("	ret");
__asm__(".globl nexttowardl");
__asm__("	.type nexttowardl,@function");
__asm__("nexttowardl:");
__asm__("	ret");
__asm__(".globl pow10");
__asm__("	.type pow10,@function");
__asm__("pow10:");
__asm__("	ret");
__asm__(".globl pow10f");
__asm__("	.type pow10f,@function");
__asm__("pow10f:");
__asm__("	ret");
__asm__(".globl pow10l");
__asm__("	.type pow10l,@function");
__asm__("pow10l:");
__asm__("	ret");
__asm__(".globl powf");
__asm__("	.type powf,@function");
__asm__("powf:");
__asm__("	ret");
__asm__(".globl powl");
__asm__("	.type powl,@function");
__asm__("powl:");
__asm__("	ret");
__asm__(".globl remainderf");
__asm__("	.type remainderf,@function");
__asm__("remainderf:");
__asm__("	ret");
__asm__(".globl remainderl");
__asm__("	.type remainderl,@function");
__asm__("remainderl:");
__asm__("	ret");
__asm__(".globl remquo");
__asm__("	.type remquo,@function");
__asm__("remquo:");
__asm__("	ret");
__asm__(".globl remquof");
__asm__("	.type remquof,@function");
__asm__("remquof:");
__asm__("	ret");
__asm__(".globl remquol");
__asm__("	.type remquol,@function");
__asm__("remquol:");
__asm__("	ret");
__asm__(".globl rintf");
__asm__("	.type rintf,@function");
__asm__("rintf:");
__asm__("	ret");
__asm__(".globl rintl");
__asm__("	.type rintl,@function");
__asm__("rintl:");
__asm__("	ret");
__asm__(".globl round");
__asm__("	.type round,@function");
__asm__("round:");
__asm__("	ret");
__asm__(".globl roundf");
__asm__("	.type roundf,@function");
__asm__("roundf:");
__asm__("	ret");
__asm__(".globl roundl");
__asm__("	.type roundl,@function");
__asm__("roundl:");
__asm__("	ret");
__asm__(".globl scalbf");
__asm__("	.type scalbf,@function");
__asm__("scalbf:");
__asm__("	ret");
__asm__(".globl scalbl");
__asm__("	.type scalbl,@function");
__asm__("scalbl:");
__asm__("	ret");
__asm__(".globl significand");
__asm__("	.type significand,@function");
__asm__("significand:");
__asm__("	ret");
__asm__(".globl significandf");
__asm__("	.type significandf,@function");
__asm__("significandf:");
__asm__("	ret");
__asm__(".globl significandl");
__asm__("	.type significandl,@function");
__asm__("significandl:");
__asm__("	ret");
__asm__(".globl sincos");
__asm__("	.type sincos,@function");
__asm__("sincos:");
__asm__("	ret");
__asm__(".globl sincosf");
__asm__("	.type sincosf,@function");
__asm__("sincosf:");
__asm__("	ret");
__asm__(".globl sincosl");
__asm__("	.type sincosl,@function");
__asm__("sincosl:");
__asm__("	ret");
__asm__(".globl sinf");
__asm__("	.type sinf,@function");
__asm__("sinf:");
__asm__("	ret");
__asm__(".globl sinhf");
__asm__("	.type sinhf,@function");
__asm__("sinhf:");
__asm__("	ret");
__asm__(".globl sinhl");
__asm__("	.type sinhl,@function");
__asm__("sinhl:");
__asm__("	ret");
__asm__(".globl sinl");
__asm__("	.type sinl,@function");
__asm__("sinl:");
__asm__("	ret");
__asm__(".globl sqrtf");
__asm__("	.type sqrtf,@function");
__asm__("sqrtf:");
__asm__("	ret");
__asm__(".globl sqrtl");
__asm__("	.type sqrtl,@function");
__asm__("sqrtl:");
__asm__("	ret");
__asm__(".globl tanf");
__asm__("	.type tanf,@function");
__asm__("tanf:");
__asm__("	ret");
__asm__(".globl tanhf");
__asm__("	.type tanhf,@function");
__asm__("tanhf:");
__asm__("	ret");
__asm__(".globl tanhl");
__asm__("	.type tanhl,@function");
__asm__("tanhl:");
__asm__("	ret");
__asm__(".globl tanl");
__asm__("	.type tanl,@function");
__asm__("tanl:");
__asm__("	ret");
__asm__(".globl tgamma");
__asm__("	.type tgamma,@function");
__asm__("tgamma:");
__asm__("	ret");
__asm__(".globl tgammaf");
__asm__("	.type tgammaf,@function");
__asm__("tgammaf:");
__asm__("	ret");
__asm__(".globl tgammal");
__asm__("	.type tgammal,@function");
__asm__("tgammal:");
__asm__("	ret");
__asm__(".globl trunc");
__asm__("	.type trunc,@function");
__asm__("trunc:");
__asm__("	ret");
__asm__(".globl truncf");
__asm__("	.type truncf,@function");
__asm__("truncf:");
__asm__("	ret");
__asm__(".globl truncl");
__asm__("	.type truncl,@function");
__asm__("truncl:");
__asm__("	ret");
__asm__(".globl y0f");
__asm__("	.type y0f,@function");
__asm__("y0f:");
__asm__("	ret");
__asm__(".globl y0l");
__asm__("	.type y0l,@function");
__asm__("y0l:");
__asm__("	ret");
__asm__(".globl y1f");
__asm__("	.type y1f,@function");
__asm__("y1f:");
__asm__("	ret");
__asm__(".globl y1l");
__asm__("	.type y1l,@function");
__asm__("y1l:");
__asm__("	ret");
__asm__(".globl ynf");
__asm__("	.type ynf,@function");
__asm__("ynf:");
__asm__("	ret");
__asm__(".globl ynl");
__asm__("	.type ynl,@function");
__asm__("ynl:");
__asm__("	ret");
__asm__(".globl signgam");
__asm__("	.type signgam,@object");
__asm__("	.size signgam,4");
__asm__("signgam:");
__asm__("	.long 0");
__asm__(".globl clog");
__asm__("	.type clog,@object");
__asm__("	.size clog,4");
__asm__("clog:");
__asm__("	.long 0");
