__asm__(".globl addch");
__asm__("	.type addch,@function");
__asm__("addch:");
__asm__("	ret");
__asm__(".globl addchnstr");
__asm__("	.type addchnstr,@function");
__asm__("addchnstr:");
__asm__("	ret");
__asm__(".globl addchstr");
__asm__("	.type addchstr,@function");
__asm__("addchstr:");
__asm__("	ret");
__asm__(".globl addnstr");
__asm__("	.type addnstr,@function");
__asm__("addnstr:");
__asm__("	ret");
__asm__(".globl addstr");
__asm__("	.type addstr,@function");
__asm__("addstr:");
__asm__("	ret");
__asm__(".globl attroff");
__asm__("	.type attroff,@function");
__asm__("attroff:");
__asm__("	ret");
__asm__(".globl attron");
__asm__("	.type attron,@function");
__asm__("attron:");
__asm__("	ret");
__asm__(".globl attrset");
__asm__("	.type attrset,@function");
__asm__("attrset:");
__asm__("	ret");
__asm__(".globl attr_get");
__asm__("	.type attr_get,@function");
__asm__("attr_get:");
__asm__("	ret");
__asm__(".globl attr_off");
__asm__("	.type attr_off,@function");
__asm__("attr_off:");
__asm__("	ret");
__asm__(".globl attr_on");
__asm__("	.type attr_on,@function");
__asm__("attr_on:");
__asm__("	ret");
__asm__(".globl attr_set");
__asm__("	.type attr_set,@function");
__asm__("attr_set:");
__asm__("	ret");
__asm__(".globl baudrate");
__asm__("	.type baudrate,@function");
__asm__("baudrate:");
__asm__("	ret");
__asm__(".globl beep");
__asm__("	.type beep,@function");
__asm__("beep:");
__asm__("	ret");
__asm__(".globl bkgd");
__asm__("	.type bkgd,@function");
__asm__("bkgd:");
__asm__("	ret");
__asm__(".globl bkgdset");
__asm__("	.type bkgdset,@function");
__asm__("bkgdset:");
__asm__("	ret");
__asm__(".globl border");
__asm__("	.type border,@function");
__asm__("border:");
__asm__("	ret");
__asm__(".globl box");
__asm__("	.type box,@function");
__asm__("box:");
__asm__("	ret");
__asm__(".globl can_change_color");
__asm__("	.type can_change_color,@function");
__asm__("can_change_color:");
__asm__("	ret");
__asm__(".globl cbreak");
__asm__("	.type cbreak,@function");
__asm__("cbreak:");
__asm__("	ret");
__asm__(".globl chgat");
__asm__("	.type chgat,@function");
__asm__("chgat:");
__asm__("	ret");
__asm__(".globl clear");
__asm__("	.type clear,@function");
__asm__("clear:");
__asm__("	ret");
__asm__(".globl clearok");
__asm__("	.type clearok,@function");
__asm__("clearok:");
__asm__("	ret");
__asm__(".globl clrtobot");
__asm__("	.type clrtobot,@function");
__asm__("clrtobot:");
__asm__("	ret");
__asm__(".globl clrtoeol");
__asm__("	.type clrtoeol,@function");
__asm__("clrtoeol:");
__asm__("	ret");
__asm__(".globl color_content");
__asm__("	.type color_content,@function");
__asm__("color_content:");
__asm__("	ret");
__asm__(".globl color_set");
__asm__("	.type color_set,@function");
__asm__("color_set:");
__asm__("	ret");
__asm__(".globl copywin");
__asm__("	.type copywin,@function");
__asm__("copywin:");
__asm__("	ret");
__asm__(".globl curs_set");
__asm__("	.type curs_set,@function");
__asm__("curs_set:");
__asm__("	ret");
__asm__(".globl def_prog_mode");
__asm__("	.type def_prog_mode,@function");
__asm__("def_prog_mode:");
__asm__("	ret");
__asm__(".globl def_shell_mode");
__asm__("	.type def_shell_mode,@function");
__asm__("def_shell_mode:");
__asm__("	ret");
__asm__(".globl delay_output");
__asm__("	.type delay_output,@function");
__asm__("delay_output:");
__asm__("	ret");
__asm__(".globl delch");
__asm__("	.type delch,@function");
__asm__("delch:");
__asm__("	ret");
__asm__(".globl delscreen");
__asm__("	.type delscreen,@function");
__asm__("delscreen:");
__asm__("	ret");
__asm__(".globl delwin");
__asm__("	.type delwin,@function");
__asm__("delwin:");
__asm__("	ret");
__asm__(".globl deleteln");
__asm__("	.type deleteln,@function");
__asm__("deleteln:");
__asm__("	ret");
__asm__(".globl derwin");
__asm__("	.type derwin,@function");
__asm__("derwin:");
__asm__("	ret");
__asm__(".globl doupdate");
__asm__("	.type doupdate,@function");
__asm__("doupdate:");
__asm__("	ret");
__asm__(".globl dupwin");
__asm__("	.type dupwin,@function");
__asm__("dupwin:");
__asm__("	ret");
__asm__(".globl echo");
__asm__("	.type echo,@function");
__asm__("echo:");
__asm__("	ret");
__asm__(".globl echochar");
__asm__("	.type echochar,@function");
__asm__("echochar:");
__asm__("	ret");
__asm__(".globl erase");
__asm__("	.type erase,@function");
__asm__("erase:");
__asm__("	ret");
__asm__(".globl endwin");
__asm__("	.type endwin,@function");
__asm__("endwin:");
__asm__("	ret");
__asm__(".globl erasechar");
__asm__("	.type erasechar,@function");
__asm__("erasechar:");
__asm__("	ret");
__asm__(".globl filter");
__asm__("	.type filter,@function");
__asm__("filter:");
__asm__("	ret");
__asm__(".globl flash");
__asm__("	.type flash,@function");
__asm__("flash:");
__asm__("	ret");
__asm__(".globl flushinp");
__asm__("	.type flushinp,@function");
__asm__("flushinp:");
__asm__("	ret");
__asm__(".globl getbkgd");
__asm__("	.type getbkgd,@function");
__asm__("getbkgd:");
__asm__("	ret");
__asm__(".globl getch");
__asm__("	.type getch,@function");
__asm__("getch:");
__asm__("	ret");
__asm__(".globl getnstr");
__asm__("	.type getnstr,@function");
__asm__("getnstr:");
__asm__("	ret");
__asm__(".globl getstr");
__asm__("	.type getstr,@function");
__asm__("getstr:");
__asm__("	ret");
__asm__(".globl getwin");
__asm__("	.type getwin,@function");
__asm__("getwin:");
__asm__("	ret");
__asm__(".globl halfdelay");
__asm__("	.type halfdelay,@function");
__asm__("halfdelay:");
__asm__("	ret");
__asm__(".globl has_colors");
__asm__("	.type has_colors,@function");
__asm__("has_colors:");
__asm__("	ret");
__asm__(".globl has_ic");
__asm__("	.type has_ic,@function");
__asm__("has_ic:");
__asm__("	ret");
__asm__(".globl has_il");
__asm__("	.type has_il,@function");
__asm__("has_il:");
__asm__("	ret");
__asm__(".globl hline");
__asm__("	.type hline,@function");
__asm__("hline:");
__asm__("	ret");
__asm__(".globl idcok");
__asm__("	.type idcok,@function");
__asm__("idcok:");
__asm__("	ret");
__asm__(".globl idlok");
__asm__("	.type idlok,@function");
__asm__("idlok:");
__asm__("	ret");
__asm__(".globl immedok");
__asm__("	.type immedok,@function");
__asm__("immedok:");
__asm__("	ret");
__asm__(".globl inch");
__asm__("	.type inch,@function");
__asm__("inch:");
__asm__("	ret");
__asm__(".globl inchnstr");
__asm__("	.type inchnstr,@function");
__asm__("inchnstr:");
__asm__("	ret");
__asm__(".globl inchstr");
__asm__("	.type inchstr,@function");
__asm__("inchstr:");
__asm__("	ret");
__asm__(".globl initscr");
__asm__("	.type initscr,@function");
__asm__("initscr:");
__asm__("	ret");
__asm__(".globl init_color");
__asm__("	.type init_color,@function");
__asm__("init_color:");
__asm__("	ret");
__asm__(".globl init_pair");
__asm__("	.type init_pair,@function");
__asm__("init_pair:");
__asm__("	ret");
__asm__(".globl innstr");
__asm__("	.type innstr,@function");
__asm__("innstr:");
__asm__("	ret");
__asm__(".globl insch");
__asm__("	.type insch,@function");
__asm__("insch:");
__asm__("	ret");
__asm__(".globl insdelln");
__asm__("	.type insdelln,@function");
__asm__("insdelln:");
__asm__("	ret");
__asm__(".globl insertln");
__asm__("	.type insertln,@function");
__asm__("insertln:");
__asm__("	ret");
__asm__(".globl insnstr");
__asm__("	.type insnstr,@function");
__asm__("insnstr:");
__asm__("	ret");
__asm__(".globl insstr");
__asm__("	.type insstr,@function");
__asm__("insstr:");
__asm__("	ret");
__asm__(".globl instr");
__asm__("	.type instr,@function");
__asm__("instr:");
__asm__("	ret");
__asm__(".globl intrflush");
__asm__("	.type intrflush,@function");
__asm__("intrflush:");
__asm__("	ret");
__asm__(".globl isendwin");
__asm__("	.type isendwin,@function");
__asm__("isendwin:");
__asm__("	ret");
__asm__(".globl is_linetouched");
__asm__("	.type is_linetouched,@function");
__asm__("is_linetouched:");
__asm__("	ret");
__asm__(".globl is_wintouched");
__asm__("	.type is_wintouched,@function");
__asm__("is_wintouched:");
__asm__("	ret");
__asm__(".globl keyname");
__asm__("	.type keyname,@function");
__asm__("keyname:");
__asm__("	ret");
__asm__(".globl keypad");
__asm__("	.type keypad,@function");
__asm__("keypad:");
__asm__("	ret");
__asm__(".globl killchar");
__asm__("	.type killchar,@function");
__asm__("killchar:");
__asm__("	ret");
__asm__(".globl leaveok");
__asm__("	.type leaveok,@function");
__asm__("leaveok:");
__asm__("	ret");
__asm__(".globl longname");
__asm__("	.type longname,@function");
__asm__("longname:");
__asm__("	ret");
__asm__(".globl meta");
__asm__("	.type meta,@function");
__asm__("meta:");
__asm__("	ret");
__asm__(".globl move");
__asm__("	.type move,@function");
__asm__("move:");
__asm__("	ret");
__asm__(".globl mvaddch");
__asm__("	.type mvaddch,@function");
__asm__("mvaddch:");
__asm__("	ret");
__asm__(".globl mvaddchnstr");
__asm__("	.type mvaddchnstr,@function");
__asm__("mvaddchnstr:");
__asm__("	ret");
__asm__(".globl mvaddchstr");
__asm__("	.type mvaddchstr,@function");
__asm__("mvaddchstr:");
__asm__("	ret");
__asm__(".globl mvaddnstr");
__asm__("	.type mvaddnstr,@function");
__asm__("mvaddnstr:");
__asm__("	ret");
__asm__(".globl mvaddstr");
__asm__("	.type mvaddstr,@function");
__asm__("mvaddstr:");
__asm__("	ret");
__asm__(".globl mvchgat");
__asm__("	.type mvchgat,@function");
__asm__("mvchgat:");
__asm__("	ret");
__asm__(".globl mvcur");
__asm__("	.type mvcur,@function");
__asm__("mvcur:");
__asm__("	ret");
__asm__(".globl mvdelch");
__asm__("	.type mvdelch,@function");
__asm__("mvdelch:");
__asm__("	ret");
__asm__(".globl mvderwin");
__asm__("	.type mvderwin,@function");
__asm__("mvderwin:");
__asm__("	ret");
__asm__(".globl mvgetch");
__asm__("	.type mvgetch,@function");
__asm__("mvgetch:");
__asm__("	ret");
__asm__(".globl mvgetnstr");
__asm__("	.type mvgetnstr,@function");
__asm__("mvgetnstr:");
__asm__("	ret");
__asm__(".globl mvgetstr");
__asm__("	.type mvgetstr,@function");
__asm__("mvgetstr:");
__asm__("	ret");
__asm__(".globl mvhline");
__asm__("	.type mvhline,@function");
__asm__("mvhline:");
__asm__("	ret");
__asm__(".globl mvinch");
__asm__("	.type mvinch,@function");
__asm__("mvinch:");
__asm__("	ret");
__asm__(".globl mvinchnstr");
__asm__("	.type mvinchnstr,@function");
__asm__("mvinchnstr:");
__asm__("	ret");
__asm__(".globl mvinchstr");
__asm__("	.type mvinchstr,@function");
__asm__("mvinchstr:");
__asm__("	ret");
__asm__(".globl mvinnstr");
__asm__("	.type mvinnstr,@function");
__asm__("mvinnstr:");
__asm__("	ret");
__asm__(".globl mvinsch");
__asm__("	.type mvinsch,@function");
__asm__("mvinsch:");
__asm__("	ret");
__asm__(".globl mvinsnstr");
__asm__("	.type mvinsnstr,@function");
__asm__("mvinsnstr:");
__asm__("	ret");
__asm__(".globl mvinsstr");
__asm__("	.type mvinsstr,@function");
__asm__("mvinsstr:");
__asm__("	ret");
__asm__(".globl mvinstr");
__asm__("	.type mvinstr,@function");
__asm__("mvinstr:");
__asm__("	ret");
__asm__(".globl mvprintw");
__asm__("	.type mvprintw,@function");
__asm__("mvprintw:");
__asm__("	ret");
__asm__(".globl mvscanw");
__asm__("	.type mvscanw,@function");
__asm__("mvscanw:");
__asm__("	ret");
__asm__(".globl mvvline");
__asm__("	.type mvvline,@function");
__asm__("mvvline:");
__asm__("	ret");
__asm__(".globl mvwaddch");
__asm__("	.type mvwaddch,@function");
__asm__("mvwaddch:");
__asm__("	ret");
__asm__(".globl mvwaddchnstr");
__asm__("	.type mvwaddchnstr,@function");
__asm__("mvwaddchnstr:");
__asm__("	ret");
__asm__(".globl mvwaddchstr");
__asm__("	.type mvwaddchstr,@function");
__asm__("mvwaddchstr:");
__asm__("	ret");
__asm__(".globl mvwaddnstr");
__asm__("	.type mvwaddnstr,@function");
__asm__("mvwaddnstr:");
__asm__("	ret");
__asm__(".globl mvwaddstr");
__asm__("	.type mvwaddstr,@function");
__asm__("mvwaddstr:");
__asm__("	ret");
__asm__(".globl mvwchgat");
__asm__("	.type mvwchgat,@function");
__asm__("mvwchgat:");
__asm__("	ret");
__asm__(".globl mvwdelch");
__asm__("	.type mvwdelch,@function");
__asm__("mvwdelch:");
__asm__("	ret");
__asm__(".globl mvwgetch");
__asm__("	.type mvwgetch,@function");
__asm__("mvwgetch:");
__asm__("	ret");
__asm__(".globl mvwgetnstr");
__asm__("	.type mvwgetnstr,@function");
__asm__("mvwgetnstr:");
__asm__("	ret");
__asm__(".globl mvwgetstr");
__asm__("	.type mvwgetstr,@function");
__asm__("mvwgetstr:");
__asm__("	ret");
__asm__(".globl mvwhline");
__asm__("	.type mvwhline,@function");
__asm__("mvwhline:");
__asm__("	ret");
__asm__(".globl mvwin");
__asm__("	.type mvwin,@function");
__asm__("mvwin:");
__asm__("	ret");
__asm__(".globl mvwinch");
__asm__("	.type mvwinch,@function");
__asm__("mvwinch:");
__asm__("	ret");
__asm__(".globl mvwinchnstr");
__asm__("	.type mvwinchnstr,@function");
__asm__("mvwinchnstr:");
__asm__("	ret");
__asm__(".globl mvwinchstr");
__asm__("	.type mvwinchstr,@function");
__asm__("mvwinchstr:");
__asm__("	ret");
__asm__(".globl mvwinnstr");
__asm__("	.type mvwinnstr,@function");
__asm__("mvwinnstr:");
__asm__("	ret");
__asm__(".globl mvwinsch");
__asm__("	.type mvwinsch,@function");
__asm__("mvwinsch:");
__asm__("	ret");
__asm__(".globl mvwinsnstr");
__asm__("	.type mvwinsnstr,@function");
__asm__("mvwinsnstr:");
__asm__("	ret");
__asm__(".globl mvwinsstr");
__asm__("	.type mvwinsstr,@function");
__asm__("mvwinsstr:");
__asm__("	ret");
__asm__(".globl mvwinstr");
__asm__("	.type mvwinstr,@function");
__asm__("mvwinstr:");
__asm__("	ret");
__asm__(".globl mvwprintw");
__asm__("	.type mvwprintw,@function");
__asm__("mvwprintw:");
__asm__("	ret");
__asm__(".globl mvwscanw");
__asm__("	.type mvwscanw,@function");
__asm__("mvwscanw:");
__asm__("	ret");
__asm__(".globl mvwvline");
__asm__("	.type mvwvline,@function");
__asm__("mvwvline:");
__asm__("	ret");
__asm__(".globl napms");
__asm__("	.type napms,@function");
__asm__("napms:");
__asm__("	ret");
__asm__(".globl newpad");
__asm__("	.type newpad,@function");
__asm__("newpad:");
__asm__("	ret");
__asm__(".globl newterm");
__asm__("	.type newterm,@function");
__asm__("newterm:");
__asm__("	ret");
__asm__(".globl newwin");
__asm__("	.type newwin,@function");
__asm__("newwin:");
__asm__("	ret");
__asm__(".globl nl");
__asm__("	.type nl,@function");
__asm__("nl:");
__asm__("	ret");
__asm__(".globl nocbreak");
__asm__("	.type nocbreak,@function");
__asm__("nocbreak:");
__asm__("	ret");
__asm__(".globl nodelay");
__asm__("	.type nodelay,@function");
__asm__("nodelay:");
__asm__("	ret");
__asm__(".globl noecho");
__asm__("	.type noecho,@function");
__asm__("noecho:");
__asm__("	ret");
__asm__(".globl nonl");
__asm__("	.type nonl,@function");
__asm__("nonl:");
__asm__("	ret");
__asm__(".globl noqiflush");
__asm__("	.type noqiflush,@function");
__asm__("noqiflush:");
__asm__("	ret");
__asm__(".globl noraw");
__asm__("	.type noraw,@function");
__asm__("noraw:");
__asm__("	ret");
__asm__(".globl notimeout");
__asm__("	.type notimeout,@function");
__asm__("notimeout:");
__asm__("	ret");
__asm__(".globl overlay");
__asm__("	.type overlay,@function");
__asm__("overlay:");
__asm__("	ret");
__asm__(".globl overwrite");
__asm__("	.type overwrite,@function");
__asm__("overwrite:");
__asm__("	ret");
__asm__(".globl pair_content");
__asm__("	.type pair_content,@function");
__asm__("pair_content:");
__asm__("	ret");
__asm__(".globl pechochar");
__asm__("	.type pechochar,@function");
__asm__("pechochar:");
__asm__("	ret");
__asm__(".globl pnoutrefresh");
__asm__("	.type pnoutrefresh,@function");
__asm__("pnoutrefresh:");
__asm__("	ret");
__asm__(".globl prefresh");
__asm__("	.type prefresh,@function");
__asm__("prefresh:");
__asm__("	ret");
__asm__(".globl printw");
__asm__("	.type printw,@function");
__asm__("printw:");
__asm__("	ret");
__asm__(".globl putp");
__asm__("	.type putp,@function");
__asm__("putp:");
__asm__("	ret");
__asm__(".globl putwin");
__asm__("	.type putwin,@function");
__asm__("putwin:");
__asm__("	ret");
__asm__(".globl qiflush");
__asm__("	.type qiflush,@function");
__asm__("qiflush:");
__asm__("	ret");
__asm__(".globl raw");
__asm__("	.type raw,@function");
__asm__("raw:");
__asm__("	ret");
__asm__(".globl redrawwin");
__asm__("	.type redrawwin,@function");
__asm__("redrawwin:");
__asm__("	ret");
__asm__(".globl refresh");
__asm__("	.type refresh,@function");
__asm__("refresh:");
__asm__("	ret");
__asm__(".globl resetty");
__asm__("	.type resetty,@function");
__asm__("resetty:");
__asm__("	ret");
__asm__(".globl reset_prog_mode");
__asm__("	.type reset_prog_mode,@function");
__asm__("reset_prog_mode:");
__asm__("	ret");
__asm__(".globl reset_shell_mode");
__asm__("	.type reset_shell_mode,@function");
__asm__("reset_shell_mode:");
__asm__("	ret");
__asm__(".globl ripoffline");
__asm__("	.type ripoffline,@function");
__asm__("ripoffline:");
__asm__("	ret");
__asm__(".globl savetty");
__asm__("	.type savetty,@function");
__asm__("savetty:");
__asm__("	ret");
__asm__(".globl scanw");
__asm__("	.type scanw,@function");
__asm__("scanw:");
__asm__("	ret");
__asm__(".globl scr_dump");
__asm__("	.type scr_dump,@function");
__asm__("scr_dump:");
__asm__("	ret");
__asm__(".globl scr_init");
__asm__("	.type scr_init,@function");
__asm__("scr_init:");
__asm__("	ret");
__asm__(".globl scrl");
__asm__("	.type scrl,@function");
__asm__("scrl:");
__asm__("	ret");
__asm__(".globl scroll");
__asm__("	.type scroll,@function");
__asm__("scroll:");
__asm__("	ret");
__asm__(".globl scrollok");
__asm__("	.type scrollok,@function");
__asm__("scrollok:");
__asm__("	ret");
__asm__(".globl scr_restore");
__asm__("	.type scr_restore,@function");
__asm__("scr_restore:");
__asm__("	ret");
__asm__(".globl scr_set");
__asm__("	.type scr_set,@function");
__asm__("scr_set:");
__asm__("	ret");
__asm__(".globl setscrreg");
__asm__("	.type setscrreg,@function");
__asm__("setscrreg:");
__asm__("	ret");
__asm__(".globl set_term");
__asm__("	.type set_term,@function");
__asm__("set_term:");
__asm__("	ret");
__asm__(".globl slk_attroff");
__asm__("	.type slk_attroff,@function");
__asm__("slk_attroff:");
__asm__("	ret");
__asm__(".globl slk_attron");
__asm__("	.type slk_attron,@function");
__asm__("slk_attron:");
__asm__("	ret");
__asm__(".globl slk_attrset");
__asm__("	.type slk_attrset,@function");
__asm__("slk_attrset:");
__asm__("	ret");
__asm__(".globl slk_attr_set");
__asm__("	.type slk_attr_set,@function");
__asm__("slk_attr_set:");
__asm__("	ret");
__asm__(".globl slk_clear");
__asm__("	.type slk_clear,@function");
__asm__("slk_clear:");
__asm__("	ret");
__asm__(".globl slk_color");
__asm__("	.type slk_color,@function");
__asm__("slk_color:");
__asm__("	ret");
__asm__(".globl slk_init");
__asm__("	.type slk_init,@function");
__asm__("slk_init:");
__asm__("	ret");
__asm__(".globl slk_label");
__asm__("	.type slk_label,@function");
__asm__("slk_label:");
__asm__("	ret");
__asm__(".globl slk_noutrefresh");
__asm__("	.type slk_noutrefresh,@function");
__asm__("slk_noutrefresh:");
__asm__("	ret");
__asm__(".globl slk_refresh");
__asm__("	.type slk_refresh,@function");
__asm__("slk_refresh:");
__asm__("	ret");
__asm__(".globl slk_restore");
__asm__("	.type slk_restore,@function");
__asm__("slk_restore:");
__asm__("	ret");
__asm__(".globl slk_set");
__asm__("	.type slk_set,@function");
__asm__("slk_set:");
__asm__("	ret");
__asm__(".globl slk_touch");
__asm__("	.type slk_touch,@function");
__asm__("slk_touch:");
__asm__("	ret");
__asm__(".globl standout");
__asm__("	.type standout,@function");
__asm__("standout:");
__asm__("	ret");
__asm__(".globl standend");
__asm__("	.type standend,@function");
__asm__("standend:");
__asm__("	ret");
__asm__(".globl start_color");
__asm__("	.type start_color,@function");
__asm__("start_color:");
__asm__("	ret");
__asm__(".globl subpad");
__asm__("	.type subpad,@function");
__asm__("subpad:");
__asm__("	ret");
__asm__(".globl subwin");
__asm__("	.type subwin,@function");
__asm__("subwin:");
__asm__("	ret");
__asm__(".globl syncok");
__asm__("	.type syncok,@function");
__asm__("syncok:");
__asm__("	ret");
__asm__(".globl termattrs");
__asm__("	.type termattrs,@function");
__asm__("termattrs:");
__asm__("	ret");
__asm__(".globl termname");
__asm__("	.type termname,@function");
__asm__("termname:");
__asm__("	ret");
__asm__(".globl tigetflag");
__asm__("	.type tigetflag,@function");
__asm__("tigetflag:");
__asm__("	ret");
__asm__(".globl tigetnum");
__asm__("	.type tigetnum,@function");
__asm__("tigetnum:");
__asm__("	ret");
__asm__(".globl tigetstr");
__asm__("	.type tigetstr,@function");
__asm__("tigetstr:");
__asm__("	ret");
__asm__(".globl timeout");
__asm__("	.type timeout,@function");
__asm__("timeout:");
__asm__("	ret");
__asm__(".globl tparm");
__asm__("	.type tparm,@function");
__asm__("tparm:");
__asm__("	ret");
__asm__(".globl typeahead");
__asm__("	.type typeahead,@function");
__asm__("typeahead:");
__asm__("	ret");
__asm__(".globl ungetch");
__asm__("	.type ungetch,@function");
__asm__("ungetch:");
__asm__("	ret");
__asm__(".globl untouchwin");
__asm__("	.type untouchwin,@function");
__asm__("untouchwin:");
__asm__("	ret");
__asm__(".globl use_env");
__asm__("	.type use_env,@function");
__asm__("use_env:");
__asm__("	ret");
__asm__(".globl vidattr");
__asm__("	.type vidattr,@function");
__asm__("vidattr:");
__asm__("	ret");
__asm__(".globl vidputs");
__asm__("	.type vidputs,@function");
__asm__("vidputs:");
__asm__("	ret");
__asm__(".globl vline");
__asm__("	.type vline,@function");
__asm__("vline:");
__asm__("	ret");
__asm__(".globl vwprintw");
__asm__("	.type vwprintw,@function");
__asm__("vwprintw:");
__asm__("	ret");
__asm__(".globl vw_printw");
__asm__("	.type vw_printw,@function");
__asm__("vw_printw:");
__asm__("	ret");
__asm__(".globl vwscanw");
__asm__("	.type vwscanw,@function");
__asm__("vwscanw:");
__asm__("	ret");
__asm__(".globl vw_scanw");
__asm__("	.type vw_scanw,@function");
__asm__("vw_scanw:");
__asm__("	ret");
__asm__(".globl waddch");
__asm__("	.type waddch,@function");
__asm__("waddch:");
__asm__("	ret");
__asm__(".globl waddchnstr");
__asm__("	.type waddchnstr,@function");
__asm__("waddchnstr:");
__asm__("	ret");
__asm__(".globl waddchstr");
__asm__("	.type waddchstr,@function");
__asm__("waddchstr:");
__asm__("	ret");
__asm__(".globl waddnstr");
__asm__("	.type waddnstr,@function");
__asm__("waddnstr:");
__asm__("	ret");
__asm__(".globl waddstr");
__asm__("	.type waddstr,@function");
__asm__("waddstr:");
__asm__("	ret");
__asm__(".globl wattron");
__asm__("	.type wattron,@function");
__asm__("wattron:");
__asm__("	ret");
__asm__(".globl wattroff");
__asm__("	.type wattroff,@function");
__asm__("wattroff:");
__asm__("	ret");
__asm__(".globl wattrset");
__asm__("	.type wattrset,@function");
__asm__("wattrset:");
__asm__("	ret");
__asm__(".globl wattr_get");
__asm__("	.type wattr_get,@function");
__asm__("wattr_get:");
__asm__("	ret");
__asm__(".globl wattr_on");
__asm__("	.type wattr_on,@function");
__asm__("wattr_on:");
__asm__("	ret");
__asm__(".globl wattr_off");
__asm__("	.type wattr_off,@function");
__asm__("wattr_off:");
__asm__("	ret");
__asm__(".globl wattr_set");
__asm__("	.type wattr_set,@function");
__asm__("wattr_set:");
__asm__("	ret");
__asm__(".globl wbkgd");
__asm__("	.type wbkgd,@function");
__asm__("wbkgd:");
__asm__("	ret");
__asm__(".globl wbkgdset");
__asm__("	.type wbkgdset,@function");
__asm__("wbkgdset:");
__asm__("	ret");
__asm__(".globl wborder");
__asm__("	.type wborder,@function");
__asm__("wborder:");
__asm__("	ret");
__asm__(".globl wchgat");
__asm__("	.type wchgat,@function");
__asm__("wchgat:");
__asm__("	ret");
__asm__(".globl wclear");
__asm__("	.type wclear,@function");
__asm__("wclear:");
__asm__("	ret");
__asm__(".globl wclrtobot");
__asm__("	.type wclrtobot,@function");
__asm__("wclrtobot:");
__asm__("	ret");
__asm__(".globl wclrtoeol");
__asm__("	.type wclrtoeol,@function");
__asm__("wclrtoeol:");
__asm__("	ret");
__asm__(".globl wcolor_set");
__asm__("	.type wcolor_set,@function");
__asm__("wcolor_set:");
__asm__("	ret");
__asm__(".globl wcursyncup");
__asm__("	.type wcursyncup,@function");
__asm__("wcursyncup:");
__asm__("	ret");
__asm__(".globl wdelch");
__asm__("	.type wdelch,@function");
__asm__("wdelch:");
__asm__("	ret");
__asm__(".globl wdeleteln");
__asm__("	.type wdeleteln,@function");
__asm__("wdeleteln:");
__asm__("	ret");
__asm__(".globl wechochar");
__asm__("	.type wechochar,@function");
__asm__("wechochar:");
__asm__("	ret");
__asm__(".globl werase");
__asm__("	.type werase,@function");
__asm__("werase:");
__asm__("	ret");
__asm__(".globl wgetch");
__asm__("	.type wgetch,@function");
__asm__("wgetch:");
__asm__("	ret");
__asm__(".globl wgetnstr");
__asm__("	.type wgetnstr,@function");
__asm__("wgetnstr:");
__asm__("	ret");
__asm__(".globl wgetstr");
__asm__("	.type wgetstr,@function");
__asm__("wgetstr:");
__asm__("	ret");
__asm__(".globl whline");
__asm__("	.type whline,@function");
__asm__("whline:");
__asm__("	ret");
__asm__(".globl winch");
__asm__("	.type winch,@function");
__asm__("winch:");
__asm__("	ret");
__asm__(".globl winchnstr");
__asm__("	.type winchnstr,@function");
__asm__("winchnstr:");
__asm__("	ret");
__asm__(".globl winchstr");
__asm__("	.type winchstr,@function");
__asm__("winchstr:");
__asm__("	ret");
__asm__(".globl winnstr");
__asm__("	.type winnstr,@function");
__asm__("winnstr:");
__asm__("	ret");
__asm__(".globl winsch");
__asm__("	.type winsch,@function");
__asm__("winsch:");
__asm__("	ret");
__asm__(".globl winsdelln");
__asm__("	.type winsdelln,@function");
__asm__("winsdelln:");
__asm__("	ret");
__asm__(".globl winsertln");
__asm__("	.type winsertln,@function");
__asm__("winsertln:");
__asm__("	ret");
__asm__(".globl winsnstr");
__asm__("	.type winsnstr,@function");
__asm__("winsnstr:");
__asm__("	ret");
__asm__(".globl winsstr");
__asm__("	.type winsstr,@function");
__asm__("winsstr:");
__asm__("	ret");
__asm__(".globl winstr");
__asm__("	.type winstr,@function");
__asm__("winstr:");
__asm__("	ret");
__asm__(".globl wmove");
__asm__("	.type wmove,@function");
__asm__("wmove:");
__asm__("	ret");
__asm__(".globl wnoutrefresh");
__asm__("	.type wnoutrefresh,@function");
__asm__("wnoutrefresh:");
__asm__("	ret");
__asm__(".globl wprintw");
__asm__("	.type wprintw,@function");
__asm__("wprintw:");
__asm__("	ret");
__asm__(".globl wredrawln");
__asm__("	.type wredrawln,@function");
__asm__("wredrawln:");
__asm__("	ret");
__asm__(".globl wrefresh");
__asm__("	.type wrefresh,@function");
__asm__("wrefresh:");
__asm__("	ret");
__asm__(".globl wscanw");
__asm__("	.type wscanw,@function");
__asm__("wscanw:");
__asm__("	ret");
__asm__(".globl wscrl");
__asm__("	.type wscrl,@function");
__asm__("wscrl:");
__asm__("	ret");
__asm__(".globl wsetscrreg");
__asm__("	.type wsetscrreg,@function");
__asm__("wsetscrreg:");
__asm__("	ret");
__asm__(".globl wstandout");
__asm__("	.type wstandout,@function");
__asm__("wstandout:");
__asm__("	ret");
__asm__(".globl wstandend");
__asm__("	.type wstandend,@function");
__asm__("wstandend:");
__asm__("	ret");
__asm__(".globl wsyncdown");
__asm__("	.type wsyncdown,@function");
__asm__("wsyncdown:");
__asm__("	ret");
__asm__(".globl wsyncup");
__asm__("	.type wsyncup,@function");
__asm__("wsyncup:");
__asm__("	ret");
__asm__(".globl wtimeout");
__asm__("	.type wtimeout,@function");
__asm__("wtimeout:");
__asm__("	ret");
__asm__(".globl wtouchln");
__asm__("	.type wtouchln,@function");
__asm__("wtouchln:");
__asm__("	ret");
__asm__(".globl wvline");
__asm__("	.type wvline,@function");
__asm__("wvline:");
__asm__("	ret");
__asm__(".globl tgetstr");
__asm__("	.type tgetstr,@function");
__asm__("tgetstr:");
__asm__("	ret");
__asm__(".globl tgoto");
__asm__("	.type tgoto,@function");
__asm__("tgoto:");
__asm__("	ret");
__asm__(".globl tgetent");
__asm__("	.type tgetent,@function");
__asm__("tgetent:");
__asm__("	ret");
__asm__(".globl tgetflag");
__asm__("	.type tgetflag,@function");
__asm__("tgetflag:");
__asm__("	ret");
__asm__(".globl tgetnum");
__asm__("	.type tgetnum,@function");
__asm__("tgetnum:");
__asm__("	ret");
__asm__(".globl tputs");
__asm__("	.type tputs,@function");
__asm__("tputs:");
__asm__("	ret");
__asm__(".globl curscr");
__asm__("	.type curscr,@object");
__asm__("	.size curscr,4");
__asm__("curscr:");
__asm__("	.long 0");
__asm__(".globl stdscr");
__asm__("	.type stdscr,@object");
__asm__("	.size stdscr,4");
__asm__("stdscr:");
__asm__("	.long 0");
