__asm__(".globl _lsb_pthread_attr_destroy");
__asm__("	.type _lsb_pthread_attr_destroy,@function");
__asm__("_lsb_pthread_attr_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_destroy,pthread_attr_destroy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_getdetachstate");
__asm__("	.type _lsb_pthread_attr_getdetachstate,@function");
__asm__("_lsb_pthread_attr_getdetachstate:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getdetachstate,pthread_attr_getdetachstate@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_getinheritsched");
__asm__("	.type _lsb_pthread_attr_getinheritsched,@function");
__asm__("_lsb_pthread_attr_getinheritsched:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getinheritsched,pthread_attr_getinheritsched@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_getschedparam");
__asm__("	.type _lsb_pthread_attr_getschedparam,@function");
__asm__("_lsb_pthread_attr_getschedparam:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getschedparam,pthread_attr_getschedparam@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_getschedpolicy");
__asm__("	.type _lsb_pthread_attr_getschedpolicy,@function");
__asm__("_lsb_pthread_attr_getschedpolicy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getschedpolicy,pthread_attr_getschedpolicy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_getscope");
__asm__("	.type _lsb_pthread_attr_getscope,@function");
__asm__("_lsb_pthread_attr_getscope:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getscope,pthread_attr_getscope@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_init");
__asm__("	.type _lsb_pthread_attr_init,@function");
__asm__("_lsb_pthread_attr_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_init,pthread_attr_init@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_setdetachstate");
__asm__("	.type _lsb_pthread_attr_setdetachstate,@function");
__asm__("_lsb_pthread_attr_setdetachstate:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setdetachstate,pthread_attr_setdetachstate@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_setinheritsched");
__asm__("	.type _lsb_pthread_attr_setinheritsched,@function");
__asm__("_lsb_pthread_attr_setinheritsched:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setinheritsched,pthread_attr_setinheritsched@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_setschedparam");
__asm__("	.type _lsb_pthread_attr_setschedparam,@function");
__asm__("_lsb_pthread_attr_setschedparam:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setschedparam,pthread_attr_setschedparam@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_setschedpolicy");
__asm__("	.type _lsb_pthread_attr_setschedpolicy,@function");
__asm__("_lsb_pthread_attr_setschedpolicy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setschedpolicy,pthread_attr_setschedpolicy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_attr_setscope");
__asm__("	.type _lsb_pthread_attr_setscope,@function");
__asm__("_lsb_pthread_attr_setscope:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setscope,pthread_attr_setscope@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cancel");
__asm__("	.type _lsb_pthread_cancel,@function");
__asm__("_lsb_pthread_cancel:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cancel,pthread_cancel@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_broadcast");
__asm__("	.type _lsb_pthread_cond_broadcast,@function");
__asm__("_lsb_pthread_cond_broadcast:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_broadcast,pthread_cond_broadcast@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_destroy");
__asm__("	.type _lsb_pthread_cond_destroy,@function");
__asm__("_lsb_pthread_cond_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_destroy,pthread_cond_destroy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_init");
__asm__("	.type _lsb_pthread_cond_init,@function");
__asm__("_lsb_pthread_cond_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_init,pthread_cond_init@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_signal");
__asm__("	.type _lsb_pthread_cond_signal,@function");
__asm__("_lsb_pthread_cond_signal:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_signal,pthread_cond_signal@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_timedwait");
__asm__("	.type _lsb_pthread_cond_timedwait,@function");
__asm__("_lsb_pthread_cond_timedwait:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_timedwait,pthread_cond_timedwait@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_cond_wait");
__asm__("	.type _lsb_pthread_cond_wait,@function");
__asm__("_lsb_pthread_cond_wait:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_cond_wait,pthread_cond_wait@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_condattr_destroy");
__asm__("	.type _lsb_pthread_condattr_destroy,@function");
__asm__("_lsb_pthread_condattr_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_condattr_destroy,pthread_condattr_destroy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_condattr_init");
__asm__("	.type _lsb_pthread_condattr_init,@function");
__asm__("_lsb_pthread_condattr_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_condattr_init,pthread_condattr_init@@GLIBC_2.0");
__asm__(".globl pthread_create");
__asm__("	.type pthread_create,@function");
__asm__("pthread_create:");
__asm__("	ret");
__asm__(".globl _lsb_pthread_detach");
__asm__("	.type _lsb_pthread_detach,@function");
__asm__("_lsb_pthread_detach:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_detach,pthread_detach@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_equal");
__asm__("	.type _lsb_pthread_equal,@function");
__asm__("_lsb_pthread_equal:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_equal,pthread_equal@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_exit");
__asm__("	.type _lsb_pthread_exit,@function");
__asm__("_lsb_pthread_exit:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_exit,pthread_exit@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_getschedparam");
__asm__("	.type _lsb_pthread_getschedparam,@function");
__asm__("_lsb_pthread_getschedparam:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_getschedparam,pthread_getschedparam@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_getspecific");
__asm__("	.type _lsb_pthread_getspecific,@function");
__asm__("_lsb_pthread_getspecific:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_getspecific,pthread_getspecific@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_join");
__asm__("	.type _lsb_pthread_join,@function");
__asm__("_lsb_pthread_join:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_join,pthread_join@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_key_create");
__asm__("	.type _lsb_pthread_key_create,@function");
__asm__("_lsb_pthread_key_create:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_key_create,pthread_key_create@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_key_delete");
__asm__("	.type _lsb_pthread_key_delete,@function");
__asm__("_lsb_pthread_key_delete:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_key_delete,pthread_key_delete@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_kill");
__asm__("	.type _lsb_pthread_kill,@function");
__asm__("_lsb_pthread_kill:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_kill,pthread_kill@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutex_destroy");
__asm__("	.type _lsb_pthread_mutex_destroy,@function");
__asm__("_lsb_pthread_mutex_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutex_destroy,pthread_mutex_destroy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutex_init");
__asm__("	.type _lsb_pthread_mutex_init,@function");
__asm__("_lsb_pthread_mutex_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutex_init,pthread_mutex_init@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutex_lock");
__asm__("	.type _lsb_pthread_mutex_lock,@function");
__asm__("_lsb_pthread_mutex_lock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutex_lock,pthread_mutex_lock@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutex_trylock");
__asm__("	.type _lsb_pthread_mutex_trylock,@function");
__asm__("_lsb_pthread_mutex_trylock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutex_trylock,pthread_mutex_trylock@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutex_unlock");
__asm__("	.type _lsb_pthread_mutex_unlock,@function");
__asm__("_lsb_pthread_mutex_unlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutex_unlock,pthread_mutex_unlock@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_mutexattr_destroy");
__asm__("	.type _lsb_pthread_mutexattr_destroy,@function");
__asm__("_lsb_pthread_mutexattr_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutexattr_destroy,pthread_mutexattr_destroy@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_once");
__asm__("	.type _lsb_pthread_once,@function");
__asm__("_lsb_pthread_once:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_once,pthread_once@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_rwlock_destroy");
__asm__("	.type _lsb_pthread_rwlock_destroy,@function");
__asm__("_lsb_pthread_rwlock_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_destroy,pthread_rwlock_destroy@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_init");
__asm__("	.type _lsb_pthread_rwlock_init,@function");
__asm__("_lsb_pthread_rwlock_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_init,pthread_rwlock_init@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_rdlock");
__asm__("	.type _lsb_pthread_rwlock_rdlock,@function");
__asm__("_lsb_pthread_rwlock_rdlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_rdlock,pthread_rwlock_rdlock@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_tryrdlock");
__asm__("	.type _lsb_pthread_rwlock_tryrdlock,@function");
__asm__("_lsb_pthread_rwlock_tryrdlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_tryrdlock,pthread_rwlock_tryrdlock@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_trywrlock");
__asm__("	.type _lsb_pthread_rwlock_trywrlock,@function");
__asm__("_lsb_pthread_rwlock_trywrlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_trywrlock,pthread_rwlock_trywrlock@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_unlock");
__asm__("	.type _lsb_pthread_rwlock_unlock,@function");
__asm__("_lsb_pthread_rwlock_unlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_unlock,pthread_rwlock_unlock@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlock_wrlock");
__asm__("	.type _lsb_pthread_rwlock_wrlock,@function");
__asm__("_lsb_pthread_rwlock_wrlock:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlock_wrlock,pthread_rwlock_wrlock@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlockattr_destroy");
__asm__("	.type _lsb_pthread_rwlockattr_destroy,@function");
__asm__("_lsb_pthread_rwlockattr_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlockattr_destroy,pthread_rwlockattr_destroy@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlockattr_getpshared");
__asm__("	.type _lsb_pthread_rwlockattr_getpshared,@function");
__asm__("_lsb_pthread_rwlockattr_getpshared:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlockattr_getpshared,pthread_rwlockattr_getpshared@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlockattr_init");
__asm__("	.type _lsb_pthread_rwlockattr_init,@function");
__asm__("_lsb_pthread_rwlockattr_init:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlockattr_init,pthread_rwlockattr_init@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_rwlockattr_setpshared");
__asm__("	.type _lsb_pthread_rwlockattr_setpshared,@function");
__asm__("_lsb_pthread_rwlockattr_setpshared:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_rwlockattr_setpshared,pthread_rwlockattr_setpshared@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_self");
__asm__("	.type _lsb_pthread_self,@function");
__asm__("_lsb_pthread_self:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_self,pthread_self@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_setcancelstate");
__asm__("	.type _lsb_pthread_setcancelstate,@function");
__asm__("_lsb_pthread_setcancelstate:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_setcancelstate,pthread_setcancelstate@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_setcanceltype");
__asm__("	.type _lsb_pthread_setcanceltype,@function");
__asm__("_lsb_pthread_setcanceltype:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_setcanceltype,pthread_setcanceltype@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_setschedparam");
__asm__("	.type _lsb_pthread_setschedparam,@function");
__asm__("_lsb_pthread_setschedparam:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_setschedparam,pthread_setschedparam@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_setspecific");
__asm__("	.type _lsb_pthread_setspecific,@function");
__asm__("_lsb_pthread_setspecific:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_setspecific,pthread_setspecific@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_sigmask");
__asm__("	.type _lsb_pthread_sigmask,@function");
__asm__("_lsb_pthread_sigmask:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_sigmask,pthread_sigmask@@GLIBC_2.0");
__asm__(".globl _lsb_pthread_testcancel");
__asm__("	.type _lsb_pthread_testcancel,@function");
__asm__("_lsb_pthread_testcancel:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_testcancel,pthread_testcancel@@GLIBC_2.0");
__asm__(".globl _lsb_sem_close");
__asm__("	.type _lsb_sem_close,@function");
__asm__("_lsb_sem_close:");
__asm__("	ret");
__asm__(".symver _lsb_sem_close,sem_close@@GLIBC_2.1.1");
__asm__(".globl _lsb_sem_destroy");
__asm__("	.type _lsb_sem_destroy,@function");
__asm__("_lsb_sem_destroy:");
__asm__("	ret");
__asm__(".symver _lsb_sem_destroy,sem_destroy@@GLIBC_2.1");
__asm__(".globl _lsb_sem_getvalue");
__asm__("	.type _lsb_sem_getvalue,@function");
__asm__("_lsb_sem_getvalue:");
__asm__("	ret");
__asm__(".symver _lsb_sem_getvalue,sem_getvalue@@GLIBC_2.1");
__asm__(".globl _lsb_sem_init");
__asm__("	.type _lsb_sem_init,@function");
__asm__("_lsb_sem_init:");
__asm__("	ret");
__asm__(".symver _lsb_sem_init,sem_init@@GLIBC_2.1");
__asm__(".globl _lsb_sem_open");
__asm__("	.type _lsb_sem_open,@function");
__asm__("_lsb_sem_open:");
__asm__("	ret");
__asm__(".symver _lsb_sem_open,sem_open@@GLIBC_2.1.1");
__asm__(".globl _lsb_sem_post");
__asm__("	.type _lsb_sem_post,@function");
__asm__("_lsb_sem_post:");
__asm__("	ret");
__asm__(".symver _lsb_sem_post,sem_post@@GLIBC_2.1");
__asm__(".globl _lsb_sem_trywait");
__asm__("	.type _lsb_sem_trywait,@function");
__asm__("_lsb_sem_trywait:");
__asm__("	ret");
__asm__(".symver _lsb_sem_trywait,sem_trywait@@GLIBC_2.1");
__asm__(".globl _lsb_sem_unlink");
__asm__("	.type _lsb_sem_unlink,@function");
__asm__("_lsb_sem_unlink:");
__asm__("	ret");
__asm__(".symver _lsb_sem_unlink,sem_unlink@@GLIBC_2.1.1");
__asm__(".globl _lsb_sem_wait");
__asm__("	.type _lsb_sem_wait,@function");
__asm__("_lsb_sem_wait:");
__asm__("	ret");
__asm__(".symver _lsb_sem_wait,sem_wait@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_getguardsize");
__asm__("	.type _lsb_pthread_attr_getguardsize,@function");
__asm__("_lsb_pthread_attr_getguardsize:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getguardsize,pthread_attr_getguardsize@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_setguardsize");
__asm__("	.type _lsb_pthread_attr_setguardsize,@function");
__asm__("_lsb_pthread_attr_setguardsize:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setguardsize,pthread_attr_setguardsize@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_setstackaddr");
__asm__("	.type _lsb_pthread_attr_setstackaddr,@function");
__asm__("_lsb_pthread_attr_setstackaddr:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setstackaddr,pthread_attr_setstackaddr@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_getstackaddr");
__asm__("	.type _lsb_pthread_attr_getstackaddr,@function");
__asm__("_lsb_pthread_attr_getstackaddr:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getstackaddr,pthread_attr_getstackaddr@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_setstacksize");
__asm__("	.type _lsb_pthread_attr_setstacksize,@function");
__asm__("_lsb_pthread_attr_setstacksize:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_setstacksize,pthread_attr_setstacksize@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_attr_getstacksize");
__asm__("	.type _lsb_pthread_attr_getstacksize,@function");
__asm__("_lsb_pthread_attr_getstacksize:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_attr_getstacksize,pthread_attr_getstacksize@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_mutexattr_gettype");
__asm__("	.type _lsb_pthread_mutexattr_gettype,@function");
__asm__("_lsb_pthread_mutexattr_gettype:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutexattr_gettype,pthread_mutexattr_gettype@@GLIBC_2.1");
__asm__(".globl _lsb_pthread_mutexattr_settype");
__asm__("	.type _lsb_pthread_mutexattr_settype,@function");
__asm__("_lsb_pthread_mutexattr_settype:");
__asm__("	ret");
__asm__(".symver _lsb_pthread_mutexattr_settype,pthread_mutexattr_settype@@GLIBC_2.1");
__asm__(".globl sem_timedwait");
__asm__("	.type sem_timedwait,@function");
__asm__("sem_timedwait:");
__asm__("	ret");
