__asm__(".globl pthread_attr_destroy");
__asm__("	.type pthread_attr_destroy,@function");
__asm__("pthread_attr_destroy:");
__asm__("	ret");
__asm__(".globl pthread_attr_getdetachstate");
__asm__("	.type pthread_attr_getdetachstate,@function");
__asm__("pthread_attr_getdetachstate:");
__asm__("	ret");
__asm__(".globl pthread_attr_getinheritsched");
__asm__("	.type pthread_attr_getinheritsched,@function");
__asm__("pthread_attr_getinheritsched:");
__asm__("	ret");
__asm__(".globl pthread_attr_getschedparam");
__asm__("	.type pthread_attr_getschedparam,@function");
__asm__("pthread_attr_getschedparam:");
__asm__("	ret");
__asm__(".globl pthread_attr_getschedpolicy");
__asm__("	.type pthread_attr_getschedpolicy,@function");
__asm__("pthread_attr_getschedpolicy:");
__asm__("	ret");
__asm__(".globl pthread_attr_getscope");
__asm__("	.type pthread_attr_getscope,@function");
__asm__("pthread_attr_getscope:");
__asm__("	ret");
__asm__(".globl pthread_attr_init");
__asm__("	.type pthread_attr_init,@function");
__asm__("pthread_attr_init:");
__asm__("	ret");
__asm__(".globl pthread_attr_setdetachstate");
__asm__("	.type pthread_attr_setdetachstate,@function");
__asm__("pthread_attr_setdetachstate:");
__asm__("	ret");
__asm__(".globl pthread_attr_setinheritsched");
__asm__("	.type pthread_attr_setinheritsched,@function");
__asm__("pthread_attr_setinheritsched:");
__asm__("	ret");
__asm__(".globl pthread_attr_setschedparam");
__asm__("	.type pthread_attr_setschedparam,@function");
__asm__("pthread_attr_setschedparam:");
__asm__("	ret");
__asm__(".globl pthread_attr_setschedpolicy");
__asm__("	.type pthread_attr_setschedpolicy,@function");
__asm__("pthread_attr_setschedpolicy:");
__asm__("	ret");
__asm__(".globl pthread_attr_setscope");
__asm__("	.type pthread_attr_setscope,@function");
__asm__("pthread_attr_setscope:");
__asm__("	ret");
__asm__(".globl pthread_cancel");
__asm__("	.type pthread_cancel,@function");
__asm__("pthread_cancel:");
__asm__("	ret");
__asm__(".globl pthread_cond_broadcast");
__asm__("	.type pthread_cond_broadcast,@function");
__asm__("pthread_cond_broadcast:");
__asm__("	ret");
__asm__(".globl pthread_cond_destroy");
__asm__("	.type pthread_cond_destroy,@function");
__asm__("pthread_cond_destroy:");
__asm__("	ret");
__asm__(".globl pthread_cond_init");
__asm__("	.type pthread_cond_init,@function");
__asm__("pthread_cond_init:");
__asm__("	ret");
__asm__(".globl pthread_cond_signal");
__asm__("	.type pthread_cond_signal,@function");
__asm__("pthread_cond_signal:");
__asm__("	ret");
__asm__(".globl pthread_cond_timedwait");
__asm__("	.type pthread_cond_timedwait,@function");
__asm__("pthread_cond_timedwait:");
__asm__("	ret");
__asm__(".globl pthread_cond_wait");
__asm__("	.type pthread_cond_wait,@function");
__asm__("pthread_cond_wait:");
__asm__("	ret");
__asm__(".globl pthread_condattr_destroy");
__asm__("	.type pthread_condattr_destroy,@function");
__asm__("pthread_condattr_destroy:");
__asm__("	ret");
__asm__(".globl pthread_condattr_init");
__asm__("	.type pthread_condattr_init,@function");
__asm__("pthread_condattr_init:");
__asm__("	ret");
__asm__(".globl pthread_create");
__asm__("	.type pthread_create,@function");
__asm__("pthread_create:");
__asm__("	ret");
__asm__(".globl pthread_detach");
__asm__("	.type pthread_detach,@function");
__asm__("pthread_detach:");
__asm__("	ret");
__asm__(".globl pthread_equal");
__asm__("	.type pthread_equal,@function");
__asm__("pthread_equal:");
__asm__("	ret");
__asm__(".globl pthread_exit");
__asm__("	.type pthread_exit,@function");
__asm__("pthread_exit:");
__asm__("	ret");
__asm__(".globl pthread_getschedparam");
__asm__("	.type pthread_getschedparam,@function");
__asm__("pthread_getschedparam:");
__asm__("	ret");
__asm__(".globl pthread_getspecific");
__asm__("	.type pthread_getspecific,@function");
__asm__("pthread_getspecific:");
__asm__("	ret");
__asm__(".globl pthread_join");
__asm__("	.type pthread_join,@function");
__asm__("pthread_join:");
__asm__("	ret");
__asm__(".globl pthread_key_create");
__asm__("	.type pthread_key_create,@function");
__asm__("pthread_key_create:");
__asm__("	ret");
__asm__(".globl pthread_key_delete");
__asm__("	.type pthread_key_delete,@function");
__asm__("pthread_key_delete:");
__asm__("	ret");
__asm__(".globl pthread_kill");
__asm__("	.type pthread_kill,@function");
__asm__("pthread_kill:");
__asm__("	ret");
__asm__(".globl pthread_mutex_destroy");
__asm__("	.type pthread_mutex_destroy,@function");
__asm__("pthread_mutex_destroy:");
__asm__("	ret");
__asm__(".globl pthread_mutex_init");
__asm__("	.type pthread_mutex_init,@function");
__asm__("pthread_mutex_init:");
__asm__("	ret");
__asm__(".globl pthread_mutex_lock");
__asm__("	.type pthread_mutex_lock,@function");
__asm__("pthread_mutex_lock:");
__asm__("	ret");
__asm__(".globl pthread_mutex_trylock");
__asm__("	.type pthread_mutex_trylock,@function");
__asm__("pthread_mutex_trylock:");
__asm__("	ret");
__asm__(".globl pthread_mutex_unlock");
__asm__("	.type pthread_mutex_unlock,@function");
__asm__("pthread_mutex_unlock:");
__asm__("	ret");
__asm__(".globl pthread_mutexattr_destroy");
__asm__("	.type pthread_mutexattr_destroy,@function");
__asm__("pthread_mutexattr_destroy:");
__asm__("	ret");
__asm__(".globl pthread_mutexattr_init");
__asm__("	.type pthread_mutexattr_init,@function");
__asm__("pthread_mutexattr_init:");
__asm__("	ret");
__asm__(".globl pthread_once");
__asm__("	.type pthread_once,@function");
__asm__("pthread_once:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_destroy");
__asm__("	.type pthread_rwlock_destroy,@function");
__asm__("pthread_rwlock_destroy:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_init");
__asm__("	.type pthread_rwlock_init,@function");
__asm__("pthread_rwlock_init:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_rdlock");
__asm__("	.type pthread_rwlock_rdlock,@function");
__asm__("pthread_rwlock_rdlock:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_tryrdlock");
__asm__("	.type pthread_rwlock_tryrdlock,@function");
__asm__("pthread_rwlock_tryrdlock:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_trywrlock");
__asm__("	.type pthread_rwlock_trywrlock,@function");
__asm__("pthread_rwlock_trywrlock:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_unlock");
__asm__("	.type pthread_rwlock_unlock,@function");
__asm__("pthread_rwlock_unlock:");
__asm__("	ret");
__asm__(".globl pthread_rwlock_wrlock");
__asm__("	.type pthread_rwlock_wrlock,@function");
__asm__("pthread_rwlock_wrlock:");
__asm__("	ret");
__asm__(".globl pthread_rwlockattr_destroy");
__asm__("	.type pthread_rwlockattr_destroy,@function");
__asm__("pthread_rwlockattr_destroy:");
__asm__("	ret");
__asm__(".globl pthread_rwlockattr_getpshared");
__asm__("	.type pthread_rwlockattr_getpshared,@function");
__asm__("pthread_rwlockattr_getpshared:");
__asm__("	ret");
__asm__(".globl pthread_rwlockattr_init");
__asm__("	.type pthread_rwlockattr_init,@function");
__asm__("pthread_rwlockattr_init:");
__asm__("	ret");
__asm__(".globl pthread_rwlockattr_setpshared");
__asm__("	.type pthread_rwlockattr_setpshared,@function");
__asm__("pthread_rwlockattr_setpshared:");
__asm__("	ret");
__asm__(".globl pthread_self");
__asm__("	.type pthread_self,@function");
__asm__("pthread_self:");
__asm__("	ret");
__asm__(".globl pthread_setcancelstate");
__asm__("	.type pthread_setcancelstate,@function");
__asm__("pthread_setcancelstate:");
__asm__("	ret");
__asm__(".globl pthread_setcanceltype");
__asm__("	.type pthread_setcanceltype,@function");
__asm__("pthread_setcanceltype:");
__asm__("	ret");
__asm__(".globl pthread_setschedparam");
__asm__("	.type pthread_setschedparam,@function");
__asm__("pthread_setschedparam:");
__asm__("	ret");
__asm__(".globl pthread_setspecific");
__asm__("	.type pthread_setspecific,@function");
__asm__("pthread_setspecific:");
__asm__("	ret");
__asm__(".globl pthread_sigmask");
__asm__("	.type pthread_sigmask,@function");
__asm__("pthread_sigmask:");
__asm__("	ret");
__asm__(".globl pthread_testcancel");
__asm__("	.type pthread_testcancel,@function");
__asm__("pthread_testcancel:");
__asm__("	ret");
__asm__(".globl sem_close");
__asm__("	.type sem_close,@function");
__asm__("sem_close:");
__asm__("	ret");
__asm__(".globl sem_destroy");
__asm__("	.type sem_destroy,@function");
__asm__("sem_destroy:");
__asm__("	ret");
__asm__(".globl sem_getvalue");
__asm__("	.type sem_getvalue,@function");
__asm__("sem_getvalue:");
__asm__("	ret");
__asm__(".globl sem_init");
__asm__("	.type sem_init,@function");
__asm__("sem_init:");
__asm__("	ret");
__asm__(".globl sem_open");
__asm__("	.type sem_open,@function");
__asm__("sem_open:");
__asm__("	ret");
__asm__(".globl sem_post");
__asm__("	.type sem_post,@function");
__asm__("sem_post:");
__asm__("	ret");
__asm__(".globl sem_trywait");
__asm__("	.type sem_trywait,@function");
__asm__("sem_trywait:");
__asm__("	ret");
__asm__(".globl sem_unlink");
__asm__("	.type sem_unlink,@function");
__asm__("sem_unlink:");
__asm__("	ret");
__asm__(".globl sem_wait");
__asm__("	.type sem_wait,@function");
__asm__("sem_wait:");
__asm__("	ret");
__asm__(".globl pthread_attr_getguardsize");
__asm__("	.type pthread_attr_getguardsize,@function");
__asm__("pthread_attr_getguardsize:");
__asm__("	ret");
__asm__(".globl pthread_attr_setguardsize");
__asm__("	.type pthread_attr_setguardsize,@function");
__asm__("pthread_attr_setguardsize:");
__asm__("	ret");
__asm__(".globl pthread_attr_setstackaddr");
__asm__("	.type pthread_attr_setstackaddr,@function");
__asm__("pthread_attr_setstackaddr:");
__asm__("	ret");
__asm__(".globl pthread_attr_getstackaddr");
__asm__("	.type pthread_attr_getstackaddr,@function");
__asm__("pthread_attr_getstackaddr:");
__asm__("	ret");
__asm__(".globl pthread_attr_setstacksize");
__asm__("	.type pthread_attr_setstacksize,@function");
__asm__("pthread_attr_setstacksize:");
__asm__("	ret");
__asm__(".globl pthread_attr_getstacksize");
__asm__("	.type pthread_attr_getstacksize,@function");
__asm__("pthread_attr_getstacksize:");
__asm__("	ret");
__asm__(".globl pthread_mutexattr_gettype");
__asm__("	.type pthread_mutexattr_gettype,@function");
__asm__("pthread_mutexattr_gettype:");
__asm__("	ret");
__asm__(".globl pthread_mutexattr_settype");
__asm__("	.type pthread_mutexattr_settype,@function");
__asm__("pthread_mutexattr_settype:");
__asm__("	ret");
__asm__(".globl sem_timedwait");
__asm__("	.type sem_timedwait,@function");
__asm__("sem_timedwait:");
__asm__("	ret");
