__asm__(".globl _lsb_aio_read");
__asm__("	.type _lsb_aio_read,@function");
__asm__("_lsb_aio_read:");
__asm__("	ret");
__asm__(".symver _lsb_aio_read,aio_read@@GLIBC_2.1");
__asm__(".globl _lsb_aio_write");
__asm__("	.type _lsb_aio_write,@function");
__asm__("_lsb_aio_write:");
__asm__("	ret");
__asm__(".symver _lsb_aio_write,aio_write@@GLIBC_2.1");
__asm__(".globl _lsb_lio_listio");
__asm__("	.type _lsb_lio_listio,@function");
__asm__("_lsb_lio_listio:");
__asm__("	ret");
__asm__(".symver _lsb_lio_listio,lio_listio@@GLIBC_2.1");
__asm__(".globl _lsb_aio_error");
__asm__("	.type _lsb_aio_error,@function");
__asm__("_lsb_aio_error:");
__asm__("	ret");
__asm__(".symver _lsb_aio_error,aio_error@@GLIBC_2.1");
__asm__(".globl _lsb_aio_return");
__asm__("	.type _lsb_aio_return,@function");
__asm__("_lsb_aio_return:");
__asm__("	ret");
__asm__(".symver _lsb_aio_return,aio_return@@GLIBC_2.1");
__asm__(".globl _lsb_aio_cancel");
__asm__("	.type _lsb_aio_cancel,@function");
__asm__("_lsb_aio_cancel:");
__asm__("	ret");
__asm__(".symver _lsb_aio_cancel,aio_cancel@@GLIBC_2.1");
__asm__(".globl _lsb_aio_suspend");
__asm__("	.type _lsb_aio_suspend,@function");
__asm__("_lsb_aio_suspend:");
__asm__("	ret");
__asm__(".symver _lsb_aio_suspend,aio_suspend@@GLIBC_2.1");
__asm__(".globl _lsb_aio_fsync");
__asm__("	.type _lsb_aio_fsync,@function");
__asm__("_lsb_aio_fsync:");
__asm__("	ret");
__asm__(".symver _lsb_aio_fsync,aio_fsync@@GLIBC_2.1");
__asm__(".globl _lsb_aio_cancel64");
__asm__("	.type _lsb_aio_cancel64,@function");
__asm__("_lsb_aio_cancel64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_cancel64,aio_cancel64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_error64");
__asm__("	.type _lsb_aio_error64,@function");
__asm__("_lsb_aio_error64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_error64,aio_error64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_fsync64");
__asm__("	.type _lsb_aio_fsync64,@function");
__asm__("_lsb_aio_fsync64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_fsync64,aio_fsync64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_read64");
__asm__("	.type _lsb_aio_read64,@function");
__asm__("_lsb_aio_read64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_read64,aio_read64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_return64");
__asm__("	.type _lsb_aio_return64,@function");
__asm__("_lsb_aio_return64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_return64,aio_return64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_suspend64");
__asm__("	.type _lsb_aio_suspend64,@function");
__asm__("_lsb_aio_suspend64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_suspend64,aio_suspend64@@GLIBC_2.1");
__asm__(".globl _lsb_aio_write64");
__asm__("	.type _lsb_aio_write64,@function");
__asm__("_lsb_aio_write64:");
__asm__("	ret");
__asm__(".symver _lsb_aio_write64,aio_write64@@GLIBC_2.1");
__asm__(".globl clock_getcpuclockid");
__asm__("	.type clock_getcpuclockid,@function");
__asm__("clock_getcpuclockid:");
__asm__("	ret");
__asm__(".globl clock_getres");
__asm__("	.type clock_getres,@function");
__asm__("clock_getres:");
__asm__("	ret");
__asm__(".globl _lsb_clock_gettime");
__asm__("	.type _lsb_clock_gettime,@function");
__asm__("_lsb_clock_gettime:");
__asm__("	ret");
__asm__(".symver _lsb_clock_gettime,clock_gettime@@GLIBC_2.2");
__asm__(".globl clock_nanosleep");
__asm__("	.type clock_nanosleep,@function");
__asm__("clock_nanosleep:");
__asm__("	ret");
__asm__(".globl clock_settime");
__asm__("	.type clock_settime,@function");
__asm__("clock_settime:");
__asm__("	ret");
__asm__(".globl _lsb_lio_listio64");
__asm__("	.type _lsb_lio_listio64,@function");
__asm__("_lsb_lio_listio64:");
__asm__("	ret");
__asm__(".symver _lsb_lio_listio64,lio_listio64@@GLIBC_2.1");
__asm__(".globl shm_open");
__asm__("	.type shm_open,@function");
__asm__("shm_open:");
__asm__("	ret");
__asm__(".globl shm_unlink");
__asm__("	.type shm_unlink,@function");
__asm__("shm_unlink:");
__asm__("	ret");
