__asm__(".globl aio_read");
__asm__("	.type aio_read,@function");
__asm__("aio_read:");
__asm__("	ret");
__asm__(".globl aio_write");
__asm__("	.type aio_write,@function");
__asm__("aio_write:");
__asm__("	ret");
__asm__(".globl lio_listio");
__asm__("	.type lio_listio,@function");
__asm__("lio_listio:");
__asm__("	ret");
__asm__(".globl aio_error");
__asm__("	.type aio_error,@function");
__asm__("aio_error:");
__asm__("	ret");
__asm__(".globl aio_return");
__asm__("	.type aio_return,@function");
__asm__("aio_return:");
__asm__("	ret");
__asm__(".globl aio_cancel");
__asm__("	.type aio_cancel,@function");
__asm__("aio_cancel:");
__asm__("	ret");
__asm__(".globl aio_suspend");
__asm__("	.type aio_suspend,@function");
__asm__("aio_suspend:");
__asm__("	ret");
__asm__(".globl aio_fsync");
__asm__("	.type aio_fsync,@function");
__asm__("aio_fsync:");
__asm__("	ret");
__asm__(".globl aio_cancel64");
__asm__("	.type aio_cancel64,@function");
__asm__("aio_cancel64:");
__asm__("	ret");
__asm__(".globl aio_error64");
__asm__("	.type aio_error64,@function");
__asm__("aio_error64:");
__asm__("	ret");
__asm__(".globl aio_fsync64");
__asm__("	.type aio_fsync64,@function");
__asm__("aio_fsync64:");
__asm__("	ret");
__asm__(".globl aio_read64");
__asm__("	.type aio_read64,@function");
__asm__("aio_read64:");
__asm__("	ret");
__asm__(".globl aio_return64");
__asm__("	.type aio_return64,@function");
__asm__("aio_return64:");
__asm__("	ret");
__asm__(".globl aio_suspend64");
__asm__("	.type aio_suspend64,@function");
__asm__("aio_suspend64:");
__asm__("	ret");
__asm__(".globl aio_write64");
__asm__("	.type aio_write64,@function");
__asm__("aio_write64:");
__asm__("	ret");
__asm__(".globl clock_getcpuclockid");
__asm__("	.type clock_getcpuclockid,@function");
__asm__("clock_getcpuclockid:");
__asm__("	ret");
__asm__(".globl clock_getres");
__asm__("	.type clock_getres,@function");
__asm__("clock_getres:");
__asm__("	ret");
__asm__(".globl clock_gettime");
__asm__("	.type clock_gettime,@function");
__asm__("clock_gettime:");
__asm__("	ret");
__asm__(".globl clock_nanosleep");
__asm__("	.type clock_nanosleep,@function");
__asm__("clock_nanosleep:");
__asm__("	ret");
__asm__(".globl clock_settime");
__asm__("	.type clock_settime,@function");
__asm__("clock_settime:");
__asm__("	ret");
__asm__(".globl lio_listio64");
__asm__("	.type lio_listio64,@function");
__asm__("lio_listio64:");
__asm__("	ret");
__asm__(".globl shm_open");
__asm__("	.type shm_open,@function");
__asm__("shm_open:");
__asm__("	ret");
__asm__(".globl shm_unlink");
__asm__("	.type shm_unlink,@function");
__asm__("shm_unlink:");
__asm__("	ret");
