__asm__(".globl SmFreeProperty");
__asm__("	.type SmFreeProperty,@function");
__asm__("SmFreeProperty:");
__asm__("	ret");
__asm__(".globl SmFreeReasons");
__asm__("	.type SmFreeReasons,@function");
__asm__("SmFreeReasons:");
__asm__("	ret");
__asm__(".globl SmcClientID");
__asm__("	.type SmcClientID,@function");
__asm__("SmcClientID:");
__asm__("	ret");
__asm__(".globl SmcCloseConnection");
__asm__("	.type SmcCloseConnection,@function");
__asm__("SmcCloseConnection:");
__asm__("	ret");
__asm__(".globl SmcDeleteProperties");
__asm__("	.type SmcDeleteProperties,@function");
__asm__("SmcDeleteProperties:");
__asm__("	ret");
__asm__(".globl SmcGetIceConnection");
__asm__("	.type SmcGetIceConnection,@function");
__asm__("SmcGetIceConnection:");
__asm__("	ret");
__asm__(".globl SmcGetProperties");
__asm__("	.type SmcGetProperties,@function");
__asm__("SmcGetProperties:");
__asm__("	ret");
__asm__(".globl SmcInteractDone");
__asm__("	.type SmcInteractDone,@function");
__asm__("SmcInteractDone:");
__asm__("	ret");
__asm__(".globl SmcInteractRequest");
__asm__("	.type SmcInteractRequest,@function");
__asm__("SmcInteractRequest:");
__asm__("	ret");
__asm__(".globl SmcModifyCallbacks");
__asm__("	.type SmcModifyCallbacks,@function");
__asm__("SmcModifyCallbacks:");
__asm__("	ret");
__asm__(".globl SmcOpenConnection");
__asm__("	.type SmcOpenConnection,@function");
__asm__("SmcOpenConnection:");
__asm__("	ret");
__asm__(".globl SmcProtocolRevision");
__asm__("	.type SmcProtocolRevision,@function");
__asm__("SmcProtocolRevision:");
__asm__("	ret");
__asm__(".globl SmcProtocolVersion");
__asm__("	.type SmcProtocolVersion,@function");
__asm__("SmcProtocolVersion:");
__asm__("	ret");
__asm__(".globl SmcRelease");
__asm__("	.type SmcRelease,@function");
__asm__("SmcRelease:");
__asm__("	ret");
__asm__(".globl SmcRequestSaveYourself");
__asm__("	.type SmcRequestSaveYourself,@function");
__asm__("SmcRequestSaveYourself:");
__asm__("	ret");
__asm__(".globl SmcRequestSaveYourselfPhase2");
__asm__("	.type SmcRequestSaveYourselfPhase2,@function");
__asm__("SmcRequestSaveYourselfPhase2:");
__asm__("	ret");
__asm__(".globl SmcSaveYourselfDone");
__asm__("	.type SmcSaveYourselfDone,@function");
__asm__("SmcSaveYourselfDone:");
__asm__("	ret");
__asm__(".globl SmcSetErrorHandler");
__asm__("	.type SmcSetErrorHandler,@function");
__asm__("SmcSetErrorHandler:");
__asm__("	ret");
__asm__(".globl SmcSetProperties");
__asm__("	.type SmcSetProperties,@function");
__asm__("SmcSetProperties:");
__asm__("	ret");
__asm__(".globl SmcVendor");
__asm__("	.type SmcVendor,@function");
__asm__("SmcVendor:");
__asm__("	ret");
__asm__(".globl SmsCleanUp");
__asm__("	.type SmsCleanUp,@function");
__asm__("SmsCleanUp:");
__asm__("	ret");
__asm__(".globl SmsClientHostName");
__asm__("	.type SmsClientHostName,@function");
__asm__("SmsClientHostName:");
__asm__("	ret");
__asm__(".globl SmsClientID");
__asm__("	.type SmsClientID,@function");
__asm__("SmsClientID:");
__asm__("	ret");
__asm__(".globl SmsDie");
__asm__("	.type SmsDie,@function");
__asm__("SmsDie:");
__asm__("	ret");
__asm__(".globl SmsGenerateClientID");
__asm__("	.type SmsGenerateClientID,@function");
__asm__("SmsGenerateClientID:");
__asm__("	ret");
__asm__(".globl SmsGetIceConnection");
__asm__("	.type SmsGetIceConnection,@function");
__asm__("SmsGetIceConnection:");
__asm__("	ret");
__asm__(".globl SmsInitialize");
__asm__("	.type SmsInitialize,@function");
__asm__("SmsInitialize:");
__asm__("	ret");
__asm__(".globl SmsInteract");
__asm__("	.type SmsInteract,@function");
__asm__("SmsInteract:");
__asm__("	ret");
__asm__(".globl SmsProtocolRevision");
__asm__("	.type SmsProtocolRevision,@function");
__asm__("SmsProtocolRevision:");
__asm__("	ret");
__asm__(".globl SmsProtocolVersion");
__asm__("	.type SmsProtocolVersion,@function");
__asm__("SmsProtocolVersion:");
__asm__("	ret");
__asm__(".globl SmsRegisterClientReply");
__asm__("	.type SmsRegisterClientReply,@function");
__asm__("SmsRegisterClientReply:");
__asm__("	ret");
__asm__(".globl SmsReturnProperties");
__asm__("	.type SmsReturnProperties,@function");
__asm__("SmsReturnProperties:");
__asm__("	ret");
__asm__(".globl SmsSaveComplete");
__asm__("	.type SmsSaveComplete,@function");
__asm__("SmsSaveComplete:");
__asm__("	ret");
__asm__(".globl SmsSaveYourself");
__asm__("	.type SmsSaveYourself,@function");
__asm__("SmsSaveYourself:");
__asm__("	ret");
__asm__(".globl SmsSaveYourselfPhase2");
__asm__("	.type SmsSaveYourselfPhase2,@function");
__asm__("SmsSaveYourselfPhase2:");
__asm__("	ret");
__asm__(".globl SmsSetErrorHandler");
__asm__("	.type SmsSetErrorHandler,@function");
__asm__("SmsSetErrorHandler:");
__asm__("	ret");
__asm__(".globl SmsShutdownCancelled");
__asm__("	.type SmsShutdownCancelled,@function");
__asm__("SmsShutdownCancelled:");
__asm__("	ret");
