__asm__(".globl openpty");
__asm__("	.type openpty,@function");
__asm__("openpty:");
__asm__("	ret");
__asm__(".globl forkpty");
__asm__("	.type forkpty,@function");
__asm__("forkpty:");
__asm__("	ret");
__asm__(".globl login_tty");
__asm__("	.type login_tty,@function");
__asm__("login_tty:");
__asm__("	ret");
__asm__(".globl login");
__asm__("	.type login,@function");
__asm__("login:");
__asm__("	ret");
__asm__(".globl logout");
__asm__("	.type logout,@function");
__asm__("logout:");
__asm__("	ret");
__asm__(".globl logwtmp");
__asm__("	.type logwtmp,@function");
__asm__("logwtmp:");
__asm__("	ret");
