__asm__(".globl XtAddActions");
__asm__("	.type XtAddActions,@function");
__asm__("XtAddActions:");
__asm__("	ret");
__asm__(".globl XtAddCallback");
__asm__("	.type XtAddCallback,@function");
__asm__("XtAddCallback:");
__asm__("	ret");
__asm__(".globl XtAddCallbacks");
__asm__("	.type XtAddCallbacks,@function");
__asm__("XtAddCallbacks:");
__asm__("	ret");
__asm__(".globl XtAddConverter");
__asm__("	.type XtAddConverter,@function");
__asm__("XtAddConverter:");
__asm__("	ret");
__asm__(".globl XtAddEventHandler");
__asm__("	.type XtAddEventHandler,@function");
__asm__("XtAddEventHandler:");
__asm__("	ret");
__asm__(".globl XtAddExposureToRegion");
__asm__("	.type XtAddExposureToRegion,@function");
__asm__("XtAddExposureToRegion:");
__asm__("	ret");
__asm__(".globl XtAddGrab");
__asm__("	.type XtAddGrab,@function");
__asm__("XtAddGrab:");
__asm__("	ret");
__asm__(".globl XtAddInput");
__asm__("	.type XtAddInput,@function");
__asm__("XtAddInput:");
__asm__("	ret");
__asm__(".globl XtAddRawEventHandler");
__asm__("	.type XtAddRawEventHandler,@function");
__asm__("XtAddRawEventHandler:");
__asm__("	ret");
__asm__(".globl XtAddSignal");
__asm__("	.type XtAddSignal,@function");
__asm__("XtAddSignal:");
__asm__("	ret");
__asm__(".globl XtAddTimeOut");
__asm__("	.type XtAddTimeOut,@function");
__asm__("XtAddTimeOut:");
__asm__("	ret");
__asm__(".globl XtAddWorkProc");
__asm__("	.type XtAddWorkProc,@function");
__asm__("XtAddWorkProc:");
__asm__("	ret");
__asm__(".globl XtAllocateGC");
__asm__("	.type XtAllocateGC,@function");
__asm__("XtAllocateGC:");
__asm__("	ret");
__asm__(".globl XtAppAddActionHook");
__asm__("	.type XtAppAddActionHook,@function");
__asm__("XtAppAddActionHook:");
__asm__("	ret");
__asm__(".globl XtAppAddActions");
__asm__("	.type XtAppAddActions,@function");
__asm__("XtAppAddActions:");
__asm__("	ret");
__asm__(".globl XtAppAddBlockHook");
__asm__("	.type XtAppAddBlockHook,@function");
__asm__("XtAppAddBlockHook:");
__asm__("	ret");
__asm__(".globl XtAppAddConverter");
__asm__("	.type XtAppAddConverter,@function");
__asm__("XtAppAddConverter:");
__asm__("	ret");
__asm__(".globl XtAppAddInput");
__asm__("	.type XtAppAddInput,@function");
__asm__("XtAppAddInput:");
__asm__("	ret");
__asm__(".globl XtAppAddSignal");
__asm__("	.type XtAppAddSignal,@function");
__asm__("XtAppAddSignal:");
__asm__("	ret");
__asm__(".globl XtAppAddTimeOut");
__asm__("	.type XtAppAddTimeOut,@function");
__asm__("XtAppAddTimeOut:");
__asm__("	ret");
__asm__(".globl XtAppAddWorkProc");
__asm__("	.type XtAppAddWorkProc,@function");
__asm__("XtAppAddWorkProc:");
__asm__("	ret");
__asm__(".globl XtAppCreateShell");
__asm__("	.type XtAppCreateShell,@function");
__asm__("XtAppCreateShell:");
__asm__("	ret");
__asm__(".globl XtAppError");
__asm__("	.type XtAppError,@function");
__asm__("XtAppError:");
__asm__("	ret");
__asm__(".globl XtAppErrorMsg");
__asm__("	.type XtAppErrorMsg,@function");
__asm__("XtAppErrorMsg:");
__asm__("	ret");
__asm__(".globl XtAppGetErrorDatabase");
__asm__("	.type XtAppGetErrorDatabase,@function");
__asm__("XtAppGetErrorDatabase:");
__asm__("	ret");
__asm__(".globl XtAppGetErrorDatabaseText");
__asm__("	.type XtAppGetErrorDatabaseText,@function");
__asm__("XtAppGetErrorDatabaseText:");
__asm__("	ret");
__asm__(".globl XtAppGetExitFlag");
__asm__("	.type XtAppGetExitFlag,@function");
__asm__("XtAppGetExitFlag:");
__asm__("	ret");
__asm__(".globl XtAppGetSelectionTimeout");
__asm__("	.type XtAppGetSelectionTimeout,@function");
__asm__("XtAppGetSelectionTimeout:");
__asm__("	ret");
__asm__(".globl XtAppInitialize");
__asm__("	.type XtAppInitialize,@function");
__asm__("XtAppInitialize:");
__asm__("	ret");
__asm__(".globl XtAppLock");
__asm__("	.type XtAppLock,@function");
__asm__("XtAppLock:");
__asm__("	ret");
__asm__(".globl XtAppMainLoop");
__asm__("	.type XtAppMainLoop,@function");
__asm__("XtAppMainLoop:");
__asm__("	ret");
__asm__(".globl XtAppNextEvent");
__asm__("	.type XtAppNextEvent,@function");
__asm__("XtAppNextEvent:");
__asm__("	ret");
__asm__(".globl XtAppPeekEvent");
__asm__("	.type XtAppPeekEvent,@function");
__asm__("XtAppPeekEvent:");
__asm__("	ret");
__asm__(".globl XtAppPending");
__asm__("	.type XtAppPending,@function");
__asm__("XtAppPending:");
__asm__("	ret");
__asm__(".globl XtAppProcessEvent");
__asm__("	.type XtAppProcessEvent,@function");
__asm__("XtAppProcessEvent:");
__asm__("	ret");
__asm__(".globl XtAppReleaseCacheRefs");
__asm__("	.type XtAppReleaseCacheRefs,@function");
__asm__("XtAppReleaseCacheRefs:");
__asm__("	ret");
__asm__(".globl XtAppSetErrorHandler");
__asm__("	.type XtAppSetErrorHandler,@function");
__asm__("XtAppSetErrorHandler:");
__asm__("	ret");
__asm__(".globl XtAppSetErrorMsgHandler");
__asm__("	.type XtAppSetErrorMsgHandler,@function");
__asm__("XtAppSetErrorMsgHandler:");
__asm__("	ret");
__asm__(".globl XtAppSetExitFlag");
__asm__("	.type XtAppSetExitFlag,@function");
__asm__("XtAppSetExitFlag:");
__asm__("	ret");
__asm__(".globl XtAppSetFallbackResources");
__asm__("	.type XtAppSetFallbackResources,@function");
__asm__("XtAppSetFallbackResources:");
__asm__("	ret");
__asm__(".globl XtAppSetSelectionTimeout");
__asm__("	.type XtAppSetSelectionTimeout,@function");
__asm__("XtAppSetSelectionTimeout:");
__asm__("	ret");
__asm__(".globl XtAppSetTypeConverter");
__asm__("	.type XtAppSetTypeConverter,@function");
__asm__("XtAppSetTypeConverter:");
__asm__("	ret");
__asm__(".globl XtAppSetWarningHandler");
__asm__("	.type XtAppSetWarningHandler,@function");
__asm__("XtAppSetWarningHandler:");
__asm__("	ret");
__asm__(".globl XtAppSetWarningMsgHandler");
__asm__("	.type XtAppSetWarningMsgHandler,@function");
__asm__("XtAppSetWarningMsgHandler:");
__asm__("	ret");
__asm__(".globl XtAppUnlock");
__asm__("	.type XtAppUnlock,@function");
__asm__("XtAppUnlock:");
__asm__("	ret");
__asm__(".globl XtAppWarning");
__asm__("	.type XtAppWarning,@function");
__asm__("XtAppWarning:");
__asm__("	ret");
__asm__(".globl XtAppWarningMsg");
__asm__("	.type XtAppWarningMsg,@function");
__asm__("XtAppWarningMsg:");
__asm__("	ret");
__asm__(".globl XtAugmentTranslations");
__asm__("	.type XtAugmentTranslations,@function");
__asm__("XtAugmentTranslations:");
__asm__("	ret");
__asm__(".globl XtBuildEventMask");
__asm__("	.type XtBuildEventMask,@function");
__asm__("XtBuildEventMask:");
__asm__("	ret");
__asm__(".globl XtCallAcceptFocus");
__asm__("	.type XtCallAcceptFocus,@function");
__asm__("XtCallAcceptFocus:");
__asm__("	ret");
__asm__(".globl XtCallActionProc");
__asm__("	.type XtCallActionProc,@function");
__asm__("XtCallActionProc:");
__asm__("	ret");
__asm__(".globl XtCallCallbackList");
__asm__("	.type XtCallCallbackList,@function");
__asm__("XtCallCallbackList:");
__asm__("	ret");
__asm__(".globl XtCallCallbacks");
__asm__("	.type XtCallCallbacks,@function");
__asm__("XtCallCallbacks:");
__asm__("	ret");
__asm__(".globl XtCallConverter");
__asm__("	.type XtCallConverter,@function");
__asm__("XtCallConverter:");
__asm__("	ret");
__asm__(".globl XtCallbackExclusive");
__asm__("	.type XtCallbackExclusive,@function");
__asm__("XtCallbackExclusive:");
__asm__("	ret");
__asm__(".globl XtCallbackNone");
__asm__("	.type XtCallbackNone,@function");
__asm__("XtCallbackNone:");
__asm__("	ret");
__asm__(".globl XtCallbackNonexclusive");
__asm__("	.type XtCallbackNonexclusive,@function");
__asm__("XtCallbackNonexclusive:");
__asm__("	ret");
__asm__(".globl XtCallbackPopdown");
__asm__("	.type XtCallbackPopdown,@function");
__asm__("XtCallbackPopdown:");
__asm__("	ret");
__asm__(".globl XtCallbackReleaseCacheRef");
__asm__("	.type XtCallbackReleaseCacheRef,@function");
__asm__("XtCallbackReleaseCacheRef:");
__asm__("	ret");
__asm__(".globl XtCallbackReleaseCacheRefList");
__asm__("	.type XtCallbackReleaseCacheRefList,@function");
__asm__("XtCallbackReleaseCacheRefList:");
__asm__("	ret");
__asm__(".globl XtCalloc");
__asm__("	.type XtCalloc,@function");
__asm__("XtCalloc:");
__asm__("	ret");
__asm__(".globl XtCancelSelectionRequest");
__asm__("	.type XtCancelSelectionRequest,@function");
__asm__("XtCancelSelectionRequest:");
__asm__("	ret");
__asm__(".globl XtChangeManagedSet");
__asm__("	.type XtChangeManagedSet,@function");
__asm__("XtChangeManagedSet:");
__asm__("	ret");
__asm__(".globl XtClass");
__asm__("	.type XtClass,@function");
__asm__("XtClass:");
__asm__("	ret");
__asm__(".globl XtCloseDisplay");
__asm__("	.type XtCloseDisplay,@function");
__asm__("XtCloseDisplay:");
__asm__("	ret");
__asm__(".globl XtConfigureWidget");
__asm__("	.type XtConfigureWidget,@function");
__asm__("XtConfigureWidget:");
__asm__("	ret");
__asm__(".globl XtConvert");
__asm__("	.type XtConvert,@function");
__asm__("XtConvert:");
__asm__("	ret");
__asm__(".globl XtConvertAndStore");
__asm__("	.type XtConvertAndStore,@function");
__asm__("XtConvertAndStore:");
__asm__("	ret");
__asm__(".globl XtConvertCase");
__asm__("	.type XtConvertCase,@function");
__asm__("XtConvertCase:");
__asm__("	ret");
__asm__(".globl XtCreateApplicationContext");
__asm__("	.type XtCreateApplicationContext,@function");
__asm__("XtCreateApplicationContext:");
__asm__("	ret");
__asm__(".globl XtCreateApplicationShell");
__asm__("	.type XtCreateApplicationShell,@function");
__asm__("XtCreateApplicationShell:");
__asm__("	ret");
__asm__(".globl XtCreateManagedWidget");
__asm__("	.type XtCreateManagedWidget,@function");
__asm__("XtCreateManagedWidget:");
__asm__("	ret");
__asm__(".globl XtCreatePopupShell");
__asm__("	.type XtCreatePopupShell,@function");
__asm__("XtCreatePopupShell:");
__asm__("	ret");
__asm__(".globl XtCreateSelectionRequest");
__asm__("	.type XtCreateSelectionRequest,@function");
__asm__("XtCreateSelectionRequest:");
__asm__("	ret");
__asm__(".globl XtCreateWidget");
__asm__("	.type XtCreateWidget,@function");
__asm__("XtCreateWidget:");
__asm__("	ret");
__asm__(".globl XtCreateWindow");
__asm__("	.type XtCreateWindow,@function");
__asm__("XtCreateWindow:");
__asm__("	ret");
__asm__(".globl XtCvtColorToPixel");
__asm__("	.type XtCvtColorToPixel,@function");
__asm__("XtCvtColorToPixel:");
__asm__("	ret");
__asm__(".globl XtCvtIntToBool");
__asm__("	.type XtCvtIntToBool,@function");
__asm__("XtCvtIntToBool:");
__asm__("	ret");
__asm__(".globl XtCvtIntToBoolean");
__asm__("	.type XtCvtIntToBoolean,@function");
__asm__("XtCvtIntToBoolean:");
__asm__("	ret");
__asm__(".globl XtCvtIntToColor");
__asm__("	.type XtCvtIntToColor,@function");
__asm__("XtCvtIntToColor:");
__asm__("	ret");
__asm__(".globl XtCvtIntToFloat");
__asm__("	.type XtCvtIntToFloat,@function");
__asm__("XtCvtIntToFloat:");
__asm__("	ret");
__asm__(".globl XtCvtIntToFont");
__asm__("	.type XtCvtIntToFont,@function");
__asm__("XtCvtIntToFont:");
__asm__("	ret");
__asm__(".globl XtCvtIntToPixel");
__asm__("	.type XtCvtIntToPixel,@function");
__asm__("XtCvtIntToPixel:");
__asm__("	ret");
__asm__(".globl XtCvtIntToPixmap");
__asm__("	.type XtCvtIntToPixmap,@function");
__asm__("XtCvtIntToPixmap:");
__asm__("	ret");
__asm__(".globl XtCvtIntToShort");
__asm__("	.type XtCvtIntToShort,@function");
__asm__("XtCvtIntToShort:");
__asm__("	ret");
__asm__(".globl XtCvtIntToUnsignedChar");
__asm__("	.type XtCvtIntToUnsignedChar,@function");
__asm__("XtCvtIntToUnsignedChar:");
__asm__("	ret");
__asm__(".globl XtCvtStringToAcceleratorTable");
__asm__("	.type XtCvtStringToAcceleratorTable,@function");
__asm__("XtCvtStringToAcceleratorTable:");
__asm__("	ret");
__asm__(".globl XtCvtStringToAtom");
__asm__("	.type XtCvtStringToAtom,@function");
__asm__("XtCvtStringToAtom:");
__asm__("	ret");
__asm__(".globl XtCvtStringToBool");
__asm__("	.type XtCvtStringToBool,@function");
__asm__("XtCvtStringToBool:");
__asm__("	ret");
__asm__(".globl XtCvtStringToBoolean");
__asm__("	.type XtCvtStringToBoolean,@function");
__asm__("XtCvtStringToBoolean:");
__asm__("	ret");
__asm__(".globl XtCvtStringToCommandArgArray");
__asm__("	.type XtCvtStringToCommandArgArray,@function");
__asm__("XtCvtStringToCommandArgArray:");
__asm__("	ret");
__asm__(".globl XtCvtStringToCursor");
__asm__("	.type XtCvtStringToCursor,@function");
__asm__("XtCvtStringToCursor:");
__asm__("	ret");
__asm__(".globl XtCvtStringToDimension");
__asm__("	.type XtCvtStringToDimension,@function");
__asm__("XtCvtStringToDimension:");
__asm__("	ret");
__asm__(".globl XtCvtStringToDirectoryString");
__asm__("	.type XtCvtStringToDirectoryString,@function");
__asm__("XtCvtStringToDirectoryString:");
__asm__("	ret");
__asm__(".globl XtCvtStringToDisplay");
__asm__("	.type XtCvtStringToDisplay,@function");
__asm__("XtCvtStringToDisplay:");
__asm__("	ret");
__asm__(".globl XtCvtStringToFile");
__asm__("	.type XtCvtStringToFile,@function");
__asm__("XtCvtStringToFile:");
__asm__("	ret");
__asm__(".globl XtCvtStringToFloat");
__asm__("	.type XtCvtStringToFloat,@function");
__asm__("XtCvtStringToFloat:");
__asm__("	ret");
__asm__(".globl XtCvtStringToFont");
__asm__("	.type XtCvtStringToFont,@function");
__asm__("XtCvtStringToFont:");
__asm__("	ret");
__asm__(".globl XtCvtStringToFontSet");
__asm__("	.type XtCvtStringToFontSet,@function");
__asm__("XtCvtStringToFontSet:");
__asm__("	ret");
__asm__(".globl XtCvtStringToFontStruct");
__asm__("	.type XtCvtStringToFontStruct,@function");
__asm__("XtCvtStringToFontStruct:");
__asm__("	ret");
__asm__(".globl XtCvtStringToGravity");
__asm__("	.type XtCvtStringToGravity,@function");
__asm__("XtCvtStringToGravity:");
__asm__("	ret");
__asm__(".globl XtCvtStringToInitialState");
__asm__("	.type XtCvtStringToInitialState,@function");
__asm__("XtCvtStringToInitialState:");
__asm__("	ret");
__asm__(".globl XtCvtStringToInt");
__asm__("	.type XtCvtStringToInt,@function");
__asm__("XtCvtStringToInt:");
__asm__("	ret");
__asm__(".globl XtCvtStringToPixel");
__asm__("	.type XtCvtStringToPixel,@function");
__asm__("XtCvtStringToPixel:");
__asm__("	ret");
__asm__(".globl XtCvtStringToRestartStyle");
__asm__("	.type XtCvtStringToRestartStyle,@function");
__asm__("XtCvtStringToRestartStyle:");
__asm__("	ret");
__asm__(".globl XtCvtStringToShort");
__asm__("	.type XtCvtStringToShort,@function");
__asm__("XtCvtStringToShort:");
__asm__("	ret");
__asm__(".globl XtCvtStringToTranslationTable");
__asm__("	.type XtCvtStringToTranslationTable,@function");
__asm__("XtCvtStringToTranslationTable:");
__asm__("	ret");
__asm__(".globl XtCvtStringToUnsignedChar");
__asm__("	.type XtCvtStringToUnsignedChar,@function");
__asm__("XtCvtStringToUnsignedChar:");
__asm__("	ret");
__asm__(".globl XtCvtStringToVisual");
__asm__("	.type XtCvtStringToVisual,@function");
__asm__("XtCvtStringToVisual:");
__asm__("	ret");
__asm__(".globl XtDatabase");
__asm__("	.type XtDatabase,@function");
__asm__("XtDatabase:");
__asm__("	ret");
__asm__(".globl XtDestroyApplicationContext");
__asm__("	.type XtDestroyApplicationContext,@function");
__asm__("XtDestroyApplicationContext:");
__asm__("	ret");
__asm__(".globl XtDestroyGC");
__asm__("	.type XtDestroyGC,@function");
__asm__("XtDestroyGC:");
__asm__("	ret");
__asm__(".globl XtDestroyWidget");
__asm__("	.type XtDestroyWidget,@function");
__asm__("XtDestroyWidget:");
__asm__("	ret");
__asm__(".globl XtDirectConvert");
__asm__("	.type XtDirectConvert,@function");
__asm__("XtDirectConvert:");
__asm__("	ret");
__asm__(".globl XtDisownSelection");
__asm__("	.type XtDisownSelection,@function");
__asm__("XtDisownSelection:");
__asm__("	ret");
__asm__(".globl XtDispatchEvent");
__asm__("	.type XtDispatchEvent,@function");
__asm__("XtDispatchEvent:");
__asm__("	ret");
__asm__(".globl XtDispatchEventToWidget");
__asm__("	.type XtDispatchEventToWidget,@function");
__asm__("XtDispatchEventToWidget:");
__asm__("	ret");
__asm__(".globl XtDisplay");
__asm__("	.type XtDisplay,@function");
__asm__("XtDisplay:");
__asm__("	ret");
__asm__(".globl XtDisplayInitialize");
__asm__("	.type XtDisplayInitialize,@function");
__asm__("XtDisplayInitialize:");
__asm__("	ret");
__asm__(".globl XtDisplayOfObject");
__asm__("	.type XtDisplayOfObject,@function");
__asm__("XtDisplayOfObject:");
__asm__("	ret");
__asm__(".globl XtDisplayStringConversionWarning");
__asm__("	.type XtDisplayStringConversionWarning,@function");
__asm__("XtDisplayStringConversionWarning:");
__asm__("	ret");
__asm__(".globl XtDisplayToApplicationContext");
__asm__("	.type XtDisplayToApplicationContext,@function");
__asm__("XtDisplayToApplicationContext:");
__asm__("	ret");
__asm__(".globl XtError");
__asm__("	.type XtError,@function");
__asm__("XtError:");
__asm__("	ret");
__asm__(".globl XtErrorMsg");
__asm__("	.type XtErrorMsg,@function");
__asm__("XtErrorMsg:");
__asm__("	ret");
__asm__(".globl XtFindFile");
__asm__("	.type XtFindFile,@function");
__asm__("XtFindFile:");
__asm__("	ret");
__asm__(".globl XtFree");
__asm__("	.type XtFree,@function");
__asm__("XtFree:");
__asm__("	ret");
__asm__(".globl XtGetActionKeysym");
__asm__("	.type XtGetActionKeysym,@function");
__asm__("XtGetActionKeysym:");
__asm__("	ret");
__asm__(".globl XtGetActionList");
__asm__("	.type XtGetActionList,@function");
__asm__("XtGetActionList:");
__asm__("	ret");
__asm__(".globl XtGetApplicationNameAndClass");
__asm__("	.type XtGetApplicationNameAndClass,@function");
__asm__("XtGetApplicationNameAndClass:");
__asm__("	ret");
__asm__(".globl XtGetApplicationResources");
__asm__("	.type XtGetApplicationResources,@function");
__asm__("XtGetApplicationResources:");
__asm__("	ret");
__asm__(".globl XtGetClassExtension");
__asm__("	.type XtGetClassExtension,@function");
__asm__("XtGetClassExtension:");
__asm__("	ret");
__asm__(".globl XtGetConstraintResourceList");
__asm__("	.type XtGetConstraintResourceList,@function");
__asm__("XtGetConstraintResourceList:");
__asm__("	ret");
__asm__(".globl XtGetDisplays");
__asm__("	.type XtGetDisplays,@function");
__asm__("XtGetDisplays:");
__asm__("	ret");
__asm__(".globl XtGetErrorDatabase");
__asm__("	.type XtGetErrorDatabase,@function");
__asm__("XtGetErrorDatabase:");
__asm__("	ret");
__asm__(".globl XtGetErrorDatabaseText");
__asm__("	.type XtGetErrorDatabaseText,@function");
__asm__("XtGetErrorDatabaseText:");
__asm__("	ret");
__asm__(".globl XtGetGC");
__asm__("	.type XtGetGC,@function");
__asm__("XtGetGC:");
__asm__("	ret");
__asm__(".globl XtGetKeyboardFocusWidget");
__asm__("	.type XtGetKeyboardFocusWidget,@function");
__asm__("XtGetKeyboardFocusWidget:");
__asm__("	ret");
__asm__(".globl XtGetKeysymTable");
__asm__("	.type XtGetKeysymTable,@function");
__asm__("XtGetKeysymTable:");
__asm__("	ret");
__asm__(".globl XtGetMultiClickTime");
__asm__("	.type XtGetMultiClickTime,@function");
__asm__("XtGetMultiClickTime:");
__asm__("	ret");
__asm__(".globl XtGetResourceList");
__asm__("	.type XtGetResourceList,@function");
__asm__("XtGetResourceList:");
__asm__("	ret");
__asm__(".globl XtGetSelectionParameters");
__asm__("	.type XtGetSelectionParameters,@function");
__asm__("XtGetSelectionParameters:");
__asm__("	ret");
__asm__(".globl XtGetSelectionRequest");
__asm__("	.type XtGetSelectionRequest,@function");
__asm__("XtGetSelectionRequest:");
__asm__("	ret");
__asm__(".globl XtGetSelectionTimeout");
__asm__("	.type XtGetSelectionTimeout,@function");
__asm__("XtGetSelectionTimeout:");
__asm__("	ret");
__asm__(".globl XtGetSelectionValue");
__asm__("	.type XtGetSelectionValue,@function");
__asm__("XtGetSelectionValue:");
__asm__("	ret");
__asm__(".globl XtGetSelectionValueIncremental");
__asm__("	.type XtGetSelectionValueIncremental,@function");
__asm__("XtGetSelectionValueIncremental:");
__asm__("	ret");
__asm__(".globl XtGetSelectionValues");
__asm__("	.type XtGetSelectionValues,@function");
__asm__("XtGetSelectionValues:");
__asm__("	ret");
__asm__(".globl XtGetSelectionValuesIncremental");
__asm__("	.type XtGetSelectionValuesIncremental,@function");
__asm__("XtGetSelectionValuesIncremental:");
__asm__("	ret");
__asm__(".globl XtGetSubresources");
__asm__("	.type XtGetSubresources,@function");
__asm__("XtGetSubresources:");
__asm__("	ret");
__asm__(".globl XtGetSubvalues");
__asm__("	.type XtGetSubvalues,@function");
__asm__("XtGetSubvalues:");
__asm__("	ret");
__asm__(".globl XtGetValues");
__asm__("	.type XtGetValues,@function");
__asm__("XtGetValues:");
__asm__("	ret");
__asm__(".globl XtGrabButton");
__asm__("	.type XtGrabButton,@function");
__asm__("XtGrabButton:");
__asm__("	ret");
__asm__(".globl XtGrabKey");
__asm__("	.type XtGrabKey,@function");
__asm__("XtGrabKey:");
__asm__("	ret");
__asm__(".globl XtGrabKeyboard");
__asm__("	.type XtGrabKeyboard,@function");
__asm__("XtGrabKeyboard:");
__asm__("	ret");
__asm__(".globl XtGrabPointer");
__asm__("	.type XtGrabPointer,@function");
__asm__("XtGrabPointer:");
__asm__("	ret");
__asm__(".globl XtHasCallbacks");
__asm__("	.type XtHasCallbacks,@function");
__asm__("XtHasCallbacks:");
__asm__("	ret");
__asm__(".globl XtHooksOfDisplay");
__asm__("	.type XtHooksOfDisplay,@function");
__asm__("XtHooksOfDisplay:");
__asm__("	ret");
__asm__(".globl XtInitialize");
__asm__("	.type XtInitialize,@function");
__asm__("XtInitialize:");
__asm__("	ret");
__asm__(".globl XtInitializeWidgetClass");
__asm__("	.type XtInitializeWidgetClass,@function");
__asm__("XtInitializeWidgetClass:");
__asm__("	ret");
__asm__(".globl XtInsertEventHandler");
__asm__("	.type XtInsertEventHandler,@function");
__asm__("XtInsertEventHandler:");
__asm__("	ret");
__asm__(".globl XtInsertEventTypeHandler");
__asm__("	.type XtInsertEventTypeHandler,@function");
__asm__("XtInsertEventTypeHandler:");
__asm__("	ret");
__asm__(".globl XtInsertRawEventHandler");
__asm__("	.type XtInsertRawEventHandler,@function");
__asm__("XtInsertRawEventHandler:");
__asm__("	ret");
__asm__(".globl XtInstallAccelerators");
__asm__("	.type XtInstallAccelerators,@function");
__asm__("XtInstallAccelerators:");
__asm__("	ret");
__asm__(".globl XtInstallAllAccelerators");
__asm__("	.type XtInstallAllAccelerators,@function");
__asm__("XtInstallAllAccelerators:");
__asm__("	ret");
__asm__(".globl XtIsApplicationShell");
__asm__("	.type XtIsApplicationShell,@function");
__asm__("XtIsApplicationShell:");
__asm__("	ret");
__asm__(".globl XtIsComposite");
__asm__("	.type XtIsComposite,@function");
__asm__("XtIsComposite:");
__asm__("	ret");
__asm__(".globl XtIsConstraint");
__asm__("	.type XtIsConstraint,@function");
__asm__("XtIsConstraint:");
__asm__("	ret");
__asm__(".globl XtIsManaged");
__asm__("	.type XtIsManaged,@function");
__asm__("XtIsManaged:");
__asm__("	ret");
__asm__(".globl XtIsObject");
__asm__("	.type XtIsObject,@function");
__asm__("XtIsObject:");
__asm__("	ret");
__asm__(".globl XtIsOverrideShell");
__asm__("	.type XtIsOverrideShell,@function");
__asm__("XtIsOverrideShell:");
__asm__("	ret");
__asm__(".globl XtIsRealized");
__asm__("	.type XtIsRealized,@function");
__asm__("XtIsRealized:");
__asm__("	ret");
__asm__(".globl XtIsRectObj");
__asm__("	.type XtIsRectObj,@function");
__asm__("XtIsRectObj:");
__asm__("	ret");
__asm__(".globl XtIsSensitive");
__asm__("	.type XtIsSensitive,@function");
__asm__("XtIsSensitive:");
__asm__("	ret");
__asm__(".globl XtIsSessionShell");
__asm__("	.type XtIsSessionShell,@function");
__asm__("XtIsSessionShell:");
__asm__("	ret");
__asm__(".globl XtIsShell");
__asm__("	.type XtIsShell,@function");
__asm__("XtIsShell:");
__asm__("	ret");
__asm__(".globl XtIsSubclass");
__asm__("	.type XtIsSubclass,@function");
__asm__("XtIsSubclass:");
__asm__("	ret");
__asm__(".globl XtIsTopLevelShell");
__asm__("	.type XtIsTopLevelShell,@function");
__asm__("XtIsTopLevelShell:");
__asm__("	ret");
__asm__(".globl XtIsTransientShell");
__asm__("	.type XtIsTransientShell,@function");
__asm__("XtIsTransientShell:");
__asm__("	ret");
__asm__(".globl XtIsVendorShell");
__asm__("	.type XtIsVendorShell,@function");
__asm__("XtIsVendorShell:");
__asm__("	ret");
__asm__(".globl XtIsWMShell");
__asm__("	.type XtIsWMShell,@function");
__asm__("XtIsWMShell:");
__asm__("	ret");
__asm__(".globl XtIsWidget");
__asm__("	.type XtIsWidget,@function");
__asm__("XtIsWidget:");
__asm__("	ret");
__asm__(".globl XtKeysymToKeycodeList");
__asm__("	.type XtKeysymToKeycodeList,@function");
__asm__("XtKeysymToKeycodeList:");
__asm__("	ret");
__asm__(".globl XtLastEventProcessed");
__asm__("	.type XtLastEventProcessed,@function");
__asm__("XtLastEventProcessed:");
__asm__("	ret");
__asm__(".globl XtLastTimestampProcessed");
__asm__("	.type XtLastTimestampProcessed,@function");
__asm__("XtLastTimestampProcessed:");
__asm__("	ret");
__asm__(".globl XtMainLoop");
__asm__("	.type XtMainLoop,@function");
__asm__("XtMainLoop:");
__asm__("	ret");
__asm__(".globl XtMakeGeometryRequest");
__asm__("	.type XtMakeGeometryRequest,@function");
__asm__("XtMakeGeometryRequest:");
__asm__("	ret");
__asm__(".globl XtMakeResizeRequest");
__asm__("	.type XtMakeResizeRequest,@function");
__asm__("XtMakeResizeRequest:");
__asm__("	ret");
__asm__(".globl XtMalloc");
__asm__("	.type XtMalloc,@function");
__asm__("XtMalloc:");
__asm__("	ret");
__asm__(".globl XtManageChild");
__asm__("	.type XtManageChild,@function");
__asm__("XtManageChild:");
__asm__("	ret");
__asm__(".globl XtManageChildren");
__asm__("	.type XtManageChildren,@function");
__asm__("XtManageChildren:");
__asm__("	ret");
__asm__(".globl XtMapWidget");
__asm__("	.type XtMapWidget,@function");
__asm__("XtMapWidget:");
__asm__("	ret");
__asm__(".globl XtMenuPopupAction");
__asm__("	.type XtMenuPopupAction,@function");
__asm__("XtMenuPopupAction:");
__asm__("	ret");
__asm__(".globl XtMergeArgLists");
__asm__("	.type XtMergeArgLists,@function");
__asm__("XtMergeArgLists:");
__asm__("	ret");
__asm__(".globl XtMoveWidget");
__asm__("	.type XtMoveWidget,@function");
__asm__("XtMoveWidget:");
__asm__("	ret");
__asm__(".globl XtName");
__asm__("	.type XtName,@function");
__asm__("XtName:");
__asm__("	ret");
__asm__(".globl XtNameToWidget");
__asm__("	.type XtNameToWidget,@function");
__asm__("XtNameToWidget:");
__asm__("	ret");
__asm__(".globl XtNewString");
__asm__("	.type XtNewString,@function");
__asm__("XtNewString:");
__asm__("	ret");
__asm__(".globl XtNextEvent");
__asm__("	.type XtNextEvent,@function");
__asm__("XtNextEvent:");
__asm__("	ret");
__asm__(".globl XtNoticeSignal");
__asm__("	.type XtNoticeSignal,@function");
__asm__("XtNoticeSignal:");
__asm__("	ret");
__asm__(".globl XtOpenApplication");
__asm__("	.type XtOpenApplication,@function");
__asm__("XtOpenApplication:");
__asm__("	ret");
__asm__(".globl XtOpenDisplay");
__asm__("	.type XtOpenDisplay,@function");
__asm__("XtOpenDisplay:");
__asm__("	ret");
__asm__(".globl XtOverrideTranslations");
__asm__("	.type XtOverrideTranslations,@function");
__asm__("XtOverrideTranslations:");
__asm__("	ret");
__asm__(".globl XtOwnSelection");
__asm__("	.type XtOwnSelection,@function");
__asm__("XtOwnSelection:");
__asm__("	ret");
__asm__(".globl XtOwnSelectionIncremental");
__asm__("	.type XtOwnSelectionIncremental,@function");
__asm__("XtOwnSelectionIncremental:");
__asm__("	ret");
__asm__(".globl XtParent");
__asm__("	.type XtParent,@function");
__asm__("XtParent:");
__asm__("	ret");
__asm__(".globl XtParseAcceleratorTable");
__asm__("	.type XtParseAcceleratorTable,@function");
__asm__("XtParseAcceleratorTable:");
__asm__("	ret");
__asm__(".globl XtParseTranslationTable");
__asm__("	.type XtParseTranslationTable,@function");
__asm__("XtParseTranslationTable:");
__asm__("	ret");
__asm__(".globl XtPeekEvent");
__asm__("	.type XtPeekEvent,@function");
__asm__("XtPeekEvent:");
__asm__("	ret");
__asm__(".globl XtPending");
__asm__("	.type XtPending,@function");
__asm__("XtPending:");
__asm__("	ret");
__asm__(".globl XtPopdown");
__asm__("	.type XtPopdown,@function");
__asm__("XtPopdown:");
__asm__("	ret");
__asm__(".globl XtPopup");
__asm__("	.type XtPopup,@function");
__asm__("XtPopup:");
__asm__("	ret");
__asm__(".globl XtPopupSpringLoaded");
__asm__("	.type XtPopupSpringLoaded,@function");
__asm__("XtPopupSpringLoaded:");
__asm__("	ret");
__asm__(".globl XtProcessEvent");
__asm__("	.type XtProcessEvent,@function");
__asm__("XtProcessEvent:");
__asm__("	ret");
__asm__(".globl XtProcessLock");
__asm__("	.type XtProcessLock,@function");
__asm__("XtProcessLock:");
__asm__("	ret");
__asm__(".globl XtProcessUnlock");
__asm__("	.type XtProcessUnlock,@function");
__asm__("XtProcessUnlock:");
__asm__("	ret");
__asm__(".globl XtQueryGeometry");
__asm__("	.type XtQueryGeometry,@function");
__asm__("XtQueryGeometry:");
__asm__("	ret");
__asm__(".globl XtRealizeWidget");
__asm__("	.type XtRealizeWidget,@function");
__asm__("XtRealizeWidget:");
__asm__("	ret");
__asm__(".globl XtRealloc");
__asm__("	.type XtRealloc,@function");
__asm__("XtRealloc:");
__asm__("	ret");
__asm__(".globl XtRegisterCaseConverter");
__asm__("	.type XtRegisterCaseConverter,@function");
__asm__("XtRegisterCaseConverter:");
__asm__("	ret");
__asm__(".globl XtRegisterDrawable");
__asm__("	.type XtRegisterDrawable,@function");
__asm__("XtRegisterDrawable:");
__asm__("	ret");
__asm__(".globl XtRegisterExtensionSelector");
__asm__("	.type XtRegisterExtensionSelector,@function");
__asm__("XtRegisterExtensionSelector:");
__asm__("	ret");
__asm__(".globl XtRegisterGrabAction");
__asm__("	.type XtRegisterGrabAction,@function");
__asm__("XtRegisterGrabAction:");
__asm__("	ret");
__asm__(".globl XtReleaseGC");
__asm__("	.type XtReleaseGC,@function");
__asm__("XtReleaseGC:");
__asm__("	ret");
__asm__(".globl XtReleasePropertyAtom");
__asm__("	.type XtReleasePropertyAtom,@function");
__asm__("XtReleasePropertyAtom:");
__asm__("	ret");
__asm__(".globl XtRemoveActionHook");
__asm__("	.type XtRemoveActionHook,@function");
__asm__("XtRemoveActionHook:");
__asm__("	ret");
__asm__(".globl XtRemoveAllCallbacks");
__asm__("	.type XtRemoveAllCallbacks,@function");
__asm__("XtRemoveAllCallbacks:");
__asm__("	ret");
__asm__(".globl XtRemoveBlockHook");
__asm__("	.type XtRemoveBlockHook,@function");
__asm__("XtRemoveBlockHook:");
__asm__("	ret");
__asm__(".globl XtRemoveCallback");
__asm__("	.type XtRemoveCallback,@function");
__asm__("XtRemoveCallback:");
__asm__("	ret");
__asm__(".globl XtRemoveCallbacks");
__asm__("	.type XtRemoveCallbacks,@function");
__asm__("XtRemoveCallbacks:");
__asm__("	ret");
__asm__(".globl XtRemoveEventHandler");
__asm__("	.type XtRemoveEventHandler,@function");
__asm__("XtRemoveEventHandler:");
__asm__("	ret");
__asm__(".globl XtRemoveEventTypeHandler");
__asm__("	.type XtRemoveEventTypeHandler,@function");
__asm__("XtRemoveEventTypeHandler:");
__asm__("	ret");
__asm__(".globl XtRemoveGrab");
__asm__("	.type XtRemoveGrab,@function");
__asm__("XtRemoveGrab:");
__asm__("	ret");
__asm__(".globl XtRemoveInput");
__asm__("	.type XtRemoveInput,@function");
__asm__("XtRemoveInput:");
__asm__("	ret");
__asm__(".globl XtRemoveRawEventHandler");
__asm__("	.type XtRemoveRawEventHandler,@function");
__asm__("XtRemoveRawEventHandler:");
__asm__("	ret");
__asm__(".globl XtRemoveSignal");
__asm__("	.type XtRemoveSignal,@function");
__asm__("XtRemoveSignal:");
__asm__("	ret");
__asm__(".globl XtRemoveTimeOut");
__asm__("	.type XtRemoveTimeOut,@function");
__asm__("XtRemoveTimeOut:");
__asm__("	ret");
__asm__(".globl XtRemoveWorkProc");
__asm__("	.type XtRemoveWorkProc,@function");
__asm__("XtRemoveWorkProc:");
__asm__("	ret");
__asm__(".globl XtReservePropertyAtom");
__asm__("	.type XtReservePropertyAtom,@function");
__asm__("XtReservePropertyAtom:");
__asm__("	ret");
__asm__(".globl XtResizeWidget");
__asm__("	.type XtResizeWidget,@function");
__asm__("XtResizeWidget:");
__asm__("	ret");
__asm__(".globl XtResizeWindow");
__asm__("	.type XtResizeWindow,@function");
__asm__("XtResizeWindow:");
__asm__("	ret");
__asm__(".globl XtResolvePathname");
__asm__("	.type XtResolvePathname,@function");
__asm__("XtResolvePathname:");
__asm__("	ret");
__asm__(".globl XtScreen");
__asm__("	.type XtScreen,@function");
__asm__("XtScreen:");
__asm__("	ret");
__asm__(".globl XtScreenDatabase");
__asm__("	.type XtScreenDatabase,@function");
__asm__("XtScreenDatabase:");
__asm__("	ret");
__asm__(".globl XtScreenOfObject");
__asm__("	.type XtScreenOfObject,@function");
__asm__("XtScreenOfObject:");
__asm__("	ret");
__asm__(".globl XtSendSelectionRequest");
__asm__("	.type XtSendSelectionRequest,@function");
__asm__("XtSendSelectionRequest:");
__asm__("	ret");
__asm__(".globl XtSessionGetToken");
__asm__("	.type XtSessionGetToken,@function");
__asm__("XtSessionGetToken:");
__asm__("	ret");
__asm__(".globl XtSessionReturnToken");
__asm__("	.type XtSessionReturnToken,@function");
__asm__("XtSessionReturnToken:");
__asm__("	ret");
__asm__(".globl XtSetErrorHandler");
__asm__("	.type XtSetErrorHandler,@function");
__asm__("XtSetErrorHandler:");
__asm__("	ret");
__asm__(".globl XtSetErrorMsgHandler");
__asm__("	.type XtSetErrorMsgHandler,@function");
__asm__("XtSetErrorMsgHandler:");
__asm__("	ret");
__asm__(".globl XtSetEventDispatcher");
__asm__("	.type XtSetEventDispatcher,@function");
__asm__("XtSetEventDispatcher:");
__asm__("	ret");
__asm__(".globl XtSetKeyTranslator");
__asm__("	.type XtSetKeyTranslator,@function");
__asm__("XtSetKeyTranslator:");
__asm__("	ret");
__asm__(".globl XtSetKeyboardFocus");
__asm__("	.type XtSetKeyboardFocus,@function");
__asm__("XtSetKeyboardFocus:");
__asm__("	ret");
__asm__(".globl XtSetLanguageProc");
__asm__("	.type XtSetLanguageProc,@function");
__asm__("XtSetLanguageProc:");
__asm__("	ret");
__asm__(".globl XtSetMappedWhenManaged");
__asm__("	.type XtSetMappedWhenManaged,@function");
__asm__("XtSetMappedWhenManaged:");
__asm__("	ret");
__asm__(".globl XtSetMultiClickTime");
__asm__("	.type XtSetMultiClickTime,@function");
__asm__("XtSetMultiClickTime:");
__asm__("	ret");
__asm__(".globl XtSetSelectionParameters");
__asm__("	.type XtSetSelectionParameters,@function");
__asm__("XtSetSelectionParameters:");
__asm__("	ret");
__asm__(".globl XtSetSelectionTimeout");
__asm__("	.type XtSetSelectionTimeout,@function");
__asm__("XtSetSelectionTimeout:");
__asm__("	ret");
__asm__(".globl XtSetSensitive");
__asm__("	.type XtSetSensitive,@function");
__asm__("XtSetSensitive:");
__asm__("	ret");
__asm__(".globl XtSetSubvalues");
__asm__("	.type XtSetSubvalues,@function");
__asm__("XtSetSubvalues:");
__asm__("	ret");
__asm__(".globl XtSetTypeConverter");
__asm__("	.type XtSetTypeConverter,@function");
__asm__("XtSetTypeConverter:");
__asm__("	ret");
__asm__(".globl XtSetValues");
__asm__("	.type XtSetValues,@function");
__asm__("XtSetValues:");
__asm__("	ret");
__asm__(".globl XtSetWMColormapWindows");
__asm__("	.type XtSetWMColormapWindows,@function");
__asm__("XtSetWMColormapWindows:");
__asm__("	ret");
__asm__(".globl XtSetWarningHandler");
__asm__("	.type XtSetWarningHandler,@function");
__asm__("XtSetWarningHandler:");
__asm__("	ret");
__asm__(".globl XtSetWarningMsgHandler");
__asm__("	.type XtSetWarningMsgHandler,@function");
__asm__("XtSetWarningMsgHandler:");
__asm__("	ret");
__asm__(".globl XtShellStrings");
__asm__("	.type XtShellStrings,@function");
__asm__("XtShellStrings:");
__asm__("	ret");
__asm__(".globl XtStringConversionWarning");
__asm__("	.type XtStringConversionWarning,@function");
__asm__("XtStringConversionWarning:");
__asm__("	ret");
__asm__(".globl XtStrings");
__asm__("	.type XtStrings,@function");
__asm__("XtStrings:");
__asm__("	ret");
__asm__(".globl XtSuperclass");
__asm__("	.type XtSuperclass,@function");
__asm__("XtSuperclass:");
__asm__("	ret");
__asm__(".globl XtToolkitInitialize");
__asm__("	.type XtToolkitInitialize,@function");
__asm__("XtToolkitInitialize:");
__asm__("	ret");
__asm__(".globl XtToolkitThreadInitialize");
__asm__("	.type XtToolkitThreadInitialize,@function");
__asm__("XtToolkitThreadInitialize:");
__asm__("	ret");
__asm__(".globl XtTranslateCoords");
__asm__("	.type XtTranslateCoords,@function");
__asm__("XtTranslateCoords:");
__asm__("	ret");
__asm__(".globl XtTranslateKey");
__asm__("	.type XtTranslateKey,@function");
__asm__("XtTranslateKey:");
__asm__("	ret");
__asm__(".globl XtTranslateKeycode");
__asm__("	.type XtTranslateKeycode,@function");
__asm__("XtTranslateKeycode:");
__asm__("	ret");
__asm__(".globl XtUngrabButton");
__asm__("	.type XtUngrabButton,@function");
__asm__("XtUngrabButton:");
__asm__("	ret");
__asm__(".globl XtUngrabKey");
__asm__("	.type XtUngrabKey,@function");
__asm__("XtUngrabKey:");
__asm__("	ret");
__asm__(".globl XtUngrabKeyboard");
__asm__("	.type XtUngrabKeyboard,@function");
__asm__("XtUngrabKeyboard:");
__asm__("	ret");
__asm__(".globl XtUngrabPointer");
__asm__("	.type XtUngrabPointer,@function");
__asm__("XtUngrabPointer:");
__asm__("	ret");
__asm__(".globl XtUninstallTranslations");
__asm__("	.type XtUninstallTranslations,@function");
__asm__("XtUninstallTranslations:");
__asm__("	ret");
__asm__(".globl XtUnmanageChild");
__asm__("	.type XtUnmanageChild,@function");
__asm__("XtUnmanageChild:");
__asm__("	ret");
__asm__(".globl XtUnmanageChildren");
__asm__("	.type XtUnmanageChildren,@function");
__asm__("XtUnmanageChildren:");
__asm__("	ret");
__asm__(".globl XtUnmapWidget");
__asm__("	.type XtUnmapWidget,@function");
__asm__("XtUnmapWidget:");
__asm__("	ret");
__asm__(".globl XtUnrealizeWidget");
__asm__("	.type XtUnrealizeWidget,@function");
__asm__("XtUnrealizeWidget:");
__asm__("	ret");
__asm__(".globl XtUnregisterDrawable");
__asm__("	.type XtUnregisterDrawable,@function");
__asm__("XtUnregisterDrawable:");
__asm__("	ret");
__asm__(".globl XtVaAppCreateShell");
__asm__("	.type XtVaAppCreateShell,@function");
__asm__("XtVaAppCreateShell:");
__asm__("	ret");
__asm__(".globl XtVaAppInitialize");
__asm__("	.type XtVaAppInitialize,@function");
__asm__("XtVaAppInitialize:");
__asm__("	ret");
__asm__(".globl XtVaCreateArgsList");
__asm__("	.type XtVaCreateArgsList,@function");
__asm__("XtVaCreateArgsList:");
__asm__("	ret");
__asm__(".globl XtVaCreateManagedWidget");
__asm__("	.type XtVaCreateManagedWidget,@function");
__asm__("XtVaCreateManagedWidget:");
__asm__("	ret");
__asm__(".globl XtVaCreatePopupShell");
__asm__("	.type XtVaCreatePopupShell,@function");
__asm__("XtVaCreatePopupShell:");
__asm__("	ret");
__asm__(".globl XtVaCreateWidget");
__asm__("	.type XtVaCreateWidget,@function");
__asm__("XtVaCreateWidget:");
__asm__("	ret");
__asm__(".globl XtVaGetApplicationResources");
__asm__("	.type XtVaGetApplicationResources,@function");
__asm__("XtVaGetApplicationResources:");
__asm__("	ret");
__asm__(".globl XtVaGetSubresources");
__asm__("	.type XtVaGetSubresources,@function");
__asm__("XtVaGetSubresources:");
__asm__("	ret");
__asm__(".globl XtVaGetSubvalues");
__asm__("	.type XtVaGetSubvalues,@function");
__asm__("XtVaGetSubvalues:");
__asm__("	ret");
__asm__(".globl XtVaGetValues");
__asm__("	.type XtVaGetValues,@function");
__asm__("XtVaGetValues:");
__asm__("	ret");
__asm__(".globl XtVaOpenApplication");
__asm__("	.type XtVaOpenApplication,@function");
__asm__("XtVaOpenApplication:");
__asm__("	ret");
__asm__(".globl XtVaSetSubvalues");
__asm__("	.type XtVaSetSubvalues,@function");
__asm__("XtVaSetSubvalues:");
__asm__("	ret");
__asm__(".globl XtVaSetValues");
__asm__("	.type XtVaSetValues,@function");
__asm__("XtVaSetValues:");
__asm__("	ret");
__asm__(".globl XtWarning");
__asm__("	.type XtWarning,@function");
__asm__("XtWarning:");
__asm__("	ret");
__asm__(".globl XtWarningMsg");
__asm__("	.type XtWarningMsg,@function");
__asm__("XtWarningMsg:");
__asm__("	ret");
__asm__(".globl XtWidgetToApplicationContext");
__asm__("	.type XtWidgetToApplicationContext,@function");
__asm__("XtWidgetToApplicationContext:");
__asm__("	ret");
__asm__(".globl XtWindow");
__asm__("	.type XtWindow,@function");
__asm__("XtWindow:");
__asm__("	ret");
__asm__(".globl XtWindowOfObject");
__asm__("	.type XtWindowOfObject,@function");
__asm__("XtWindowOfObject:");
__asm__("	ret");
__asm__(".globl XtWindowToWidget");
__asm__("	.type XtWindowToWidget,@function");
__asm__("XtWindowToWidget:");
__asm__("	ret");
__asm__(".globl _XtCopyFromArg");
__asm__("	.type _XtCopyFromArg,@function");
__asm__("_XtCopyFromArg:");
__asm__("	ret");
__asm__(".globl _XtInherit");
__asm__("	.type _XtInherit,@function");
__asm__("_XtInherit:");
__asm__("	ret");
__asm__(".globl _XtIsSubclassOf");
__asm__("	.type _XtIsSubclassOf,@function");
__asm__("_XtIsSubclassOf:");
__asm__("	ret");
__asm__(".globl XtCXtToolkitError");
__asm__("	.type XtCXtToolkitError,@object");
__asm__("	.size XtCXtToolkitError,4");
__asm__("XtCXtToolkitError:");
__asm__("	.long 0");
__asm__(".globl _XtInheritTranslations");
__asm__("	.type _XtInheritTranslations,@object");
__asm__("	.size _XtInheritTranslations,4");
__asm__("_XtInheritTranslations:");
__asm__("	.long 0");
__asm__(".globl applicationShellWidgetClass");
__asm__("	.type applicationShellWidgetClass,@object");
__asm__("	.size applicationShellWidgetClass,4");
__asm__("applicationShellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl compositeClassRec");
__asm__("	.type compositeClassRec,@object");
__asm__("	.size compositeClassRec,4");
__asm__("compositeClassRec:");
__asm__("	.long 0");
__asm__(".globl compositeWidgetClass");
__asm__("	.type compositeWidgetClass,@object");
__asm__("	.size compositeWidgetClass,4");
__asm__("compositeWidgetClass:");
__asm__("	.long 0");
__asm__(".globl constraintClassRec");
__asm__("	.type constraintClassRec,@object");
__asm__("	.size constraintClassRec,4");
__asm__("constraintClassRec:");
__asm__("	.long 0");
__asm__(".globl constraintWidgetClass");
__asm__("	.type constraintWidgetClass,@object");
__asm__("	.size constraintWidgetClass,4");
__asm__("constraintWidgetClass:");
__asm__("	.long 0");
__asm__(".globl coreWidgetClass");
__asm__("	.type coreWidgetClass,@object");
__asm__("	.size coreWidgetClass,4");
__asm__("coreWidgetClass:");
__asm__("	.long 0");
__asm__(".globl objectClass");
__asm__("	.type objectClass,@object");
__asm__("	.size objectClass,4");
__asm__("objectClass:");
__asm__("	.long 0");
__asm__(".globl objectClassRec");
__asm__("	.type objectClassRec,@object");
__asm__("	.size objectClassRec,4");
__asm__("objectClassRec:");
__asm__("	.long 0");
__asm__(".globl overrideShellClassRec");
__asm__("	.type overrideShellClassRec,@object");
__asm__("	.size overrideShellClassRec,4");
__asm__("overrideShellClassRec:");
__asm__("	.long 0");
__asm__(".globl overrideShellWidgetClass");
__asm__("	.type overrideShellWidgetClass,@object");
__asm__("	.size overrideShellWidgetClass,4");
__asm__("overrideShellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl rectObjClass");
__asm__("	.type rectObjClass,@object");
__asm__("	.size rectObjClass,4");
__asm__("rectObjClass:");
__asm__("	.long 0");
__asm__(".globl rectObjClassRec");
__asm__("	.type rectObjClassRec,@object");
__asm__("	.size rectObjClassRec,4");
__asm__("rectObjClassRec:");
__asm__("	.long 0");
__asm__(".globl sessionShellClassRec");
__asm__("	.type sessionShellClassRec,@object");
__asm__("	.size sessionShellClassRec,4");
__asm__("sessionShellClassRec:");
__asm__("	.long 0");
__asm__(".globl sessionShellWidgetClass");
__asm__("	.type sessionShellWidgetClass,@object");
__asm__("	.size sessionShellWidgetClass,4");
__asm__("sessionShellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl shellClassRec");
__asm__("	.type shellClassRec,@object");
__asm__("	.size shellClassRec,4");
__asm__("shellClassRec:");
__asm__("	.long 0");
__asm__(".globl shellWidgetClass");
__asm__("	.type shellWidgetClass,@object");
__asm__("	.size shellWidgetClass,4");
__asm__("shellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl topLevelShellClassRec");
__asm__("	.type topLevelShellClassRec,@object");
__asm__("	.size topLevelShellClassRec,4");
__asm__("topLevelShellClassRec:");
__asm__("	.long 0");
__asm__(".globl topLevelShellWidgetClass");
__asm__("	.type topLevelShellWidgetClass,@object");
__asm__("	.size topLevelShellWidgetClass,4");
__asm__("topLevelShellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl transientShellClassRec");
__asm__("	.type transientShellClassRec,@object");
__asm__("	.size transientShellClassRec,4");
__asm__("transientShellClassRec:");
__asm__("	.long 0");
__asm__(".globl transientShellWidgetClass");
__asm__("	.type transientShellWidgetClass,@object");
__asm__("	.size transientShellWidgetClass,4");
__asm__("transientShellWidgetClass:");
__asm__("	.long 0");
__asm__(".globl widgetClass");
__asm__("	.type widgetClass,@object");
__asm__("	.size widgetClass,4");
__asm__("widgetClass:");
__asm__("	.long 0");
__asm__(".globl widgetClassRec");
__asm__("	.type widgetClassRec,@object");
__asm__("	.size widgetClassRec,4");
__asm__("widgetClassRec:");
__asm__("	.long 0");
__asm__(".globl wmShellClassRec");
__asm__("	.type wmShellClassRec,@object");
__asm__("	.size wmShellClassRec,4");
__asm__("wmShellClassRec:");
__asm__("	.long 0");
__asm__(".globl wmShellWidgetClass");
__asm__("	.type wmShellWidgetClass,@object");
__asm__("	.size wmShellWidgetClass,4");
__asm__("wmShellWidgetClass:");
__asm__("	.long 0");
