__asm__(".globl XMITMiscGetBugMode");
__asm__("	.type XMITMiscGetBugMode,@function");
__asm__("XMITMiscGetBugMode:");
__asm__("	ret");
__asm__(".globl XMITMiscQueryExtension");
__asm__("	.type XMITMiscQueryExtension,@function");
__asm__("XMITMiscQueryExtension:");
__asm__("	ret");
__asm__(".globl XMITMiscSetBugMode");
__asm__("	.type XMITMiscSetBugMode,@function");
__asm__("XMITMiscSetBugMode:");
__asm__("	ret");
__asm__(".globl XShapeCombineMask");
__asm__("	.type XShapeCombineMask,@function");
__asm__("XShapeCombineMask:");
__asm__("	ret");
__asm__(".globl XShapeCombineRectangles");
__asm__("	.type XShapeCombineRectangles,@function");
__asm__("XShapeCombineRectangles:");
__asm__("	ret");
__asm__(".globl XShapeCombineRegion");
__asm__("	.type XShapeCombineRegion,@function");
__asm__("XShapeCombineRegion:");
__asm__("	ret");
__asm__(".globl XShapeCombineShape");
__asm__("	.type XShapeCombineShape,@function");
__asm__("XShapeCombineShape:");
__asm__("	ret");
__asm__(".globl XShapeGetRectangles");
__asm__("	.type XShapeGetRectangles,@function");
__asm__("XShapeGetRectangles:");
__asm__("	ret");
__asm__(".globl XShapeInputSelected");
__asm__("	.type XShapeInputSelected,@function");
__asm__("XShapeInputSelected:");
__asm__("	ret");
__asm__(".globl XShapeOffsetShape");
__asm__("	.type XShapeOffsetShape,@function");
__asm__("XShapeOffsetShape:");
__asm__("	ret");
__asm__(".globl XShapeQueryExtension");
__asm__("	.type XShapeQueryExtension,@function");
__asm__("XShapeQueryExtension:");
__asm__("	ret");
__asm__(".globl XShapeQueryExtents");
__asm__("	.type XShapeQueryExtents,@function");
__asm__("XShapeQueryExtents:");
__asm__("	ret");
__asm__(".globl XShapeQueryVersion");
__asm__("	.type XShapeQueryVersion,@function");
__asm__("XShapeQueryVersion:");
__asm__("	ret");
__asm__(".globl XShapeSelectInput");
__asm__("	.type XShapeSelectInput,@function");
__asm__("XShapeSelectInput:");
__asm__("	ret");
__asm__(".globl XShmAttach");
__asm__("	.type XShmAttach,@function");
__asm__("XShmAttach:");
__asm__("	ret");
__asm__(".globl XShmCreateImage");
__asm__("	.type XShmCreateImage,@function");
__asm__("XShmCreateImage:");
__asm__("	ret");
__asm__(".globl XShmCreatePixmap");
__asm__("	.type XShmCreatePixmap,@function");
__asm__("XShmCreatePixmap:");
__asm__("	ret");
__asm__(".globl XShmDetach");
__asm__("	.type XShmDetach,@function");
__asm__("XShmDetach:");
__asm__("	ret");
__asm__(".globl XShmGetEventBase");
__asm__("	.type XShmGetEventBase,@function");
__asm__("XShmGetEventBase:");
__asm__("	ret");
__asm__(".globl XShmGetImage");
__asm__("	.type XShmGetImage,@function");
__asm__("XShmGetImage:");
__asm__("	ret");
__asm__(".globl XShmPixmapFormat");
__asm__("	.type XShmPixmapFormat,@function");
__asm__("XShmPixmapFormat:");
__asm__("	ret");
__asm__(".globl XShmPutImage");
__asm__("	.type XShmPutImage,@function");
__asm__("XShmPutImage:");
__asm__("	ret");
__asm__(".globl XShmQueryExtension");
__asm__("	.type XShmQueryExtension,@function");
__asm__("XShmQueryExtension:");
__asm__("	ret");
__asm__(".globl XShmQueryVersion");
__asm__("	.type XShmQueryVersion,@function");
__asm__("XShmQueryVersion:");
__asm__("	ret");
__asm__(".globl XSyncAwait");
__asm__("	.type XSyncAwait,@function");
__asm__("XSyncAwait:");
__asm__("	ret");
__asm__(".globl XSyncChangeAlarm");
__asm__("	.type XSyncChangeAlarm,@function");
__asm__("XSyncChangeAlarm:");
__asm__("	ret");
__asm__(".globl XSyncChangeCounter");
__asm__("	.type XSyncChangeCounter,@function");
__asm__("XSyncChangeCounter:");
__asm__("	ret");
__asm__(".globl XSyncCreateAlarm");
__asm__("	.type XSyncCreateAlarm,@function");
__asm__("XSyncCreateAlarm:");
__asm__("	ret");
__asm__(".globl XSyncCreateCounter");
__asm__("	.type XSyncCreateCounter,@function");
__asm__("XSyncCreateCounter:");
__asm__("	ret");
__asm__(".globl XSyncDestroyAlarm");
__asm__("	.type XSyncDestroyAlarm,@function");
__asm__("XSyncDestroyAlarm:");
__asm__("	ret");
__asm__(".globl XSyncDestroyCounter");
__asm__("	.type XSyncDestroyCounter,@function");
__asm__("XSyncDestroyCounter:");
__asm__("	ret");
__asm__(".globl XSyncFreeSystemCounterList");
__asm__("	.type XSyncFreeSystemCounterList,@function");
__asm__("XSyncFreeSystemCounterList:");
__asm__("	ret");
__asm__(".globl XSyncGetPriority");
__asm__("	.type XSyncGetPriority,@function");
__asm__("XSyncGetPriority:");
__asm__("	ret");
__asm__(".globl XSyncInitialize");
__asm__("	.type XSyncInitialize,@function");
__asm__("XSyncInitialize:");
__asm__("	ret");
__asm__(".globl XSyncIntToValue");
__asm__("	.type XSyncIntToValue,@function");
__asm__("XSyncIntToValue:");
__asm__("	ret");
__asm__(".globl XSyncIntsToValue");
__asm__("	.type XSyncIntsToValue,@function");
__asm__("XSyncIntsToValue:");
__asm__("	ret");
__asm__(".globl XSyncListSystemCounters");
__asm__("	.type XSyncListSystemCounters,@function");
__asm__("XSyncListSystemCounters:");
__asm__("	ret");
__asm__(".globl XSyncMaxValue");
__asm__("	.type XSyncMaxValue,@function");
__asm__("XSyncMaxValue:");
__asm__("	ret");
__asm__(".globl XSyncMinValue");
__asm__("	.type XSyncMinValue,@function");
__asm__("XSyncMinValue:");
__asm__("	ret");
__asm__(".globl XSyncQueryAlarm");
__asm__("	.type XSyncQueryAlarm,@function");
__asm__("XSyncQueryAlarm:");
__asm__("	ret");
__asm__(".globl XSyncQueryCounter");
__asm__("	.type XSyncQueryCounter,@function");
__asm__("XSyncQueryCounter:");
__asm__("	ret");
__asm__(".globl XSyncQueryExtension");
__asm__("	.type XSyncQueryExtension,@function");
__asm__("XSyncQueryExtension:");
__asm__("	ret");
__asm__(".globl XSyncSetCounter");
__asm__("	.type XSyncSetCounter,@function");
__asm__("XSyncSetCounter:");
__asm__("	ret");
__asm__(".globl XSyncSetPriority");
__asm__("	.type XSyncSetPriority,@function");
__asm__("XSyncSetPriority:");
__asm__("	ret");
__asm__(".globl XSyncValueAdd");
__asm__("	.type XSyncValueAdd,@function");
__asm__("XSyncValueAdd:");
__asm__("	ret");
__asm__(".globl XSyncValueEqual");
__asm__("	.type XSyncValueEqual,@function");
__asm__("XSyncValueEqual:");
__asm__("	ret");
__asm__(".globl XSyncValueGreaterOrEqual");
__asm__("	.type XSyncValueGreaterOrEqual,@function");
__asm__("XSyncValueGreaterOrEqual:");
__asm__("	ret");
__asm__(".globl XSyncValueGreaterThan");
__asm__("	.type XSyncValueGreaterThan,@function");
__asm__("XSyncValueGreaterThan:");
__asm__("	ret");
__asm__(".globl XSyncValueHigh32");
__asm__("	.type XSyncValueHigh32,@function");
__asm__("XSyncValueHigh32:");
__asm__("	ret");
__asm__(".globl XSyncValueIsNegative");
__asm__("	.type XSyncValueIsNegative,@function");
__asm__("XSyncValueIsNegative:");
__asm__("	ret");
__asm__(".globl XSyncValueIsPositive");
__asm__("	.type XSyncValueIsPositive,@function");
__asm__("XSyncValueIsPositive:");
__asm__("	ret");
__asm__(".globl XSyncValueIsZero");
__asm__("	.type XSyncValueIsZero,@function");
__asm__("XSyncValueIsZero:");
__asm__("	ret");
__asm__(".globl XSyncValueLessOrEqual");
__asm__("	.type XSyncValueLessOrEqual,@function");
__asm__("XSyncValueLessOrEqual:");
__asm__("	ret");
__asm__(".globl XSyncValueLessThan");
__asm__("	.type XSyncValueLessThan,@function");
__asm__("XSyncValueLessThan:");
__asm__("	ret");
__asm__(".globl XSyncValueLow32");
__asm__("	.type XSyncValueLow32,@function");
__asm__("XSyncValueLow32:");
__asm__("	ret");
__asm__(".globl XSyncValueSubtract");
__asm__("	.type XSyncValueSubtract,@function");
__asm__("XSyncValueSubtract:");
__asm__("	ret");
__asm__(".globl XagCreateAssociation");
__asm__("	.type XagCreateAssociation,@function");
__asm__("XagCreateAssociation:");
__asm__("	ret");
__asm__(".globl XagCreateEmbeddedApplicationGroup");
__asm__("	.type XagCreateEmbeddedApplicationGroup,@function");
__asm__("XagCreateEmbeddedApplicationGroup:");
__asm__("	ret");
__asm__(".globl XagCreateNonembeddedApplicationGroup");
__asm__("	.type XagCreateNonembeddedApplicationGroup,@function");
__asm__("XagCreateNonembeddedApplicationGroup:");
__asm__("	ret");
__asm__(".globl XagDestroyApplicationGroup");
__asm__("	.type XagDestroyApplicationGroup,@function");
__asm__("XagDestroyApplicationGroup:");
__asm__("	ret");
__asm__(".globl XagDestroyAssociation");
__asm__("	.type XagDestroyAssociation,@function");
__asm__("XagDestroyAssociation:");
__asm__("	ret");
__asm__(".globl XagGetApplicationGroupAttributes");
__asm__("	.type XagGetApplicationGroupAttributes,@function");
__asm__("XagGetApplicationGroupAttributes:");
__asm__("	ret");
__asm__(".globl XagQueryApplicationGroup");
__asm__("	.type XagQueryApplicationGroup,@function");
__asm__("XagQueryApplicationGroup:");
__asm__("	ret");
__asm__(".globl XagQueryVersion");
__asm__("	.type XagQueryVersion,@function");
__asm__("XagQueryVersion:");
__asm__("	ret");
__asm__(".globl XdbeAllocateBackBufferName");
__asm__("	.type XdbeAllocateBackBufferName,@function");
__asm__("XdbeAllocateBackBufferName:");
__asm__("	ret");
__asm__(".globl XdbeBeginIdiom");
__asm__("	.type XdbeBeginIdiom,@function");
__asm__("XdbeBeginIdiom:");
__asm__("	ret");
__asm__(".globl XdbeDeallocateBackBufferName");
__asm__("	.type XdbeDeallocateBackBufferName,@function");
__asm__("XdbeDeallocateBackBufferName:");
__asm__("	ret");
__asm__(".globl XdbeEndIdiom");
__asm__("	.type XdbeEndIdiom,@function");
__asm__("XdbeEndIdiom:");
__asm__("	ret");
__asm__(".globl XdbeFreeVisualInfo");
__asm__("	.type XdbeFreeVisualInfo,@function");
__asm__("XdbeFreeVisualInfo:");
__asm__("	ret");
__asm__(".globl XdbeGetBackBufferAttributes");
__asm__("	.type XdbeGetBackBufferAttributes,@function");
__asm__("XdbeGetBackBufferAttributes:");
__asm__("	ret");
__asm__(".globl XdbeGetVisualInfo");
__asm__("	.type XdbeGetVisualInfo,@function");
__asm__("XdbeGetVisualInfo:");
__asm__("	ret");
__asm__(".globl XdbeQueryExtension");
__asm__("	.type XdbeQueryExtension,@function");
__asm__("XdbeQueryExtension:");
__asm__("	ret");
__asm__(".globl XdbeSwapBuffers");
__asm__("	.type XdbeSwapBuffers,@function");
__asm__("XdbeSwapBuffers:");
__asm__("	ret");
__asm__(".globl XmbufChangeBufferAttributes");
__asm__("	.type XmbufChangeBufferAttributes,@function");
__asm__("XmbufChangeBufferAttributes:");
__asm__("	ret");
__asm__(".globl XmbufChangeWindowAttributes");
__asm__("	.type XmbufChangeWindowAttributes,@function");
__asm__("XmbufChangeWindowAttributes:");
__asm__("	ret");
__asm__(".globl XmbufClearBufferArea");
__asm__("	.type XmbufClearBufferArea,@function");
__asm__("XmbufClearBufferArea:");
__asm__("	ret");
__asm__(".globl XmbufCreateBuffers");
__asm__("	.type XmbufCreateBuffers,@function");
__asm__("XmbufCreateBuffers:");
__asm__("	ret");
__asm__(".globl XmbufCreateStereoWindow");
__asm__("	.type XmbufCreateStereoWindow,@function");
__asm__("XmbufCreateStereoWindow:");
__asm__("	ret");
__asm__(".globl XmbufDestroyBuffers");
__asm__("	.type XmbufDestroyBuffers,@function");
__asm__("XmbufDestroyBuffers:");
__asm__("	ret");
__asm__(".globl XmbufDisplayBuffers");
__asm__("	.type XmbufDisplayBuffers,@function");
__asm__("XmbufDisplayBuffers:");
__asm__("	ret");
__asm__(".globl XmbufGetBufferAttributes");
__asm__("	.type XmbufGetBufferAttributes,@function");
__asm__("XmbufGetBufferAttributes:");
__asm__("	ret");
__asm__(".globl XmbufGetScreenInfo");
__asm__("	.type XmbufGetScreenInfo,@function");
__asm__("XmbufGetScreenInfo:");
__asm__("	ret");
__asm__(".globl XmbufGetVersion");
__asm__("	.type XmbufGetVersion,@function");
__asm__("XmbufGetVersion:");
__asm__("	ret");
__asm__(".globl XmbufGetWindowAttributes");
__asm__("	.type XmbufGetWindowAttributes,@function");
__asm__("XmbufGetWindowAttributes:");
__asm__("	ret");
__asm__(".globl XmbufQueryExtension");
__asm__("	.type XmbufQueryExtension,@function");
__asm__("XmbufQueryExtension:");
__asm__("	ret");
