__asm__(".globl XActivateScreenSaver");
__asm__("	.type XActivateScreenSaver,@function");
__asm__("XActivateScreenSaver:");
__asm__("	ret");
__asm__(".globl XAddConnectionWatch");
__asm__("	.type XAddConnectionWatch,@function");
__asm__("XAddConnectionWatch:");
__asm__("	ret");
__asm__(".globl XAddExtension");
__asm__("	.type XAddExtension,@function");
__asm__("XAddExtension:");
__asm__("	ret");
__asm__(".globl XAddHost");
__asm__("	.type XAddHost,@function");
__asm__("XAddHost:");
__asm__("	ret");
__asm__(".globl XAddHosts");
__asm__("	.type XAddHosts,@function");
__asm__("XAddHosts:");
__asm__("	ret");
__asm__(".globl XAddPixel");
__asm__("	.type XAddPixel,@function");
__asm__("XAddPixel:");
__asm__("	ret");
__asm__(".globl XAddToExtensionList");
__asm__("	.type XAddToExtensionList,@function");
__asm__("XAddToExtensionList:");
__asm__("	ret");
__asm__(".globl XAddToSaveSet");
__asm__("	.type XAddToSaveSet,@function");
__asm__("XAddToSaveSet:");
__asm__("	ret");
__asm__(".globl XAllPlanes");
__asm__("	.type XAllPlanes,@function");
__asm__("XAllPlanes:");
__asm__("	ret");
__asm__(".globl XAllocClassHint");
__asm__("	.type XAllocClassHint,@function");
__asm__("XAllocClassHint:");
__asm__("	ret");
__asm__(".globl XAllocColor");
__asm__("	.type XAllocColor,@function");
__asm__("XAllocColor:");
__asm__("	ret");
__asm__(".globl XAllocColorCells");
__asm__("	.type XAllocColorCells,@function");
__asm__("XAllocColorCells:");
__asm__("	ret");
__asm__(".globl XAllocColorPlanes");
__asm__("	.type XAllocColorPlanes,@function");
__asm__("XAllocColorPlanes:");
__asm__("	ret");
__asm__(".globl XAllocIconSize");
__asm__("	.type XAllocIconSize,@function");
__asm__("XAllocIconSize:");
__asm__("	ret");
__asm__(".globl XAllocNamedColor");
__asm__("	.type XAllocNamedColor,@function");
__asm__("XAllocNamedColor:");
__asm__("	ret");
__asm__(".globl XAllocSizeHints");
__asm__("	.type XAllocSizeHints,@function");
__asm__("XAllocSizeHints:");
__asm__("	ret");
__asm__(".globl XAllocStandardColormap");
__asm__("	.type XAllocStandardColormap,@function");
__asm__("XAllocStandardColormap:");
__asm__("	ret");
__asm__(".globl XAllocWMHints");
__asm__("	.type XAllocWMHints,@function");
__asm__("XAllocWMHints:");
__asm__("	ret");
__asm__(".globl XAllowEvents");
__asm__("	.type XAllowEvents,@function");
__asm__("XAllowEvents:");
__asm__("	ret");
__asm__(".globl XAutoRepeatOff");
__asm__("	.type XAutoRepeatOff,@function");
__asm__("XAutoRepeatOff:");
__asm__("	ret");
__asm__(".globl XAutoRepeatOn");
__asm__("	.type XAutoRepeatOn,@function");
__asm__("XAutoRepeatOn:");
__asm__("	ret");
__asm__(".globl XBaseFontNameListOfFontSet");
__asm__("	.type XBaseFontNameListOfFontSet,@function");
__asm__("XBaseFontNameListOfFontSet:");
__asm__("	ret");
__asm__(".globl XBell");
__asm__("	.type XBell,@function");
__asm__("XBell:");
__asm__("	ret");
__asm__(".globl XBitmapBitOrder");
__asm__("	.type XBitmapBitOrder,@function");
__asm__("XBitmapBitOrder:");
__asm__("	ret");
__asm__(".globl XBitmapPad");
__asm__("	.type XBitmapPad,@function");
__asm__("XBitmapPad:");
__asm__("	ret");
__asm__(".globl XBitmapUnit");
__asm__("	.type XBitmapUnit,@function");
__asm__("XBitmapUnit:");
__asm__("	ret");
__asm__(".globl XBlackPixel");
__asm__("	.type XBlackPixel,@function");
__asm__("XBlackPixel:");
__asm__("	ret");
__asm__(".globl XBlackPixelOfScreen");
__asm__("	.type XBlackPixelOfScreen,@function");
__asm__("XBlackPixelOfScreen:");
__asm__("	ret");
__asm__(".globl XCellsOfScreen");
__asm__("	.type XCellsOfScreen,@function");
__asm__("XCellsOfScreen:");
__asm__("	ret");
__asm__(".globl XChangeActivePointerGrab");
__asm__("	.type XChangeActivePointerGrab,@function");
__asm__("XChangeActivePointerGrab:");
__asm__("	ret");
__asm__(".globl XChangeGC");
__asm__("	.type XChangeGC,@function");
__asm__("XChangeGC:");
__asm__("	ret");
__asm__(".globl XChangeKeyboardControl");
__asm__("	.type XChangeKeyboardControl,@function");
__asm__("XChangeKeyboardControl:");
__asm__("	ret");
__asm__(".globl XChangeKeyboardMapping");
__asm__("	.type XChangeKeyboardMapping,@function");
__asm__("XChangeKeyboardMapping:");
__asm__("	ret");
__asm__(".globl XChangePointerControl");
__asm__("	.type XChangePointerControl,@function");
__asm__("XChangePointerControl:");
__asm__("	ret");
__asm__(".globl XChangeProperty");
__asm__("	.type XChangeProperty,@function");
__asm__("XChangeProperty:");
__asm__("	ret");
__asm__(".globl XChangeSaveSet");
__asm__("	.type XChangeSaveSet,@function");
__asm__("XChangeSaveSet:");
__asm__("	ret");
__asm__(".globl XChangeWindowAttributes");
__asm__("	.type XChangeWindowAttributes,@function");
__asm__("XChangeWindowAttributes:");
__asm__("	ret");
__asm__(".globl XCheckIfEvent");
__asm__("	.type XCheckIfEvent,@function");
__asm__("XCheckIfEvent:");
__asm__("	ret");
__asm__(".globl XCheckMaskEvent");
__asm__("	.type XCheckMaskEvent,@function");
__asm__("XCheckMaskEvent:");
__asm__("	ret");
__asm__(".globl XCheckTypedEvent");
__asm__("	.type XCheckTypedEvent,@function");
__asm__("XCheckTypedEvent:");
__asm__("	ret");
__asm__(".globl XCheckTypedWindowEvent");
__asm__("	.type XCheckTypedWindowEvent,@function");
__asm__("XCheckTypedWindowEvent:");
__asm__("	ret");
__asm__(".globl XCheckWindowEvent");
__asm__("	.type XCheckWindowEvent,@function");
__asm__("XCheckWindowEvent:");
__asm__("	ret");
__asm__(".globl XCirculateSubwindows");
__asm__("	.type XCirculateSubwindows,@function");
__asm__("XCirculateSubwindows:");
__asm__("	ret");
__asm__(".globl XCirculateSubwindowsDown");
__asm__("	.type XCirculateSubwindowsDown,@function");
__asm__("XCirculateSubwindowsDown:");
__asm__("	ret");
__asm__(".globl XCirculateSubwindowsUp");
__asm__("	.type XCirculateSubwindowsUp,@function");
__asm__("XCirculateSubwindowsUp:");
__asm__("	ret");
__asm__(".globl XClearArea");
__asm__("	.type XClearArea,@function");
__asm__("XClearArea:");
__asm__("	ret");
__asm__(".globl XClearWindow");
__asm__("	.type XClearWindow,@function");
__asm__("XClearWindow:");
__asm__("	ret");
__asm__(".globl XClipBox");
__asm__("	.type XClipBox,@function");
__asm__("XClipBox:");
__asm__("	ret");
__asm__(".globl XCloseDisplay");
__asm__("	.type XCloseDisplay,@function");
__asm__("XCloseDisplay:");
__asm__("	ret");
__asm__(".globl XCloseIM");
__asm__("	.type XCloseIM,@function");
__asm__("XCloseIM:");
__asm__("	ret");
__asm__(".globl XCloseOM");
__asm__("	.type XCloseOM,@function");
__asm__("XCloseOM:");
__asm__("	ret");
__asm__(".globl XConfigureWindow");
__asm__("	.type XConfigureWindow,@function");
__asm__("XConfigureWindow:");
__asm__("	ret");
__asm__(".globl XConnectionNumber");
__asm__("	.type XConnectionNumber,@function");
__asm__("XConnectionNumber:");
__asm__("	ret");
__asm__(".globl XContextDependentDrawing");
__asm__("	.type XContextDependentDrawing,@function");
__asm__("XContextDependentDrawing:");
__asm__("	ret");
__asm__(".globl XContextualDrawing");
__asm__("	.type XContextualDrawing,@function");
__asm__("XContextualDrawing:");
__asm__("	ret");
__asm__(".globl XConvertCase");
__asm__("	.type XConvertCase,@function");
__asm__("XConvertCase:");
__asm__("	ret");
__asm__(".globl XConvertSelection");
__asm__("	.type XConvertSelection,@function");
__asm__("XConvertSelection:");
__asm__("	ret");
__asm__(".globl XCopyArea");
__asm__("	.type XCopyArea,@function");
__asm__("XCopyArea:");
__asm__("	ret");
__asm__(".globl XCopyColormapAndFree");
__asm__("	.type XCopyColormapAndFree,@function");
__asm__("XCopyColormapAndFree:");
__asm__("	ret");
__asm__(".globl XCopyGC");
__asm__("	.type XCopyGC,@function");
__asm__("XCopyGC:");
__asm__("	ret");
__asm__(".globl XCopyPlane");
__asm__("	.type XCopyPlane,@function");
__asm__("XCopyPlane:");
__asm__("	ret");
__asm__(".globl XCreateBitmapFromData");
__asm__("	.type XCreateBitmapFromData,@function");
__asm__("XCreateBitmapFromData:");
__asm__("	ret");
__asm__(".globl XCreateColormap");
__asm__("	.type XCreateColormap,@function");
__asm__("XCreateColormap:");
__asm__("	ret");
__asm__(".globl XCreateFontCursor");
__asm__("	.type XCreateFontCursor,@function");
__asm__("XCreateFontCursor:");
__asm__("	ret");
__asm__(".globl XCreateFontSet");
__asm__("	.type XCreateFontSet,@function");
__asm__("XCreateFontSet:");
__asm__("	ret");
__asm__(".globl XCreateGC");
__asm__("	.type XCreateGC,@function");
__asm__("XCreateGC:");
__asm__("	ret");
__asm__(".globl XCreateGlyphCursor");
__asm__("	.type XCreateGlyphCursor,@function");
__asm__("XCreateGlyphCursor:");
__asm__("	ret");
__asm__(".globl XCreateIC");
__asm__("	.type XCreateIC,@function");
__asm__("XCreateIC:");
__asm__("	ret");
__asm__(".globl XCreateImage");
__asm__("	.type XCreateImage,@function");
__asm__("XCreateImage:");
__asm__("	ret");
__asm__(".globl XCreateOC");
__asm__("	.type XCreateOC,@function");
__asm__("XCreateOC:");
__asm__("	ret");
__asm__(".globl XCreatePixmap");
__asm__("	.type XCreatePixmap,@function");
__asm__("XCreatePixmap:");
__asm__("	ret");
__asm__(".globl XCreatePixmapCursor");
__asm__("	.type XCreatePixmapCursor,@function");
__asm__("XCreatePixmapCursor:");
__asm__("	ret");
__asm__(".globl XCreatePixmapFromBitmapData");
__asm__("	.type XCreatePixmapFromBitmapData,@function");
__asm__("XCreatePixmapFromBitmapData:");
__asm__("	ret");
__asm__(".globl XCreateRegion");
__asm__("	.type XCreateRegion,@function");
__asm__("XCreateRegion:");
__asm__("	ret");
__asm__(".globl XCreateSimpleWindow");
__asm__("	.type XCreateSimpleWindow,@function");
__asm__("XCreateSimpleWindow:");
__asm__("	ret");
__asm__(".globl XCreateWindow");
__asm__("	.type XCreateWindow,@function");
__asm__("XCreateWindow:");
__asm__("	ret");
__asm__(".globl XDefaultColormap");
__asm__("	.type XDefaultColormap,@function");
__asm__("XDefaultColormap:");
__asm__("	ret");
__asm__(".globl XDefaultColormapOfScreen");
__asm__("	.type XDefaultColormapOfScreen,@function");
__asm__("XDefaultColormapOfScreen:");
__asm__("	ret");
__asm__(".globl XDefaultDepth");
__asm__("	.type XDefaultDepth,@function");
__asm__("XDefaultDepth:");
__asm__("	ret");
__asm__(".globl XDefaultDepthOfScreen");
__asm__("	.type XDefaultDepthOfScreen,@function");
__asm__("XDefaultDepthOfScreen:");
__asm__("	ret");
__asm__(".globl XDefaultGC");
__asm__("	.type XDefaultGC,@function");
__asm__("XDefaultGC:");
__asm__("	ret");
__asm__(".globl XDefaultGCOfScreen");
__asm__("	.type XDefaultGCOfScreen,@function");
__asm__("XDefaultGCOfScreen:");
__asm__("	ret");
__asm__(".globl XDefaultRootWindow");
__asm__("	.type XDefaultRootWindow,@function");
__asm__("XDefaultRootWindow:");
__asm__("	ret");
__asm__(".globl XDefaultScreen");
__asm__("	.type XDefaultScreen,@function");
__asm__("XDefaultScreen:");
__asm__("	ret");
__asm__(".globl XDefaultScreenOfDisplay");
__asm__("	.type XDefaultScreenOfDisplay,@function");
__asm__("XDefaultScreenOfDisplay:");
__asm__("	ret");
__asm__(".globl XDefaultString");
__asm__("	.type XDefaultString,@function");
__asm__("XDefaultString:");
__asm__("	ret");
__asm__(".globl XDefaultVisual");
__asm__("	.type XDefaultVisual,@function");
__asm__("XDefaultVisual:");
__asm__("	ret");
__asm__(".globl XDefaultVisualOfScreen");
__asm__("	.type XDefaultVisualOfScreen,@function");
__asm__("XDefaultVisualOfScreen:");
__asm__("	ret");
__asm__(".globl XDefineCursor");
__asm__("	.type XDefineCursor,@function");
__asm__("XDefineCursor:");
__asm__("	ret");
__asm__(".globl XDeleteContext");
__asm__("	.type XDeleteContext,@function");
__asm__("XDeleteContext:");
__asm__("	ret");
__asm__(".globl XDeleteModifiermapEntry");
__asm__("	.type XDeleteModifiermapEntry,@function");
__asm__("XDeleteModifiermapEntry:");
__asm__("	ret");
__asm__(".globl XDeleteProperty");
__asm__("	.type XDeleteProperty,@function");
__asm__("XDeleteProperty:");
__asm__("	ret");
__asm__(".globl XDestroyIC");
__asm__("	.type XDestroyIC,@function");
__asm__("XDestroyIC:");
__asm__("	ret");
__asm__(".globl XDestroyImage");
__asm__("	.type XDestroyImage,@function");
__asm__("XDestroyImage:");
__asm__("	ret");
__asm__(".globl XDestroyOC");
__asm__("	.type XDestroyOC,@function");
__asm__("XDestroyOC:");
__asm__("	ret");
__asm__(".globl XDestroyRegion");
__asm__("	.type XDestroyRegion,@function");
__asm__("XDestroyRegion:");
__asm__("	ret");
__asm__(".globl XDestroySubwindows");
__asm__("	.type XDestroySubwindows,@function");
__asm__("XDestroySubwindows:");
__asm__("	ret");
__asm__(".globl XDestroyWindow");
__asm__("	.type XDestroyWindow,@function");
__asm__("XDestroyWindow:");
__asm__("	ret");
__asm__(".globl XDirectionalDependentDrawing");
__asm__("	.type XDirectionalDependentDrawing,@function");
__asm__("XDirectionalDependentDrawing:");
__asm__("	ret");
__asm__(".globl XDisableAccessControl");
__asm__("	.type XDisableAccessControl,@function");
__asm__("XDisableAccessControl:");
__asm__("	ret");
__asm__(".globl XDisplayCells");
__asm__("	.type XDisplayCells,@function");
__asm__("XDisplayCells:");
__asm__("	ret");
__asm__(".globl XDisplayHeight");
__asm__("	.type XDisplayHeight,@function");
__asm__("XDisplayHeight:");
__asm__("	ret");
__asm__(".globl XDisplayHeightMM");
__asm__("	.type XDisplayHeightMM,@function");
__asm__("XDisplayHeightMM:");
__asm__("	ret");
__asm__(".globl XDisplayKeycodes");
__asm__("	.type XDisplayKeycodes,@function");
__asm__("XDisplayKeycodes:");
__asm__("	ret");
__asm__(".globl XDisplayMotionBufferSize");
__asm__("	.type XDisplayMotionBufferSize,@function");
__asm__("XDisplayMotionBufferSize:");
__asm__("	ret");
__asm__(".globl XDisplayName");
__asm__("	.type XDisplayName,@function");
__asm__("XDisplayName:");
__asm__("	ret");
__asm__(".globl XDisplayOfIM");
__asm__("	.type XDisplayOfIM,@function");
__asm__("XDisplayOfIM:");
__asm__("	ret");
__asm__(".globl XDisplayOfOM");
__asm__("	.type XDisplayOfOM,@function");
__asm__("XDisplayOfOM:");
__asm__("	ret");
__asm__(".globl XDisplayOfScreen");
__asm__("	.type XDisplayOfScreen,@function");
__asm__("XDisplayOfScreen:");
__asm__("	ret");
__asm__(".globl XDisplayPlanes");
__asm__("	.type XDisplayPlanes,@function");
__asm__("XDisplayPlanes:");
__asm__("	ret");
__asm__(".globl XDisplayString");
__asm__("	.type XDisplayString,@function");
__asm__("XDisplayString:");
__asm__("	ret");
__asm__(".globl XDisplayWidth");
__asm__("	.type XDisplayWidth,@function");
__asm__("XDisplayWidth:");
__asm__("	ret");
__asm__(".globl XDisplayWidthMM");
__asm__("	.type XDisplayWidthMM,@function");
__asm__("XDisplayWidthMM:");
__asm__("	ret");
__asm__(".globl XDoesBackingStore");
__asm__("	.type XDoesBackingStore,@function");
__asm__("XDoesBackingStore:");
__asm__("	ret");
__asm__(".globl XDoesSaveUnders");
__asm__("	.type XDoesSaveUnders,@function");
__asm__("XDoesSaveUnders:");
__asm__("	ret");
__asm__(".globl XDrawArc");
__asm__("	.type XDrawArc,@function");
__asm__("XDrawArc:");
__asm__("	ret");
__asm__(".globl XDrawArcs");
__asm__("	.type XDrawArcs,@function");
__asm__("XDrawArcs:");
__asm__("	ret");
__asm__(".globl XDrawImageString");
__asm__("	.type XDrawImageString,@function");
__asm__("XDrawImageString:");
__asm__("	ret");
__asm__(".globl XDrawImageString16");
__asm__("	.type XDrawImageString16,@function");
__asm__("XDrawImageString16:");
__asm__("	ret");
__asm__(".globl XDrawLine");
__asm__("	.type XDrawLine,@function");
__asm__("XDrawLine:");
__asm__("	ret");
__asm__(".globl XDrawLines");
__asm__("	.type XDrawLines,@function");
__asm__("XDrawLines:");
__asm__("	ret");
__asm__(".globl XDrawPoint");
__asm__("	.type XDrawPoint,@function");
__asm__("XDrawPoint:");
__asm__("	ret");
__asm__(".globl XDrawPoints");
__asm__("	.type XDrawPoints,@function");
__asm__("XDrawPoints:");
__asm__("	ret");
__asm__(".globl XDrawRectangle");
__asm__("	.type XDrawRectangle,@function");
__asm__("XDrawRectangle:");
__asm__("	ret");
__asm__(".globl XDrawRectangles");
__asm__("	.type XDrawRectangles,@function");
__asm__("XDrawRectangles:");
__asm__("	ret");
__asm__(".globl XDrawSegments");
__asm__("	.type XDrawSegments,@function");
__asm__("XDrawSegments:");
__asm__("	ret");
__asm__(".globl XDrawString");
__asm__("	.type XDrawString,@function");
__asm__("XDrawString:");
__asm__("	ret");
__asm__(".globl XDrawString16");
__asm__("	.type XDrawString16,@function");
__asm__("XDrawString16:");
__asm__("	ret");
__asm__(".globl XDrawText");
__asm__("	.type XDrawText,@function");
__asm__("XDrawText:");
__asm__("	ret");
__asm__(".globl XDrawText16");
__asm__("	.type XDrawText16,@function");
__asm__("XDrawText16:");
__asm__("	ret");
__asm__(".globl XEmptyRegion");
__asm__("	.type XEmptyRegion,@function");
__asm__("XEmptyRegion:");
__asm__("	ret");
__asm__(".globl XEnableAccessControl");
__asm__("	.type XEnableAccessControl,@function");
__asm__("XEnableAccessControl:");
__asm__("	ret");
__asm__(".globl XEqualRegion");
__asm__("	.type XEqualRegion,@function");
__asm__("XEqualRegion:");
__asm__("	ret");
__asm__(".globl XEventMaskOfScreen");
__asm__("	.type XEventMaskOfScreen,@function");
__asm__("XEventMaskOfScreen:");
__asm__("	ret");
__asm__(".globl XEventsQueued");
__asm__("	.type XEventsQueued,@function");
__asm__("XEventsQueued:");
__asm__("	ret");
__asm__(".globl XExtendedMaxRequestSize");
__asm__("	.type XExtendedMaxRequestSize,@function");
__asm__("XExtendedMaxRequestSize:");
__asm__("	ret");
__asm__(".globl XExtentsOfFontSet");
__asm__("	.type XExtentsOfFontSet,@function");
__asm__("XExtentsOfFontSet:");
__asm__("	ret");
__asm__(".globl XFetchBuffer");
__asm__("	.type XFetchBuffer,@function");
__asm__("XFetchBuffer:");
__asm__("	ret");
__asm__(".globl XFetchBytes");
__asm__("	.type XFetchBytes,@function");
__asm__("XFetchBytes:");
__asm__("	ret");
__asm__(".globl XFetchName");
__asm__("	.type XFetchName,@function");
__asm__("XFetchName:");
__asm__("	ret");
__asm__(".globl XFillArc");
__asm__("	.type XFillArc,@function");
__asm__("XFillArc:");
__asm__("	ret");
__asm__(".globl XFillArcs");
__asm__("	.type XFillArcs,@function");
__asm__("XFillArcs:");
__asm__("	ret");
__asm__(".globl XFillPolygon");
__asm__("	.type XFillPolygon,@function");
__asm__("XFillPolygon:");
__asm__("	ret");
__asm__(".globl XFillRectangle");
__asm__("	.type XFillRectangle,@function");
__asm__("XFillRectangle:");
__asm__("	ret");
__asm__(".globl XFillRectangles");
__asm__("	.type XFillRectangles,@function");
__asm__("XFillRectangles:");
__asm__("	ret");
__asm__(".globl XFilterEvent");
__asm__("	.type XFilterEvent,@function");
__asm__("XFilterEvent:");
__asm__("	ret");
__asm__(".globl XFindContext");
__asm__("	.type XFindContext,@function");
__asm__("XFindContext:");
__asm__("	ret");
__asm__(".globl XFindOnExtensionList");
__asm__("	.type XFindOnExtensionList,@function");
__asm__("XFindOnExtensionList:");
__asm__("	ret");
__asm__(".globl XFlush");
__asm__("	.type XFlush,@function");
__asm__("XFlush:");
__asm__("	ret");
__asm__(".globl XFlushGC");
__asm__("	.type XFlushGC,@function");
__asm__("XFlushGC:");
__asm__("	ret");
__asm__(".globl XFontsOfFontSet");
__asm__("	.type XFontsOfFontSet,@function");
__asm__("XFontsOfFontSet:");
__asm__("	ret");
__asm__(".globl XForceScreenSaver");
__asm__("	.type XForceScreenSaver,@function");
__asm__("XForceScreenSaver:");
__asm__("	ret");
__asm__(".globl XFree");
__asm__("	.type XFree,@function");
__asm__("XFree:");
__asm__("	ret");
__asm__(".globl XFreeColormap");
__asm__("	.type XFreeColormap,@function");
__asm__("XFreeColormap:");
__asm__("	ret");
__asm__(".globl XFreeColors");
__asm__("	.type XFreeColors,@function");
__asm__("XFreeColors:");
__asm__("	ret");
__asm__(".globl XFreeCursor");
__asm__("	.type XFreeCursor,@function");
__asm__("XFreeCursor:");
__asm__("	ret");
__asm__(".globl XFreeExtensionList");
__asm__("	.type XFreeExtensionList,@function");
__asm__("XFreeExtensionList:");
__asm__("	ret");
__asm__(".globl XFreeFont");
__asm__("	.type XFreeFont,@function");
__asm__("XFreeFont:");
__asm__("	ret");
__asm__(".globl XFreeFontInfo");
__asm__("	.type XFreeFontInfo,@function");
__asm__("XFreeFontInfo:");
__asm__("	ret");
__asm__(".globl XFreeFontNames");
__asm__("	.type XFreeFontNames,@function");
__asm__("XFreeFontNames:");
__asm__("	ret");
__asm__(".globl XFreeFontPath");
__asm__("	.type XFreeFontPath,@function");
__asm__("XFreeFontPath:");
__asm__("	ret");
__asm__(".globl XFreeFontSet");
__asm__("	.type XFreeFontSet,@function");
__asm__("XFreeFontSet:");
__asm__("	ret");
__asm__(".globl XFreeGC");
__asm__("	.type XFreeGC,@function");
__asm__("XFreeGC:");
__asm__("	ret");
__asm__(".globl XFreeModifiermap");
__asm__("	.type XFreeModifiermap,@function");
__asm__("XFreeModifiermap:");
__asm__("	ret");
__asm__(".globl XFreePixmap");
__asm__("	.type XFreePixmap,@function");
__asm__("XFreePixmap:");
__asm__("	ret");
__asm__(".globl XFreeStringList");
__asm__("	.type XFreeStringList,@function");
__asm__("XFreeStringList:");
__asm__("	ret");
__asm__(".globl XGContextFromGC");
__asm__("	.type XGContextFromGC,@function");
__asm__("XGContextFromGC:");
__asm__("	ret");
__asm__(".globl XGeometry");
__asm__("	.type XGeometry,@function");
__asm__("XGeometry:");
__asm__("	ret");
__asm__(".globl XGetAtomName");
__asm__("	.type XGetAtomName,@function");
__asm__("XGetAtomName:");
__asm__("	ret");
__asm__(".globl XGetAtomNames");
__asm__("	.type XGetAtomNames,@function");
__asm__("XGetAtomNames:");
__asm__("	ret");
__asm__(".globl XGetClassHint");
__asm__("	.type XGetClassHint,@function");
__asm__("XGetClassHint:");
__asm__("	ret");
__asm__(".globl XGetCommand");
__asm__("	.type XGetCommand,@function");
__asm__("XGetCommand:");
__asm__("	ret");
__asm__(".globl XGetDefault");
__asm__("	.type XGetDefault,@function");
__asm__("XGetDefault:");
__asm__("	ret");
__asm__(".globl XGetErrorDatabaseText");
__asm__("	.type XGetErrorDatabaseText,@function");
__asm__("XGetErrorDatabaseText:");
__asm__("	ret");
__asm__(".globl XGetErrorText");
__asm__("	.type XGetErrorText,@function");
__asm__("XGetErrorText:");
__asm__("	ret");
__asm__(".globl XGetFontPath");
__asm__("	.type XGetFontPath,@function");
__asm__("XGetFontPath:");
__asm__("	ret");
__asm__(".globl XGetFontProperty");
__asm__("	.type XGetFontProperty,@function");
__asm__("XGetFontProperty:");
__asm__("	ret");
__asm__(".globl XGetGCValues");
__asm__("	.type XGetGCValues,@function");
__asm__("XGetGCValues:");
__asm__("	ret");
__asm__(".globl XGetGeometry");
__asm__("	.type XGetGeometry,@function");
__asm__("XGetGeometry:");
__asm__("	ret");
__asm__(".globl XGetICValues");
__asm__("	.type XGetICValues,@function");
__asm__("XGetICValues:");
__asm__("	ret");
__asm__(".globl XGetIMValues");
__asm__("	.type XGetIMValues,@function");
__asm__("XGetIMValues:");
__asm__("	ret");
__asm__(".globl XGetIconName");
__asm__("	.type XGetIconName,@function");
__asm__("XGetIconName:");
__asm__("	ret");
__asm__(".globl XGetIconSizes");
__asm__("	.type XGetIconSizes,@function");
__asm__("XGetIconSizes:");
__asm__("	ret");
__asm__(".globl XGetImage");
__asm__("	.type XGetImage,@function");
__asm__("XGetImage:");
__asm__("	ret");
__asm__(".globl XGetInputFocus");
__asm__("	.type XGetInputFocus,@function");
__asm__("XGetInputFocus:");
__asm__("	ret");
__asm__(".globl XGetKeyboardControl");
__asm__("	.type XGetKeyboardControl,@function");
__asm__("XGetKeyboardControl:");
__asm__("	ret");
__asm__(".globl XGetKeyboardMapping");
__asm__("	.type XGetKeyboardMapping,@function");
__asm__("XGetKeyboardMapping:");
__asm__("	ret");
__asm__(".globl XGetModifierMapping");
__asm__("	.type XGetModifierMapping,@function");
__asm__("XGetModifierMapping:");
__asm__("	ret");
__asm__(".globl XGetMotionEvents");
__asm__("	.type XGetMotionEvents,@function");
__asm__("XGetMotionEvents:");
__asm__("	ret");
__asm__(".globl XGetNormalHints");
__asm__("	.type XGetNormalHints,@function");
__asm__("XGetNormalHints:");
__asm__("	ret");
__asm__(".globl XGetOCValues");
__asm__("	.type XGetOCValues,@function");
__asm__("XGetOCValues:");
__asm__("	ret");
__asm__(".globl XGetOMValues");
__asm__("	.type XGetOMValues,@function");
__asm__("XGetOMValues:");
__asm__("	ret");
__asm__(".globl XGetPixel");
__asm__("	.type XGetPixel,@function");
__asm__("XGetPixel:");
__asm__("	ret");
__asm__(".globl XGetPointerControl");
__asm__("	.type XGetPointerControl,@function");
__asm__("XGetPointerControl:");
__asm__("	ret");
__asm__(".globl XGetPointerMapping");
__asm__("	.type XGetPointerMapping,@function");
__asm__("XGetPointerMapping:");
__asm__("	ret");
__asm__(".globl XGetRGBColormaps");
__asm__("	.type XGetRGBColormaps,@function");
__asm__("XGetRGBColormaps:");
__asm__("	ret");
__asm__(".globl XGetScreenSaver");
__asm__("	.type XGetScreenSaver,@function");
__asm__("XGetScreenSaver:");
__asm__("	ret");
__asm__(".globl XGetSelectionOwner");
__asm__("	.type XGetSelectionOwner,@function");
__asm__("XGetSelectionOwner:");
__asm__("	ret");
__asm__(".globl XGetSizeHints");
__asm__("	.type XGetSizeHints,@function");
__asm__("XGetSizeHints:");
__asm__("	ret");
__asm__(".globl XGetStandardColormap");
__asm__("	.type XGetStandardColormap,@function");
__asm__("XGetStandardColormap:");
__asm__("	ret");
__asm__(".globl XGetSubImage");
__asm__("	.type XGetSubImage,@function");
__asm__("XGetSubImage:");
__asm__("	ret");
__asm__(".globl XGetTextProperty");
__asm__("	.type XGetTextProperty,@function");
__asm__("XGetTextProperty:");
__asm__("	ret");
__asm__(".globl XGetTransientForHint");
__asm__("	.type XGetTransientForHint,@function");
__asm__("XGetTransientForHint:");
__asm__("	ret");
__asm__(".globl XGetVisualInfo");
__asm__("	.type XGetVisualInfo,@function");
__asm__("XGetVisualInfo:");
__asm__("	ret");
__asm__(".globl XGetWMClientMachine");
__asm__("	.type XGetWMClientMachine,@function");
__asm__("XGetWMClientMachine:");
__asm__("	ret");
__asm__(".globl XGetWMColormapWindows");
__asm__("	.type XGetWMColormapWindows,@function");
__asm__("XGetWMColormapWindows:");
__asm__("	ret");
__asm__(".globl XGetWMHints");
__asm__("	.type XGetWMHints,@function");
__asm__("XGetWMHints:");
__asm__("	ret");
__asm__(".globl XGetWMIconName");
__asm__("	.type XGetWMIconName,@function");
__asm__("XGetWMIconName:");
__asm__("	ret");
__asm__(".globl XGetWMName");
__asm__("	.type XGetWMName,@function");
__asm__("XGetWMName:");
__asm__("	ret");
__asm__(".globl XGetWMNormalHints");
__asm__("	.type XGetWMNormalHints,@function");
__asm__("XGetWMNormalHints:");
__asm__("	ret");
__asm__(".globl XGetWMProtocols");
__asm__("	.type XGetWMProtocols,@function");
__asm__("XGetWMProtocols:");
__asm__("	ret");
__asm__(".globl XGetWMSizeHints");
__asm__("	.type XGetWMSizeHints,@function");
__asm__("XGetWMSizeHints:");
__asm__("	ret");
__asm__(".globl XGetWindowAttributes");
__asm__("	.type XGetWindowAttributes,@function");
__asm__("XGetWindowAttributes:");
__asm__("	ret");
__asm__(".globl XGetWindowProperty");
__asm__("	.type XGetWindowProperty,@function");
__asm__("XGetWindowProperty:");
__asm__("	ret");
__asm__(".globl XGetZoomHints");
__asm__("	.type XGetZoomHints,@function");
__asm__("XGetZoomHints:");
__asm__("	ret");
__asm__(".globl XGrabButton");
__asm__("	.type XGrabButton,@function");
__asm__("XGrabButton:");
__asm__("	ret");
__asm__(".globl XGrabKey");
__asm__("	.type XGrabKey,@function");
__asm__("XGrabKey:");
__asm__("	ret");
__asm__(".globl XGrabKeyboard");
__asm__("	.type XGrabKeyboard,@function");
__asm__("XGrabKeyboard:");
__asm__("	ret");
__asm__(".globl XGrabPointer");
__asm__("	.type XGrabPointer,@function");
__asm__("XGrabPointer:");
__asm__("	ret");
__asm__(".globl XGrabServer");
__asm__("	.type XGrabServer,@function");
__asm__("XGrabServer:");
__asm__("	ret");
__asm__(".globl XHeightMMOfScreen");
__asm__("	.type XHeightMMOfScreen,@function");
__asm__("XHeightMMOfScreen:");
__asm__("	ret");
__asm__(".globl XHeightOfScreen");
__asm__("	.type XHeightOfScreen,@function");
__asm__("XHeightOfScreen:");
__asm__("	ret");
__asm__(".globl XIMOfIC");
__asm__("	.type XIMOfIC,@function");
__asm__("XIMOfIC:");
__asm__("	ret");
__asm__(".globl XIconifyWindow");
__asm__("	.type XIconifyWindow,@function");
__asm__("XIconifyWindow:");
__asm__("	ret");
__asm__(".globl XIfEvent");
__asm__("	.type XIfEvent,@function");
__asm__("XIfEvent:");
__asm__("	ret");
__asm__(".globl XImageByteOrder");
__asm__("	.type XImageByteOrder,@function");
__asm__("XImageByteOrder:");
__asm__("	ret");
__asm__(".globl XInitExtension");
__asm__("	.type XInitExtension,@function");
__asm__("XInitExtension:");
__asm__("	ret");
__asm__(".globl XInitImage");
__asm__("	.type XInitImage,@function");
__asm__("XInitImage:");
__asm__("	ret");
__asm__(".globl XInitThreads");
__asm__("	.type XInitThreads,@function");
__asm__("XInitThreads:");
__asm__("	ret");
__asm__(".globl XInsertModifiermapEntry");
__asm__("	.type XInsertModifiermapEntry,@function");
__asm__("XInsertModifiermapEntry:");
__asm__("	ret");
__asm__(".globl XInstallColormap");
__asm__("	.type XInstallColormap,@function");
__asm__("XInstallColormap:");
__asm__("	ret");
__asm__(".globl XInternAtom");
__asm__("	.type XInternAtom,@function");
__asm__("XInternAtom:");
__asm__("	ret");
__asm__(".globl XInternAtoms");
__asm__("	.type XInternAtoms,@function");
__asm__("XInternAtoms:");
__asm__("	ret");
__asm__(".globl XInternalConnectionNumbers");
__asm__("	.type XInternalConnectionNumbers,@function");
__asm__("XInternalConnectionNumbers:");
__asm__("	ret");
__asm__(".globl XIntersectRegion");
__asm__("	.type XIntersectRegion,@function");
__asm__("XIntersectRegion:");
__asm__("	ret");
__asm__(".globl XKeycodeToKeysym");
__asm__("	.type XKeycodeToKeysym,@function");
__asm__("XKeycodeToKeysym:");
__asm__("	ret");
__asm__(".globl XKeysymToKeycode");
__asm__("	.type XKeysymToKeycode,@function");
__asm__("XKeysymToKeycode:");
__asm__("	ret");
__asm__(".globl XKeysymToString");
__asm__("	.type XKeysymToString,@function");
__asm__("XKeysymToString:");
__asm__("	ret");
__asm__(".globl XKillClient");
__asm__("	.type XKillClient,@function");
__asm__("XKillClient:");
__asm__("	ret");
__asm__(".globl XLastKnownRequestProcessed");
__asm__("	.type XLastKnownRequestProcessed,@function");
__asm__("XLastKnownRequestProcessed:");
__asm__("	ret");
__asm__(".globl XListDepths");
__asm__("	.type XListDepths,@function");
__asm__("XListDepths:");
__asm__("	ret");
__asm__(".globl XListExtensions");
__asm__("	.type XListExtensions,@function");
__asm__("XListExtensions:");
__asm__("	ret");
__asm__(".globl XListFonts");
__asm__("	.type XListFonts,@function");
__asm__("XListFonts:");
__asm__("	ret");
__asm__(".globl XListFontsWithInfo");
__asm__("	.type XListFontsWithInfo,@function");
__asm__("XListFontsWithInfo:");
__asm__("	ret");
__asm__(".globl XListHosts");
__asm__("	.type XListHosts,@function");
__asm__("XListHosts:");
__asm__("	ret");
__asm__(".globl XListInstalledColormaps");
__asm__("	.type XListInstalledColormaps,@function");
__asm__("XListInstalledColormaps:");
__asm__("	ret");
__asm__(".globl XListPixmapFormats");
__asm__("	.type XListPixmapFormats,@function");
__asm__("XListPixmapFormats:");
__asm__("	ret");
__asm__(".globl XListProperties");
__asm__("	.type XListProperties,@function");
__asm__("XListProperties:");
__asm__("	ret");
__asm__(".globl XLoadFont");
__asm__("	.type XLoadFont,@function");
__asm__("XLoadFont:");
__asm__("	ret");
__asm__(".globl XLoadQueryFont");
__asm__("	.type XLoadQueryFont,@function");
__asm__("XLoadQueryFont:");
__asm__("	ret");
__asm__(".globl XLocaleOfFontSet");
__asm__("	.type XLocaleOfFontSet,@function");
__asm__("XLocaleOfFontSet:");
__asm__("	ret");
__asm__(".globl XLocaleOfIM");
__asm__("	.type XLocaleOfIM,@function");
__asm__("XLocaleOfIM:");
__asm__("	ret");
__asm__(".globl XLocaleOfOM");
__asm__("	.type XLocaleOfOM,@function");
__asm__("XLocaleOfOM:");
__asm__("	ret");
__asm__(".globl XLockDisplay");
__asm__("	.type XLockDisplay,@function");
__asm__("XLockDisplay:");
__asm__("	ret");
__asm__(".globl XLookupColor");
__asm__("	.type XLookupColor,@function");
__asm__("XLookupColor:");
__asm__("	ret");
__asm__(".globl XLookupKeysym");
__asm__("	.type XLookupKeysym,@function");
__asm__("XLookupKeysym:");
__asm__("	ret");
__asm__(".globl XLookupString");
__asm__("	.type XLookupString,@function");
__asm__("XLookupString:");
__asm__("	ret");
__asm__(".globl XLowerWindow");
__asm__("	.type XLowerWindow,@function");
__asm__("XLowerWindow:");
__asm__("	ret");
__asm__(".globl XMapRaised");
__asm__("	.type XMapRaised,@function");
__asm__("XMapRaised:");
__asm__("	ret");
__asm__(".globl XMapSubwindows");
__asm__("	.type XMapSubwindows,@function");
__asm__("XMapSubwindows:");
__asm__("	ret");
__asm__(".globl XMapWindow");
__asm__("	.type XMapWindow,@function");
__asm__("XMapWindow:");
__asm__("	ret");
__asm__(".globl XMaskEvent");
__asm__("	.type XMaskEvent,@function");
__asm__("XMaskEvent:");
__asm__("	ret");
__asm__(".globl XMatchVisualInfo");
__asm__("	.type XMatchVisualInfo,@function");
__asm__("XMatchVisualInfo:");
__asm__("	ret");
__asm__(".globl XMaxCmapsOfScreen");
__asm__("	.type XMaxCmapsOfScreen,@function");
__asm__("XMaxCmapsOfScreen:");
__asm__("	ret");
__asm__(".globl XMaxRequestSize");
__asm__("	.type XMaxRequestSize,@function");
__asm__("XMaxRequestSize:");
__asm__("	ret");
__asm__(".globl XMinCmapsOfScreen");
__asm__("	.type XMinCmapsOfScreen,@function");
__asm__("XMinCmapsOfScreen:");
__asm__("	ret");
__asm__(".globl XMoveResizeWindow");
__asm__("	.type XMoveResizeWindow,@function");
__asm__("XMoveResizeWindow:");
__asm__("	ret");
__asm__(".globl XMoveWindow");
__asm__("	.type XMoveWindow,@function");
__asm__("XMoveWindow:");
__asm__("	ret");
__asm__(".globl XNewModifiermap");
__asm__("	.type XNewModifiermap,@function");
__asm__("XNewModifiermap:");
__asm__("	ret");
__asm__(".globl XNextEvent");
__asm__("	.type XNextEvent,@function");
__asm__("XNextEvent:");
__asm__("	ret");
__asm__(".globl XNextRequest");
__asm__("	.type XNextRequest,@function");
__asm__("XNextRequest:");
__asm__("	ret");
__asm__(".globl XNoOp");
__asm__("	.type XNoOp,@function");
__asm__("XNoOp:");
__asm__("	ret");
__asm__(".globl XOMOfOC");
__asm__("	.type XOMOfOC,@function");
__asm__("XOMOfOC:");
__asm__("	ret");
__asm__(".globl XOffsetRegion");
__asm__("	.type XOffsetRegion,@function");
__asm__("XOffsetRegion:");
__asm__("	ret");
__asm__(".globl XOpenDisplay");
__asm__("	.type XOpenDisplay,@function");
__asm__("XOpenDisplay:");
__asm__("	ret");
__asm__(".globl XOpenIM");
__asm__("	.type XOpenIM,@function");
__asm__("XOpenIM:");
__asm__("	ret");
__asm__(".globl XOpenOM");
__asm__("	.type XOpenOM,@function");
__asm__("XOpenOM:");
__asm__("	ret");
__asm__(".globl XParseColor");
__asm__("	.type XParseColor,@function");
__asm__("XParseColor:");
__asm__("	ret");
__asm__(".globl XParseGeometry");
__asm__("	.type XParseGeometry,@function");
__asm__("XParseGeometry:");
__asm__("	ret");
__asm__(".globl XPeekEvent");
__asm__("	.type XPeekEvent,@function");
__asm__("XPeekEvent:");
__asm__("	ret");
__asm__(".globl XPeekIfEvent");
__asm__("	.type XPeekIfEvent,@function");
__asm__("XPeekIfEvent:");
__asm__("	ret");
__asm__(".globl XPending");
__asm__("	.type XPending,@function");
__asm__("XPending:");
__asm__("	ret");
__asm__(".globl XPlanesOfScreen");
__asm__("	.type XPlanesOfScreen,@function");
__asm__("XPlanesOfScreen:");
__asm__("	ret");
__asm__(".globl XPointInRegion");
__asm__("	.type XPointInRegion,@function");
__asm__("XPointInRegion:");
__asm__("	ret");
__asm__(".globl XPolygonRegion");
__asm__("	.type XPolygonRegion,@function");
__asm__("XPolygonRegion:");
__asm__("	ret");
__asm__(".globl XProcessInternalConnection");
__asm__("	.type XProcessInternalConnection,@function");
__asm__("XProcessInternalConnection:");
__asm__("	ret");
__asm__(".globl XProtocolRevision");
__asm__("	.type XProtocolRevision,@function");
__asm__("XProtocolRevision:");
__asm__("	ret");
__asm__(".globl XProtocolVersion");
__asm__("	.type XProtocolVersion,@function");
__asm__("XProtocolVersion:");
__asm__("	ret");
__asm__(".globl XPutBackEvent");
__asm__("	.type XPutBackEvent,@function");
__asm__("XPutBackEvent:");
__asm__("	ret");
__asm__(".globl XPutImage");
__asm__("	.type XPutImage,@function");
__asm__("XPutImage:");
__asm__("	ret");
__asm__(".globl XPutPixel");
__asm__("	.type XPutPixel,@function");
__asm__("XPutPixel:");
__asm__("	ret");
__asm__(".globl XQLength");
__asm__("	.type XQLength,@function");
__asm__("XQLength:");
__asm__("	ret");
__asm__(".globl XQueryBestCursor");
__asm__("	.type XQueryBestCursor,@function");
__asm__("XQueryBestCursor:");
__asm__("	ret");
__asm__(".globl XQueryBestSize");
__asm__("	.type XQueryBestSize,@function");
__asm__("XQueryBestSize:");
__asm__("	ret");
__asm__(".globl XQueryBestStipple");
__asm__("	.type XQueryBestStipple,@function");
__asm__("XQueryBestStipple:");
__asm__("	ret");
__asm__(".globl XQueryBestTile");
__asm__("	.type XQueryBestTile,@function");
__asm__("XQueryBestTile:");
__asm__("	ret");
__asm__(".globl XQueryColor");
__asm__("	.type XQueryColor,@function");
__asm__("XQueryColor:");
__asm__("	ret");
__asm__(".globl XQueryColors");
__asm__("	.type XQueryColors,@function");
__asm__("XQueryColors:");
__asm__("	ret");
__asm__(".globl XQueryExtension");
__asm__("	.type XQueryExtension,@function");
__asm__("XQueryExtension:");
__asm__("	ret");
__asm__(".globl XQueryFont");
__asm__("	.type XQueryFont,@function");
__asm__("XQueryFont:");
__asm__("	ret");
__asm__(".globl XQueryKeymap");
__asm__("	.type XQueryKeymap,@function");
__asm__("XQueryKeymap:");
__asm__("	ret");
__asm__(".globl XQueryPointer");
__asm__("	.type XQueryPointer,@function");
__asm__("XQueryPointer:");
__asm__("	ret");
__asm__(".globl XQueryTextExtents");
__asm__("	.type XQueryTextExtents,@function");
__asm__("XQueryTextExtents:");
__asm__("	ret");
__asm__(".globl XQueryTextExtents16");
__asm__("	.type XQueryTextExtents16,@function");
__asm__("XQueryTextExtents16:");
__asm__("	ret");
__asm__(".globl XQueryTree");
__asm__("	.type XQueryTree,@function");
__asm__("XQueryTree:");
__asm__("	ret");
__asm__(".globl XRaiseWindow");
__asm__("	.type XRaiseWindow,@function");
__asm__("XRaiseWindow:");
__asm__("	ret");
__asm__(".globl XReadBitmapFile");
__asm__("	.type XReadBitmapFile,@function");
__asm__("XReadBitmapFile:");
__asm__("	ret");
__asm__(".globl XReadBitmapFileData");
__asm__("	.type XReadBitmapFileData,@function");
__asm__("XReadBitmapFileData:");
__asm__("	ret");
__asm__(".globl XRebindKeysym");
__asm__("	.type XRebindKeysym,@function");
__asm__("XRebindKeysym:");
__asm__("	ret");
__asm__(".globl XRecolorCursor");
__asm__("	.type XRecolorCursor,@function");
__asm__("XRecolorCursor:");
__asm__("	ret");
__asm__(".globl XReconfigureWMWindow");
__asm__("	.type XReconfigureWMWindow,@function");
__asm__("XReconfigureWMWindow:");
__asm__("	ret");
__asm__(".globl XRectInRegion");
__asm__("	.type XRectInRegion,@function");
__asm__("XRectInRegion:");
__asm__("	ret");
__asm__(".globl XRefreshKeyboardMapping");
__asm__("	.type XRefreshKeyboardMapping,@function");
__asm__("XRefreshKeyboardMapping:");
__asm__("	ret");
__asm__(".globl XRegisterIMInstantiateCallback");
__asm__("	.type XRegisterIMInstantiateCallback,@function");
__asm__("XRegisterIMInstantiateCallback:");
__asm__("	ret");
__asm__(".globl XRemoveConnectionWatch");
__asm__("	.type XRemoveConnectionWatch,@function");
__asm__("XRemoveConnectionWatch:");
__asm__("	ret");
__asm__(".globl XRemoveFromSaveSet");
__asm__("	.type XRemoveFromSaveSet,@function");
__asm__("XRemoveFromSaveSet:");
__asm__("	ret");
__asm__(".globl XRemoveHost");
__asm__("	.type XRemoveHost,@function");
__asm__("XRemoveHost:");
__asm__("	ret");
__asm__(".globl XRemoveHosts");
__asm__("	.type XRemoveHosts,@function");
__asm__("XRemoveHosts:");
__asm__("	ret");
__asm__(".globl XReparentWindow");
__asm__("	.type XReparentWindow,@function");
__asm__("XReparentWindow:");
__asm__("	ret");
__asm__(".globl XResetScreenSaver");
__asm__("	.type XResetScreenSaver,@function");
__asm__("XResetScreenSaver:");
__asm__("	ret");
__asm__(".globl XResizeWindow");
__asm__("	.type XResizeWindow,@function");
__asm__("XResizeWindow:");
__asm__("	ret");
__asm__(".globl XResourceManagerString");
__asm__("	.type XResourceManagerString,@function");
__asm__("XResourceManagerString:");
__asm__("	ret");
__asm__(".globl XRestackWindows");
__asm__("	.type XRestackWindows,@function");
__asm__("XRestackWindows:");
__asm__("	ret");
__asm__(".globl XRootWindow");
__asm__("	.type XRootWindow,@function");
__asm__("XRootWindow:");
__asm__("	ret");
__asm__(".globl XRootWindowOfScreen");
__asm__("	.type XRootWindowOfScreen,@function");
__asm__("XRootWindowOfScreen:");
__asm__("	ret");
__asm__(".globl XRotateBuffers");
__asm__("	.type XRotateBuffers,@function");
__asm__("XRotateBuffers:");
__asm__("	ret");
__asm__(".globl XRotateWindowProperties");
__asm__("	.type XRotateWindowProperties,@function");
__asm__("XRotateWindowProperties:");
__asm__("	ret");
__asm__(".globl XSaveContext");
__asm__("	.type XSaveContext,@function");
__asm__("XSaveContext:");
__asm__("	ret");
__asm__(".globl XScreenCount");
__asm__("	.type XScreenCount,@function");
__asm__("XScreenCount:");
__asm__("	ret");
__asm__(".globl XScreenNumberOfScreen");
__asm__("	.type XScreenNumberOfScreen,@function");
__asm__("XScreenNumberOfScreen:");
__asm__("	ret");
__asm__(".globl XScreenOfDisplay");
__asm__("	.type XScreenOfDisplay,@function");
__asm__("XScreenOfDisplay:");
__asm__("	ret");
__asm__(".globl XScreenResourceString");
__asm__("	.type XScreenResourceString,@function");
__asm__("XScreenResourceString:");
__asm__("	ret");
__asm__(".globl XSelectInput");
__asm__("	.type XSelectInput,@function");
__asm__("XSelectInput:");
__asm__("	ret");
__asm__(".globl XSendEvent");
__asm__("	.type XSendEvent,@function");
__asm__("XSendEvent:");
__asm__("	ret");
__asm__(".globl XServerVendor");
__asm__("	.type XServerVendor,@function");
__asm__("XServerVendor:");
__asm__("	ret");
__asm__(".globl XSetAccessControl");
__asm__("	.type XSetAccessControl,@function");
__asm__("XSetAccessControl:");
__asm__("	ret");
__asm__(".globl XSetAfterFunction");
__asm__("	.type XSetAfterFunction,@function");
__asm__("XSetAfterFunction:");
__asm__("	ret");
__asm__(".globl XSetArcMode");
__asm__("	.type XSetArcMode,@function");
__asm__("XSetArcMode:");
__asm__("	ret");
__asm__(".globl XSetAuthorization");
__asm__("	.type XSetAuthorization,@function");
__asm__("XSetAuthorization:");
__asm__("	ret");
__asm__(".globl XSetBackground");
__asm__("	.type XSetBackground,@function");
__asm__("XSetBackground:");
__asm__("	ret");
__asm__(".globl XSetClassHint");
__asm__("	.type XSetClassHint,@function");
__asm__("XSetClassHint:");
__asm__("	ret");
__asm__(".globl XSetClipMask");
__asm__("	.type XSetClipMask,@function");
__asm__("XSetClipMask:");
__asm__("	ret");
__asm__(".globl XSetClipOrigin");
__asm__("	.type XSetClipOrigin,@function");
__asm__("XSetClipOrigin:");
__asm__("	ret");
__asm__(".globl XSetClipRectangles");
__asm__("	.type XSetClipRectangles,@function");
__asm__("XSetClipRectangles:");
__asm__("	ret");
__asm__(".globl XSetCloseDownMode");
__asm__("	.type XSetCloseDownMode,@function");
__asm__("XSetCloseDownMode:");
__asm__("	ret");
__asm__(".globl XSetCommand");
__asm__("	.type XSetCommand,@function");
__asm__("XSetCommand:");
__asm__("	ret");
__asm__(".globl XSetDashes");
__asm__("	.type XSetDashes,@function");
__asm__("XSetDashes:");
__asm__("	ret");
__asm__(".globl XSetErrorHandler");
__asm__("	.type XSetErrorHandler,@function");
__asm__("XSetErrorHandler:");
__asm__("	ret");
__asm__(".globl XSetFillRule");
__asm__("	.type XSetFillRule,@function");
__asm__("XSetFillRule:");
__asm__("	ret");
__asm__(".globl XSetFillStyle");
__asm__("	.type XSetFillStyle,@function");
__asm__("XSetFillStyle:");
__asm__("	ret");
__asm__(".globl XSetFont");
__asm__("	.type XSetFont,@function");
__asm__("XSetFont:");
__asm__("	ret");
__asm__(".globl XSetFontPath");
__asm__("	.type XSetFontPath,@function");
__asm__("XSetFontPath:");
__asm__("	ret");
__asm__(".globl XSetForeground");
__asm__("	.type XSetForeground,@function");
__asm__("XSetForeground:");
__asm__("	ret");
__asm__(".globl XSetFunction");
__asm__("	.type XSetFunction,@function");
__asm__("XSetFunction:");
__asm__("	ret");
__asm__(".globl XSetGraphicsExposures");
__asm__("	.type XSetGraphicsExposures,@function");
__asm__("XSetGraphicsExposures:");
__asm__("	ret");
__asm__(".globl XSetICFocus");
__asm__("	.type XSetICFocus,@function");
__asm__("XSetICFocus:");
__asm__("	ret");
__asm__(".globl XSetICValues");
__asm__("	.type XSetICValues,@function");
__asm__("XSetICValues:");
__asm__("	ret");
__asm__(".globl XSetIMValues");
__asm__("	.type XSetIMValues,@function");
__asm__("XSetIMValues:");
__asm__("	ret");
__asm__(".globl XSetIOErrorHandler");
__asm__("	.type XSetIOErrorHandler,@function");
__asm__("XSetIOErrorHandler:");
__asm__("	ret");
__asm__(".globl XSetIconName");
__asm__("	.type XSetIconName,@function");
__asm__("XSetIconName:");
__asm__("	ret");
__asm__(".globl XSetIconSizes");
__asm__("	.type XSetIconSizes,@function");
__asm__("XSetIconSizes:");
__asm__("	ret");
__asm__(".globl XSetInputFocus");
__asm__("	.type XSetInputFocus,@function");
__asm__("XSetInputFocus:");
__asm__("	ret");
__asm__(".globl XSetLineAttributes");
__asm__("	.type XSetLineAttributes,@function");
__asm__("XSetLineAttributes:");
__asm__("	ret");
__asm__(".globl XSetLocaleModifiers");
__asm__("	.type XSetLocaleModifiers,@function");
__asm__("XSetLocaleModifiers:");
__asm__("	ret");
__asm__(".globl XSetModifierMapping");
__asm__("	.type XSetModifierMapping,@function");
__asm__("XSetModifierMapping:");
__asm__("	ret");
__asm__(".globl XSetNormalHints");
__asm__("	.type XSetNormalHints,@function");
__asm__("XSetNormalHints:");
__asm__("	ret");
__asm__(".globl XSetOCValues");
__asm__("	.type XSetOCValues,@function");
__asm__("XSetOCValues:");
__asm__("	ret");
__asm__(".globl XSetOMValues");
__asm__("	.type XSetOMValues,@function");
__asm__("XSetOMValues:");
__asm__("	ret");
__asm__(".globl XSetPlaneMask");
__asm__("	.type XSetPlaneMask,@function");
__asm__("XSetPlaneMask:");
__asm__("	ret");
__asm__(".globl XSetPointerMapping");
__asm__("	.type XSetPointerMapping,@function");
__asm__("XSetPointerMapping:");
__asm__("	ret");
__asm__(".globl XSetRGBColormaps");
__asm__("	.type XSetRGBColormaps,@function");
__asm__("XSetRGBColormaps:");
__asm__("	ret");
__asm__(".globl XSetRegion");
__asm__("	.type XSetRegion,@function");
__asm__("XSetRegion:");
__asm__("	ret");
__asm__(".globl XSetScreenSaver");
__asm__("	.type XSetScreenSaver,@function");
__asm__("XSetScreenSaver:");
__asm__("	ret");
__asm__(".globl XSetSelectionOwner");
__asm__("	.type XSetSelectionOwner,@function");
__asm__("XSetSelectionOwner:");
__asm__("	ret");
__asm__(".globl XSetSizeHints");
__asm__("	.type XSetSizeHints,@function");
__asm__("XSetSizeHints:");
__asm__("	ret");
__asm__(".globl XSetStandardColormap");
__asm__("	.type XSetStandardColormap,@function");
__asm__("XSetStandardColormap:");
__asm__("	ret");
__asm__(".globl XSetStandardProperties");
__asm__("	.type XSetStandardProperties,@function");
__asm__("XSetStandardProperties:");
__asm__("	ret");
__asm__(".globl XSetState");
__asm__("	.type XSetState,@function");
__asm__("XSetState:");
__asm__("	ret");
__asm__(".globl XSetStipple");
__asm__("	.type XSetStipple,@function");
__asm__("XSetStipple:");
__asm__("	ret");
__asm__(".globl XSetSubwindowMode");
__asm__("	.type XSetSubwindowMode,@function");
__asm__("XSetSubwindowMode:");
__asm__("	ret");
__asm__(".globl XSetTSOrigin");
__asm__("	.type XSetTSOrigin,@function");
__asm__("XSetTSOrigin:");
__asm__("	ret");
__asm__(".globl XSetTextProperty");
__asm__("	.type XSetTextProperty,@function");
__asm__("XSetTextProperty:");
__asm__("	ret");
__asm__(".globl XSetTile");
__asm__("	.type XSetTile,@function");
__asm__("XSetTile:");
__asm__("	ret");
__asm__(".globl XSetTransientForHint");
__asm__("	.type XSetTransientForHint,@function");
__asm__("XSetTransientForHint:");
__asm__("	ret");
__asm__(".globl XSetWMClientMachine");
__asm__("	.type XSetWMClientMachine,@function");
__asm__("XSetWMClientMachine:");
__asm__("	ret");
__asm__(".globl XSetWMColormapWindows");
__asm__("	.type XSetWMColormapWindows,@function");
__asm__("XSetWMColormapWindows:");
__asm__("	ret");
__asm__(".globl XSetWMHints");
__asm__("	.type XSetWMHints,@function");
__asm__("XSetWMHints:");
__asm__("	ret");
__asm__(".globl XSetWMIconName");
__asm__("	.type XSetWMIconName,@function");
__asm__("XSetWMIconName:");
__asm__("	ret");
__asm__(".globl XSetWMName");
__asm__("	.type XSetWMName,@function");
__asm__("XSetWMName:");
__asm__("	ret");
__asm__(".globl XSetWMNormalHints");
__asm__("	.type XSetWMNormalHints,@function");
__asm__("XSetWMNormalHints:");
__asm__("	ret");
__asm__(".globl XSetWMProperties");
__asm__("	.type XSetWMProperties,@function");
__asm__("XSetWMProperties:");
__asm__("	ret");
__asm__(".globl XSetWMProtocols");
__asm__("	.type XSetWMProtocols,@function");
__asm__("XSetWMProtocols:");
__asm__("	ret");
__asm__(".globl XSetWMSizeHints");
__asm__("	.type XSetWMSizeHints,@function");
__asm__("XSetWMSizeHints:");
__asm__("	ret");
__asm__(".globl XSetWindowBackground");
__asm__("	.type XSetWindowBackground,@function");
__asm__("XSetWindowBackground:");
__asm__("	ret");
__asm__(".globl XSetWindowBackgroundPixmap");
__asm__("	.type XSetWindowBackgroundPixmap,@function");
__asm__("XSetWindowBackgroundPixmap:");
__asm__("	ret");
__asm__(".globl XSetWindowBorder");
__asm__("	.type XSetWindowBorder,@function");
__asm__("XSetWindowBorder:");
__asm__("	ret");
__asm__(".globl XSetWindowBorderPixmap");
__asm__("	.type XSetWindowBorderPixmap,@function");
__asm__("XSetWindowBorderPixmap:");
__asm__("	ret");
__asm__(".globl XSetWindowBorderWidth");
__asm__("	.type XSetWindowBorderWidth,@function");
__asm__("XSetWindowBorderWidth:");
__asm__("	ret");
__asm__(".globl XSetWindowColormap");
__asm__("	.type XSetWindowColormap,@function");
__asm__("XSetWindowColormap:");
__asm__("	ret");
__asm__(".globl XSetZoomHints");
__asm__("	.type XSetZoomHints,@function");
__asm__("XSetZoomHints:");
__asm__("	ret");
__asm__(".globl XShrinkRegion");
__asm__("	.type XShrinkRegion,@function");
__asm__("XShrinkRegion:");
__asm__("	ret");
__asm__(".globl XStoreBuffer");
__asm__("	.type XStoreBuffer,@function");
__asm__("XStoreBuffer:");
__asm__("	ret");
__asm__(".globl XStoreBytes");
__asm__("	.type XStoreBytes,@function");
__asm__("XStoreBytes:");
__asm__("	ret");
__asm__(".globl XStoreColor");
__asm__("	.type XStoreColor,@function");
__asm__("XStoreColor:");
__asm__("	ret");
__asm__(".globl XStoreColors");
__asm__("	.type XStoreColors,@function");
__asm__("XStoreColors:");
__asm__("	ret");
__asm__(".globl XStoreName");
__asm__("	.type XStoreName,@function");
__asm__("XStoreName:");
__asm__("	ret");
__asm__(".globl XStoreNamedColor");
__asm__("	.type XStoreNamedColor,@function");
__asm__("XStoreNamedColor:");
__asm__("	ret");
__asm__(".globl XStringListToTextProperty");
__asm__("	.type XStringListToTextProperty,@function");
__asm__("XStringListToTextProperty:");
__asm__("	ret");
__asm__(".globl XStringToKeysym");
__asm__("	.type XStringToKeysym,@function");
__asm__("XStringToKeysym:");
__asm__("	ret");
__asm__(".globl XSubImage");
__asm__("	.type XSubImage,@function");
__asm__("XSubImage:");
__asm__("	ret");
__asm__(".globl XSubtractRegion");
__asm__("	.type XSubtractRegion,@function");
__asm__("XSubtractRegion:");
__asm__("	ret");
__asm__(".globl XSupportsLocale");
__asm__("	.type XSupportsLocale,@function");
__asm__("XSupportsLocale:");
__asm__("	ret");
__asm__(".globl XSync");
__asm__("	.type XSync,@function");
__asm__("XSync:");
__asm__("	ret");
__asm__(".globl XSynchronize");
__asm__("	.type XSynchronize,@function");
__asm__("XSynchronize:");
__asm__("	ret");
__asm__(".globl XTextExtents");
__asm__("	.type XTextExtents,@function");
__asm__("XTextExtents:");
__asm__("	ret");
__asm__(".globl XTextExtents16");
__asm__("	.type XTextExtents16,@function");
__asm__("XTextExtents16:");
__asm__("	ret");
__asm__(".globl XTextPropertyToStringList");
__asm__("	.type XTextPropertyToStringList,@function");
__asm__("XTextPropertyToStringList:");
__asm__("	ret");
__asm__(".globl XTextWidth");
__asm__("	.type XTextWidth,@function");
__asm__("XTextWidth:");
__asm__("	ret");
__asm__(".globl XTextWidth16");
__asm__("	.type XTextWidth16,@function");
__asm__("XTextWidth16:");
__asm__("	ret");
__asm__(".globl XTranslateCoordinates");
__asm__("	.type XTranslateCoordinates,@function");
__asm__("XTranslateCoordinates:");
__asm__("	ret");
__asm__(".globl XUndefineCursor");
__asm__("	.type XUndefineCursor,@function");
__asm__("XUndefineCursor:");
__asm__("	ret");
__asm__(".globl XUngrabButton");
__asm__("	.type XUngrabButton,@function");
__asm__("XUngrabButton:");
__asm__("	ret");
__asm__(".globl XUngrabKey");
__asm__("	.type XUngrabKey,@function");
__asm__("XUngrabKey:");
__asm__("	ret");
__asm__(".globl XUngrabKeyboard");
__asm__("	.type XUngrabKeyboard,@function");
__asm__("XUngrabKeyboard:");
__asm__("	ret");
__asm__(".globl XUngrabPointer");
__asm__("	.type XUngrabPointer,@function");
__asm__("XUngrabPointer:");
__asm__("	ret");
__asm__(".globl XUngrabServer");
__asm__("	.type XUngrabServer,@function");
__asm__("XUngrabServer:");
__asm__("	ret");
__asm__(".globl XUninstallColormap");
__asm__("	.type XUninstallColormap,@function");
__asm__("XUninstallColormap:");
__asm__("	ret");
__asm__(".globl XUnionRectWithRegion");
__asm__("	.type XUnionRectWithRegion,@function");
__asm__("XUnionRectWithRegion:");
__asm__("	ret");
__asm__(".globl XUnionRegion");
__asm__("	.type XUnionRegion,@function");
__asm__("XUnionRegion:");
__asm__("	ret");
__asm__(".globl XUnloadFont");
__asm__("	.type XUnloadFont,@function");
__asm__("XUnloadFont:");
__asm__("	ret");
__asm__(".globl XUnlockDisplay");
__asm__("	.type XUnlockDisplay,@function");
__asm__("XUnlockDisplay:");
__asm__("	ret");
__asm__(".globl XUnmapSubwindows");
__asm__("	.type XUnmapSubwindows,@function");
__asm__("XUnmapSubwindows:");
__asm__("	ret");
__asm__(".globl XUnmapWindow");
__asm__("	.type XUnmapWindow,@function");
__asm__("XUnmapWindow:");
__asm__("	ret");
__asm__(".globl XUnregisterIMInstantiateCallback");
__asm__("	.type XUnregisterIMInstantiateCallback,@function");
__asm__("XUnregisterIMInstantiateCallback:");
__asm__("	ret");
__asm__(".globl XUnsetICFocus");
__asm__("	.type XUnsetICFocus,@function");
__asm__("XUnsetICFocus:");
__asm__("	ret");
__asm__(".globl XVaCreateNestedList");
__asm__("	.type XVaCreateNestedList,@function");
__asm__("XVaCreateNestedList:");
__asm__("	ret");
__asm__(".globl XVendorRelease");
__asm__("	.type XVendorRelease,@function");
__asm__("XVendorRelease:");
__asm__("	ret");
__asm__(".globl XVisualIDFromVisual");
__asm__("	.type XVisualIDFromVisual,@function");
__asm__("XVisualIDFromVisual:");
__asm__("	ret");
__asm__(".globl XWMGeometry");
__asm__("	.type XWMGeometry,@function");
__asm__("XWMGeometry:");
__asm__("	ret");
__asm__(".globl XWarpPointer");
__asm__("	.type XWarpPointer,@function");
__asm__("XWarpPointer:");
__asm__("	ret");
__asm__(".globl XWhitePixel");
__asm__("	.type XWhitePixel,@function");
__asm__("XWhitePixel:");
__asm__("	ret");
__asm__(".globl XWhitePixelOfScreen");
__asm__("	.type XWhitePixelOfScreen,@function");
__asm__("XWhitePixelOfScreen:");
__asm__("	ret");
__asm__(".globl XWidthMMOfScreen");
__asm__("	.type XWidthMMOfScreen,@function");
__asm__("XWidthMMOfScreen:");
__asm__("	ret");
__asm__(".globl XWidthOfScreen");
__asm__("	.type XWidthOfScreen,@function");
__asm__("XWidthOfScreen:");
__asm__("	ret");
__asm__(".globl XWindowEvent");
__asm__("	.type XWindowEvent,@function");
__asm__("XWindowEvent:");
__asm__("	ret");
__asm__(".globl XWithdrawWindow");
__asm__("	.type XWithdrawWindow,@function");
__asm__("XWithdrawWindow:");
__asm__("	ret");
__asm__(".globl XWriteBitmapFile");
__asm__("	.type XWriteBitmapFile,@function");
__asm__("XWriteBitmapFile:");
__asm__("	ret");
__asm__(".globl XXorRegion");
__asm__("	.type XXorRegion,@function");
__asm__("XXorRegion:");
__asm__("	ret");
__asm__(".globl XauDisposeAuth");
__asm__("	.type XauDisposeAuth,@function");
__asm__("XauDisposeAuth:");
__asm__("	ret");
__asm__(".globl XauFileName");
__asm__("	.type XauFileName,@function");
__asm__("XauFileName:");
__asm__("	ret");
__asm__(".globl XauGetBestAuthByAddr");
__asm__("	.type XauGetBestAuthByAddr,@function");
__asm__("XauGetBestAuthByAddr:");
__asm__("	ret");
__asm__(".globl XauReadAuth");
__asm__("	.type XauReadAuth,@function");
__asm__("XauReadAuth:");
__asm__("	ret");
__asm__(".globl XcmsAddColorSpace");
__asm__("	.type XcmsAddColorSpace,@function");
__asm__("XcmsAddColorSpace:");
__asm__("	ret");
__asm__(".globl XcmsAddFunctionSet");
__asm__("	.type XcmsAddFunctionSet,@function");
__asm__("XcmsAddFunctionSet:");
__asm__("	ret");
__asm__(".globl XcmsAllocColor");
__asm__("	.type XcmsAllocColor,@function");
__asm__("XcmsAllocColor:");
__asm__("	ret");
__asm__(".globl XcmsAllocNamedColor");
__asm__("	.type XcmsAllocNamedColor,@function");
__asm__("XcmsAllocNamedColor:");
__asm__("	ret");
__asm__(".globl XcmsCCCOfColormap");
__asm__("	.type XcmsCCCOfColormap,@function");
__asm__("XcmsCCCOfColormap:");
__asm__("	ret");
__asm__(".globl XcmsCIELabClipL");
__asm__("	.type XcmsCIELabClipL,@function");
__asm__("XcmsCIELabClipL:");
__asm__("	ret");
__asm__(".globl XcmsCIELabClipLab");
__asm__("	.type XcmsCIELabClipLab,@function");
__asm__("XcmsCIELabClipLab:");
__asm__("	ret");
__asm__(".globl XcmsCIELabClipab");
__asm__("	.type XcmsCIELabClipab,@function");
__asm__("XcmsCIELabClipab:");
__asm__("	ret");
__asm__(".globl XcmsCIELabQueryMaxC");
__asm__("	.type XcmsCIELabQueryMaxC,@function");
__asm__("XcmsCIELabQueryMaxC:");
__asm__("	ret");
__asm__(".globl XcmsCIELabQueryMaxL");
__asm__("	.type XcmsCIELabQueryMaxL,@function");
__asm__("XcmsCIELabQueryMaxL:");
__asm__("	ret");
__asm__(".globl XcmsCIELabQueryMaxLC");
__asm__("	.type XcmsCIELabQueryMaxLC,@function");
__asm__("XcmsCIELabQueryMaxLC:");
__asm__("	ret");
__asm__(".globl XcmsCIELabQueryMinL");
__asm__("	.type XcmsCIELabQueryMinL,@function");
__asm__("XcmsCIELabQueryMinL:");
__asm__("	ret");
__asm__(".globl XcmsCIELabToCIEXYZ");
__asm__("	.type XcmsCIELabToCIEXYZ,@function");
__asm__("XcmsCIELabToCIEXYZ:");
__asm__("	ret");
__asm__(".globl XcmsCIELabWhiteShiftColors");
__asm__("	.type XcmsCIELabWhiteShiftColors,@function");
__asm__("XcmsCIELabWhiteShiftColors:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvClipL");
__asm__("	.type XcmsCIELuvClipL,@function");
__asm__("XcmsCIELuvClipL:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvClipLuv");
__asm__("	.type XcmsCIELuvClipLuv,@function");
__asm__("XcmsCIELuvClipLuv:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvClipuv");
__asm__("	.type XcmsCIELuvClipuv,@function");
__asm__("XcmsCIELuvClipuv:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvQueryMaxC");
__asm__("	.type XcmsCIELuvQueryMaxC,@function");
__asm__("XcmsCIELuvQueryMaxC:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvQueryMaxL");
__asm__("	.type XcmsCIELuvQueryMaxL,@function");
__asm__("XcmsCIELuvQueryMaxL:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvQueryMaxLC");
__asm__("	.type XcmsCIELuvQueryMaxLC,@function");
__asm__("XcmsCIELuvQueryMaxLC:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvQueryMinL");
__asm__("	.type XcmsCIELuvQueryMinL,@function");
__asm__("XcmsCIELuvQueryMinL:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvToCIEuvY");
__asm__("	.type XcmsCIELuvToCIEuvY,@function");
__asm__("XcmsCIELuvToCIEuvY:");
__asm__("	ret");
__asm__(".globl XcmsCIELuvWhiteShiftColors");
__asm__("	.type XcmsCIELuvWhiteShiftColors,@function");
__asm__("XcmsCIELuvWhiteShiftColors:");
__asm__("	ret");
__asm__(".globl XcmsCIEXYZToCIELab");
__asm__("	.type XcmsCIEXYZToCIELab,@function");
__asm__("XcmsCIEXYZToCIELab:");
__asm__("	ret");
__asm__(".globl XcmsCIEXYZToCIEuvY");
__asm__("	.type XcmsCIEXYZToCIEuvY,@function");
__asm__("XcmsCIEXYZToCIEuvY:");
__asm__("	ret");
__asm__(".globl XcmsCIEXYZToCIExyY");
__asm__("	.type XcmsCIEXYZToCIExyY,@function");
__asm__("XcmsCIEXYZToCIExyY:");
__asm__("	ret");
__asm__(".globl XcmsCIEXYZToRGBi");
__asm__("	.type XcmsCIEXYZToRGBi,@function");
__asm__("XcmsCIEXYZToRGBi:");
__asm__("	ret");
__asm__(".globl XcmsCIEuvYToCIELuv");
__asm__("	.type XcmsCIEuvYToCIELuv,@function");
__asm__("XcmsCIEuvYToCIELuv:");
__asm__("	ret");
__asm__(".globl XcmsCIEuvYToCIEXYZ");
__asm__("	.type XcmsCIEuvYToCIEXYZ,@function");
__asm__("XcmsCIEuvYToCIEXYZ:");
__asm__("	ret");
__asm__(".globl XcmsCIEuvYToTekHVC");
__asm__("	.type XcmsCIEuvYToTekHVC,@function");
__asm__("XcmsCIEuvYToTekHVC:");
__asm__("	ret");
__asm__(".globl XcmsCIExyYToCIEXYZ");
__asm__("	.type XcmsCIExyYToCIEXYZ,@function");
__asm__("XcmsCIExyYToCIEXYZ:");
__asm__("	ret");
__asm__(".globl XcmsClientWhitePointOfCCC");
__asm__("	.type XcmsClientWhitePointOfCCC,@function");
__asm__("XcmsClientWhitePointOfCCC:");
__asm__("	ret");
__asm__(".globl XcmsConvertColors");
__asm__("	.type XcmsConvertColors,@function");
__asm__("XcmsConvertColors:");
__asm__("	ret");
__asm__(".globl XcmsCreateCCC");
__asm__("	.type XcmsCreateCCC,@function");
__asm__("XcmsCreateCCC:");
__asm__("	ret");
__asm__(".globl XcmsDefaultCCC");
__asm__("	.type XcmsDefaultCCC,@function");
__asm__("XcmsDefaultCCC:");
__asm__("	ret");
__asm__(".globl XcmsDisplayOfCCC");
__asm__("	.type XcmsDisplayOfCCC,@function");
__asm__("XcmsDisplayOfCCC:");
__asm__("	ret");
__asm__(".globl XcmsFormatOfPrefix");
__asm__("	.type XcmsFormatOfPrefix,@function");
__asm__("XcmsFormatOfPrefix:");
__asm__("	ret");
__asm__(".globl XcmsFreeCCC");
__asm__("	.type XcmsFreeCCC,@function");
__asm__("XcmsFreeCCC:");
__asm__("	ret");
__asm__(".globl XcmsLookupColor");
__asm__("	.type XcmsLookupColor,@function");
__asm__("XcmsLookupColor:");
__asm__("	ret");
__asm__(".globl XcmsPrefixOfFormat");
__asm__("	.type XcmsPrefixOfFormat,@function");
__asm__("XcmsPrefixOfFormat:");
__asm__("	ret");
__asm__(".globl XcmsQueryBlack");
__asm__("	.type XcmsQueryBlack,@function");
__asm__("XcmsQueryBlack:");
__asm__("	ret");
__asm__(".globl XcmsQueryBlue");
__asm__("	.type XcmsQueryBlue,@function");
__asm__("XcmsQueryBlue:");
__asm__("	ret");
__asm__(".globl XcmsQueryColor");
__asm__("	.type XcmsQueryColor,@function");
__asm__("XcmsQueryColor:");
__asm__("	ret");
__asm__(".globl XcmsQueryColors");
__asm__("	.type XcmsQueryColors,@function");
__asm__("XcmsQueryColors:");
__asm__("	ret");
__asm__(".globl XcmsQueryGreen");
__asm__("	.type XcmsQueryGreen,@function");
__asm__("XcmsQueryGreen:");
__asm__("	ret");
__asm__(".globl XcmsQueryRed");
__asm__("	.type XcmsQueryRed,@function");
__asm__("XcmsQueryRed:");
__asm__("	ret");
__asm__(".globl XcmsQueryWhite");
__asm__("	.type XcmsQueryWhite,@function");
__asm__("XcmsQueryWhite:");
__asm__("	ret");
__asm__(".globl XcmsRGBToRGBi");
__asm__("	.type XcmsRGBToRGBi,@function");
__asm__("XcmsRGBToRGBi:");
__asm__("	ret");
__asm__(".globl XcmsRGBiToCIEXYZ");
__asm__("	.type XcmsRGBiToCIEXYZ,@function");
__asm__("XcmsRGBiToCIEXYZ:");
__asm__("	ret");
__asm__(".globl XcmsRGBiToRGB");
__asm__("	.type XcmsRGBiToRGB,@function");
__asm__("XcmsRGBiToRGB:");
__asm__("	ret");
__asm__(".globl XcmsScreenNumberOfCCC");
__asm__("	.type XcmsScreenNumberOfCCC,@function");
__asm__("XcmsScreenNumberOfCCC:");
__asm__("	ret");
__asm__(".globl XcmsScreenWhitePointOfCCC");
__asm__("	.type XcmsScreenWhitePointOfCCC,@function");
__asm__("XcmsScreenWhitePointOfCCC:");
__asm__("	ret");
__asm__(".globl XcmsSetCCCOfColormap");
__asm__("	.type XcmsSetCCCOfColormap,@function");
__asm__("XcmsSetCCCOfColormap:");
__asm__("	ret");
__asm__(".globl XcmsSetCompressionProc");
__asm__("	.type XcmsSetCompressionProc,@function");
__asm__("XcmsSetCompressionProc:");
__asm__("	ret");
__asm__(".globl XcmsSetWhiteAdjustProc");
__asm__("	.type XcmsSetWhiteAdjustProc,@function");
__asm__("XcmsSetWhiteAdjustProc:");
__asm__("	ret");
__asm__(".globl XcmsSetWhitePoint");
__asm__("	.type XcmsSetWhitePoint,@function");
__asm__("XcmsSetWhitePoint:");
__asm__("	ret");
__asm__(".globl XcmsStoreColor");
__asm__("	.type XcmsStoreColor,@function");
__asm__("XcmsStoreColor:");
__asm__("	ret");
__asm__(".globl XcmsStoreColors");
__asm__("	.type XcmsStoreColors,@function");
__asm__("XcmsStoreColors:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCClipC");
__asm__("	.type XcmsTekHVCClipC,@function");
__asm__("XcmsTekHVCClipC:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCClipV");
__asm__("	.type XcmsTekHVCClipV,@function");
__asm__("XcmsTekHVCClipV:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCClipVC");
__asm__("	.type XcmsTekHVCClipVC,@function");
__asm__("XcmsTekHVCClipVC:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCQueryMaxC");
__asm__("	.type XcmsTekHVCQueryMaxC,@function");
__asm__("XcmsTekHVCQueryMaxC:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCQueryMaxV");
__asm__("	.type XcmsTekHVCQueryMaxV,@function");
__asm__("XcmsTekHVCQueryMaxV:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCQueryMaxVC");
__asm__("	.type XcmsTekHVCQueryMaxVC,@function");
__asm__("XcmsTekHVCQueryMaxVC:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCQueryMaxVSamples");
__asm__("	.type XcmsTekHVCQueryMaxVSamples,@function");
__asm__("XcmsTekHVCQueryMaxVSamples:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCQueryMinV");
__asm__("	.type XcmsTekHVCQueryMinV,@function");
__asm__("XcmsTekHVCQueryMinV:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCToCIEuvY");
__asm__("	.type XcmsTekHVCToCIEuvY,@function");
__asm__("XcmsTekHVCToCIEuvY:");
__asm__("	ret");
__asm__(".globl XcmsTekHVCWhiteShiftColors");
__asm__("	.type XcmsTekHVCWhiteShiftColors,@function");
__asm__("XcmsTekHVCWhiteShiftColors:");
__asm__("	ret");
__asm__(".globl XcmsVisualOfCCC");
__asm__("	.type XcmsVisualOfCCC,@function");
__asm__("XcmsVisualOfCCC:");
__asm__("	ret");
__asm__(".globl XkbAllocClientMap");
__asm__("	.type XkbAllocClientMap,@function");
__asm__("XkbAllocClientMap:");
__asm__("	ret");
__asm__(".globl XkbAllocCompatMap");
__asm__("	.type XkbAllocCompatMap,@function");
__asm__("XkbAllocCompatMap:");
__asm__("	ret");
__asm__(".globl XkbAllocControls");
__asm__("	.type XkbAllocControls,@function");
__asm__("XkbAllocControls:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomColors");
__asm__("	.type XkbAllocGeomColors,@function");
__asm__("XkbAllocGeomColors:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomDoodads");
__asm__("	.type XkbAllocGeomDoodads,@function");
__asm__("XkbAllocGeomDoodads:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomKeyAliases");
__asm__("	.type XkbAllocGeomKeyAliases,@function");
__asm__("XkbAllocGeomKeyAliases:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomKeys");
__asm__("	.type XkbAllocGeomKeys,@function");
__asm__("XkbAllocGeomKeys:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomOutlines");
__asm__("	.type XkbAllocGeomOutlines,@function");
__asm__("XkbAllocGeomOutlines:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomOverlayKeys");
__asm__("	.type XkbAllocGeomOverlayKeys,@function");
__asm__("XkbAllocGeomOverlayKeys:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomOverlayRows");
__asm__("	.type XkbAllocGeomOverlayRows,@function");
__asm__("XkbAllocGeomOverlayRows:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomOverlays");
__asm__("	.type XkbAllocGeomOverlays,@function");
__asm__("XkbAllocGeomOverlays:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomPoints");
__asm__("	.type XkbAllocGeomPoints,@function");
__asm__("XkbAllocGeomPoints:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomProps");
__asm__("	.type XkbAllocGeomProps,@function");
__asm__("XkbAllocGeomProps:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomRows");
__asm__("	.type XkbAllocGeomRows,@function");
__asm__("XkbAllocGeomRows:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomSectionDoodads");
__asm__("	.type XkbAllocGeomSectionDoodads,@function");
__asm__("XkbAllocGeomSectionDoodads:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomSections");
__asm__("	.type XkbAllocGeomSections,@function");
__asm__("XkbAllocGeomSections:");
__asm__("	ret");
__asm__(".globl XkbAllocGeomShapes");
__asm__("	.type XkbAllocGeomShapes,@function");
__asm__("XkbAllocGeomShapes:");
__asm__("	ret");
__asm__(".globl XkbAllocGeometry");
__asm__("	.type XkbAllocGeometry,@function");
__asm__("XkbAllocGeometry:");
__asm__("	ret");
__asm__(".globl XkbAllocIndicatorMaps");
__asm__("	.type XkbAllocIndicatorMaps,@function");
__asm__("XkbAllocIndicatorMaps:");
__asm__("	ret");
__asm__(".globl XkbAllocKeyboard");
__asm__("	.type XkbAllocKeyboard,@function");
__asm__("XkbAllocKeyboard:");
__asm__("	ret");
__asm__(".globl XkbAllocNames");
__asm__("	.type XkbAllocNames,@function");
__asm__("XkbAllocNames:");
__asm__("	ret");
__asm__(".globl XkbAllocServerMap");
__asm__("	.type XkbAllocServerMap,@function");
__asm__("XkbAllocServerMap:");
__asm__("	ret");
__asm__(".globl XkbApplyCompatMapToKey");
__asm__("	.type XkbApplyCompatMapToKey,@function");
__asm__("XkbApplyCompatMapToKey:");
__asm__("	ret");
__asm__(".globl XkbApplyVirtualModChanges");
__asm__("	.type XkbApplyVirtualModChanges,@function");
__asm__("XkbApplyVirtualModChanges:");
__asm__("	ret");
__asm__(".globl XkbBell");
__asm__("	.type XkbBell,@function");
__asm__("XkbBell:");
__asm__("	ret");
__asm__(".globl XkbBellEvent");
__asm__("	.type XkbBellEvent,@function");
__asm__("XkbBellEvent:");
__asm__("	ret");
__asm__(".globl XkbChangeEnabledControls");
__asm__("	.type XkbChangeEnabledControls,@function");
__asm__("XkbChangeEnabledControls:");
__asm__("	ret");
__asm__(".globl XkbChangeKeycodeRange");
__asm__("	.type XkbChangeKeycodeRange,@function");
__asm__("XkbChangeKeycodeRange:");
__asm__("	ret");
__asm__(".globl XkbChangeMap");
__asm__("	.type XkbChangeMap,@function");
__asm__("XkbChangeMap:");
__asm__("	ret");
__asm__(".globl XkbChangeNames");
__asm__("	.type XkbChangeNames,@function");
__asm__("XkbChangeNames:");
__asm__("	ret");
__asm__(".globl XkbChangeTypesOfKey");
__asm__("	.type XkbChangeTypesOfKey,@function");
__asm__("XkbChangeTypesOfKey:");
__asm__("	ret");
__asm__(".globl XkbComputeEffectiveMap");
__asm__("	.type XkbComputeEffectiveMap,@function");
__asm__("XkbComputeEffectiveMap:");
__asm__("	ret");
__asm__(".globl XkbComputeRowBounds");
__asm__("	.type XkbComputeRowBounds,@function");
__asm__("XkbComputeRowBounds:");
__asm__("	ret");
__asm__(".globl XkbComputeSectionBounds");
__asm__("	.type XkbComputeSectionBounds,@function");
__asm__("XkbComputeSectionBounds:");
__asm__("	ret");
__asm__(".globl XkbComputeShapeBounds");
__asm__("	.type XkbComputeShapeBounds,@function");
__asm__("XkbComputeShapeBounds:");
__asm__("	ret");
__asm__(".globl XkbComputeShapeTop");
__asm__("	.type XkbComputeShapeTop,@function");
__asm__("XkbComputeShapeTop:");
__asm__("	ret");
__asm__(".globl XkbCopyKeyType");
__asm__("	.type XkbCopyKeyType,@function");
__asm__("XkbCopyKeyType:");
__asm__("	ret");
__asm__(".globl XkbCopyKeyTypes");
__asm__("	.type XkbCopyKeyTypes,@function");
__asm__("XkbCopyKeyTypes:");
__asm__("	ret");
__asm__(".globl XkbFindOverlayForKey");
__asm__("	.type XkbFindOverlayForKey,@function");
__asm__("XkbFindOverlayForKey:");
__asm__("	ret");
__asm__(".globl XkbForceBell");
__asm__("	.type XkbForceBell,@function");
__asm__("XkbForceBell:");
__asm__("	ret");
__asm__(".globl XkbFreeClientMap");
__asm__("	.type XkbFreeClientMap,@function");
__asm__("XkbFreeClientMap:");
__asm__("	ret");
__asm__(".globl XkbFreeCompatMap");
__asm__("	.type XkbFreeCompatMap,@function");
__asm__("XkbFreeCompatMap:");
__asm__("	ret");
__asm__(".globl XkbFreeComponentList");
__asm__("	.type XkbFreeComponentList,@function");
__asm__("XkbFreeComponentList:");
__asm__("	ret");
__asm__(".globl XkbFreeControls");
__asm__("	.type XkbFreeControls,@function");
__asm__("XkbFreeControls:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomColors");
__asm__("	.type XkbFreeGeomColors,@function");
__asm__("XkbFreeGeomColors:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomDoodads");
__asm__("	.type XkbFreeGeomDoodads,@function");
__asm__("XkbFreeGeomDoodads:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomKeyAliases");
__asm__("	.type XkbFreeGeomKeyAliases,@function");
__asm__("XkbFreeGeomKeyAliases:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomKeys");
__asm__("	.type XkbFreeGeomKeys,@function");
__asm__("XkbFreeGeomKeys:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomOutlines");
__asm__("	.type XkbFreeGeomOutlines,@function");
__asm__("XkbFreeGeomOutlines:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomOverlayKeys");
__asm__("	.type XkbFreeGeomOverlayKeys,@function");
__asm__("XkbFreeGeomOverlayKeys:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomOverlayRows");
__asm__("	.type XkbFreeGeomOverlayRows,@function");
__asm__("XkbFreeGeomOverlayRows:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomOverlays");
__asm__("	.type XkbFreeGeomOverlays,@function");
__asm__("XkbFreeGeomOverlays:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomPoints");
__asm__("	.type XkbFreeGeomPoints,@function");
__asm__("XkbFreeGeomPoints:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomProperties");
__asm__("	.type XkbFreeGeomProperties,@function");
__asm__("XkbFreeGeomProperties:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomRows");
__asm__("	.type XkbFreeGeomRows,@function");
__asm__("XkbFreeGeomRows:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomSections");
__asm__("	.type XkbFreeGeomSections,@function");
__asm__("XkbFreeGeomSections:");
__asm__("	ret");
__asm__(".globl XkbFreeGeomShapes");
__asm__("	.type XkbFreeGeomShapes,@function");
__asm__("XkbFreeGeomShapes:");
__asm__("	ret");
__asm__(".globl XkbFreeGeometry");
__asm__("	.type XkbFreeGeometry,@function");
__asm__("XkbFreeGeometry:");
__asm__("	ret");
__asm__(".globl XkbFreeIndicatorMaps");
__asm__("	.type XkbFreeIndicatorMaps,@function");
__asm__("XkbFreeIndicatorMaps:");
__asm__("	ret");
__asm__(".globl XkbFreeKeyboard");
__asm__("	.type XkbFreeKeyboard,@function");
__asm__("XkbFreeKeyboard:");
__asm__("	ret");
__asm__(".globl XkbFreeNames");
__asm__("	.type XkbFreeNames,@function");
__asm__("XkbFreeNames:");
__asm__("	ret");
__asm__(".globl XkbFreeServerMap");
__asm__("	.type XkbFreeServerMap,@function");
__asm__("XkbFreeServerMap:");
__asm__("	ret");
__asm__(".globl XkbGetAutoRepeatRate");
__asm__("	.type XkbGetAutoRepeatRate,@function");
__asm__("XkbGetAutoRepeatRate:");
__asm__("	ret");
__asm__(".globl XkbGetCompatMap");
__asm__("	.type XkbGetCompatMap,@function");
__asm__("XkbGetCompatMap:");
__asm__("	ret");
__asm__(".globl XkbGetControls");
__asm__("	.type XkbGetControls,@function");
__asm__("XkbGetControls:");
__asm__("	ret");
__asm__(".globl XkbGetGeometry");
__asm__("	.type XkbGetGeometry,@function");
__asm__("XkbGetGeometry:");
__asm__("	ret");
__asm__(".globl XkbGetIndicatorMap");
__asm__("	.type XkbGetIndicatorMap,@function");
__asm__("XkbGetIndicatorMap:");
__asm__("	ret");
__asm__(".globl XkbGetIndicatorState");
__asm__("	.type XkbGetIndicatorState,@function");
__asm__("XkbGetIndicatorState:");
__asm__("	ret");
__asm__(".globl XkbGetKeyActions");
__asm__("	.type XkbGetKeyActions,@function");
__asm__("XkbGetKeyActions:");
__asm__("	ret");
__asm__(".globl XkbGetKeyBehaviors");
__asm__("	.type XkbGetKeyBehaviors,@function");
__asm__("XkbGetKeyBehaviors:");
__asm__("	ret");
__asm__(".globl XkbGetKeyExplicitComponents");
__asm__("	.type XkbGetKeyExplicitComponents,@function");
__asm__("XkbGetKeyExplicitComponents:");
__asm__("	ret");
__asm__(".globl XkbGetKeyModifierMap");
__asm__("	.type XkbGetKeyModifierMap,@function");
__asm__("XkbGetKeyModifierMap:");
__asm__("	ret");
__asm__(".globl XkbGetKeySyms");
__asm__("	.type XkbGetKeySyms,@function");
__asm__("XkbGetKeySyms:");
__asm__("	ret");
__asm__(".globl XkbGetKeyTypes");
__asm__("	.type XkbGetKeyTypes,@function");
__asm__("XkbGetKeyTypes:");
__asm__("	ret");
__asm__(".globl XkbGetKeyVirtualModMap");
__asm__("	.type XkbGetKeyVirtualModMap,@function");
__asm__("XkbGetKeyVirtualModMap:");
__asm__("	ret");
__asm__(".globl XkbGetKeyboard");
__asm__("	.type XkbGetKeyboard,@function");
__asm__("XkbGetKeyboard:");
__asm__("	ret");
__asm__(".globl XkbGetKeyboardByName");
__asm__("	.type XkbGetKeyboardByName,@function");
__asm__("XkbGetKeyboardByName:");
__asm__("	ret");
__asm__(".globl XkbGetMap");
__asm__("	.type XkbGetMap,@function");
__asm__("XkbGetMap:");
__asm__("	ret");
__asm__(".globl XkbGetMapChanges");
__asm__("	.type XkbGetMapChanges,@function");
__asm__("XkbGetMapChanges:");
__asm__("	ret");
__asm__(".globl XkbGetNamedGeometry");
__asm__("	.type XkbGetNamedGeometry,@function");
__asm__("XkbGetNamedGeometry:");
__asm__("	ret");
__asm__(".globl XkbGetNamedIndicator");
__asm__("	.type XkbGetNamedIndicator,@function");
__asm__("XkbGetNamedIndicator:");
__asm__("	ret");
__asm__(".globl XkbGetNames");
__asm__("	.type XkbGetNames,@function");
__asm__("XkbGetNames:");
__asm__("	ret");
__asm__(".globl XkbGetState");
__asm__("	.type XkbGetState,@function");
__asm__("XkbGetState:");
__asm__("	ret");
__asm__(".globl XkbGetUpdatedMap");
__asm__("	.type XkbGetUpdatedMap,@function");
__asm__("XkbGetUpdatedMap:");
__asm__("	ret");
__asm__(".globl XkbGetVirtualMods");
__asm__("	.type XkbGetVirtualMods,@function");
__asm__("XkbGetVirtualMods:");
__asm__("	ret");
__asm__(".globl XkbGetXlibControls");
__asm__("	.type XkbGetXlibControls,@function");
__asm__("XkbGetXlibControls:");
__asm__("	ret");
__asm__(".globl XkbIgnoreExtension");
__asm__("	.type XkbIgnoreExtension,@function");
__asm__("XkbIgnoreExtension:");
__asm__("	ret");
__asm__(".globl XkbInitCanonicalKeyTypes");
__asm__("	.type XkbInitCanonicalKeyTypes,@function");
__asm__("XkbInitCanonicalKeyTypes:");
__asm__("	ret");
__asm__(".globl XkbKeyTypesForCoreSymbols");
__asm__("	.type XkbKeyTypesForCoreSymbols,@function");
__asm__("XkbKeyTypesForCoreSymbols:");
__asm__("	ret");
__asm__(".globl XkbKeycodeToKeysym");
__asm__("	.type XkbKeycodeToKeysym,@function");
__asm__("XkbKeycodeToKeysym:");
__asm__("	ret");
__asm__(".globl XkbKeysymToModifiers");
__asm__("	.type XkbKeysymToModifiers,@function");
__asm__("XkbKeysymToModifiers:");
__asm__("	ret");
__asm__(".globl XkbLatchGroup");
__asm__("	.type XkbLatchGroup,@function");
__asm__("XkbLatchGroup:");
__asm__("	ret");
__asm__(".globl XkbLatchModifiers");
__asm__("	.type XkbLatchModifiers,@function");
__asm__("XkbLatchModifiers:");
__asm__("	ret");
__asm__(".globl XkbLibraryVersion");
__asm__("	.type XkbLibraryVersion,@function");
__asm__("XkbLibraryVersion:");
__asm__("	ret");
__asm__(".globl XkbListComponents");
__asm__("	.type XkbListComponents,@function");
__asm__("XkbListComponents:");
__asm__("	ret");
__asm__(".globl XkbLockGroup");
__asm__("	.type XkbLockGroup,@function");
__asm__("XkbLockGroup:");
__asm__("	ret");
__asm__(".globl XkbLockModifiers");
__asm__("	.type XkbLockModifiers,@function");
__asm__("XkbLockModifiers:");
__asm__("	ret");
__asm__(".globl XkbLookupKeyBinding");
__asm__("	.type XkbLookupKeyBinding,@function");
__asm__("XkbLookupKeyBinding:");
__asm__("	ret");
__asm__(".globl XkbLookupKeySym");
__asm__("	.type XkbLookupKeySym,@function");
__asm__("XkbLookupKeySym:");
__asm__("	ret");
__asm__(".globl XkbNoteControlsChanges");
__asm__("	.type XkbNoteControlsChanges,@function");
__asm__("XkbNoteControlsChanges:");
__asm__("	ret");
__asm__(".globl XkbNoteMapChanges");
__asm__("	.type XkbNoteMapChanges,@function");
__asm__("XkbNoteMapChanges:");
__asm__("	ret");
__asm__(".globl XkbNoteNameChanges");
__asm__("	.type XkbNoteNameChanges,@function");
__asm__("XkbNoteNameChanges:");
__asm__("	ret");
__asm__(".globl XkbOpenDisplay");
__asm__("	.type XkbOpenDisplay,@function");
__asm__("XkbOpenDisplay:");
__asm__("	ret");
__asm__(".globl XkbQueryExtension");
__asm__("	.type XkbQueryExtension,@function");
__asm__("XkbQueryExtension:");
__asm__("	ret");
__asm__(".globl XkbRefreshKeyboardMapping");
__asm__("	.type XkbRefreshKeyboardMapping,@function");
__asm__("XkbRefreshKeyboardMapping:");
__asm__("	ret");
__asm__(".globl XkbResizeKeyActions");
__asm__("	.type XkbResizeKeyActions,@function");
__asm__("XkbResizeKeyActions:");
__asm__("	ret");
__asm__(".globl XkbResizeKeySyms");
__asm__("	.type XkbResizeKeySyms,@function");
__asm__("XkbResizeKeySyms:");
__asm__("	ret");
__asm__(".globl XkbResizeKeyType");
__asm__("	.type XkbResizeKeyType,@function");
__asm__("XkbResizeKeyType:");
__asm__("	ret");
__asm__(".globl XkbSelectEventDetails");
__asm__("	.type XkbSelectEventDetails,@function");
__asm__("XkbSelectEventDetails:");
__asm__("	ret");
__asm__(".globl XkbSelectEvents");
__asm__("	.type XkbSelectEvents,@function");
__asm__("XkbSelectEvents:");
__asm__("	ret");
__asm__(".globl XkbSetAtomFuncs");
__asm__("	.type XkbSetAtomFuncs,@function");
__asm__("XkbSetAtomFuncs:");
__asm__("	ret");
__asm__(".globl XkbSetAutoRepeatRate");
__asm__("	.type XkbSetAutoRepeatRate,@function");
__asm__("XkbSetAutoRepeatRate:");
__asm__("	ret");
__asm__(".globl XkbSetAutoResetControls");
__asm__("	.type XkbSetAutoResetControls,@function");
__asm__("XkbSetAutoResetControls:");
__asm__("	ret");
__asm__(".globl XkbSetCompatMap");
__asm__("	.type XkbSetCompatMap,@function");
__asm__("XkbSetCompatMap:");
__asm__("	ret");
__asm__(".globl XkbSetControls");
__asm__("	.type XkbSetControls,@function");
__asm__("XkbSetControls:");
__asm__("	ret");
__asm__(".globl XkbSetDebuggingFlags");
__asm__("	.type XkbSetDebuggingFlags,@function");
__asm__("XkbSetDebuggingFlags:");
__asm__("	ret");
__asm__(".globl XkbSetDetectableAutoRepeat");
__asm__("	.type XkbSetDetectableAutoRepeat,@function");
__asm__("XkbSetDetectableAutoRepeat:");
__asm__("	ret");
__asm__(".globl XkbSetGeometry");
__asm__("	.type XkbSetGeometry,@function");
__asm__("XkbSetGeometry:");
__asm__("	ret");
__asm__(".globl XkbSetIgnoreLockMods");
__asm__("	.type XkbSetIgnoreLockMods,@function");
__asm__("XkbSetIgnoreLockMods:");
__asm__("	ret");
__asm__(".globl XkbSetIndicatorMap");
__asm__("	.type XkbSetIndicatorMap,@function");
__asm__("XkbSetIndicatorMap:");
__asm__("	ret");
__asm__(".globl XkbSetMap");
__asm__("	.type XkbSetMap,@function");
__asm__("XkbSetMap:");
__asm__("	ret");
__asm__(".globl XkbSetNamedIndicator");
__asm__("	.type XkbSetNamedIndicator,@function");
__asm__("XkbSetNamedIndicator:");
__asm__("	ret");
__asm__(".globl XkbSetNames");
__asm__("	.type XkbSetNames,@function");
__asm__("XkbSetNames:");
__asm__("	ret");
__asm__(".globl XkbSetServerInternalMods");
__asm__("	.type XkbSetServerInternalMods,@function");
__asm__("XkbSetServerInternalMods:");
__asm__("	ret");
__asm__(".globl XkbSetXlibControls");
__asm__("	.type XkbSetXlibControls,@function");
__asm__("XkbSetXlibControls:");
__asm__("	ret");
__asm__(".globl XkbToControl");
__asm__("	.type XkbToControl,@function");
__asm__("XkbToControl:");
__asm__("	ret");
__asm__(".globl XkbTranslateKey");
__asm__("	.type XkbTranslateKey,@function");
__asm__("XkbTranslateKey:");
__asm__("	ret");
__asm__(".globl XkbTranslateKeyCode");
__asm__("	.type XkbTranslateKeyCode,@function");
__asm__("XkbTranslateKeyCode:");
__asm__("	ret");
__asm__(".globl XkbTranslateKeySym");
__asm__("	.type XkbTranslateKeySym,@function");
__asm__("XkbTranslateKeySym:");
__asm__("	ret");
__asm__(".globl XkbUpdateActionVirtualMods");
__asm__("	.type XkbUpdateActionVirtualMods,@function");
__asm__("XkbUpdateActionVirtualMods:");
__asm__("	ret");
__asm__(".globl XkbUpdateKeyTypeVirtualMods");
__asm__("	.type XkbUpdateKeyTypeVirtualMods,@function");
__asm__("XkbUpdateKeyTypeVirtualMods:");
__asm__("	ret");
__asm__(".globl XkbUpdateMapFromCore");
__asm__("	.type XkbUpdateMapFromCore,@function");
__asm__("XkbUpdateMapFromCore:");
__asm__("	ret");
__asm__(".globl XkbUseExtension");
__asm__("	.type XkbUseExtension,@function");
__asm__("XkbUseExtension:");
__asm__("	ret");
__asm__(".globl XkbVirtualModsToReal");
__asm__("	.type XkbVirtualModsToReal,@function");
__asm__("XkbVirtualModsToReal:");
__asm__("	ret");
__asm__(".globl XkbXlibControlsImplemented");
__asm__("	.type XkbXlibControlsImplemented,@function");
__asm__("XkbXlibControlsImplemented:");
__asm__("	ret");
__asm__(".globl XmbDrawImageString");
__asm__("	.type XmbDrawImageString,@function");
__asm__("XmbDrawImageString:");
__asm__("	ret");
__asm__(".globl XmbDrawString");
__asm__("	.type XmbDrawString,@function");
__asm__("XmbDrawString:");
__asm__("	ret");
__asm__(".globl XmbDrawText");
__asm__("	.type XmbDrawText,@function");
__asm__("XmbDrawText:");
__asm__("	ret");
__asm__(".globl XmbLookupString");
__asm__("	.type XmbLookupString,@function");
__asm__("XmbLookupString:");
__asm__("	ret");
__asm__(".globl XmbResetIC");
__asm__("	.type XmbResetIC,@function");
__asm__("XmbResetIC:");
__asm__("	ret");
__asm__(".globl XmbSetWMProperties");
__asm__("	.type XmbSetWMProperties,@function");
__asm__("XmbSetWMProperties:");
__asm__("	ret");
__asm__(".globl XmbTextEscapement");
__asm__("	.type XmbTextEscapement,@function");
__asm__("XmbTextEscapement:");
__asm__("	ret");
__asm__(".globl XmbTextExtents");
__asm__("	.type XmbTextExtents,@function");
__asm__("XmbTextExtents:");
__asm__("	ret");
__asm__(".globl XmbTextListToTextProperty");
__asm__("	.type XmbTextListToTextProperty,@function");
__asm__("XmbTextListToTextProperty:");
__asm__("	ret");
__asm__(".globl XmbTextPerCharExtents");
__asm__("	.type XmbTextPerCharExtents,@function");
__asm__("XmbTextPerCharExtents:");
__asm__("	ret");
__asm__(".globl XmbTextPropertyToTextList");
__asm__("	.type XmbTextPropertyToTextList,@function");
__asm__("XmbTextPropertyToTextList:");
__asm__("	ret");
__asm__(".globl XrmCombineDatabase");
__asm__("	.type XrmCombineDatabase,@function");
__asm__("XrmCombineDatabase:");
__asm__("	ret");
__asm__(".globl XrmCombineFileDatabase");
__asm__("	.type XrmCombineFileDatabase,@function");
__asm__("XrmCombineFileDatabase:");
__asm__("	ret");
__asm__(".globl XrmDestroyDatabase");
__asm__("	.type XrmDestroyDatabase,@function");
__asm__("XrmDestroyDatabase:");
__asm__("	ret");
__asm__(".globl XrmEnumerateDatabase");
__asm__("	.type XrmEnumerateDatabase,@function");
__asm__("XrmEnumerateDatabase:");
__asm__("	ret");
__asm__(".globl XrmGetDatabase");
__asm__("	.type XrmGetDatabase,@function");
__asm__("XrmGetDatabase:");
__asm__("	ret");
__asm__(".globl XrmGetFileDatabase");
__asm__("	.type XrmGetFileDatabase,@function");
__asm__("XrmGetFileDatabase:");
__asm__("	ret");
__asm__(".globl XrmGetResource");
__asm__("	.type XrmGetResource,@function");
__asm__("XrmGetResource:");
__asm__("	ret");
__asm__(".globl XrmGetStringDatabase");
__asm__("	.type XrmGetStringDatabase,@function");
__asm__("XrmGetStringDatabase:");
__asm__("	ret");
__asm__(".globl XrmInitialize");
__asm__("	.type XrmInitialize,@function");
__asm__("XrmInitialize:");
__asm__("	ret");
__asm__(".globl XrmLocaleOfDatabase");
__asm__("	.type XrmLocaleOfDatabase,@function");
__asm__("XrmLocaleOfDatabase:");
__asm__("	ret");
__asm__(".globl XrmMergeDatabases");
__asm__("	.type XrmMergeDatabases,@function");
__asm__("XrmMergeDatabases:");
__asm__("	ret");
__asm__(".globl XrmParseCommand");
__asm__("	.type XrmParseCommand,@function");
__asm__("XrmParseCommand:");
__asm__("	ret");
__asm__(".globl XrmPermStringToQuark");
__asm__("	.type XrmPermStringToQuark,@function");
__asm__("XrmPermStringToQuark:");
__asm__("	ret");
__asm__(".globl XrmPutFileDatabase");
__asm__("	.type XrmPutFileDatabase,@function");
__asm__("XrmPutFileDatabase:");
__asm__("	ret");
__asm__(".globl XrmPutLineResource");
__asm__("	.type XrmPutLineResource,@function");
__asm__("XrmPutLineResource:");
__asm__("	ret");
__asm__(".globl XrmPutResource");
__asm__("	.type XrmPutResource,@function");
__asm__("XrmPutResource:");
__asm__("	ret");
__asm__(".globl XrmPutStringResource");
__asm__("	.type XrmPutStringResource,@function");
__asm__("XrmPutStringResource:");
__asm__("	ret");
__asm__(".globl XrmQGetResource");
__asm__("	.type XrmQGetResource,@function");
__asm__("XrmQGetResource:");
__asm__("	ret");
__asm__(".globl XrmQGetSearchList");
__asm__("	.type XrmQGetSearchList,@function");
__asm__("XrmQGetSearchList:");
__asm__("	ret");
__asm__(".globl XrmQGetSearchResource");
__asm__("	.type XrmQGetSearchResource,@function");
__asm__("XrmQGetSearchResource:");
__asm__("	ret");
__asm__(".globl XrmQPutResource");
__asm__("	.type XrmQPutResource,@function");
__asm__("XrmQPutResource:");
__asm__("	ret");
__asm__(".globl XrmQPutStringResource");
__asm__("	.type XrmQPutStringResource,@function");
__asm__("XrmQPutStringResource:");
__asm__("	ret");
__asm__(".globl XrmQuarkToString");
__asm__("	.type XrmQuarkToString,@function");
__asm__("XrmQuarkToString:");
__asm__("	ret");
__asm__(".globl XrmSetDatabase");
__asm__("	.type XrmSetDatabase,@function");
__asm__("XrmSetDatabase:");
__asm__("	ret");
__asm__(".globl XrmStringToBindingQuarkList");
__asm__("	.type XrmStringToBindingQuarkList,@function");
__asm__("XrmStringToBindingQuarkList:");
__asm__("	ret");
__asm__(".globl XrmStringToQuark");
__asm__("	.type XrmStringToQuark,@function");
__asm__("XrmStringToQuark:");
__asm__("	ret");
__asm__(".globl XrmStringToQuarkList");
__asm__("	.type XrmStringToQuarkList,@function");
__asm__("XrmStringToQuarkList:");
__asm__("	ret");
__asm__(".globl XrmUniqueQuark");
__asm__("	.type XrmUniqueQuark,@function");
__asm__("XrmUniqueQuark:");
__asm__("	ret");
__asm__(".globl XwcDrawImageString");
__asm__("	.type XwcDrawImageString,@function");
__asm__("XwcDrawImageString:");
__asm__("	ret");
__asm__(".globl XwcDrawString");
__asm__("	.type XwcDrawString,@function");
__asm__("XwcDrawString:");
__asm__("	ret");
__asm__(".globl XwcDrawText");
__asm__("	.type XwcDrawText,@function");
__asm__("XwcDrawText:");
__asm__("	ret");
__asm__(".globl XwcFreeStringList");
__asm__("	.type XwcFreeStringList,@function");
__asm__("XwcFreeStringList:");
__asm__("	ret");
__asm__(".globl XwcLookupString");
__asm__("	.type XwcLookupString,@function");
__asm__("XwcLookupString:");
__asm__("	ret");
__asm__(".globl XwcResetIC");
__asm__("	.type XwcResetIC,@function");
__asm__("XwcResetIC:");
__asm__("	ret");
__asm__(".globl XwcTextEscapement");
__asm__("	.type XwcTextEscapement,@function");
__asm__("XwcTextEscapement:");
__asm__("	ret");
__asm__(".globl XwcTextExtents");
__asm__("	.type XwcTextExtents,@function");
__asm__("XwcTextExtents:");
__asm__("	ret");
__asm__(".globl XwcTextListToTextProperty");
__asm__("	.type XwcTextListToTextProperty,@function");
__asm__("XwcTextListToTextProperty:");
__asm__("	ret");
__asm__(".globl XwcTextPerCharExtents");
__asm__("	.type XwcTextPerCharExtents,@function");
__asm__("XwcTextPerCharExtents:");
__asm__("	ret");
__asm__(".globl XwcTextPropertyToTextList");
__asm__("	.type XwcTextPropertyToTextList,@function");
__asm__("XwcTextPropertyToTextList:");
__asm__("	ret");
__asm__(".globl XcmsLinearRGBFunctionSet");
__asm__("	.type XcmsLinearRGBFunctionSet,@object");
__asm__("	.size XcmsLinearRGBFunctionSet,4");
__asm__("XcmsLinearRGBFunctionSet:");
__asm__("	.long 0");
__asm__(".globl XcmsRGBColorSpace");
__asm__("	.type XcmsRGBColorSpace,@object");
__asm__("	.size XcmsRGBColorSpace,4");
__asm__("XcmsRGBColorSpace:");
__asm__("	.long 0");
