__asm__(".globl XShapeCombineMask");
__asm__("	.type XShapeCombineMask,@function");
__asm__("XShapeCombineMask:");
__asm__("	ret");
__asm__(".globl XShapeCombineRectangles");
__asm__("	.type XShapeCombineRectangles,@function");
__asm__("XShapeCombineRectangles:");
__asm__("	ret");
__asm__(".globl XShapeCombineRegion");
__asm__("	.type XShapeCombineRegion,@function");
__asm__("XShapeCombineRegion:");
__asm__("	ret");
__asm__(".globl XShapeCombineShape");
__asm__("	.type XShapeCombineShape,@function");
__asm__("XShapeCombineShape:");
__asm__("	ret");
__asm__(".globl XShapeGetRectangles");
__asm__("	.type XShapeGetRectangles,@function");
__asm__("XShapeGetRectangles:");
__asm__("	ret");
__asm__(".globl XShapeInputSelected");
__asm__("	.type XShapeInputSelected,@function");
__asm__("XShapeInputSelected:");
__asm__("	ret");
__asm__(".globl XShapeOffsetShape");
__asm__("	.type XShapeOffsetShape,@function");
__asm__("XShapeOffsetShape:");
__asm__("	ret");
__asm__(".globl XShapeQueryExtension");
__asm__("	.type XShapeQueryExtension,@function");
__asm__("XShapeQueryExtension:");
__asm__("	ret");
__asm__(".globl XShapeQueryExtents");
__asm__("	.type XShapeQueryExtents,@function");
__asm__("XShapeQueryExtents:");
__asm__("	ret");
__asm__(".globl XShapeQueryVersion");
__asm__("	.type XShapeQueryVersion,@function");
__asm__("XShapeQueryVersion:");
__asm__("	ret");
__asm__(".globl XShapeSelectInput");
__asm__("	.type XShapeSelectInput,@function");
__asm__("XShapeSelectInput:");
__asm__("	ret");
__asm__(".globl XShmAttach");
__asm__("	.type XShmAttach,@function");
__asm__("XShmAttach:");
__asm__("	ret");
__asm__(".globl XShmCreateImage");
__asm__("	.type XShmCreateImage,@function");
__asm__("XShmCreateImage:");
__asm__("	ret");
__asm__(".globl XShmCreatePixmap");
__asm__("	.type XShmCreatePixmap,@function");
__asm__("XShmCreatePixmap:");
__asm__("	ret");
__asm__(".globl XShmDetach");
__asm__("	.type XShmDetach,@function");
__asm__("XShmDetach:");
__asm__("	ret");
__asm__(".globl XShmGetEventBase");
__asm__("	.type XShmGetEventBase,@function");
__asm__("XShmGetEventBase:");
__asm__("	ret");
__asm__(".globl XShmGetImage");
__asm__("	.type XShmGetImage,@function");
__asm__("XShmGetImage:");
__asm__("	ret");
__asm__(".globl XShmPixmapFormat");
__asm__("	.type XShmPixmapFormat,@function");
__asm__("XShmPixmapFormat:");
__asm__("	ret");
__asm__(".globl XShmPutImage");
__asm__("	.type XShmPutImage,@function");
__asm__("XShmPutImage:");
__asm__("	ret");
__asm__(".globl XShmQueryExtension");
__asm__("	.type XShmQueryExtension,@function");
__asm__("XShmQueryExtension:");
__asm__("	ret");
__asm__(".globl XShmQueryVersion");
__asm__("	.type XShmQueryVersion,@function");
__asm__("XShmQueryVersion:");
__asm__("	ret");
__asm__(".globl XdbeAllocateBackBufferName");
__asm__("	.type XdbeAllocateBackBufferName,@function");
__asm__("XdbeAllocateBackBufferName:");
__asm__("	ret");
__asm__(".globl XdbeBeginIdiom");
__asm__("	.type XdbeBeginIdiom,@function");
__asm__("XdbeBeginIdiom:");
__asm__("	ret");
__asm__(".globl XdbeDeallocateBackBufferName");
__asm__("	.type XdbeDeallocateBackBufferName,@function");
__asm__("XdbeDeallocateBackBufferName:");
__asm__("	ret");
__asm__(".globl XdbeEndIdiom");
__asm__("	.type XdbeEndIdiom,@function");
__asm__("XdbeEndIdiom:");
__asm__("	ret");
__asm__(".globl XdbeFreeVisualInfo");
__asm__("	.type XdbeFreeVisualInfo,@function");
__asm__("XdbeFreeVisualInfo:");
__asm__("	ret");
__asm__(".globl XdbeGetBackBufferAttributes");
__asm__("	.type XdbeGetBackBufferAttributes,@function");
__asm__("XdbeGetBackBufferAttributes:");
__asm__("	ret");
__asm__(".globl XdbeGetVisualInfo");
__asm__("	.type XdbeGetVisualInfo,@function");
__asm__("XdbeGetVisualInfo:");
__asm__("	ret");
__asm__(".globl XdbeQueryExtension");
__asm__("	.type XdbeQueryExtension,@function");
__asm__("XdbeQueryExtension:");
__asm__("	ret");
__asm__(".globl XdbeSwapBuffers");
__asm__("	.type XdbeSwapBuffers,@function");
__asm__("XdbeSwapBuffers:");
__asm__("	ret");
