__asm__(".globl gzread");
__asm__("	.type gzread,@function");
__asm__("gzread:");
__asm__("	ret");
__asm__(".globl gzclose");
__asm__("	.type gzclose,@function");
__asm__("gzclose:");
__asm__("	ret");
__asm__(".globl gzopen");
__asm__("	.type gzopen,@function");
__asm__("gzopen:");
__asm__("	ret");
__asm__(".globl gzdopen");
__asm__("	.type gzdopen,@function");
__asm__("gzdopen:");
__asm__("	ret");
__asm__(".globl gzwrite");
__asm__("	.type gzwrite,@function");
__asm__("gzwrite:");
__asm__("	ret");
__asm__(".globl gzflush");
__asm__("	.type gzflush,@function");
__asm__("gzflush:");
__asm__("	ret");
__asm__(".globl gzerror");
__asm__("	.type gzerror,@function");
__asm__("gzerror:");
__asm__("	ret");
__asm__(".globl adler32");
__asm__("	.type adler32,@function");
__asm__("adler32:");
__asm__("	ret");
__asm__(".globl compress");
__asm__("	.type compress,@function");
__asm__("compress:");
__asm__("	ret");
__asm__(".globl compress2");
__asm__("	.type compress2,@function");
__asm__("compress2:");
__asm__("	ret");
__asm__(".globl crc32");
__asm__("	.type crc32,@function");
__asm__("crc32:");
__asm__("	ret");
__asm__(".globl deflate");
__asm__("	.type deflate,@function");
__asm__("deflate:");
__asm__("	ret");
__asm__(".globl deflateCopy");
__asm__("	.type deflateCopy,@function");
__asm__("deflateCopy:");
__asm__("	ret");
__asm__(".globl deflateEnd");
__asm__("	.type deflateEnd,@function");
__asm__("deflateEnd:");
__asm__("	ret");
__asm__(".globl deflateInit2_");
__asm__("	.type deflateInit2_,@function");
__asm__("deflateInit2_:");
__asm__("	ret");
__asm__(".globl deflateInit_");
__asm__("	.type deflateInit_,@function");
__asm__("deflateInit_:");
__asm__("	ret");
__asm__(".globl deflateParams");
__asm__("	.type deflateParams,@function");
__asm__("deflateParams:");
__asm__("	ret");
__asm__(".globl deflateReset");
__asm__("	.type deflateReset,@function");
__asm__("deflateReset:");
__asm__("	ret");
__asm__(".globl deflateSetDictionary");
__asm__("	.type deflateSetDictionary,@function");
__asm__("deflateSetDictionary:");
__asm__("	ret");
__asm__(".globl get_crc_table");
__asm__("	.type get_crc_table,@function");
__asm__("get_crc_table:");
__asm__("	ret");
__asm__(".globl gzeof");
__asm__("	.type gzeof,@function");
__asm__("gzeof:");
__asm__("	ret");
__asm__(".globl gzgetc");
__asm__("	.type gzgetc,@function");
__asm__("gzgetc:");
__asm__("	ret");
__asm__(".globl gzgets");
__asm__("	.type gzgets,@function");
__asm__("gzgets:");
__asm__("	ret");
__asm__(".globl gzprintf");
__asm__("	.type gzprintf,@function");
__asm__("gzprintf:");
__asm__("	ret");
__asm__(".globl gzputc");
__asm__("	.type gzputc,@function");
__asm__("gzputc:");
__asm__("	ret");
__asm__(".globl gzputs");
__asm__("	.type gzputs,@function");
__asm__("gzputs:");
__asm__("	ret");
__asm__(".globl gzrewind");
__asm__("	.type gzrewind,@function");
__asm__("gzrewind:");
__asm__("	ret");
__asm__(".globl gzseek");
__asm__("	.type gzseek,@function");
__asm__("gzseek:");
__asm__("	ret");
__asm__(".globl gzsetparams");
__asm__("	.type gzsetparams,@function");
__asm__("gzsetparams:");
__asm__("	ret");
__asm__(".globl gztell");
__asm__("	.type gztell,@function");
__asm__("gztell:");
__asm__("	ret");
__asm__(".globl inflate");
__asm__("	.type inflate,@function");
__asm__("inflate:");
__asm__("	ret");
__asm__(".globl inflateEnd");
__asm__("	.type inflateEnd,@function");
__asm__("inflateEnd:");
__asm__("	ret");
__asm__(".globl inflateInit2_");
__asm__("	.type inflateInit2_,@function");
__asm__("inflateInit2_:");
__asm__("	ret");
__asm__(".globl inflateInit_");
__asm__("	.type inflateInit_,@function");
__asm__("inflateInit_:");
__asm__("	ret");
__asm__(".globl inflateReset");
__asm__("	.type inflateReset,@function");
__asm__("inflateReset:");
__asm__("	ret");
__asm__(".globl inflateSetDictionary");
__asm__("	.type inflateSetDictionary,@function");
__asm__("inflateSetDictionary:");
__asm__("	ret");
__asm__(".globl inflateSync");
__asm__("	.type inflateSync,@function");
__asm__("inflateSync:");
__asm__("	ret");
__asm__(".globl inflateSyncPoint");
__asm__("	.type inflateSyncPoint,@function");
__asm__("inflateSyncPoint:");
__asm__("	ret");
__asm__(".globl uncompress");
__asm__("	.type uncompress,@function");
__asm__("uncompress:");
__asm__("	ret");
__asm__(".globl zError");
__asm__("	.type zError,@function");
__asm__("zError:");
__asm__("	ret");
