#!/usr/bin/perl

use Getopt::Long;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

sub usage()
{
print STDERR "mklibsrc -l <libname>\n";
die;
}

#
# 1) process the arguments
#
GetOptions("l=s" => \$libname);

if( !$libname ) { usage(); }

#
# 2) Establish connection to the database
#
$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER,$LSBDBPASSWD) || die $Mysql::db_errstr;

$select  = "SELECT DISTINCT Interface.Iname FROM Interface,LGInt,LibGroup,Library ";
$select .= "WHERE Interface.Iid=LGInt.LGIint ";
$select .= "AND LGInt.LGIlibg=LibGroup.LGid ";
$select .= "AND LibGroup.LGlib=Library.Lid ";
$select .= "AND Library.Lname=".$Dbh->quote($libname);
$sth = $Dbh->query($select) || die $Dbh->errmsg();

for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	printf "__asm__(\".globl _lsb_%s\");\n",
				$entry{'Iname'};
	printf "__asm__(\"\t.type _lsb_%s,\@function\");\n",
				$entry{'Iname'};
	printf "__asm__(\"_lsb_%s:\");\n",
				$entry{'Iname'};
	printf "__asm__(\"\tjmp %s\");\n",
				$entry{'Iname'};
	printf "__asm__(\".symver _lsb_%s,%s\@\@LSB_1.0\");\n",
				$entry{'Iname'},$entry{'Iname'};
}
