void __finite() {} ;
void __finitef() {} ;
void __finitel() {} ;
void __finitel_depr_0() {} ;
__asm__(".symver __finitel_depr_0,__finitel@GLIBC_2.3");
void __fpclassify() {} ;
void __fpclassifyf() {} ;
void __fpclassifyl() {} ;
void __signbit() {} ;
void __signbitf() {} ;
void __signbitl() {} ;
void acos() {} ;
void acosf() {} ;
void acosh() {} ;
void acoshf() {} ;
void acoshl() {} ;
void acoshl_depr_0() {} ;
__asm__(".symver acoshl_depr_0,acoshl@GLIBC_2.3");
void acosl() {} ;
void acosl_depr_0() {} ;
__asm__(".symver acosl_depr_0,acosl@GLIBC_2.3");
void asin() {} ;
void asinf() {} ;
void asinh() {} ;
void asinhf() {} ;
void asinhl() {} ;
void asinhl_depr_0() {} ;
__asm__(".symver asinhl_depr_0,asinhl@GLIBC_2.3");
void asinl() {} ;
void asinl_depr_0() {} ;
__asm__(".symver asinl_depr_0,asinl@GLIBC_2.3");
void atan() {} ;
void atan2() {} ;
void atan2f() {} ;
void atan2l() {} ;
void atan2l_depr_0() {} ;
__asm__(".symver atan2l_depr_0,atan2l@GLIBC_2.3");
void atanf() {} ;
void atanh() {} ;
void atanhf() {} ;
void atanhl() {} ;
void atanhl_depr_0() {} ;
__asm__(".symver atanhl_depr_0,atanhl@GLIBC_2.3");
void atanl() {} ;
void atanl_depr_0() {} ;
__asm__(".symver atanl_depr_0,atanl@GLIBC_2.3");
void cabs() {} ;
void cabsf() {} ;
void cabsl() {} ;
void cabsl_depr_0() {} ;
__asm__(".symver cabsl_depr_0,cabsl@GLIBC_2.3");
void cacos() {} ;
void cacosf() {} ;
void cacosh() {} ;
void cacoshf() {} ;
void cacoshl() {} ;
void cacoshl_depr_0() {} ;
__asm__(".symver cacoshl_depr_0,cacoshl@GLIBC_2.3");
void cacosl() {} ;
void cacosl_depr_0() {} ;
__asm__(".symver cacosl_depr_0,cacosl@GLIBC_2.3");
void carg() {} ;
void cargf() {} ;
void cargl() {} ;
void cargl_depr_0() {} ;
__asm__(".symver cargl_depr_0,cargl@GLIBC_2.3");
void casin() {} ;
void casinf() {} ;
void casinh() {} ;
void casinhf() {} ;
void casinhl() {} ;
void casinhl_depr_0() {} ;
__asm__(".symver casinhl_depr_0,casinhl@GLIBC_2.3");
void casinl() {} ;
void casinl_depr_0() {} ;
__asm__(".symver casinl_depr_0,casinl@GLIBC_2.3");
void catan() {} ;
void catanf() {} ;
void catanh() {} ;
void catanhf() {} ;
void catanhl() {} ;
void catanhl_depr_0() {} ;
__asm__(".symver catanhl_depr_0,catanhl@GLIBC_2.3");
void catanl() {} ;
void catanl_depr_0() {} ;
__asm__(".symver catanl_depr_0,catanl@GLIBC_2.3");
void cbrt() {} ;
void cbrtf() {} ;
void cbrtl() {} ;
void cbrtl_depr_0() {} ;
__asm__(".symver cbrtl_depr_0,cbrtl@GLIBC_2.3");
void ccos() {} ;
void ccosf() {} ;
void ccosh() {} ;
void ccoshf() {} ;
void ccoshl() {} ;
void ccoshl_depr_0() {} ;
__asm__(".symver ccoshl_depr_0,ccoshl@GLIBC_2.3");
void ccosl() {} ;
void ccosl_depr_0() {} ;
__asm__(".symver ccosl_depr_0,ccosl@GLIBC_2.3");
void ceil() {} ;
void ceilf() {} ;
void ceill() {} ;
void ceill_depr_0() {} ;
__asm__(".symver ceill_depr_0,ceill@GLIBC_2.3");
void cexp() {} ;
void cexpf() {} ;
void cexpl() {} ;
void cexpl_depr_0() {} ;
__asm__(".symver cexpl_depr_0,cexpl@GLIBC_2.3");
void cimag() {} ;
void cimagf() {} ;
void cimagl() {} ;
void cimagl_depr_0() {} ;
__asm__(".symver cimagl_depr_0,cimagl@GLIBC_2.3");
void clog() {} ;
void clog10() {} ;
void clog10f() {} ;
void clog10l() {} ;
void clog10l_depr_0() {} ;
__asm__(".symver clog10l_depr_0,clog10l@GLIBC_2.3");
void clogf() {} ;
void clogl() {} ;
void clogl_depr_0() {} ;
__asm__(".symver clogl_depr_0,clogl@GLIBC_2.3");
void conj() {} ;
void conjf() {} ;
void conjl() {} ;
void conjl_depr_0() {} ;
__asm__(".symver conjl_depr_0,conjl@GLIBC_2.3");
void copysign() {} ;
void copysignf() {} ;
void copysignl() {} ;
void copysignl_depr_0() {} ;
__asm__(".symver copysignl_depr_0,copysignl@GLIBC_2.3");
void cos() {} ;
void cosf() {} ;
void cosh() {} ;
void coshf() {} ;
void coshl() {} ;
void coshl_depr_0() {} ;
__asm__(".symver coshl_depr_0,coshl@GLIBC_2.3");
void cosl() {} ;
void cosl_depr_0() {} ;
__asm__(".symver cosl_depr_0,cosl@GLIBC_2.3");
void cpow() {} ;
void cpowf() {} ;
void cpowl() {} ;
void cpowl_depr_0() {} ;
__asm__(".symver cpowl_depr_0,cpowl@GLIBC_2.3");
void cproj() {} ;
void cprojf() {} ;
void cprojl() {} ;
void cprojl_depr_0() {} ;
__asm__(".symver cprojl_depr_0,cprojl@GLIBC_2.3");
void creal() {} ;
void crealf() {} ;
void creall() {} ;
void creall_depr_0() {} ;
__asm__(".symver creall_depr_0,creall@GLIBC_2.3");
void csin() {} ;
void csinf() {} ;
void csinh() {} ;
void csinhf() {} ;
void csinhl() {} ;
void csinhl_depr_0() {} ;
__asm__(".symver csinhl_depr_0,csinhl@GLIBC_2.3");
void csinl() {} ;
void csinl_depr_0() {} ;
__asm__(".symver csinl_depr_0,csinl@GLIBC_2.3");
void csqrt() {} ;
void csqrtf() {} ;
void csqrtl() {} ;
void csqrtl_depr_0() {} ;
__asm__(".symver csqrtl_depr_0,csqrtl@GLIBC_2.3");
void ctan() {} ;
void ctanf() {} ;
void ctanh() {} ;
void ctanhf() {} ;
void ctanhl() {} ;
void ctanhl_depr_0() {} ;
__asm__(".symver ctanhl_depr_0,ctanhl@GLIBC_2.3");
void ctanl() {} ;
void ctanl_depr_0() {} ;
__asm__(".symver ctanl_depr_0,ctanl@GLIBC_2.3");
void drem() {} ;
void dremf() {} ;
void dreml() {} ;
void dreml_depr_0() {} ;
__asm__(".symver dreml_depr_0,dreml@GLIBC_2.4");
void erf() {} ;
void erfc() {} ;
void erfcf() {} ;
void erfcl() {} ;
void erfcl_depr_0() {} ;
__asm__(".symver erfcl_depr_0,erfcl@GLIBC_2.3");
void erff() {} ;
void erfl() {} ;
void erfl_depr_0() {} ;
__asm__(".symver erfl_depr_0,erfl@GLIBC_2.3");
void exp() {} ;
void exp10() {} ;
void exp10f() {} ;
void exp10l() {} ;
void exp10l_depr_0() {} ;
__asm__(".symver exp10l_depr_0,exp10l@GLIBC_2.3");
void exp2() {} ;
void exp2f() {} ;
void exp2l() {} ;
void expf() {} ;
void expl() {} ;
void expl_depr_0() {} ;
__asm__(".symver expl_depr_0,expl@GLIBC_2.3");
void expm1() {} ;
void expm1f() {} ;
void expm1l() {} ;
void expm1l_depr_0() {} ;
__asm__(".symver expm1l_depr_0,expm1l@GLIBC_2.3");
void fabs() {} ;
void fabsf() {} ;
void fabsl() {} ;
void fabsl_depr_0() {} ;
__asm__(".symver fabsl_depr_0,fabsl@GLIBC_2.3");
void fdim() {} ;
void fdimf() {} ;
void fdiml() {} ;
void fdiml_depr_0() {} ;
__asm__(".symver fdiml_depr_0,fdiml@GLIBC_2.3");
void feclearexcept() {} ;
void fedisableexcept() {} ;
void feenableexcept() {} ;
void fegetenv() {} ;
void fegetexcept() {} ;
void fegetexceptflag() {} ;
void fegetround() {} ;
void feholdexcept() {} ;
void feraiseexcept() {} ;
void fesetenv() {} ;
void fesetexceptflag() {} ;
void fesetround() {} ;
void fetestexcept() {} ;
void feupdateenv() {} ;
void finite() {} ;
void finitef() {} ;
void finitel() {} ;
void finitel_depr_0() {} ;
__asm__(".symver finitel_depr_0,finitel@GLIBC_2.4");
void floor() {} ;
void floorf() {} ;
void floorl() {} ;
void floorl_depr_0() {} ;
__asm__(".symver floorl_depr_0,floorl@GLIBC_2.3");
void fma() {} ;
void fmaf() {} ;
void fmal() {} ;
void fmal_depr_0() {} ;
__asm__(".symver fmal_depr_0,fmal@GLIBC_2.3");
void fmax() {} ;
void fmaxf() {} ;
void fmaxl() {} ;
void fmaxl_depr_0() {} ;
__asm__(".symver fmaxl_depr_0,fmaxl@GLIBC_2.3");
void fmin() {} ;
void fminf() {} ;
void fminl() {} ;
void fminl_depr_0() {} ;
__asm__(".symver fminl_depr_0,fminl@GLIBC_2.3");
void fmod() {} ;
void fmodf() {} ;
void fmodl() {} ;
void fmodl_depr_0() {} ;
__asm__(".symver fmodl_depr_0,fmodl@GLIBC_2.3");
void frexp() {} ;
void frexpf() {} ;
void frexpl() {} ;
void frexpl_depr_0() {} ;
__asm__(".symver frexpl_depr_0,frexpl@GLIBC_2.3");
void gamma() {} ;
void gammaf() {} ;
void gammal() {} ;
void gammal_depr_0() {} ;
__asm__(".symver gammal_depr_0,gammal@GLIBC_2.4");
void hypot() {} ;
void hypotf() {} ;
void hypotl() {} ;
void hypotl_depr_0() {} ;
__asm__(".symver hypotl_depr_0,hypotl@GLIBC_2.3");
void ilogb() {} ;
void ilogbf() {} ;
void ilogbl() {} ;
void ilogbl_depr_0() {} ;
__asm__(".symver ilogbl_depr_0,ilogbl@GLIBC_2.3");
void j0() {} ;
void j0f() {} ;
void j0l() {} ;
void j0l_depr_0() {} ;
__asm__(".symver j0l_depr_0,j0l@GLIBC_2.3");
void j1() {} ;
void j1f() {} ;
void j1l() {} ;
void j1l_depr_0() {} ;
__asm__(".symver j1l_depr_0,j1l@GLIBC_2.3");
void jn() {} ;
void jnf() {} ;
void jnl() {} ;
void jnl_depr_0() {} ;
__asm__(".symver jnl_depr_0,jnl@GLIBC_2.3");
void ldexp() {} ;
void ldexpf() {} ;
void ldexpl() {} ;
void ldexpl_depr_0() {} ;
__asm__(".symver ldexpl_depr_0,ldexpl@GLIBC_2.3");
void lgamma() {} ;
void lgamma_r() {} ;
void lgammaf() {} ;
void lgammaf_r() {} ;
void lgammal() {} ;
void lgammal_depr_0() {} ;
__asm__(".symver lgammal_depr_0,lgammal@GLIBC_2.3");
void lgammal_r() {} ;
void lgammal_r_depr_0() {} ;
__asm__(".symver lgammal_r_depr_0,lgammal_r@GLIBC_2.3");
void llrint() {} ;
void llrintf() {} ;
void llrintl() {} ;
void llrintl_depr_0() {} ;
__asm__(".symver llrintl_depr_0,llrintl@GLIBC_2.3");
void llround() {} ;
void llroundf() {} ;
void llroundl() {} ;
void llroundl_depr_0() {} ;
__asm__(".symver llroundl_depr_0,llroundl@GLIBC_2.3");
void log() {} ;
void log10() {} ;
void log10f() {} ;
void log10l() {} ;
void log10l_depr_0() {} ;
__asm__(".symver log10l_depr_0,log10l@GLIBC_2.3");
void log1p() {} ;
void log1pf() {} ;
void log1pl() {} ;
void log1pl_depr_0() {} ;
__asm__(".symver log1pl_depr_0,log1pl@GLIBC_2.3");
void log2() {} ;
void log2f() {} ;
void log2l() {} ;
void log2l_depr_0() {} ;
__asm__(".symver log2l_depr_0,log2l@GLIBC_2.3");
void logb() {} ;
void logbf() {} ;
void logbl() {} ;
void logbl_depr_0() {} ;
__asm__(".symver logbl_depr_0,logbl@GLIBC_2.3");
void logf() {} ;
void logl() {} ;
void logl_depr_0() {} ;
__asm__(".symver logl_depr_0,logl@GLIBC_2.3");
void lrint() {} ;
void lrintf() {} ;
void lrintl() {} ;
void lrintl_depr_0() {} ;
__asm__(".symver lrintl_depr_0,lrintl@GLIBC_2.3");
void lround() {} ;
void lroundf() {} ;
void lroundl() {} ;
void lroundl_depr_0() {} ;
__asm__(".symver lroundl_depr_0,lroundl@GLIBC_2.3");
void matherr() {} ;
void modf() {} ;
void modff() {} ;
void modfl() {} ;
void modfl_depr_0() {} ;
__asm__(".symver modfl_depr_0,modfl@GLIBC_2.3");
void nan() {} ;
void nanf() {} ;
void nanl() {} ;
void nanl_depr_0() {} ;
__asm__(".symver nanl_depr_0,nanl@GLIBC_2.3");
void nearbyint() {} ;
void nearbyintf() {} ;
void nearbyintl() {} ;
void nearbyintl_depr_0() {} ;
__asm__(".symver nearbyintl_depr_0,nearbyintl@GLIBC_2.3");
void nextafter() {} ;
void nextafterf() {} ;
void nextafterl() {} ;
void nextafterl_depr_0() {} ;
__asm__(".symver nextafterl_depr_0,nextafterl@GLIBC_2.3");
void nexttoward() {} ;
void nexttoward_depr_0() {} ;
__asm__(".symver nexttoward_depr_0,nexttoward@GLIBC_2.3");
void nexttowardf() {} ;
void nexttowardf_depr_0() {} ;
__asm__(".symver nexttowardf_depr_0,nexttowardf@GLIBC_2.3");
void nexttowardl() {} ;
void nexttowardl_depr_0() {} ;
__asm__(".symver nexttowardl_depr_0,nexttowardl@GLIBC_2.3");
void pow() {} ;
void pow10() {} ;
void pow10f() {} ;
void pow10l() {} ;
void pow10l_depr_0() {} ;
__asm__(".symver pow10l_depr_0,pow10l@GLIBC_2.3");
void powf() {} ;
void powl() {} ;
void powl_depr_0() {} ;
__asm__(".symver powl_depr_0,powl@GLIBC_2.3");
void remainder() {} ;
void remainderf() {} ;
void remainderl() {} ;
void remainderl_depr_0() {} ;
__asm__(".symver remainderl_depr_0,remainderl@GLIBC_2.3");
void remquo() {} ;
void remquof() {} ;
void remquol() {} ;
void remquol_depr_0() {} ;
__asm__(".symver remquol_depr_0,remquol@GLIBC_2.3");
void rint() {} ;
void rintf() {} ;
void rintl() {} ;
void rintl_depr_0() {} ;
__asm__(".symver rintl_depr_0,rintl@GLIBC_2.3");
void round() {} ;
void roundf() {} ;
void roundl() {} ;
void roundl_depr_0() {} ;
__asm__(".symver roundl_depr_0,roundl@GLIBC_2.3");
void scalb() {} ;
void scalbf() {} ;
void scalbl() {} ;
void scalbl_depr_0() {} ;
__asm__(".symver scalbl_depr_0,scalbl@GLIBC_2.3");
void scalbln() {} ;
void scalblnf() {} ;
void scalblnl() {} ;
void scalblnl_depr_0() {} ;
__asm__(".symver scalblnl_depr_0,scalblnl@GLIBC_2.3");
void scalbn() {} ;
void scalbnf() {} ;
void scalbnl() {} ;
void scalbnl_depr_0() {} ;
__asm__(".symver scalbnl_depr_0,scalbnl@GLIBC_2.3");
void significand() {} ;
void significandf() {} ;
void significandl() {} ;
void significandl_depr_0() {} ;
__asm__(".symver significandl_depr_0,significandl@GLIBC_2.3");
void sin() {} ;
void sincos() {} ;
void sincosf() {} ;
void sincosl() {} ;
void sincosl_depr_0() {} ;
__asm__(".symver sincosl_depr_0,sincosl@GLIBC_2.3");
void sinf() {} ;
void sinh() {} ;
void sinhf() {} ;
void sinhl() {} ;
void sinhl_depr_0() {} ;
__asm__(".symver sinhl_depr_0,sinhl@GLIBC_2.3");
void sinl() {} ;
void sinl_depr_0() {} ;
__asm__(".symver sinl_depr_0,sinl@GLIBC_2.3");
void sqrt() {} ;
void sqrtf() {} ;
void sqrtl() {} ;
void sqrtl_depr_0() {} ;
__asm__(".symver sqrtl_depr_0,sqrtl@GLIBC_2.3");
void tan() {} ;
void tanf() {} ;
void tanh() {} ;
void tanhf() {} ;
void tanhl() {} ;
void tanhl_depr_0() {} ;
__asm__(".symver tanhl_depr_0,tanhl@GLIBC_2.3");
void tanl() {} ;
void tanl_depr_0() {} ;
__asm__(".symver tanl_depr_0,tanl@GLIBC_2.3");
void tgamma() {} ;
void tgammaf() {} ;
void tgammal() {} ;
void tgammal_depr_0() {} ;
__asm__(".symver tgammal_depr_0,tgammal@GLIBC_2.3");
void trunc() {} ;
void truncf() {} ;
void truncl() {} ;
void truncl_depr_0() {} ;
__asm__(".symver truncl_depr_0,truncl@GLIBC_2.3");
void y0() {} ;
void y0f() {} ;
void y0l() {} ;
void y0l_depr_0() {} ;
__asm__(".symver y0l_depr_0,y0l@GLIBC_2.3");
void y1() {} ;
void y1f() {} ;
void y1l() {} ;
void y1l_depr_0() {} ;
__asm__(".symver y1l_depr_0,y1l@GLIBC_2.3");
void yn() {} ;
void ynf() {} ;
void ynl() {} ;
void ynl_depr_0() {} ;
__asm__(".symver ynl_depr_0,ynl@GLIBC_2.3");
__asm__(".globl signgam; .pushsection .data; .type signgam,@object; .size signgam, 4; signgam: .long 0; .popsection");
