#if (__LSB_VERSION__ >= 32 )
#ifndef _FREETYPE_CONFIG_FTOPTION_H_
#define _FREETYPE_CONFIG_FTOPTION_H_


#ifdef __cplusplus
extern "C" {
#endif


#if __LSB_VERSION__ >= 32
#define FT_CONFIG_OPTION_ADOBE_GLYPH_LIST
#define FT_CONFIG_OPTION_GUESSING_EMBEDDED_RFORK
#define FT_CONFIG_OPTION_MAC_FONTS
#define FT_CONFIG_OPTION_POSTSCRIPT_NAMES
#define FT_CONFIG_OPTION_USE_LZW
#define FT_CONFIG_OPTION_USE_ZLIB
#define TT_CONFIG_CMAP_FORMAT_0
#define TT_CONFIG_CMAP_FORMAT_10
#define TT_CONFIG_CMAP_FORMAT_12
#define TT_CONFIG_CMAP_FORMAT_2
#define TT_CONFIG_CMAP_FORMAT_4
#define TT_CONFIG_CMAP_FORMAT_6
#define TT_CONFIG_CMAP_FORMAT_8
#define TT_CONFIG_OPTION_EMBEDDED_BITMAPS
#define TT_CONFIG_OPTION_GX_VAR_SUPPORT
#define TT_CONFIG_OPTION_INTERPRETER_SWITCH
#define TT_CONFIG_OPTION_POSTSCRIPT_NAMES
#define TT_CONFIG_OPTION_SFNT_NAMES
#define TT_CONFIG_OPTION_UNPATENTED_HINTING
#define T1_MAX_SUBRS_CALLS	16
#define FT_RENDER_POOL_SIZE	16384L
#define T1_MAX_CHARSTRINGS_OPERANDS	256
#define FT_MAX_MODULES	32
#define T1_MAX_DICT_DEPTH	5
#endif				// __LSB_VERSION__ >= 3.2



#ifdef __cplusplus
}
#endif
#endif				// protection
#endif				// LSB version
