void _ZN10QSvgWidget10paintEventEP11QPaintEvent() {} ;
void _ZN10QSvgWidget11qt_metacallEN11QMetaObject4CallEiPPv() {} ;
void _ZN10QSvgWidget11qt_metacastEPKc() {} ;
void _ZN10QSvgWidget4loadERK10QByteArray() {} ;
void _ZN10QSvgWidget4loadERK7QString() {} ;
void _ZN10QSvgWidgetC1EP7QWidget() {} ;
void _ZN10QSvgWidgetC1ERK7QStringP7QWidget() {} ;
void _ZN10QSvgWidgetC2EP7QWidget() {} ;
void _ZN10QSvgWidgetC2ERK7QStringP7QWidget() {} ;
void _ZN10QSvgWidgetD0Ev() {} ;
void _ZN10QSvgWidgetD1Ev() {} ;
void _ZN10QSvgWidgetD2Ev() {} ;
void _ZN12QSvgRenderer10setViewBoxERK5QRect() {} ;
void _ZN12QSvgRenderer10setViewBoxERK6QRectF() {} ;
void _ZN12QSvgRenderer11qt_metacallEN11QMetaObject4CallEiPPv() {} ;
void _ZN12QSvgRenderer11qt_metacastEPKc() {} ;
void _ZN12QSvgRenderer13repaintNeededEv() {} ;
void _ZN12QSvgRenderer15setCurrentFrameEi() {} ;
void _ZN12QSvgRenderer18setFramesPerSecondEi() {} ;
void _ZN12QSvgRenderer4loadERK10QByteArray() {} ;
void _ZN12QSvgRenderer4loadERK7QString() {} ;
void _ZN12QSvgRenderer6renderEP8QPainter() {} ;
void _ZN12QSvgRenderer6renderEP8QPainterRK6QRectF() {} ;
void _ZN12QSvgRenderer6renderEP8QPainterRK7QStringRK6QRectF() {} ;
void _ZN12QSvgRendererC1EP7QObject() {} ;
void _ZN12QSvgRendererC1ERK10QByteArrayP7QObject() {} ;
void _ZN12QSvgRendererC1ERK7QStringP7QObject() {} ;
void _ZN12QSvgRendererC2EP7QObject() {} ;
void _ZN12QSvgRendererC2ERK10QByteArrayP7QObject() {} ;
void _ZN12QSvgRendererC2ERK7QStringP7QObject() {} ;
void _ZN12QSvgRendererD0Ev() {} ;
void _ZN12QSvgRendererD1Ev() {} ;
void _ZN12QSvgRendererD2Ev() {} ;
void _ZN16QGraphicsSvgItem11qt_metacallEN11QMetaObject4CallEiPPv() {} ;
void _ZN16QGraphicsSvgItem11qt_metacastEPKc() {} ;
void _ZN16QGraphicsSvgItem12setElementIdERK7QString() {} ;
void _ZN16QGraphicsSvgItem17setCachingEnabledEb() {} ;
void _ZN16QGraphicsSvgItem17setSharedRendererEP12QSvgRenderer() {} ;
void _ZN16QGraphicsSvgItem19setMaximumCacheSizeERK5QSize() {} ;
void _ZN16QGraphicsSvgItem5paintEP8QPainterPK24QStyleOptionGraphicsItemP7QWidget() {} ;
void _ZN16QGraphicsSvgItemC1EP13QGraphicsItem() {} ;
void _ZN16QGraphicsSvgItemC1ERK7QStringP13QGraphicsItem() {} ;
void _ZN16QGraphicsSvgItemC2EP13QGraphicsItem() {} ;
void _ZN16QGraphicsSvgItemC2ERK7QStringP13QGraphicsItem() {} ;
void _ZNK10QSvgWidget10metaObjectEv() {} ;
void _ZNK10QSvgWidget8rendererEv() {} ;
void _ZNK10QSvgWidget8sizeHintEv() {} ;
void _ZNK12QSvgRenderer10metaObjectEv() {} ;
void _ZNK12QSvgRenderer11defaultSizeEv() {} ;
void _ZNK12QSvgRenderer12currentFrameEv() {} ;
void _ZNK12QSvgRenderer13elementExistsERK7QString() {} ;
void _ZNK12QSvgRenderer15boundsOnElementERK7QString() {} ;
void _ZNK12QSvgRenderer15framesPerSecondEv() {} ;
void _ZNK12QSvgRenderer16matrixForElementERK7QString() {} ;
void _ZNK12QSvgRenderer17animationDurationEv() {} ;
void _ZNK12QSvgRenderer7isValidEv() {} ;
void _ZNK12QSvgRenderer7viewBoxEv() {} ;
void _ZNK12QSvgRenderer8animatedEv() {} ;
void _ZNK12QSvgRenderer8viewBoxFEv() {} ;
void _ZNK16QGraphicsSvgItem10metaObjectEv() {} ;
void _ZNK16QGraphicsSvgItem12boundingRectEv() {} ;
void _ZNK16QGraphicsSvgItem16isCachingEnabledEv() {} ;
void _ZNK16QGraphicsSvgItem16maximumCacheSizeEv() {} ;
void _ZNK16QGraphicsSvgItem4typeEv() {} ;
void _ZNK16QGraphicsSvgItem8rendererEv() {} ;
void _ZNK16QGraphicsSvgItem9elementIdEv() {} ;
void _ZThn8_N10QSvgWidgetD0Ev() {} ;
void _ZThn8_N10QSvgWidgetD1Ev() {} ;
void _ZThn8_N16QGraphicsSvgItem5paintEP8QPainterPK24QStyleOptionGraphicsItemP7QWidget() {} ;
void _ZThn8_NK16QGraphicsSvgItem12boundingRectEv() {} ;
void _ZThn8_NK16QGraphicsSvgItem4typeEv() {} ;
__asm__(".globl _ZN10QSvgWidget16staticMetaObjectE; .pushsection .data; .type _ZN10QSvgWidget16staticMetaObjectE,@object; .size _ZN10QSvgWidget16staticMetaObjectE, 16; _ZN10QSvgWidget16staticMetaObjectE: .long 0; .popsection");
__asm__(".globl _ZN12QSvgRenderer16staticMetaObjectE; .pushsection .data; .type _ZN12QSvgRenderer16staticMetaObjectE,@object; .size _ZN12QSvgRenderer16staticMetaObjectE, 16; _ZN12QSvgRenderer16staticMetaObjectE: .long 0; .popsection");
__asm__(".globl _ZN16QGraphicsSvgItem16staticMetaObjectE; .pushsection .data; .type _ZN16QGraphicsSvgItem16staticMetaObjectE,@object; .size _ZN16QGraphicsSvgItem16staticMetaObjectE, 16; _ZN16QGraphicsSvgItem16staticMetaObjectE: .long 0; .popsection");
__asm__(".globl _ZTI10QSvgWidget; .pushsection .data; .type _ZTI10QSvgWidget,@object; .size _ZTI10QSvgWidget, 12; _ZTI10QSvgWidget: .long 0; .popsection");
__asm__(".globl _ZTI12QSvgRenderer; .pushsection .data; .type _ZTI12QSvgRenderer,@object; .size _ZTI12QSvgRenderer, 12; _ZTI12QSvgRenderer: .long 0; .popsection");
__asm__(".globl _ZTI16QGraphicsSvgItem; .pushsection .data; .type _ZTI16QGraphicsSvgItem,@object; .size _ZTI16QGraphicsSvgItem, 32; _ZTI16QGraphicsSvgItem: .long 0; .popsection");
__asm__(".globl _ZTI16QSvgTinyDocument; .pushsection .data; .type _ZTI16QSvgTinyDocument,@object; .size _ZTI16QSvgTinyDocument, 12; _ZTI16QSvgTinyDocument: .long 0; .popsection");
__asm__(".globl _ZTV10QSvgWidget; .pushsection .data; .type _ZTV10QSvgWidget,@object; .size _ZTV10QSvgWidget, 252; _ZTV10QSvgWidget: .long 0; .popsection");
__asm__(".globl _ZTV12QSvgRenderer; .pushsection .data; .type _ZTV12QSvgRenderer,@object; .size _ZTV12QSvgRenderer, 56; _ZTV12QSvgRenderer: .long 0; .popsection");
__asm__(".globl _ZTV16QGraphicsSvgItem; .pushsection .data; .type _ZTV16QGraphicsSvgItem,@object; .size _ZTV16QGraphicsSvgItem, 224; _ZTV16QGraphicsSvgItem: .long 0; .popsection");
__asm__(".globl _ZTV16QSvgTinyDocument; .pushsection .data; .type _ZTV16QSvgTinyDocument,@object; .size _ZTV16QSvgTinyDocument, 28; _ZTV16QSvgTinyDocument: .long 0; .popsection");
