.TH lsbcc "1" "" "lsbcc (LSB)" LSB
.SH NAME
lsbcc, lsbc++ \- compiler driver for building LSB conforming applications
.SH SYNOPSIS
.B lsbcc
.RI [ compiler-options ]
.br
.B lsbc++
.RI [ compiler-options ]
.SH DESCRIPTION
.P
This tool should be used in place of the
.I cc
(or
.IR c++ )
command when
building an LSB-conforming program.
.P
The LSB development environment provides
a set of headers and libraries nominally found in
.I /opt/lsbdev-base/include
and
.I /opt/lsdev-base/lib
respectively. These headers and libraries have been
carefully built so that they contain only the interfaces
specified in the LSB. 
.P
LSB programs also need to be linked with 
.I ld-lsb.so.1
.RI ( ld-lsb-ia64.so.1
for the Itanium architecture)
as the program intepreter.   
.P
.I lsbcc
is designed to take care of these build issues 
(to the extent possible) without requiring changes
to existing build setups. 
.P
.IR lsbcc
takes no options; 
it first modifies the command line to follow the
LSB build rules, then passes the resulting
command line on to the regular compiler.
.P
Behavior other than the default is controlled
by a set of environment variables.
.P
.SH ENVIRONMENT
The following environment variables affect the behavior of
.I lsbcc
.TP
LSBCC_DEBUG
A numeric value which represents a bit pattern that specifies what
kind of debugging output to produce. The bits in this pattern are
.nf

0x0001   Display enviromental overrides
0x0002   Display the arguments passed in
0x0004   Display the arguments that are specifically recognized
0x0008   Display the arguments that are not recognized
0x0010   Display changes made to the include arguments
0x0020   Display changes made to the library arguments
0x0040   Display the modified argument list
.fi
.TP
LSBCC
Specifies the name of the C compiler to invoke with the modifed
argument set. If this environment variable is not found,
the default 
.I cc
will be used.
.TP
LSBCXX
Specifies the name of the C++ compiler to invoke with the modifed
argument set. If this environment variable is not found,
the default 
.I c++
will be used.
.P
.SH EXAMPLES
.B "lsbcc hello.c -o hello"
.P
.B "make CC=lsbcc"
.P
.B "CC=lsbcc CXX=lsbc++ ./configure; make"
.P
.SH "AUTHORS"
Stuart Anderson <anderson@freestandards.org>
.SH "REPORTING BUGS"
Report bugs to <lsb-build@linuxbase.org>.
.SH "BUGS"
.P
It is a little too easy to confuse lsbcc (and lsbc++). 
In particular, build systems that include "clever" tools
to manage which libraries to use, such as GNU libtool
and pkgconfig, may defeat the checks for non-LSB libraries.
.SH FILES
.TP
/opt/lsbdev-base/include
the LSB header files
.TP
/opt/lsbdev-base/lib
the LSB stub libraries
.SH SEE ALSO
lsbappchk
.P
.SH NOTES
.P
.I lsbcc
is commonly delivered as a package named
.IR lsbdev-cc .
If this package is used, the support package
.I lsbdev-base
must also be installed.
.SH COPYRIGHT
Copyright \(co 2002 Free Standards Group.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linuxbase.org/
