#!/bin/bash

proginterp="-Wl,--dynamic-linker=/lib/ld-lsb.so.1"
libs="-lc /usr/lib/libc_nonshared.a"
userlibs=""
opts=""
target=""

libgcc=`gcc -print-libgcc-file-name`
gccbasedir=`dirname $libgcc`
# The LSB 'lib' and 'include' directories are located under here:
lsbbasedir=/usr/lsb

TEMP=`getopt -o l:EgMcD:U:O:f:W:I:Sp:o:s:L: -n 'lsbcc' -- "$@"`

eval set -- "$TEMP"

while true ; do
	case "$1" in
		-E)
			opts="$opts $1 ";
			proginterp="";
			libs="";shift
			;;
		-c)
			opts="$opts $1 ";
			proginterp="";
			libs="";shift
			;;
		-s)
			opts="$opts $1$2 ";
			libs="";shift 2
			;;
		-o)
			target="-o $2";shift 2
			;;
		-O|-D|-I|-f)
			opts="$opts $1$2 ";shift 2
			;;
		-L|-U|-W|-p)
			opts="$opts $1$2 ";shift 2
			;;
		-l)
			case $2 in
				GL|Xt|ICE|SM|X11|Xext)
					userlibs="$userlibs -l$2"
					;;
				crypt|pthread|c|util|z|dl|m|ncurses)
					userlibs="$userlibs -l$2"
					;;
				*)
					#echo "Statically linking library $1 $2"
					userlibs="$userlibs -Wl,-Bstatic -l$2 -Wl,-Bdynamic"
					;;
			esac
			shift 2
			;;
		-g|-M)
			opts="$opts $1";shift
			;;
		--)
#echo "End of options: $*"
			shift; break
			;;
		*)
			echo "Internal error! $1" ; exit 1 
			;;
	esac
done

set -x
exec gcc $proginterp $target $opts -I$lsbbasedir/include -I$gccbasedir/include \
	-nodefaultlibs -L$gccbasedir -L$lsbbasedir/lib -L/lib -L/usr/lib \
	$* $userlibs $libs

