#!/bin/bash 

libgcc=`gcc -print-libgcc-file-name`
gccbasedir=`dirname $libgcc`

exec gcc -nostdinc -I$gccbasedir/include -I/usr/lsb/include \
	-nodefaultlibs -L$gccbasedir -L/usr/lsb/lib -L/lib -L/usr/lib \
	-Wl,--dynamic-linker=/lib/lsb/ld-lsb.so.1 $* \
	-lc /usr/lib/libc_nonshared.a
